// Expressions & Formulae — MCQ papers (4 × 20).
// Options are shuffled at display time; explanations name distractors by value.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "expressions-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "expressions-m1-q01",
        question: "Simplify {{7a + 4b - 2a + b}}.",
        options: ["{{5a + 5b}}", "{{5a + 4b}}", "{{9a + 5b}}", "{{10ab}}"],
        answerIndex: 0,
        explanation: "Collect the a-terms and the b-terms separately: {{7a - 2a = 5a}} and {{4b + b = 5b}}, so the answer is {{5a + 5b}}. {{5a + 4b}} forgets that b on its own means 1b. {{10ab}} adds everything together, but a-terms and b-terms are unlike terms and cannot be combined.",
        difficulty: "warmup",
        guideRef: "simplifying",
        hints: ["Group the a-terms together and the b-terms together. Remember that b on its own means 1b."],
        strategy: "Group like terms",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q02",
        question: "Which of these is an **equation**: something you could solve to find the value of the letter?",
        options: ["{{3x + 2}}", "{{A = lw}}", "{{3x + 2 = 11}}", "{{2(x + 3) ≡ 2x + 6}}"],
        answerIndex: 2,
        explanation: "{{3x + 2 = 11}} is true for just one value, x = 3, so you can solve it. {{3x + 2}} has no equals sign, so it is an expression. {{A = lw}} is a formula: it links area, length and width and works for every rectangle. {{2(x + 3) ≡ 2x + 6}} is an identity: it is true for every x, so there is nothing to solve.",
        difficulty: "warmup",
        guideRef: "language-of-algebra",
        hints: ["For each one, ask: is it true for one particular value of the letter, for every value, or is there no equals sign at all?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q03",
        question: "Find the value of {{4a - 2b}} when a = 5 and b = 3.",
        options: ["22", "14", "4", "26"],
        answerIndex: 1,
        explanation: "{{4a}} means 4 × a = 20 and {{2b}} means 2 × b = 6, so {{4a - 2b = 20 - 6 = 14}}. 22 comes from reading 4a as the two-digit number 45 and 2b as 23. 26 adds the 6 instead of subtracting it.",
        difficulty: "warmup",
        guideRef: "substitution",
        hints: ["4a means 4 × a: the number and the letter are multiplied, not written side by side like digits."],
        strategy: "Replace letters with brackets",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q04",
        question: "Expand {{5(2x - 4)}}.",
        options: ["{{10x - 4}}", "{{10x + 20}}", "{{7x + 1}}", "{{10x - 20}}"],
        answerIndex: 3,
        explanation: "Multiply the 5 by **every** term inside: {{5 * 2x = 10x}} and {{5 * (-4) = -20}}, giving {{10x - 20}}. {{10x - 4}} multiplies only the first term. {{7x + 1}} adds 5 to each term instead of multiplying.",
        difficulty: "warmup",
        guideRef: "expanding",
        hints: ["The 5 multiplies everything inside the bracket: both the 2x and the −4."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q05",
        question: "Priya buys n kaya toast sets at $4 each and pays with a $20 note. Which expression gives her change, in dollars?",
        options: ["{{4n - 20}}", "{{16n}}", "{{20 - 4n}}", "{{20 - n}}"],
        answerIndex: 2,
        explanation: "n sets cost 4 × n = {{4n}} dollars, and change = amount paid − cost, so {{20 - 4n}}. {{4n - 20}} subtracts the wrong way round: for 2 sets it gives −12. {{16n}} works out 20 − 4 first, but 20 and 4n are unlike terms. {{20 - n}} forgets that each set costs $4.",
        difficulty: "warmup",
        guideRef: "writing-expressions",
        hints: ["Try a number first: what is her change if she buys 2 sets? Then replace the 2 with n."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q06",
        question: "Simplify {{5a^3 * 2a^4}}.",
        options: ["{{10a^7}}", "{{7a^7}}", "{{10a^12}}", "{{7a^12}}"],
        answerIndex: 0,
        explanation: "Multiply the numbers and add the indices: {{5 * 2 = 10}} and {{a^3 * a^4 = a^(3+4) = a^7}}, so {{10a^7}}. {{10a^12}} multiplies the indices, but {{a^3 * a^4}} is (a × a × a) × (a × a × a × a), which is seven a's. {{7a^7}} adds the 5 and 2 instead of multiplying them.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Deal with the numbers and the letters separately.", "Write {{a^3 * a^4}} out in full as a × a × … How many a's are there?", "Numbers: 5 × 2. Letters: count the a's, which means adding the indices."],
        strategy: "Use the index laws",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q07",
        question: "Find the value of {{x^2 + 2x}} when x = −3.",
        options: ["−15", "15", "−12", "3"],
        answerIndex: 3,
        explanation: "Put −3 in brackets: {{(-3)^2 + 2 * (-3) = 9 - 6 = 3}}. −15 comes from treating {{(-3)^2}} as −9, but a negative times a negative is positive. 15 adds 6 instead of subtracting it: {{2 * (-3)}} is −6. −12 treats {{x^2}} as 2x.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Replace each x with (−3), brackets included.", "{{(-3)^2 = (-3) * (-3)}}. What sign does that give?", "{{(-3)^2 = 9}} and {{2 * (-3) = -6}}. Now combine them."],
        strategy: "Replace letters with brackets",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q08",
        question: "Factorise fully {{12x + 18}}.",
        options: ["{{2(6x + 9)}}", "{{6(2x + 3)}}", "{{3(4x + 6)}}", "{{6(2x + 18)}}"],
        answerIndex: 1,
        explanation: "The HCF of 12 and 18 is 6, so {{12x + 18 = 6(2x + 3)}}. Check: {{6 * 2x = 12x}} and {{6 * 3 = 18}}. {{2(6x + 9)}} and {{3(4x + 6)}} are correct but not **fully** factorised, because each bracket still has a common factor. {{6(2x + 18)}} forgets to divide the 18 by 6.",
        difficulty: "core",
        guideRef: "factorising",
        hints: ["What is the **highest** number that divides both 12 and 18?", "The HCF is 6. Divide each term by 6.", "Check by expanding: you should get back to {{12x + 18}}."],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q09",
        question: "What is the coefficient of x in {{5x^2 - 3x + 7}}?",
        options: ["3", "−3", "5", "7"],
        answerIndex: 1,
        explanation: "The x-term is {{-3x}}, and the sign belongs to the term, so the coefficient is −3. Answering 3 drops the minus sign. 5 is the coefficient of {{x^2}}, which is a different term. 7 is the constant term, which has no x at all.",
        difficulty: "core",
        guideRef: "language-of-algebra",
        hints: ["Split the expression into its terms, keeping each sign with the term after it.", "Which term contains x (not {{x^2}})? Its coefficient is the number in front, sign included."],
        strategy: "Split into terms",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q10",
        question: "Expand {{-2(3x - 5)}}.",
        options: ["{{-6x - 10}}", "{{6x - 10}}", "{{-6x + 10}}", "{{-6x - 5}}"],
        answerIndex: 2,
        explanation: "Multiply −2 by each term: {{-2 * 3x = -6x}} and {{-2 * (-5) = +10}}, so {{-6x + 10}}. {{-6x - 10}} is the classic sign slip: negative × negative is **positive**. {{6x - 10}} ignores the minus sign in front of the 2. {{-6x - 5}} multiplies only the first term.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["The −2 multiplies both terms in the bracket, and its sign comes too.", "Take care with the second term: {{-2 * (-5)}}.", "Negative × negative = positive."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q11",
        question: "Wei Ling thinks of a number n. She halves it, then subtracts 3. Which expression is her answer?",
        options: ["{{n/2 - 3}}", "{{(n - 3)/2}}", "{{2n - 3}}", "{{3 - n/2}}"],
        answerIndex: 0,
        explanation: "Halve first, {{n/2}}, then subtract 3: {{n/2 - 3}}. {{(n - 3)/2}} does the steps in the wrong order: it subtracts first, then halves. With n = 10, halving then subtracting gives 2, but {{(10 - 3)/2 = 3.5}}. {{2n - 3}} doubles instead of halving.",
        difficulty: "core",
        guideRef: "writing-expressions",
        hints: ["Build it one step at a time, in the order the words say.", "After halving you have {{n/2}}. What happens to that next?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q12",
        question: "Make x the subject of {{y = 3x + 5}}.",
        options: ["{{x = y/3 - 5}}", "{{x = (y + 5)/3}}", "{{x = (y - 3)/5}}", "{{x = (y - 5)/3}}"],
        answerIndex: 3,
        explanation: "To get x on its own, undo the steps in reverse order: subtract 5, then divide by 3. {{y - 5 = 3x}}, so {{x = (y - 5)/3}}. {{x = y/3 - 5}} undoes the steps in the wrong order (dividing first). {{x = (y + 5)/3}} adds 5, but the inverse of + 5 is − 5.",
        difficulty: "core",
        guideRef: "changing-the-subject",
        hints: ["Think of a function machine: x → × 3 → + 5 → y. Run it backwards.", "First undo the + 5 on both sides.", "{{y - 5 = 3x}}. Now undo the × 3."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q13",
        question: "Simplify {{3a^2 + 2a - a^2 + 4a}}.",
        options: ["{{8a^2}}", "{{4a^2 + 6a}}", "{{2a^4 + 6a^2}}", "{{2a^2 + 6a}}"],
        answerIndex: 3,
        explanation: "{{a^2}}-terms and a-terms are unlike, so collect them separately: {{3a^2 - a^2 = 2a^2}} and {{2a + 4a = 6a}}, giving {{2a^2 + 6a}}. {{2a^4 + 6a^2}} adds the powers while collecting, but 3 lots of {{a^2}} take away 1 lot of {{a^2}} is 2 lots of {{a^2}}: the power does not change. {{4a^2 + 6a}} adds the {{-a^2}} instead of subtracting it. {{8a^2}} lumps unlike terms together.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Are {{a^2}} and a like terms? Try a = 10: {{a^2}} is 100 but a is 10.", "Collect the {{a^2}}-terms, then the a-terms. {{-a^2}} means take away 1 lot of {{a^2}}.", "When you collect like terms, only the number in front changes. The power stays the same."],
        strategy: "Group like terms",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q14",
        question: "A hawker centre catering order for n people costs C dollars, where {{C = 50 + 6n}}. How much does an order for 25 people cost?",
        options: ["$1400", "$200", "$675", "$81"],
        answerIndex: 1,
        explanation: "Multiplication comes before addition: {{6 * 25 = 150}}, then {{50 + 150 = 200}}, so $200. $1400 adds first, {{(50 + 6) * 25}}, which breaks the order of operations. $675 reads 6n as the digits 6 and 25 written side by side (625). $81 just adds the three numbers.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["6n means 6 × n.", "In {{50 + 6 * 25}}, which comes first: the + or the ×?"],
        strategy: "Use the order of operations",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q15",
        question: "Expand and simplify {{3(x + 4) - 2(x - 1)}}.",
        options: ["{{x + 10}}", "{{x + 11}}", "{{x + 14}}", "{{5x + 14}}"],
        answerIndex: 2,
        explanation: "{{3(x + 4) = 3x + 12}} and {{-2(x - 1) = -2x + 2}}. Collect: {{3x - 2x + 12 + 2 = x + 14}}. {{x + 10}} comes from writing {{-2 * (-1)}} as −2, but it is +2. {{x + 11}} multiplies only the x by −2 and leaves the −1 unchanged. {{5x + 14}} treats the −2x as +2x.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["Expand each bracket separately. The −2 belongs to the second bracket.", "In {{-2(x - 1)}}, what is {{-2 * (-1)}}?", "Now collect the x-terms and the number terms."],
        strategy: "Expand, then collect",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q16",
        question: "The grid is being used to expand {{(x + 5)(x + 2)}}. When it is complete, what is the expanded and simplified answer?",
        diagram: `<svg viewBox="0 0 230 165" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A two by two grid for expanding (x + 5)(x + 2). The columns are headed x and 5, the rows are headed x and 2. The top-left cell shows x squared; the other three cells show question marks."><rect x="0" y="0" width="230" height="165" fill="#ffffff"/><rect x="50" y="40" width="100" height="80" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><rect x="150" y="40" width="60" height="80" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="50" y="120" width="100" height="35" fill="#bbf7d0" stroke="#334155" stroke-width="1.5"/><rect x="150" y="120" width="60" height="35" fill="#fecaca" stroke="#334155" stroke-width="1.5"/><g font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle"><text x="30" y="30">×</text><text x="100" y="30" font-style="italic">x</text><text x="180" y="30">5</text><text x="30" y="85" font-style="italic">x</text><text x="30" y="143">2</text><text x="100" y="85" font-style="italic">x²</text><text x="180" y="85">?</text><text x="100" y="143">?</text><text x="180" y="143">?</text></g></svg>`,
        options: ["{{x^2 + 7x + 10}}", "{{x^2 + 10}}", "{{x^2 + 7x + 7}}", "{{x^2 + 10x + 7}}"],
        answerIndex: 0,
        explanation: "The four cells are {{x^2}}, 5x, 2x and 10. Adding them: {{x^2 + 5x + 2x + 10 = x^2 + 7x + 10}}. {{x^2 + 10}} multiplies only first × first and last × last, missing the two middle cells. {{x^2 + 7x + 7}} adds 5 + 2 for the number cell instead of multiplying 5 × 2.",
        difficulty: "core",
        guideRef: "double-brackets",
        hints: ["Each cell is its row heading × its column heading.", "Fill in the other three cells. Which of them are like terms?", "The cells are {{x^2}}, 5x, 2x and 10. Add them and collect the x-terms."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q17",
        question: "All the corners of this L-shape are right angles. Which expression gives its perimeter?",
        diagram: `<svg viewBox="0 0 240 150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="An L-shape with right-angled corners. The left side is 2x, the bottom is 3x, the top of the upright part is x and the short right-hand side is x. The two inner sides are not labelled."><rect x="0" y="0" width="240" height="150" fill="#ffffff"/><polygon points="40,20 90,20 90,70 190,70 190,120 40,120" fill="#bae6fd" stroke="#1f2937" stroke-width="2"/><g font-family="sans-serif" fill="#1f2937" font-size="14" font-style="italic"><text x="65" y="14" text-anchor="middle">x</text><text x="32" y="75" text-anchor="end">2x</text><text x="115" y="140" text-anchor="middle">3x</text><text x="198" y="100" text-anchor="start">x</text></g></svg>`,
        options: ["{{7x}}", "{{9x}}", "{{10x}}", "{{4x^2}}"],
        answerIndex: 2,
        explanation: "Work out the two unlabelled sides first. The short vertical one is {{2x - x = x}} and the horizontal one is {{3x - x = 2x}}. Perimeter = {{2x + 3x + x + x + x + 2x = 10x}}. A slicker way: push the inner corner outwards and the perimeter matches a 3x by 2x rectangle, {{2(3x + 2x) = 10x}}. {{7x}} adds only the labelled sides. {{9x}} guesses that both missing sides are x. {{4x^2}} is the area, not the perimeter.",
        difficulty: "challenge",
        guideRef: "writing-expressions",
        hints: ["There are six sides, but only four are labelled. Can you work out the other two?", "Compare the left side (2x) with the short right side (x). How long must the missing vertical side be?", "The missing sides are x and 2x. Now add all six."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q18",
        question: "For a number x greater than 1, {{x^a * x^b = x^12}} and {{x^a ÷ x^b = x^4}}. What is the value of a?",
        options: ["6", "3", "16", "8"],
        answerIndex: 3,
        explanation: "Multiplying adds indices, so {{a + b = 12}}. Dividing subtracts them, so {{a - b = 4}}. The two numbers that add to 12 and differ by 4 are 8 and 4, so a = 8. Check: {{x^8 * x^4 = x^12}} and {{x^8 ÷ x^4 = x^4}}. 6 just halves 12 and ignores the division fact. 3 divides 12 by 4, as if the indices were divided. 16 adds 12 and 4 but forgets that this gives 2a, not a.",
        difficulty: "challenge",
        guideRef: "simplifying",
        hints: ["Turn each fact into a statement about a and b using the index laws.", "Multiplying gives a + b = 12. What does dividing give?", "Which two numbers add to 12 and differ by 4?"],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q19",
        question: "The area of a trapezium is {{A = 1/2 (a + b)h}}. Which formula has b as the subject?",
        options: ["{{b = 2A/h - a}}", "{{b = (2A - a)/h}}", "{{b = A/(2h) - a}}", "{{b = 2A - a - h}}"],
        answerIndex: 0,
        explanation: "Undo one layer at a time. Multiply by 2: {{2A = (a + b)h}}. Divide by h: {{2A/h = a + b}}. Subtract a: {{b = 2A/h - a}}. {{b = (2A - a)/h}} subtracts a before dividing by h, but a is inside the bracket that h multiplies. {{b = A/(2h) - a}} divides by 2 instead of multiplying: the inverse of halving is doubling. {{b = 2A - a - h}} subtracts h, but h multiplies the bracket.",
        difficulty: "challenge",
        guideRef: "changing-the-subject",
        hints: ["What has happened to b? It is added to a, multiplied by h, then halved.", "Undo in reverse order, so undo the halving first.", "{{2A = (a + b)h}}. Next undo the × h, then the + a."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expressions-m1-q20",
        question: "n is a whole number. Is {{n^2 + n}} always even, sometimes even, or never even?",
        options: ["Even only when n is even", "Always even", "Even only when n is odd", "Never even"],
        answerIndex: 1,
        explanation: "Factorise: {{n^2 + n = n(n + 1)}}, the product of two consecutive whole numbers. One of any two consecutive whole numbers is even, so the product is always even. 'Even only when n is even' forgets that when n is odd, n + 1 is even: n = 3 gives 3 × 4 = 12. Trying cases (2, 6, 12, 20, …) suggests the pattern; the factorisation proves it.",
        difficulty: "challenge",
        guideRef: "factorising",
        hints: ["Try n = 1, 2, 3, 4, 5. What do you notice?", "Factorise {{n^2 + n}} by taking out the common factor n.", "{{n(n + 1)}} is the product of two consecutive numbers. What must be true about one of them?"],
        strategy: "Try small cases",
      },
    ],
  },
  {
    id: "expressions-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "expressions-m2-q01",
        question: "Which of these is an **identity**: true for every value of x?",
        options: ["{{2x + 3 = 9}}", "{{2(x + 3) = 2x + 6}}", "{{x + x = x^2}}", "{{3(x + 1) = 3x + 1}}"],
        answerIndex: 1,
        explanation: "Expanding {{2(x + 3)}} always gives {{2x + 6}}, so the two sides agree for every x. That makes it an identity, which can be written {{2(x + 3) ≡ 2x + 6}}. {{2x + 3 = 9}} is an equation, true only when x = 3. {{x + x = x^2}} mixes up adding and multiplying: {{x + x = 2x}}, which equals {{x^2}} only when x is 0 or 2. {{3(x + 1) = 3x + 1}} forgets to multiply the 1 by 3.",
        difficulty: "warmup",
        guideRef: "language-of-algebra",
        hints: ["Test each one with two different values, such as x = 1 and x = 5. Which works both times?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q02",
        question: "Simplify {{20x^5 ÷ 4x^2}}.",
        options: ["{{16x^3}}", "{{5x^7}}", "{{80x^7}}", "{{5x^3}}"],
        answerIndex: 3,
        explanation: "Divide the numbers and subtract the indices: {{20 ÷ 4 = 5}} and {{x^5 ÷ x^2 = x^(5-2) = x^3}}, so {{5x^3}}. {{16x^3}} subtracts the numbers instead of dividing them. {{5x^7}} adds the indices, but that rule is for multiplying. {{80x^7}} multiplies instead of dividing.",
        difficulty: "warmup",
        guideRef: "simplifying",
        hints: ["Numbers: divide. Letters: cancel the x's, five on top and two underneath."],
        strategy: "Use the index laws",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q03",
        question: "Find the value of {{4x^2}} when {{x = 1/2}}.",
        options: ["1", "4", "2", "{{1/4}}"],
        answerIndex: 0,
        explanation: "Square first: {{(1/2)^2 = 1/4}}. Then {{4 * 1/4 = 1}}. 4 squares the 4 as well, working out {{(4 * 1/2)^2 = 2^2}}. 2 comes from squaring only the top of the fraction, as if {{(1/2)^2}} were {{1/2}}. {{1/4}} forgets to multiply by 4.",
        difficulty: "warmup",
        guideRef: "substitution",
        hints: ["Powers come before multiplication, so square {{1/2}} first. Remember {{(1/2)^2 = 1/2 * 1/2}}."],
        strategy: "Use the order of operations",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q04",
        question: "Factorise {{5x + 15}}.",
        options: ["{{5(x + 15)}}", "{{x(5 + 15)}}", "{{5(x + 3)}}", "{{3(x + 5)}}"],
        answerIndex: 2,
        explanation: "Both terms are multiples of 5: {{5x = 5 * x}} and {{15 = 5 * 3}}, so {{5x + 15 = 5(x + 3)}}. {{5(x + 15)}} forgets to divide the 15 by 5; it expands to {{5x + 75}}. {{x(5 + 15)}} takes out x, but 15 has no x in it. {{3(x + 5)}} expands to {{3x + 15}}, not {{5x + 15}}.",
        difficulty: "warmup",
        guideRef: "factorising",
        hints: ["Find the HCF of 5 and 15, divide each term by it, then check by expanding."],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q05",
        question: "Hana is h years old. Her brother Jun is 3 years younger than twice Hana's age. Which expression gives Jun's age?",
        options: ["{{3 - 2h}}", "{{2(h - 3)}}", "{{2h + 3}}", "{{2h - 3}}"],
        answerIndex: 3,
        explanation: "Twice Hana's age is {{2h}}, and 3 years younger means subtract 3: {{2h - 3}}. {{2(h - 3)}} subtracts before doubling: if Hana is 10, it gives 14 instead of 17. {{3 - 2h}} subtracts the wrong way round. {{2h + 3}} makes Jun older, not younger.",
        difficulty: "warmup",
        guideRef: "writing-expressions",
        hints: ["Try it with a number first: if Hana were 10, how old would Jun be?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q06",
        question: "In {{P = 2(l + w)}}, P is the perimeter of a rectangle with length l and width w. Which description is correct?",
        options: ["An equation: solve it to find the one correct value of l", "A formula: it gives P once you know l and w", "An identity: it is true for any values of P, l and w", "An expression: it has letters but no equals sign"],
        answerIndex: 1,
        explanation: "{{P = 2(l + w)}} is a **formula**: a rule linking different quantities, so you substitute values of l and w to find P. It is not an identity, because P = 10, l = 1, w = 1 makes it false ({{2(1 + 1) = 4}}, not 10). It is not an equation with one solution for l either: l can be any length, and P changes with it. And it does have an equals sign, so it is more than an expression.",
        difficulty: "core",
        guideRef: "language-of-algebra",
        hints: ["Does it have an equals sign? Does it link different quantities?", "Try P = 10, l = 1 and w = 1. Is the statement still true? What does that tell you?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q07",
        question: "The table shows the value of an expression for x = 1 to 4.\n\n| x | 1 | 2 | 3 | 4 |\n|---|---|---|---|---|\n| value | 3 | 7 | 13 | 21 |\n\nWhich expression could it be?",
        options: ["{{4x - 1}}", "{{3x}}", "{{x^2 + x + 1}}", "{{2x^2 + 1}}"],
        answerIndex: 2,
        explanation: "Check every column: {{x^2 + x + 1}} gives 1 + 1 + 1 = 3, 4 + 2 + 1 = 7, 9 + 3 + 1 = 13 and 16 + 4 + 1 = 21. {{4x - 1}} is the trap: it fits the first two columns (3 and 7) but gives 11 when x = 3. {{3x}} and {{2x^2 + 1}} fit only x = 1. Always test every row, not just the first one or two.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Substitute x = 1 into each option, then x = 2, and keep going.", "Several options work for x = 1, and one of the wrong ones also works for x = 2. Do not stop early.", "Only one expression gives 13 when x = 3."],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q08",
        question: "Expand {{2x(3x - 4)}}.",
        options: ["{{6x^2 - 8x}}", "{{6x^2 - 4}}", "{{5x^2 - 8x}}", "{{6x^2 - 8}}"],
        answerIndex: 0,
        explanation: "Multiply 2x by each term: {{2x * 3x = 6x^2}} and {{2x * (-4) = -8x}}, giving {{6x^2 - 8x}}. {{6x^2 - 4}} multiplies only the first term. {{5x^2 - 8x}} adds 2 and 3 instead of multiplying. {{6x^2 - 8}} multiplies the 4 by 2 but forgets the x in 2x.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["2x multiplies both terms inside the bracket.", "For {{2x * 3x}}, multiply the numbers, then use {{x * x = x^2}}.", "{{2x * (-4)}} keeps the x: it is −8x."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q09",
        question: "Factorise fully {{6x^2 + 9x}}.",
        options: ["{{3x(2x + 3)}}", "{{3(2x^2 + 3x)}}", "{{x(6x + 9)}}", "{{3x(2x^2 + 3)}}"],
        answerIndex: 0,
        explanation: "The HCF of {{6x^2}} and 9x is 3x (3 from the numbers, x from the letters). {{6x^2 ÷ 3x = 2x}} and {{9x ÷ 3x = 3}}, so {{3x(2x + 3)}}. {{3(2x^2 + 3x)}} and {{x(6x + 9)}} are correct but not fully factorised, because each bracket still has a common factor. {{3x(2x^2 + 3)}} forgets to take the x out of {{6x^2}}: it expands to {{6x^3 + 9x}}.",
        difficulty: "core",
        guideRef: "factorising",
        hints: ["Find the HCF of the numbers AND of the letters.", "6 and 9 share 3; {{x^2}} and x share x. So the HCF is 3x.", "Divide each term by 3x, then check by expanding."],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q10",
        question: "Which expression means 'add x and y, then square the result'?",
        options: ["{{x^2 + y^2}}", "{{x + y^2}}", "{{2(x + y)}}", "{{(x + y)^2}}"],
        answerIndex: 3,
        explanation: "The adding happens first, so it goes in a bracket, and then the whole bracket is squared: {{(x + y)^2}}. {{x^2 + y^2}} squares each letter separately. Try x = 1, y = 2: {{(1 + 2)^2 = 9}} but {{1^2 + 2^2 = 5}}. {{x + y^2}} squares only the y. {{2(x + y)}} doubles instead of squaring.",
        difficulty: "core",
        guideRef: "writing-expressions",
        hints: ["Which operation happens first? How do you show that in algebra?", "A bracket makes the addition happen first. Then square the whole bracket."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q11",
        question: "This function machine turns x into y. Which formula gives x in terms of y?",
        diagram: `<svg viewBox="0 0 380 80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A function machine: the input x goes into a box labelled times 4, then into a box labelled minus 7, and the output is y."><rect x="0" y="0" width="380" height="80" fill="#ffffff"/><g stroke="#334155" stroke-width="2"><line x1="32" y1="40" x2="72" y2="40"/><line x1="160" y1="40" x2="197" y2="40"/><line x1="285" y1="40" x2="322" y2="40"/></g><g fill="#334155"><polygon points="72,34 82,40 72,46"/><polygon points="197,34 207,40 197,46"/><polygon points="322,34 332,40 322,46"/></g><rect x="82" y="18" width="78" height="44" rx="6" fill="#c7d2fe" stroke="#1f2937" stroke-width="2"/><rect x="207" y="18" width="78" height="44" rx="6" fill="#fde68a" stroke="#1f2937" stroke-width="2"/><g font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle"><text x="18" y="45" font-style="italic">x</text><text x="121" y="45">× 4</text><text x="246" y="45">− 7</text><text x="352" y="45" font-style="italic">y</text></g></svg>`,
        options: ["{{x = y/4 + 7}}", "{{x = (y + 7)/4}}", "{{x = (y - 7)/4}}", "{{x = 4(y + 7)}}"],
        answerIndex: 1,
        explanation: "The machine does × 4 then − 7, so {{y = 4x - 7}}. Run it backwards: undo the − 7 by adding 7, then undo the × 4 by dividing by 4, giving {{x = (y + 7)/4}}. {{x = y/4 + 7}} uses the right inverses but in the wrong order. {{x = (y - 7)/4}} repeats the − 7 instead of undoing it. {{x = 4(y + 7)}} undoes the − 7 but repeats the × 4.",
        difficulty: "core",
        guideRef: "changing-the-subject",
        hints: ["To go backwards, start at y and undo the **last** operation first.", "The inverse of − 7 is + 7. The inverse of × 4 is ÷ 4.", "y → + 7 → ÷ 4 → x."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q12",
        question: "Is {{a * a = 2a}} true always, sometimes or never?",
        options: ["Always", "Sometimes: only when a = 2", "Sometimes: only when a = 0 or a = 2", "Never"],
        answerIndex: 2,
        explanation: "{{a * a = a^2}}, not 2a, so it is not always true: a = 3 gives 9 on the left and 6 on the right. But it can happen: a = 2 gives 4 = 4, and a = 0 gives 0 = 0. So it is true **sometimes**, for exactly a = 0 and a = 2. 'Always' is the misconception that {{a * a}} means 2a. 'Only when a = 2' forgets to test zero. 'Never' assumes two different-looking expressions can never be equal.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Write {{a * a}} in index form. Is that the same thing as 2a?", "Try a = 1, 2, 3, … Do any of them work?", "Have you tried a = 0?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q13",
        question: "Find the value of {{a^2 - ab}} when a = −2 and b = 3.",
        options: ["−2", "−10", "10", "2"],
        answerIndex: 2,
        explanation: "{{a^2 = (-2)^2 = 4}} and {{ab = (-2) * 3 = -6}}. So {{a^2 - ab = 4 - (-6) = 10}}. −2 comes from {{4 - 6}}, but subtracting −6 means adding 6. 2 treats {{(-2)^2}} as −4: {{-4 - (-6) = 2}}. −10 makes both of those slips: {{-4 - 6}}.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Work out {{a^2}} and ab separately first.", "{{(-2)^2 = 4}} and {{ab = -6}}.", "Subtracting a negative: what is {{4 - (-6)}}?"],
        strategy: "Replace letters with brackets",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q14",
        question: "The rectangle has height 4x and is split into two parts with areas {{4x^2}} and 12x. Which expression gives its total length?",
        diagram: `<svg viewBox="0 0 260 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A rectangle of height 4x split into two parts, with areas 4x squared and 12x. The total length is marked with a question mark. Not to scale."><rect x="0" y="0" width="260" height="170" fill="#ffffff"/><rect x="50" y="20" width="90" height="100" fill="#c7d2fe" stroke="#1f2937" stroke-width="2"/><rect x="140" y="20" width="90" height="100" fill="#fde68a" stroke="#1f2937" stroke-width="2"/><g stroke="#334155" stroke-width="1.5"><line x1="50" y1="135" x2="230" y2="135"/><line x1="50" y1="129" x2="50" y2="141"/><line x1="230" y1="129" x2="230" y2="141"/></g><g font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle"><text x="95" y="75" font-style="italic">4x²</text><text x="185" y="75" font-style="italic">12x</text><text x="42" y="75" text-anchor="end" font-style="italic">4x</text><text x="140" y="157">length = ?</text></g><text x="252" y="165" font-family="sans-serif" fill="#1f2937" font-size="11" text-anchor="end">not to scale</text></svg>`,
        options: ["{{x + 3}}", "{{x + 12}}", "{{4x + 3}}", "{{x^2 + 3x}}"],
        answerIndex: 0,
        explanation: "Area = height × length, so the length is the total area ÷ 4x. Part by part: {{4x^2 ÷ 4x = x}} and {{12x ÷ 4x = 3}}, so the length is {{x + 3}}. That is factorising: {{4x^2 + 12x = 4x(x + 3)}}. {{x + 12}} divides only the first part. {{x^2 + 3x}} divides by 4 but forgets the x in 4x. {{4x + 3}} divides {{4x^2}} by x only.",
        difficulty: "core",
        guideRef: "factorising",
        hints: ["Area = height × length, so length = area ÷ height.", "Find each part's length: {{4x^2 ÷ 4x}} and {{12x ÷ 4x}}.", "This is factorising: {{4x^2 + 12x = 4x(…)}}."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q15",
        question: "Zara expands and simplifies {{5(x + 3) - (x - 4)}} and gets {{4x + 11}}. What is the correct answer, and what went wrong?",
        options: ["{{4x + 11}}: her answer is correct", "{{6x + 11}}: she should have added the x-terms", "{{4x - 1}}: the 5 should multiply only the x", "{{4x + 19}}: she wrote −4 where it should be +4"],
        answerIndex: 3,
        explanation: "The minus in front of the second bracket multiplies both of its terms: {{-(x - 4) = -x + 4}}. So {{5x + 15 - x + 4 = 4x + 19}}. Zara wrote {{-x - 4}}, which gave her {{4x + 11}}. {{4x - 1}} treats {{5(x + 3)}} as {{5x + 3}}, but the 5 multiplies every term inside. {{6x + 11}} adds the x instead of subtracting it.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["{{-(x - 4)}} means {{-1 * (x - 4)}}.", "What is {{-1 * (-4)}}?", "Expand both brackets fully, then collect like terms."],
        strategy: "Spot the error",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q16",
        question: "Expand and simplify {{(x - 4)(x + 6)}}.",
        options: ["{{x^2 - 2x - 24}}", "{{x^2 + 2x - 24}}", "{{x^2 + 2x + 24}}", "{{x^2 - 24}}"],
        answerIndex: 1,
        explanation: "Grid: {{x * x = x^2}}, {{x * 6 = 6x}}, {{-4 * x = -4x}} and {{-4 * 6 = -24}}. Total: {{x^2 + 6x - 4x - 24 = x^2 + 2x - 24}}. {{x^2 - 2x - 24}} mixes up the signs: +6x and −4x make +2x. {{x^2 + 2x + 24}} loses the minus on −4 × 6. {{x^2 - 24}} misses the two middle terms.",
        difficulty: "core",
        guideRef: "double-brackets",
        hints: ["Multiply every term in the first bracket by every term in the second. A grid helps.", "Keep each sign with its term: the terms are x and −4, then x and +6.", "The middle terms are +6x and −4x. Collect them."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q17",
        question: "Which statement is true for **no** value of x?",
        options: ["{{2x = x + 2}}", "{{x + 5 = x + 7}}", "{{x^2 = 4}}", "{{2(x + 1) = 2x + 2}}"],
        answerIndex: 1,
        explanation: "Take x away from both sides of {{x + 5 = x + 7}} and you get 5 = 7, which is impossible, so no value of x works. {{2x = x + 2}} is an equation with one solution, x = 2. {{x^2 = 4}} has two solutions, 2 and −2. {{2(x + 1) = 2x + 2}} is an identity: it is true for every x.",
        difficulty: "core",
        guideRef: "language-of-algebra",
        hints: ["For each one, ask: one value? Every value? No value?", "What happens if you subtract x from both sides of each?", "If the letters disappear and what is left is false, no value can work."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q18",
        question: "{{2^n + 2^n = 2^k}}. What is k in terms of n?",
        options: ["{{2n}}", "{{n}}", "{{n + 1}}", "{{n^2}}"],
        answerIndex: 2,
        explanation: "{{2^n + 2^n}} is two lots of {{2^n}}, which is {{2 * 2^n = 2^1 * 2^n = 2^(n+1)}}. So k = n + 1. Check with n = 3: 8 + 8 = 16 = {{2^4}}. {{2n}} comes from adding the indices, but that law is for **multiplying** powers: {{2^3 * 2^3 = 64}}, not 16. {{n}} treats {{2^n + 2^n}} as if it were just {{2^n}}.",
        difficulty: "challenge",
        guideRef: "simplifying",
        hints: ["Try n = 3. What is {{2^3 + 2^3}} as a power of 2?", "Two lots of something is 2 × that something.", "Write the 2 as {{2^1}} and use the index law for multiplying."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q19",
        question: "{{a(x + 3) + b(x - 1) ≡ 5x + 7}}, where a and b are numbers. Find a and b.",
        options: ["a = 2, b = 3", "a = 4, b = 1", "a = 2, b = −1", "a = 3, b = 2"],
        answerIndex: 3,
        explanation: "Expand: {{ax + 3a + bx - b = (a + b)x + 3a - b}}. Matching the x-terms gives {{a + b = 5}}; matching the numbers gives {{3a - b = 7}}. Adding these, 4a = 12, so a = 3 and b = 2. Check: {{3x + 9 + 2x - 2 = 5x + 7}}. a = 2, b = 3 and a = 4, b = 1 match the x-terms but not the number: for example {{2x + 6 + 3x - 3 = 5x + 3}}. a = 2, b = −1 matches only the number: {{2x + 6 - x + 1 = x + 7}}.",
        difficulty: "challenge",
        guideRef: "expanding",
        hints: ["Expand the left-hand side and collect the x-terms and the number terms.", "For an identity, the x-terms must match AND the numbers must match.", "{{a + b = 5}} and {{3a - b = 7}}. What happens if you add these?"],
        strategy: "Match coefficients",
      },
      {
        kind: "mcq",
        id: "expressions-m2-q20",
        question: "The area of a circle is {{A = pi r^2}}. Which formula gives r in terms of A?",
        options: ["{{r = sqrt(A/pi)}}", "{{r = A/(2pi)}}", "{{r = sqrt(A)/pi}}", "{{r = (A/pi)^2}}"],
        answerIndex: 0,
        explanation: "r is squared, then multiplied by π. Undo in reverse: divide by π to get {{r^2 = A/pi}}, then square root: {{r = sqrt(A/pi)}}. {{r = A/(2pi)}} treats 'squared' as 'times 2', but the inverse of squaring is square-rooting, not halving. {{r = (A/pi)^2}} squares instead of square-rooting. {{r = sqrt(A)/pi}} does the inverses in the wrong order.",
        difficulty: "challenge",
        guideRef: "changing-the-subject",
        hints: ["What happens to r? It is squared, then multiplied by π.", "Undo the × π first: {{r^2 = A/pi}}.", "What is the inverse of squaring?"],
        strategy: "Use the inverse",
      },
    ],
  },
  {
    id: "expressions-m3",
    title: "MCQ Paper 3",
    questions: [
      {
        kind: "mcq",
        id: "expressions-m3-q01",
        question: "Which of these means the same as {{3n}}?",
        options: ["{{n * n * n}}", "{{n + 3}}", "{{n + n + n}}", "{{30 + n}}"],
        answerIndex: 2,
        explanation: "{{3n}} means 3 × n, which is three lots of n: {{n + n + n}}. {{n * n * n}} is {{n^3}}: three n's multiplied, not added. {{n + 3}} adds 3 instead of multiplying by 3. {{30 + n}} reads 3n like a two-digit number with n as the units digit.",
        difficulty: "warmup",
        guideRef: "language-of-algebra",
        hints: ["Try n = 5. What is 3n? Which option also gives that?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q02",
        question: "Write {{a * a * a * b * b}} in its simplest form.",
        options: ["{{a^3 b^2}}", "{{3a + 2b}}", "{{a^3 + b^2}}", "{{(ab)^5}}"],
        answerIndex: 0,
        explanation: "Three a's multiplied make {{a^3}} and two b's multiplied make {{b^2}}, so the product is {{a^3 b^2}}. {{3a + 2b}} counts the letters by adding, but they are multiplied. {{a^3 + b^2}} puts a + between parts that are multiplied together. {{(ab)^5}} would need five a's and five b's.",
        difficulty: "warmup",
        guideRef: "simplifying",
        hints: ["Count how many a's and how many b's are multiplied. An index counts repeated multiplication."],
        strategy: "Use the index laws",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q03",
        question: "Find the value of {{(x + 3)/2}} when x = 7.",
        options: ["8.5", "6.5", "10", "5"],
        answerIndex: 3,
        explanation: "The fraction line acts like a bracket: work out the top first, {{7 + 3 = 10}}, then divide by 2 to get 5. 8.5 divides only the 3 by 2 ({{7 + 1.5}}). 6.5 divides only the 7. 10 forgets to divide at all.",
        difficulty: "warmup",
        guideRef: "substitution",
        hints: ["Work out the whole of the top line before you divide."],
        strategy: "Use the order of operations",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q04",
        question: "Expand {{x(x + 3)}}.",
        options: ["{{x^2 + 3}}", "{{x^2 + 3x}}", "{{5x}}", "{{4x^2}}"],
        answerIndex: 1,
        explanation: "x multiplies both terms: {{x * x = x^2}} and {{x * 3 = 3x}}, so {{x^2 + 3x}}. {{x^2 + 3}} forgets to multiply the 3. {{5x}} comes from thinking {{x * x = 2x}}, then adding 3x. {{4x^2}} adds the unlike terms {{x^2}} and 3x.",
        difficulty: "warmup",
        guideRef: "expanding",
        hints: ["x multiplies every term inside the bracket, and {{x * x = x^2}}, not 2x."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q05",
        question: "Ethan has x stickers. Siti has 7 more stickers than Ethan. How many stickers do they have altogether?",
        options: ["{{x + 7}}", "{{2x + 7}}", "{{7x}}", "{{2x + 14}}"],
        answerIndex: 1,
        explanation: "Siti has {{x + 7}}, so together they have {{x + (x + 7) = 2x + 7}}. {{x + 7}} is just Siti's stickers. {{2x + 14}} adds the extra 7 twice, but only Siti has 7 extra. {{7x}} multiplies instead of adding.",
        difficulty: "warmup",
        guideRef: "writing-expressions",
        hints: ["Write Siti's amount first, then add Ethan's."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q06",
        question: "When m = −4, which expression has the **greatest** value?",
        options: ["{{m^3}}", "{{-m^2}}", "{{10 - m}}", "{{m^2}}"],
        answerIndex: 3,
        explanation: "{{m^2 = (-4)^2 = 16}}, {{10 - m = 10 - (-4) = 14}}, {{-m^2 = -16}} (square first, then make it negative) and {{m^3 = (-4)^3 = -64}}. So {{m^2}} is greatest. If you chose {{m^3}}, you treated {{(-4)^3}} as +64, but three negatives multiply to a negative. {{10 - m}} is close, but 14 is less than 16. {{-m^2}} is not {{(-m)^2}}: the minus is applied after squaring.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Work out all four values before comparing.", "Squaring a negative gives a positive; cubing a negative gives a negative.", "{{-m^2}} means: square m, then make the result negative."],
        strategy: "Replace letters with brackets",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q07",
        question: "Simplify {{(15a^2 b)/(5ab)}}.",
        options: ["{{3a}}", "{{10a}}", "{{3a^3}}", "3"],
        answerIndex: 0,
        explanation: "Divide the numbers: 15 ÷ 5 = 3. Cancel the letters: {{a^2 ÷ a = a}} and {{b ÷ b = 1}}. Result: {{3a}}. {{10a}} subtracts 5 from 15 instead of dividing. {{3a^3}} adds the indices of a, but when dividing you subtract them. 3 cancels all the a's, but there are two on top and only one underneath.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Split it up: numbers, then a's, then b's.", "For {{a^2 ÷ a}}, write the top as a × a and cancel.", "b ÷ b = 1, so b disappears completely."],
        strategy: "Use the index laws",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q08",
        question: "The diagram shows a rectangle 4 units high and {{2x + 5}} units long, split into two parts. Which statement does it show?",
        diagram: `<svg viewBox="0 0 270 100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A rectangle 4 units high split into two parts. The left part is 2x wide and the right part is 5 wide. Each part has a question mark inside."><rect x="0" y="0" width="270" height="100" fill="#ffffff"/><rect x="40" y="30" width="140" height="56" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><rect x="180" y="30" width="70" height="56" fill="#fecaca" stroke="#1f2937" stroke-width="2"/><g font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle"><text x="110" y="22" font-style="italic">2x</text><text x="215" y="22">5</text><text x="30" y="63" text-anchor="end">4</text><text x="110" y="63">?</text><text x="215" y="63">?</text></g></svg>`,
        options: ["{{4(2x + 5) = 8x + 5}}", "{{4(2x + 5) = 6x + 9}}", "{{4(2x + 5) = 8x + 20}}", "{{4(2x + 5) = 2x + 20}}"],
        answerIndex: 2,
        explanation: "The whole area is {{4(2x + 5)}}. The two parts have areas {{4 * 2x = 8x}} and {{4 * 5 = 20}}, so the total is {{8x + 20}}. {{8x + 5}} forgets that the second part is 4 units high too. {{6x + 9}} adds the 4 instead of multiplying. {{2x + 20}} forgets that the first part is 4 units high.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["Find the area of each part: height × width.", "Left part: 4 × 2x. Right part: 4 × 5.", "The whole rectangle's area equals the sum of the two parts."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q09",
        question: "Factorise fully {{10a^2 - 15ab}}.",
        options: ["{{5(2a^2 - 3ab)}}", "{{a(10a - 15b)}}", "{{5a(2a + 3b)}}", "{{5a(2a - 3b)}}"],
        answerIndex: 3,
        explanation: "The HCF of 10 and 15 is 5, and both terms contain a, so take out 5a: {{10a^2 ÷ 5a = 2a}} and {{-15ab ÷ 5a = -3b}}, giving {{5a(2a - 3b)}}. {{5(2a^2 - 3ab)}} misses the common factor a. {{a(10a - 15b)}} misses the common factor 5. {{5a(2a + 3b)}} loses the minus sign: it expands to {{10a^2 + 15ab}}.",
        difficulty: "core",
        guideRef: "factorising",
        hints: ["Find the HCF of 10 and 15, then check which letters appear in both terms.", "The HCF is 5a.", "Divide each term by 5a, keeping its sign, then check by expanding."],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q10",
        question: "For a CCA trip, a coach costing $250 is shared equally by n students, and each student also pays $12 entry. Which formula gives the cost, C dollars, for each student?",
        options: ["{{C = (250 + 12)/n}}", "{{C = 250/n + 12}}", "{{C = 250n + 12}}", "{{C = 250/n + 12n}}"],
        answerIndex: 1,
        explanation: "Each student's share of the coach is {{250/n}}, and each pays their own $12, so {{C = 250/n + 12}}. Check with n = 25: $10 + $12 = $22. {{C = (250 + 12)/n}} shares the entry fee as well, but every student pays the full $12. {{C = 250/n + 12n}} charges each student the entry fee for everybody. {{C = 250n + 12}} multiplies instead of sharing.",
        difficulty: "core",
        guideRef: "writing-expressions",
        hints: ["Try a number: if 25 students go, how much does each pay?", "Which cost is shared, and which does every student pay in full?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q11",
        question: "Use {{s = 1/2 (u + v)t}} to find s when u = 4, v = 10 and t = 6.",
        options: ["84", "62", "42", "72"],
        answerIndex: 2,
        explanation: "Bracket first: {{u + v = 14}}. Then {{1/2 * 14 * 6 = 7 * 6 = 42}}. 84 forgets the half. 62 ignores the bracket and works out {{1/2 * 4 + 10 * 6}}. 72 halves only the u: {{(2 + 10) * 6}}.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Which part must be worked out first?", "{{u + v = 14}}. Now multiply by t and halve, in either order."],
        strategy: "Use the order of operations",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q12",
        question: "Ravi makes x the subject of {{y = 5x - 2}}. His working is:\n\n    {{y - 2 = 5x}}\n    {{x = (y - 2)/5}}\n\nWhat was his mistake?",
        options: ["He should add 2, not subtract it: {{x = (y + 2)/5}}", "No mistake: {{x = (y - 2)/5}} is correct", "He should divide first: {{x = y/5 + 2}}", "He should subtract 5: {{x = y + 2 - 5}}"],
        answerIndex: 0,
        explanation: "In {{y = 5x - 2}}, 2 is subtracted, so to undo it you **add** 2 to both sides: {{y + 2 = 5x}}, giving {{x = (y + 2)/5}}. Ravi repeated the operation instead of using its inverse. Test it with x = 1: then y = 3, and {{(3 + 2)/5 = 1}}, but {{(3 - 2)/5 = 0.2}}. {{x = y/5 + 2}} uses the inverses in the wrong order. {{x = y + 2 - 5}} undoes × 5 by subtracting 5, but the inverse of × 5 is ÷ 5.",
        difficulty: "core",
        guideRef: "changing-the-subject",
        hints: ["What is the inverse of − 2?", "Test his formula: choose x = 1, work out y, then put that y into his answer. Do you get 1 back?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q13",
        question: "Expand and simplify {{x(x + 5) - 2(x - 3)}}.",
        options: ["{{x^2 + 3x + 6}}", "{{x^2 + 3x - 6}}", "{{x^2 + 7x + 6}}", "{{x^2 + 3x + 3}}"],
        answerIndex: 0,
        explanation: "{{x(x + 5) = x^2 + 5x}} and {{-2(x - 3) = -2x + 6}}. Collect: {{x^2 + 5x - 2x + 6 = x^2 + 3x + 6}}. {{x^2 + 3x - 6}} gets {{-2 * (-3)}} wrong: it is +6. {{x^2 + 7x + 6}} adds 2x instead of subtracting it. {{x^2 + 3x + 3}} forgets to multiply the 3 by 2.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["Expand each bracket separately. The −2 belongs to the second bracket.", "{{-2 * x = -2x}}. What is {{-2 * (-3)}}?", "Collect the x-terms: 5x − 2x."],
        strategy: "Expand, then collect",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q14",
        question: "Bubble tea costs $b and a potato curry puff costs $c. Arjun buys 3 bubble teas and 2 curry puffs. Priya buys 1 bubble tea and 4 curry puffs. How much more, in dollars, does Arjun spend than Priya?",
        options: ["{{2b + 6c}}", "{{4b + 6c}}", "{{2b - 2c}}", "{{2c - 2b}}"],
        answerIndex: 2,
        explanation: "Arjun spends {{3b + 2c}} and Priya spends {{b + 4c}}. The difference is {{(3b + 2c) - (b + 4c) = 3b + 2c - b - 4c = 2b - 2c}}. {{2b + 6c}} subtracts only Priya's b; the whole of her bill must be subtracted, so −4c too. {{4b + 6c}} adds the two bills. {{2c - 2b}} subtracts the wrong way round.",
        difficulty: "core",
        guideRef: "writing-expressions",
        hints: ["Write an expression for each person's spending.", "'How much more' means Arjun's total − Priya's total. Put Priya's total in a bracket.", "The minus sign applies to both terms in the bracket."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q15",
        question: "The perimeter of a rectangle is {{P = 2(l + w)}}. Which formula has w as the subject?",
        options: ["{{w = (P - l)/2}}", "{{w = P/2 - l}}", "{{w = P - 2l}}", "{{w = 2P - l}}"],
        answerIndex: 1,
        explanation: "Divide by 2 first: {{P/2 = l + w}}. Then subtract l: {{w = P/2 - l}}. {{w = (P - l)/2}} subtracts l before halving, but l is inside the bracket, so it was doubled too. Test with l = 5, w = 3: P = 16, and {{16/2 - 5 = 3}}, but {{(16 - 5)/2 = 5.5}}. {{w = 2P - l}} doubles instead of halving. {{w = P - 2l}} forgets to halve at the end.",
        difficulty: "core",
        guideRef: "changing-the-subject",
        hints: ["What was the last thing done to the bracket? Undo that first.", "The bracket is multiplied by 2, so divide both sides by 2.", "{{P/2 = l + w}}. Now undo the + l."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q16",
        question: "Expand and simplify {{(x + 3)^2}}.",
        options: ["{{x^2 + 9}}", "{{x^2 + 3x + 9}}", "{{2x + 6}}", "{{x^2 + 6x + 9}}"],
        answerIndex: 3,
        explanation: "{{(x + 3)^2}} means {{(x + 3)(x + 3)}}. A grid gives {{x^2}}, 3x, 3x and 9, so the answer is {{x^2 + 6x + 9}}. {{x^2 + 9}} squares each term separately and misses both 3x pieces: try x = 1, where {{4^2 = 16}}, not 10. {{x^2 + 3x + 9}} counts only one of the 3x cells. {{2x + 6}} doubles instead of squaring.",
        difficulty: "core",
        guideRef: "double-brackets",
        hints: ["Write the square as two brackets multiplied together.", "Use a grid with x and 3 across the top and x and 3 down the side.", "There are two 3x cells. Add all four cells."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q17",
        question: "a + b = 7 and ab = 10. What is the value of {{a^2 b + ab^2}}?",
        options: ["150", "200", "17", "70"],
        answerIndex: 3,
        explanation: "Factorise first: {{a^2 b + ab^2 = ab(a + b) = 10 * 7 = 70}}. (Or spot that a = 5, b = 2 works: {{25 * 2 + 5 * 4 = 50 + 20 = 70}}.) 150 squares the whole of ab in {{ab^2}}, but the power belongs only to b. 200 squares ab in both terms. 17 just adds 7 and 10.",
        difficulty: "challenge",
        guideRef: "substitution",
        hints: ["Is there a common factor in {{a^2 b}} and {{ab^2}}?", "Both terms contain ab.", "{{a^2 b + ab^2 = ab(a + b)}}. Now substitute."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q18",
        question: "Factorise fully {{3x(x + 2) + 5(x + 2)}}.",
        options: ["{{(x + 2)(3x + 5)}}", "{{(x + 2)^2(3x + 5)}}", "{{8x(x + 2)}}", "{{3x^2 + 11x + 10}}"],
        answerIndex: 0,
        explanation: "The bracket {{(x + 2)}} is a common factor of both terms. Treat it like a single letter, say B: {{3xB + 5B = B(3x + 5)}}. So the answer is {{(x + 2)(3x + 5)}}. {{8x(x + 2)}} adds 3x and 5, which are unlike terms. {{3x^2 + 11x + 10}} is equal in value, but it is the **expanded** form, not factorised. {{(x + 2)^2(3x + 5)}} keeps both copies of the bracket instead of taking it out once.",
        difficulty: "challenge",
        guideRef: "factorising",
        hints: ["What do the two terms have in common?", "Replace {{(x + 2)}} with a single letter, say B. Now factorise {{3xB + 5B}}.", "Take B out to get {{B(3x + 5)}}, then put {{(x + 2)}} back."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q19",
        question: "A square patio is n tiles long and n tiles wide. The tiles around the edge are yellow; the diagram shows n = 5. Which formula gives the number of yellow tiles, Y?",
        diagram: `<svg viewBox="0 0 170 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A 5 by 5 square of tiles. The 16 tiles around the edge are shaded yellow and the 9 tiles in the middle are white."><rect x="0" y="0" width="170" height="170" fill="#ffffff"/><rect x="20" y="12" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="46" y="12" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="72" y="12" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="98" y="12" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="124" y="12" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="20" y="38" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="46" y="38" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="72" y="38" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="98" y="38" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="124" y="38" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="20" y="64" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="46" y="64" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="72" y="64" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="98" y="64" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="124" y="64" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="20" y="90" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="46" y="90" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="72" y="90" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="98" y="90" width="26" height="26" fill="#ffffff" stroke="#334155" stroke-width="1.5"/><rect x="124" y="90" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="20" y="116" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="46" y="116" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="72" y="116" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="98" y="116" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><rect x="124" y="116" width="26" height="26" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><text x="85" y="162" font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle">n = 5</text></svg>`,
        options: ["{{Y = 4n}}", "{{Y = 4n - 8}}", "{{Y = 4n - 4}}", "{{Y = n^2}}"],
        answerIndex: 2,
        explanation: "Each of the 4 sides has n tiles, giving 4n, but each corner tile belongs to two sides, so the 4 corners have been counted twice. So {{Y = 4n - 4}}. Check with n = 5: 20 − 4 = 16, and the diagram has 16 yellow tiles. {{Y = 4n}} double-counts the corners. {{Y = 4n - 8}} removes the corners completely. {{Y = n^2}} counts every tile, not just the edge.",
        difficulty: "challenge",
        guideRef: "writing-expressions",
        hints: ["Count the yellow tiles in the diagram. Does 4 × 5 match?", "Which tiles belong to two sides at once?", "Count 4 sides of n tiles, then fix the corners."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m3-q20",
        question: "Make x the subject of {{ax + b = cx}}, where c ≠ a.",
        options: ["{{x = b/(a - c)}}", "{{x = b/(c - a)}}", "{{x = (cx - b)/a}}", "{{x = b/c - a}}"],
        answerIndex: 1,
        explanation: "Collect the x-terms on one side: {{b = cx - ax}}. Factorise: {{b = x(c - a)}}. Divide: {{x = b/(c - a)}}. {{x = b/(a - c)}} slips a sign when moving the x-terms across. {{x = (cx - b)/a}} looks like an answer but still has x on the right-hand side, so x is not yet the subject. {{x = b/c - a}} loses the bracket: dividing by {{(c - a)}} is not the same as dividing by c and then subtracting a.",
        difficulty: "challenge",
        guideRef: "changing-the-subject",
        hints: ["x appears twice. Get both x-terms on the same side.", "Subtract ax from both sides: {{b = cx - ax}}.", "x is a common factor on the right. Factorise, then divide."],
        strategy: "Make it simpler",
      },
    ],
  },
  {
    id: "expressions-m4",
    title: "MCQ Paper 4",
    questions: [
      {
        kind: "mcq",
        id: "expressions-m4-q01",
        question: "Jun writes {{x + y = 10}} and says, 'So x must be 5.' Which statement is correct?",
        options: ["Jun is right: x and y must be equal, so each is 5", "x and y must be different numbers, so x cannot be 5", "x cannot have any value, because there are two letters", "x could be many values: for example x = 3 and y = 7"],
        answerIndex: 3,
        explanation: "{{x + y = 10}} has lots of solutions: x = 3 and y = 7, x = 5 and y = 5, x = 9.5 and y = 0.5, and so on. So x is not fixed at 5. Different letters *can* stand for the same number (x = y = 5 works), but they don't *have* to, so 'x cannot be 5' is wrong too.",
        difficulty: "warmup",
        guideRef: "language-of-algebra",
        hints: ["Can you find two different pairs of numbers that add to 10?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q02",
        question: "Simplify {{4m + 3 - m - 7}}.",
        options: ["{{5m - 4}}", "{{3m - 4}}", "{{3m + 4}}", "{{3m - 10}}"],
        answerIndex: 1,
        explanation: "m-terms: {{4m - m = 3m}}. Numbers: {{3 - 7 = -4}}. So {{3m - 4}}. {{5m - 4}} adds the m instead of subtracting it: the minus sign in front belongs to the m. {{3m + 4}} gets the sign of 3 − 7 wrong. {{3m - 10}} works out 3 − 7 as −10.",
        difficulty: "warmup",
        guideRef: "simplifying",
        hints: ["Each term carries the sign in front of it: the terms are +4m, +3, −m and −7."],
        strategy: "Group like terms",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q03",
        question: "Find the value of {{5 - 3t}} when t = −2.",
        options: ["−1", "−4", "11", "4"],
        answerIndex: 2,
        explanation: "{{3t = 3 * (-2) = -6}}, so {{5 - 3t = 5 - (-6) = 11}}. −1 comes from {{5 - 6}}, but subtracting −6 means adding 6. −4 works from left to right, doing {{(5 - 3) * (-2)}}, but multiplication comes first. 4 treats 3t as 3 + t.",
        difficulty: "warmup",
        guideRef: "substitution",
        hints: ["Work out 3t first, then subtract it from 5. Watch the double negative."],
        strategy: "Replace letters with brackets",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q04",
        question: "Factorise {{7y - 21}}.",
        options: ["{{7(y - 3)}}", "{{7(y - 21)}}", "{{7(y + 3)}}", "{{y(7 - 21)}}"],
        answerIndex: 0,
        explanation: "7 is a factor of both terms: {{7y - 21 = 7(y - 3)}}. Check: {{7 * y = 7y}} and {{7 * (-3) = -21}}. {{7(y + 3)}} loses the minus sign: it expands to {{7y + 21}}. {{7(y - 21)}} forgets to divide 21 by 7. {{y(7 - 21)}} takes out y, but 21 has no y in it.",
        difficulty: "warmup",
        guideRef: "factorising",
        hints: ["Take out 7, divide each term by 7, and check by expanding."],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q05",
        question: "A square has sides of length {{(x + 2)}} cm. Which expression gives its perimeter in cm?",
        options: ["{{4x + 8}}", "{{4x + 2}}", "{{(x + 2)^2}}", "{{2x + 4}}"],
        answerIndex: 0,
        explanation: "There are four equal sides: {{4(x + 2) = 4x + 8}}. {{4x + 2}} multiplies only the x by 4, but every side has the extra 2. {{(x + 2)^2}} is the area, not the perimeter. {{2x + 4}} counts only two sides.",
        difficulty: "warmup",
        guideRef: "writing-expressions",
        hints: ["A square has 4 equal sides, each {{x + 2}} long. Add them all."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q06",
        question: "Which of these is a **like term** with {{3x^2 y}}?",
        options: ["{{3xy^2}}", "{{3x^2}}", "{{-5yx^2}}", "{{x^2 y^2}}"],
        answerIndex: 2,
        explanation: "Like terms have exactly the same letters with the same powers. {{-5yx^2}} is {{-5x^2 y}} written in a different order (you can multiply in any order), so it is like {{3x^2 y}}; the coefficient and its sign don't matter. {{3xy^2}} has the same letters, but the square is on y instead of x. {{3x^2}} has no y. {{x^2 y^2}} has y squared, not y.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Like terms need the same letters AND the same power on each letter.", "Does the order of the letters matter? Is {{yx^2}} the same as {{x^2 y}}?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q07",
        question: "What is the coefficient of x in {{(3x - 4)/2}}?",
        options: ["3", "−2", "{{1/2}}", "{{3/2}}"],
        answerIndex: 3,
        explanation: "Dividing the whole top by 2 divides each term: {{(3x - 4)/2 = 3/2 x - 2}}. So the coefficient of x is {{3/2}} (that is, 1.5). 3 ignores the division by 2. −2 is the constant term, {{-4/2}}. {{1/2}} keeps the halving but forgets the 3.",
        difficulty: "core",
        guideRef: "language-of-algebra",
        hints: ["Split the fraction: divide each term on the top by 2.", "{{(3x)/2 = 3/2 x}}. Which number is multiplying x?"],
        strategy: "Split into terms",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q08",
        question: "Expand {{-x(4 - x)}}.",
        options: ["{{-4x - x^2}}", "{{x^2 - 4x}}", "{{4x - x^2}}", "{{x^2 - 4}}"],
        answerIndex: 1,
        explanation: "Multiply −x by each term: {{-x * 4 = -4x}} and {{-x * (-x) = +x^2}}. That gives {{-4x + x^2}}, usually written {{x^2 - 4x}}. {{-4x - x^2}} slips on the second term: negative × negative is positive. {{4x - x^2}} ignores the minus sign in front of the x. {{x^2 - 4}} forgets the x when multiplying the 4.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["The −x multiplies both terms, and its minus sign comes too.", "For {{-x * (-x)}}: what is the sign, and what is the power?", "Negative × negative = positive, and {{x * x = x^2}}."],
        strategy: "Draw an area model",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q09",
        question: "The energy of a moving trolley is {{E = 1/2 m v^2}}. Estimate E when m = 3.9 and v = 5.1, by first rounding each value to the nearest whole number.",
        options: ["10", "100", "50", "200"],
        answerIndex: 2,
        explanation: "Round: m ≈ 4 and v ≈ 5. Then {{E ≈ 1/2 * 4 * 5^2 = 1/2 * 4 * 25 = 50}}. (The exact value is about 50.7, so the estimate is good.) 10 forgets to square v. 100 forgets the half. 200 squares {{m * v}} instead of just v, but the power belongs only to v.",
        difficulty: "core",
        guideRef: "substitution",
        hints: ["Round m and v to the nearest whole number.", "Which part is squared: only v, or m and v together?", "Square v first, then multiply by m and halve."],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q10",
        question: "Kai factorises {{4x^2 + 8x}} and writes {{4(x^2 + 2x)}}. Which statement is correct?",
        options: ["It is correct but not fully factorised: the answer is {{4x(x + 2)}}", "It is fully factorised, because 4 is the HCF of 4 and 8", "It is wrong: the answer is {{4x(x + 8)}}", "It is wrong: the answer is {{x(4x + 8)}}"],
        answerIndex: 0,
        explanation: "Kai's answer does expand back to {{4x^2 + 8x}}, but the bracket {{x^2 + 2x}} still has a common factor, x. The HCF of the two terms is 4x, so fully factorised it is {{4x(x + 2)}}. Saying '4 is the HCF' looks only at the numbers; the letters count too. {{x(4x + 8)}} is also only partly factorised. {{4x(x + 8)}} forgets to divide the 8x by 4x.",
        difficulty: "core",
        guideRef: "factorising",
        hints: ["Expand Kai's answer. Is it equal to the original?", "Look inside his bracket. Do its terms still share a factor?", "The HCF includes letters as well as numbers."],
        strategy: "Spot the error",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q11",
        question: "Mei spends {{2/5}} of her pocket money, $p, on books, and then $3 on a snack. Which expression gives how much she has left, in dollars?",
        options: ["{{p - 2/5 - 3}}", "{{3/5 p - 3}}", "{{2/5 p - 3}}", "{{3/5 (p - 3)}}"],
        answerIndex: 1,
        explanation: "The books cost {{2/5 p}}, which leaves {{p - 2/5 p = 3/5 p}}. Then the snack: {{3/5 p - 3}}. Check with p = 20: books $8, snack $3, left $9, and {{3/5 * 20 - 3 = 9}}. {{p - 2/5 - 3}} takes away {{2/5}} of a dollar instead of {{2/5}} of p. {{3/5 (p - 3)}} pays for the snack first, but she buys the books first. {{2/5 p - 3}} works with what she spent on books, not what she kept.",
        difficulty: "core",
        guideRef: "writing-expressions",
        hints: ["Try it with a number first, say p = 20.", "The books cost {{2/5}} of p, not {{2/5}} of a dollar. What fraction of p is left?", "After the books she has {{3/5}} of p. Now take off the snack."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q12",
        question: "Which of these is **not** equal to {{x^6}}?",
        options: ["{{x^2 * x^4}}", "{{x^3 * x^3}}", "{{x^8 ÷ x^2}}", "{{x^12 ÷ x^2}}"],
        answerIndex: 3,
        explanation: "When dividing, subtract the indices: {{x^12 ÷ x^2 = x^10}}, not {{x^6}}. Dividing 12 by 2 is the trap. The others are all {{x^6}}: {{x^2 * x^4 = x^(2+4)}}, {{x^3 * x^3 = x^(3+3)}} and {{x^8 ÷ x^2 = x^(8-2)}}. If you picked {{x^3 * x^3}}, you multiplied the indices to get {{x^9}}, but three x's times three x's is six x's.",
        difficulty: "core",
        guideRef: "simplifying",
        hints: ["Use the index laws on each one.", "Multiplying: add the indices. Dividing: subtract them.", "Find the one that does not come out as {{x^6}}."],
        strategy: "Use the index laws",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q13",
        question: "Which expression is **not** equivalent to {{6(2x - 3)}}?",
        options: ["{{12x - 18}}", "{{6 * 2x - 3}}", "{{3(4x - 6)}}", "{{2(6x - 9)}}"],
        answerIndex: 1,
        explanation: "{{6(2x - 3) = 12x - 18}}. But {{6 * 2x - 3}} is {{12x - 3}}: the 6 multiplies only the 2x, which is exactly the mistake brackets prevent. {{3(4x - 6)}} and {{2(6x - 9)}} both expand to {{12x - 18}}, so they *are* equivalent, just not fully factorised.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["Expand or work out each option.", "Which one gives something other than {{12x - 18}}?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q14",
        question: "{{F = 9/5 C + 32}} converts a temperature in °C to °F. Which formula converts °F back to °C?",
        options: ["{{C = 5/9 F - 32}}", "{{C = 9/5 (F - 32)}}", "{{C = 5/9 (F + 32)}}", "{{C = 5/9 (F - 32)}}"],
        answerIndex: 3,
        explanation: "C is multiplied by {{9/5}}, then 32 is added. Undo in reverse order: subtract 32, then multiply by {{5/9}} (dividing by {{9/5}} is the same as multiplying by {{5/9}}). So {{C = 5/9 (F - 32)}}. Check: F = 212 gives {{5/9 * 180 = 100}} °C, the boiling point of water. {{C = 5/9 F - 32}} undoes the steps in the wrong order. {{C = 9/5 (F - 32)}} forgets to flip the fraction. {{C = 5/9 (F + 32)}} adds 32 instead of subtracting it.",
        difficulty: "core",
        guideRef: "changing-the-subject",
        hints: ["Function machine: C → × {{9/5}} → + 32 → F. Run it backwards.", "First undo the + 32.", "To undo × {{9/5}}, multiply by {{5/9}}."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q15",
        question: "How many values of n make {{4(n + 3) - n = 3(n + 4)}} true?",
        options: ["Every value of n", "Only n = 0", "No values", "Exactly one value, n = 3"],
        answerIndex: 0,
        explanation: "Simplify both sides. The left is {{4n + 12 - n = 3n + 12}} and the right is {{3n + 12}}. They are the same expression, so the statement is true for every n: it is an identity. 'Only n = 0' comes from testing just one value. n = 0 does work, but so do n = 1, n = 10 and every other number. 'No values' assumes that two sides which look different can never be equal.",
        difficulty: "core",
        guideRef: "language-of-algebra",
        hints: ["Expand and simplify each side separately.", "Compare the two simplified sides. What do you notice?"],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q16",
        question: "Which statement about {{3(2x - 1) - 2(3x - 4)}} is true?",
        options: ["It equals −11 for every value of x", "It equals 1 for every value of x", "It equals 5 for every value of x", "It depends on x: it simplifies to {{12x + 5}}"],
        answerIndex: 2,
        explanation: "Expand: {{3(2x - 1) = 6x - 3}} and {{-2(3x - 4) = -6x + 8}}. The x-terms cancel: {{6x - 6x - 3 + 8 = 5}}. So it is 5 whatever x is. −11 comes from writing {{-2 * (-4)}} as −8. 1 comes from forgetting to multiply the 4 by 2. {{12x + 5}} treats {{-2 * 3x}} as +6x.",
        difficulty: "core",
        guideRef: "expanding",
        hints: ["Expand both brackets. The −2 belongs to the second one.", "What are {{-2 * 3x}} and {{-2 * (-4)}}?", "Collect the x-terms. What happens to them?"],
        strategy: "Expand, then collect",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q17",
        question: "Which statement is true for the sum of **any** three consecutive whole numbers?",
        options: ["It is always a multiple of 3", "It is always even", "It is always a multiple of 6", "It is always odd"],
        answerIndex: 0,
        explanation: "Call the numbers n, n + 1 and n + 2. Their sum is {{n + (n + 1) + (n + 2) = 3n + 3 = 3(n + 1)}}, which is always a multiple of 3 (in fact, 3 times the middle number). 'Always even' and 'always a multiple of 6' come from testing only 1 + 2 + 3 = 6; try 2 + 3 + 4 = 9. 'Always odd' fails for 1 + 2 + 3 = 6.",
        difficulty: "challenge",
        guideRef: "simplifying",
        hints: ["Try a few examples: 1 + 2 + 3, 2 + 3 + 4, 3 + 4 + 5.", "Call the smallest number n. Write the other two in terms of n.", "Add and simplify {{n + (n + 1) + (n + 2)}}. Can you factorise the result?"],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q18",
        question: "Arjun notices that {{n^2 - n + 11}} gives a prime number when n = 1, 2 and 3. He claims it gives a prime for every whole number n. Which value of n proves him wrong?",
        options: ["n = 4", "n = 11", "n = 5", "n = 10"],
        answerIndex: 1,
        explanation: "When n = 11, every term is a multiple of 11: {{11^2 - 11 + 11 = 121 = 11 * 11}}, which is not prime. The other values really do give primes: n = 4 gives 23, n = 5 gives 31 and n = 10 gives 101. If you got 15, 16 or 21 for those, you worked out {{n^2}} as 2n instead of n × n.",
        difficulty: "challenge",
        guideRef: "substitution",
        hints: ["Testing values one at a time could take a while. Is there a value of n that makes all three terms share a factor?", "Look at the 11 on the end. Which n would make {{n^2}} and n multiples of 11 as well?"],
        strategy: "Look for a common factor",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q19",
        question: "Make a the subject of {{s = ut + 1/2 a t^2}}.",
        options: ["{{a = (2s - ut)/t^2}}", "{{a = (2(s - ut))/t}}", "{{a = (2(s - ut))/t^2}}", "{{a = (s - ut)/(2t^2)}}"],
        answerIndex: 2,
        explanation: "Subtract ut: {{s - ut = 1/2 a t^2}}. Multiply by 2: {{2(s - ut) = a t^2}}. Divide by {{t^2}}: {{a = (2(s - ut))/t^2}}. {{(2s - ut)/t^2}} doubles only the s, but the whole of {{s - ut}} must be doubled. {{(s - ut)/(2t^2)}} divides by 2 instead of multiplying: the inverse of halving is doubling. {{(2(s - ut))/t}} divides by t instead of by {{t^2}}.",
        difficulty: "challenge",
        guideRef: "changing-the-subject",
        hints: ["First get the term containing a on its own.", "{{s - ut = 1/2 a t^2}}. Now undo the half.", "{{2(s - ut) = a t^2}}. Finally undo the × {{t^2}}."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expressions-m4-q20",
        question: "A square of side {{x + 4}} has a square of side x cut from one corner, leaving the shaded L-shape. Which expression gives the shaded area?",
        diagram: `<svg viewBox="0 0 200 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A large square of side x + 4. A smaller square of side x is cut out of the top-left corner, leaving a shaded L-shape. The top edge is marked x then 4, and the left edge is marked x then 4."><rect x="0" y="0" width="200" height="180" fill="#ffffff"/><rect x="40" y="25" width="140" height="140" fill="#fde68a" stroke="#1f2937" stroke-width="2"/><rect x="40" y="25" width="100" height="100" fill="#ffffff" stroke="#1f2937" stroke-width="1.5" stroke-dasharray="5 4"/><g stroke="#334155" stroke-width="1.5"><line x1="140" y1="19" x2="140" y2="31"/><line x1="34" y1="125" x2="46" y2="125"/></g><g font-family="sans-serif" fill="#1f2937" font-size="14" text-anchor="middle"><text x="90" y="17" font-style="italic">x</text><text x="160" y="17">4</text><text x="30" y="80" text-anchor="end" font-style="italic">x</text><text x="30" y="150" text-anchor="end">4</text><text x="90" y="80" font-size="12">cut out</text></g></svg>`,
        options: ["16", "{{4x + 16}}", "{{x^2 + 8x + 16}}", "{{8x + 16}}"],
        answerIndex: 3,
        explanation: "{{(x + 4)^2 = x^2 + 4x + 4x + 16 = x^2 + 8x + 16}}. Take away the {{x^2}} square to leave {{8x + 16}}. You can see this in the diagram: two x-by-4 strips (4x each) plus a 4-by-4 corner (16). 16 comes from thinking {{(x + 4)^2 = x^2 + 16}}, which misses both strips. {{4x + 16}} counts only one strip. {{x^2 + 8x + 16}} forgets to remove the cut-out square.",
        difficulty: "challenge",
        guideRef: "double-brackets",
        hints: ["Shaded area = big square − small square.", "Expand {{(x + 4)^2}} using a grid. How many pieces are there?", "Or split the L-shape into rectangles: two strips and a small corner square."],
        strategy: "Draw a diagram",
      },
    ],
  },
];
