import type { TopicPractice } from "../../types.ts";

// Expressions & Formulae — quiz, two practice papers and the challenge set.

export const practice: TopicPractice = {
  // ===========================================================================
  // QUIZ — quick check of the whole topic (4 mcq, 5 short, 1 written)
  // ===========================================================================
  quiz: [
    {
      kind: "mcq",
      id: "expressions-quiz-q01",
      question: "Which of these statements is true for **every** value of x (an identity)?",
      options: ["{{3(x + 2) = 3x + 6}}", "{{3x + 2 = 11}}", "{{2(x + 3) = 2x + 3}}", "{{x^2 = 2x}}"],
      answerIndex: 0,
      explanation:
        "Expanding gives {{3(x + 2) = 3x + 6}} for any x, so it is an identity: we can write {{3(x + 2) ≡ 3x + 6}}. {{3x + 2 = 11}} is an equation, true only when x = 3. {{x^2 = 2x}} is only true when x = 0 or x = 2, because {{x^2}} means x × x, not 2 × x. {{2(x + 3) = 2x + 3}} is never true: the 2 must multiply the 3 as well, giving 2x + 6.",
      difficulty: "warmup",
      guideRef: "language-of-algebra",
      hints: ["Try x = 5 in each statement. Which ones still balance? Then try a different value."],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "expressions-quiz-q02",
      question: "Simplify {{9c + 2d - 4c + d}}.",
      answer: { type: "expression", expr: "5c+3d", form: "simplified" },
      traps: [
        { spec: { type: "expression", expr: "5c+2d" }, feedback: "Nearly. The last term is d, which means 1d. So 2d + d = 3d." },
        { spec: { type: "expression", expr: "13c+3d" }, feedback: "The 4c has a minus sign in front of it, so it is subtracted: 9c − 4c = 5c." },
      ],
      solution: [
        "Group the like terms, keeping each sign with its term: {{9c - 4c}} and {{2d + d}}.",
        "{{9c - 4c = 5c}} and {{2d + 1d = 3d}}.",
        "c-terms and d-terms are unlike, so stop here: {{5c + 3d}}.",
      ],
      commonError: "Forgetting that d on its own means 1d.",
      difficulty: "warmup",
      guideRef: "simplifying",
      hints: ["Which terms are 'like' terms — with exactly the same letter part? Keep each sign with the term after it."],
      strategy: "Group like terms",
    },
    {
      kind: "short",
      id: "expressions-quiz-q03",
      question: "Find the value of {{5a - 2b}} when a = 4 and b = −3.",
      answer: { type: "number", value: 26 },
      traps: [
        { spec: { type: "number", value: 14 }, feedback: "You worked out 20 − 6. But 2b = 2 × (−3) = −6, and subtracting −6 is the same as adding 6." },
      ],
      solution: [
        "Put brackets round each value: {{5 * 4 - 2 * (-3)}}.",
        "{{5 * 4 = 20}} and {{2 * (-3) = -6}}.",
        "{{20 - (-6) = 20 + 6 = 26}}.",
      ],
      commonError: "Treating −2b as −2 × 3 and forgetting that b itself is negative.",
      difficulty: "warmup",
      guideRef: "substitution",
      hints: ["Write the values in brackets: {{5(4) - 2(-3)}}. What is {{2 * (-3)}}, and what happens when you subtract it?"],
      strategy: "Use brackets for negatives",
    },
    {
      kind: "mcq",
      id: "expressions-quiz-q04",
      question: "Expand {{-5(2x - 3)}}.",
      options: ["{{-10x - 15}}", "{{-10x + 15}}", "{{-10x - 3}}", "{{10x - 15}}"],
      answerIndex: 1,
      explanation:
        "Multiply −5 by **each** term inside: {{-5 * 2x = -10x}} and {{-5 * (-3) = +15}}, giving {{-10x + 15}}. {{-10x - 15}} forgets that negative × negative is positive. {{-10x - 3}} only multiplies the first term. {{10x - 15}} ignores the minus sign in front of the 5.",
      difficulty: "core",
      guideRef: "expanding",
      hints: [
        "The −5 multiplies everything inside the bracket — both terms.",
        "Work out {{-5 * 2x}} and {{-5 * (-3)}} separately.",
        "Negative × negative = positive, so {{-5 * (-3) = +15}}.",
      ],
      strategy: "Use the area model",
    },
    {
      kind: "mcq",
      id: "expressions-quiz-q05",
      question: "Which of these is {{10x^2 + 15x}} factorised **fully**?",
      options: ["{{x(10x + 15)}}", "{{5(2x^2 + 3x)}}", "{{5x(2x + 3)}}", "{{5x(2x + 3x)}}"],
      answerIndex: 2,
      explanation:
        "The HCF of {{10x^2}} and 15x is 5x (5 is the HCF of 10 and 15, and both terms contain x). {{10x^2 ÷ 5x = 2x}} and {{15x ÷ 5x = 3}}, so {{10x^2 + 15x = 5x(2x + 3)}}. {{x(10x + 15)}} and {{5(2x^2 + 3x)}} are correct but not *fully* factorised: 10x + 15 still has a common factor 5, and {{2x^2 + 3x}} still has a common factor x. {{5x(2x + 3x)}} is wrong: it expands to {{25x^2}}, because 15x ÷ 5x leaves 3, not 3x.",
      difficulty: "core",
      guideRef: "factorising",
      hints: [
        "Find the HCF of the numbers 10 and 15 first.",
        "Do both terms contain an x? Then x is part of the HCF too.",
        "Take 5x outside the bracket and divide each term by 5x.",
      ],
      strategy: "Check by expanding",
    },
    {
      kind: "mcq",
      id: "expressions-quiz-q06",
      question: "Simplify {{4x^3 * 5x^2}}.",
      options: ["{{20x^6}}", "{{9x^5}}", "{{9x^6}}", "{{20x^5}}"],
      answerIndex: 3,
      explanation:
        "Multiply the numbers and use the index law for the letters: {{4 * 5 = 20}} and {{x^3 * x^2 = x^(3+2) = x^5}}, so the answer is {{20x^5}}. {{20x^6}} multiplies the indices instead of adding them. {{9x^5}} adds the numbers 4 and 5 instead of multiplying them. {{9x^6}} makes both mistakes.",
      difficulty: "core",
      guideRef: "simplifying",
      hints: [
        "Deal with the numbers and the letters separately.",
        "Write {{x^3 * x^2}} out in full: {{(x * x * x) * (x * x)}}. How many x's are multiplied?",
        "Numbers multiply: 4 × 5. Indices add: 3 + 2.",
      ],
      strategy: "Write it out in full",
    },
    {
      kind: "short",
      id: "expressions-quiz-q07",
      question:
        "Marcus is m years old. His sister Zara is 3 years younger than half of Marcus's age. Write a simplified expression for the **sum** of their ages in 5 years' time.",
      answer: { type: "expression", expr: "3m/2+7", display: "{{3/2 m + 7}} (or {{(3m + 14)/2}})" },
      traps: [
        { spec: { type: "expression", expr: "3m/2+2" }, feedback: "Both of them get 5 years older, so you need to add 5 twice: once for Marcus and once for Zara." },
        { spec: { type: "expression", expr: "3m/2-3" }, feedback: "That is the sum of their ages *now*. In 5 years' time each of them is 5 years older." },
      ],
      solution: [
        "Now: Marcus is m and Zara is {{m/2 - 3}}.",
        "In 5 years: Marcus is {{m + 5}} and Zara is {{m/2 - 3 + 5 = m/2 + 2}}.",
        "Sum: {{m + 5 + m/2 + 2 = 3/2 m + 7}}.",
        "Check with m = 12: Zara is 3 now. In 5 years they are 17 and 8, total 25, and {{3/2 * 12 + 7 = 18 + 7 = 25}}. ✓",
      ],
      commonError: "Adding the 5 years to only one person.",
      difficulty: "core",
      guideRef: "writing-expressions",
      hints: [
        "Try it with a number first: if Marcus is 12, how old is Zara? What is the total in 5 years?",
        "Zara's age now is {{m/2 - 3}}. Write both ages in 5 years' time.",
        "Add the two expressions: {{m + m/2 = 3/2 m}}.",
      ],
      strategy: "Try small cases",
    },
    {
      kind: "short",
      id: "expressions-quiz-q08",
      question: "Make x the subject of {{y = 7 - 2x}}.",
      answer: { type: "expression", expr: "(7-y)/2", display: "{{x = (7 - y)/2}}" },
      traps: [
        { spec: { type: "expression", expr: "(y-7)/2" }, feedback: "Sign slip. Test it: x = 1 gives y = 5, but {{(5 - 7)/2 = -1}}, not 1. Try adding 2x to both sides first so the x-term is positive." },
        { spec: { type: "expression", expr: "7-y/2" }, feedback: "Brackets needed: the whole of 7 − y is divided by 2, so write {{(7 - y)/2}}." },
      ],
      solution: [
        "Add 2x to both sides so the x-term is positive: {{y + 2x = 7}}.",
        "Subtract y from both sides: {{2x = 7 - y}}.",
        "Divide both sides by 2: {{x = (7 - y)/2}}.",
        "Check with x = 1: y = 7 − 2 = 5, and {{(7 - 5)/2 = 1}}. ✓",
      ],
      solutions: [
        {
          label: "Undo in reverse order",
          steps: [
            "Subtract 7 from both sides: {{y - 7 = -2x}}.",
            "Divide both sides by −2: {{x = (y - 7)/(-2)}}, which is the same as {{(7 - y)/2}}.",
            "Both routes work; adding 2x first is quicker because you never divide by a negative.",
          ],
        },
      ],
      commonError: "Losing the minus sign on the 2x.",
      difficulty: "core",
      guideRef: "changing-the-subject",
      hints: [
        "What has been done to x? It is multiplied by −2, then added to 7.",
        "A negative x-term is awkward. Add 2x to both sides.",
        "From {{y + 2x = 7}}, subtract y, then divide by 2.",
      ],
      strategy: "Use the inverse",
    },
    {
      kind: "written",
      id: "expressions-quiz-q09",
      question: "Ravi simplifies {{3x + 4y}} and writes {{7xy}}. Explain why Ravi is wrong. Use numbers to support your answer.",
      marks: 3,
      modelAnswer:
        "3x and 4y are **unlike terms**: one counts x's and the other counts y's, so they cannot be added together.\n\nTesting with x = 2 and y = 1: {{3x + 4y = 6 + 4 = 10}}, but {{7xy = 7 * 2 * 1 = 14}}. The results are different, so the expressions are not equal. (Careful: x = 1, y = 1 happens to give 7 both times, and one matching example proves nothing.)\n\n7xy means 7 × x × y, which is a different thing altogether. {{3x + 4y}} is already in its simplest form.",
      markScheme: [
        { point: "3x and 4y are not like terms (different letters), so they cannot be combined", keywords: ["like terms", "unlike", "different letters", "cannot be combined", "can't be added", "not like"] },
        { point: "Tests values and shows different results, e.g. x = 2, y = 1 gives 10 and 14", keywords: ["10", "14", "x = 2", "substitute", "different", "not equal"] },
        { point: "States 7xy means 7 × x × y and 3x + 4y is already simplest", keywords: ["7 × x × y", "multiply", "already", "simplest", "cannot be simplified"] },
      ],
      commonError: "Saying 'you can't do that' without explaining why or testing with numbers.",
      difficulty: "core",
      guideRef: "simplifying",
      hints: [
        "Pick numbers for x and y, say x = 2 and y = 1. Work out both expressions.",
        "What makes two terms 'like terms'?",
      ],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "expressions-quiz-q10",
      question: "Expand and simplify {{(n + 3)^2 - (n + 1)^2}}.",
      answer: { type: "expression", expr: "4n+8", form: "simplified" },
      traps: [
        { spec: { type: "expression", expr: "8" }, feedback: "{{(n + 3)^2}} is not {{n^2 + 9}}. Write it as {{(n + 3)(n + 3)}} and use a grid: there are two 3n terms." },
        { spec: { type: "expression", expr: "8n+10" }, feedback: "The minus sign applies to the whole of {{(n + 1)^2 = n^2 + 2n + 1}}. Keep it in a bracket: {{-(n^2 + 2n + 1) = -n^2 - 2n - 1}}." },
      ],
      solution: [
        "{{(n + 3)^2 = (n + 3)(n + 3) = n^2 + 3n + 3n + 9 = n^2 + 6n + 9}}.",
        "{{(n + 1)^2 = (n + 1)(n + 1) = n^2 + 2n + 1}}.",
        "Subtract the whole of the second: {{n^2 + 6n + 9 - (n^2 + 2n + 1) = n^2 + 6n + 9 - n^2 - 2n - 1}}.",
        "Collect like terms: {{4n + 8}}.",
        "Check with n = 1: {{4^2 - 2^2 = 16 - 4 = 12}} and {{4 * 1 + 8 = 12}}. ✓",
        "Bonus: {{4n + 8 = 4(n + 2)}}, so the answer is always a multiple of 4.",
      ],
      solutions: [
        {
          label: "Difference of two squares (stretch)",
          steps: [
            "{{A^2 - B^2 = (A - B)(A + B)}}, with A = n + 3 and B = n + 1.",
            "{{A - B = 2}} and {{A + B = 2n + 4}}.",
            "So the answer is {{2(2n + 4) = 4n + 8}}. Slicker if you know the pattern; expanding both squares is the safe method.",
          ],
        },
      ],
      commonError: "Writing {{(n + 3)^2 = n^2 + 9}}.",
      difficulty: "challenge",
      guideRef: "double-brackets",
      hints: [
        "{{(n + 3)^2}} means {{(n + 3)(n + 3)}}, not {{n^2 + 9}}.",
        "Expand each square with a grid, then subtract.",
        "Put the second expansion in a bracket before you subtract: {{-(n^2 + 2n + 1)}}.",
      ],
      strategy: "Check by substituting",
    },
  ],

  // ===========================================================================
  // PRACTICE PAPERS — 16 short + 4 written each, easy → hard
  // ===========================================================================
  papers: [
    {
      id: "expressions-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "expressions-p1-q01",
          question: "Simplify {{8m - 3m + m}}.",
          answer: { type: "expression", expr: "6m", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "4m" }, feedback: "The minus sign belongs only to the 3m. The last m has a + in front, so 8m − 3m = 5m, then 5m + m = 6m." },
            { spec: { type: "expression", expr: "5m" }, feedback: "Don't lose the last term: m on its own means 1m, so 5m + m = 6m." },
          ],
          solution: ["Work left to right, keeping each sign with its term: {{8m - 3m = 5m}}.", "Then {{5m + m = 5m + 1m = 6m}}."],
          commonError: "Treating the minus sign as if it applies to every term after it.",
          difficulty: "warmup",
          guideRef: "simplifying",
          hints: ["m on its own means 1m. Take the terms one at a time, from left to right."],
          strategy: "Group like terms",
        },
        {
          kind: "short",
          id: "expressions-p1-q02",
          question: "Find the value of {{3n^2}} when n = 4.",
          answer: { type: "number", value: 48 },
          traps: [
            { spec: { type: "number", value: 144 }, feedback: "Only n is squared, not 3n. You worked out {{(3n)^2 = 12^2}}. Instead, {{3n^2 = 3 * n^2 = 3 * 16}}." },
            { spec: { type: "number", value: 24 }, feedback: "{{n^2}} means n × n = 16, not 2 × n = 8." },
          ],
          solution: ["The index applies only to n: {{3n^2 = 3 * n^2}}.", "{{n^2 = 4^2 = 16}}.", "{{3 * 16 = 48}}."],
          commonError: "Squaring the 3 as well as the n.",
          difficulty: "warmup",
          guideRef: "substitution",
          hints: ["Which part is squared: 3n, or just n?"],
          strategy: "Use the order of operations",
        },
        {
          kind: "short",
          id: "expressions-p1-q03",
          question: "Expand {{4(3x - 2)}}.",
          answer: { type: "expression", expr: "12x-8", form: "expanded" },
          traps: [
            { spec: { type: "expression", expr: "12x-2" }, feedback: "The 4 multiplies **every** term inside the bracket, including the 2: {{4 * (-2) = -8}}." },
          ],
          solution: ["Multiply the 4 by each term inside: {{4 * 3x = 12x}} and {{4 * (-2) = -8}}.", "So {{4(3x - 2) = 12x - 8}}."],
          commonError: "Multiplying only the first term in the bracket.",
          difficulty: "warmup",
          guideRef: "expanding",
          hints: ["The 4 multiplies both terms inside the bracket."],
          strategy: "Use the area model",
        },
        {
          kind: "short",
          id: "expressions-p1-q04",
          question:
            "At a hawker centre, a plate of vegetarian bee hoon costs $4 and a cup of kopi costs $k. Write a formula for C, the total cost in dollars of 3 plates of bee hoon and 2 cups of kopi.",
          answer: { type: "expression", expr: "12+2k", display: "{{C = 12 + 2k}}" },
          traps: [
            { spec: { type: "expression", expr: "14+k" }, feedback: "Two cups of kopi cost 2 × k = 2k dollars, not k + 2." },
            { spec: { type: "expression", expr: "4+2k" }, feedback: "That's only one plate. Three plates cost 3 × 4 = $12." },
          ],
          solution: ["Three plates cost {{3 * 4 = 12}} dollars.", "Two cups cost {{2 * k = 2k}} dollars.", "So {{C = 12 + 2k}}."],
          commonError: "Writing k + 2 for the cost of two cups.",
          difficulty: "warmup",
          guideRef: "writing-expressions",
          hints: ["Try it with a price for the kopi first, say $2. Then replace the 2 with k."],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "expressions-p1-q05",
          question: "In the expression {{x^2 - 6xy + 9y^2}}, what is the coefficient of xy?",
          answer: { type: "number", value: -6, display: "−6" },
          traps: [
            { spec: { type: "number", value: 6 }, feedback: "The sign in front of a term belongs to it. The xy-term is −6xy, so its coefficient is −6." },
            { spec: { type: "number", value: 9 }, feedback: "9 is the coefficient of {{y^2}}. Look for the term whose letter part is exactly xy." },
          ],
          solution: ["The terms are {{x^2}}, {{-6xy}} and {{9y^2}}.", "The xy-term is {{-6xy}}, so the number multiplying xy is −6."],
          difficulty: "warmup",
          guideRef: "language-of-algebra",
          hints: ["List the terms, keeping each sign with the term after it."],
        },
        {
          kind: "short",
          id: "expressions-p1-q06",
          question: "Simplify {{5y^2 - 3y + 2y^2 + y - 4y^2}}.",
          answer: { type: "expression", expr: "3y^2-2y", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "y^2" }, feedback: "{{y^2}} and y are not like terms ({{y^2}} means y × y). Collect the {{y^2}} terms and the y terms separately." },
            { spec: { type: "expression", expr: "3y^2-4y" }, feedback: "Check the y-terms: {{-3y + y = -2y}}. The y has a + in front of it." },
          ],
          solution: [
            "Like terms have exactly the same letter part. {{y^2}} terms: {{5y^2 + 2y^2 - 4y^2}}. y terms: {{-3y + y}}.",
            "{{5y^2 + 2y^2 - 4y^2 = 3y^2}}.",
            "{{-3y + 1y = -2y}}.",
            "Answer: {{3y^2 - 2y}}. These two are unlike terms, so stop.",
          ],
          commonError: "Combining {{y^2}} terms with y terms.",
          difficulty: "core",
          guideRef: "simplifying",
          hints: [
            "Underline the {{y^2}} terms in one colour and the y terms in another.",
            "Keep each sign with its term: the y-terms are −3y and +y.",
            "{{5 + 2 - 4 = 3}} for the {{y^2}} terms.",
          ],
          strategy: "Group like terms",
        },
        {
          kind: "short",
          id: "expressions-p1-q07",
          question: "Simplify {{(6a^4 * 2a^3)/(4a^5)}}.",
          answer: { type: "expression", expr: "3a^2", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "3a^7" }, feedback: "When you multiply, **add** the indices: {{a^4 * a^3 = a^7}} (not {{a^12}}). Then {{a^7 ÷ a^5 = a^2}}." },
            { spec: { type: "expression", expr: "2a^2" }, feedback: "Multiply the numbers on top: {{6 * 2 = 12}} (not 6 + 2). Then {{12 ÷ 4 = 3}}." },
          ],
          solution: [
            "Top: multiply the numbers and add the indices: {{6 * 2 = 12}} and {{a^4 * a^3 = a^7}}, so the top is {{12a^7}}.",
            "Divide: {{12 ÷ 4 = 3}} and {{a^7 ÷ a^5 = a^(7-5) = a^2}}.",
            "Answer: {{3a^2}}.",
          ],
          commonError: "Multiplying the indices instead of adding them.",
          difficulty: "core",
          guideRef: "simplifying",
          hints: [
            "Simplify the top first.",
            "Multiplying powers of the same letter: add the indices. Dividing: subtract them.",
            "The top is {{12a^7}}. Now divide by {{4a^5}}.",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "expressions-p1-q08",
          question: "Find the value of {{2x^2 - 5x}} when x = −3.",
          answer: { type: "number", value: 33 },
          traps: [
            { spec: { type: "number", value: -3 }, feedback: "{{(-3)^2 = +9}}, not −9: a negative times a negative is positive. So {{2x^2 = 18}}." },
            { spec: { type: "number", value: 3 }, feedback: "{{-5x = -5 * (-3) = +15}}, so you add 15 rather than subtract it." },
          ],
          solution: [
            "Use brackets: {{2 * (-3)^2 - 5 * (-3)}}.",
            "Index first: {{(-3)^2 = 9}}, so {{2 * 9 = 18}}.",
            "{{-5 * (-3) = +15}}.",
            "{{18 + 15 = 33}}.",
          ],
          commonError: "Writing {{(-3)^2 = -9}}.",
          difficulty: "core",
          guideRef: "substitution",
          hints: [
            "Write −3 in brackets every time you see x.",
            "Square first: {{(-3)^2 = (-3) * (-3)}}. Positive or negative?",
            "{{-5 * (-3)}} is positive too.",
          ],
          strategy: "Use brackets for negatives",
        },
        {
          kind: "short",
          id: "expressions-p1-q09",
          question: "Expand and simplify {{4(3x - 1) - 2(x - 6)}}.",
          answer: { type: "expression", expr: "10x+8", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "10x-16" }, feedback: "{{-2 * (-6) = +12}}, not −12. A negative times a negative is positive." },
            { spec: { type: "expression", expr: "10x+2" }, feedback: "Multiply −2 by **both** terms in the second bracket: {{-2 * (-6) = +12}}, so the constant is −4 + 12 = 8." },
          ],
          solution: [
            "Expand the first bracket: {{4(3x - 1) = 12x - 4}}.",
            "Expand the second, multiplying by −2: {{-2(x - 6) = -2x + 12}}.",
            "Collect: {{12x - 2x - 4 + 12 = 10x + 8}}.",
            "Check with x = 1: {{4(2) - 2(-5) = 8 + 10 = 18}} and {{10 + 8 = 18}}. ✓",
          ],
          commonError: "Getting the sign of the last term wrong after multiplying by a negative.",
          difficulty: "core",
          guideRef: "expanding",
          hints: [
            "Treat −2 as the number in front of the second bracket, sign included.",
            "Work out {{-2 * x}} and {{-2 * (-6)}}.",
            "You should get {{12x - 4 - 2x + 12}}. Now collect like terms.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "expressions-p1-q10",
          question: "Factorise fully {{9y^2 - 12y}}.",
          answer: { type: "expression", expr: "3y(3y-4)", form: "factorised" },
          traps: [
            { spec: { type: "expression", expr: "3(3y-4)" }, feedback: "Expand to check: {{3(3y - 4) = 9y - 12}}. Both terms also have a factor y, so the HCF is 3y." },
            { spec: { type: "expression", expr: "3y(3y-4y)" }, feedback: "{{12y ÷ 3y = 4}}, not 4y. Expand to check: your answer gives {{-3y^2}}." },
          ],
          solution: [
            "HCF of 9 and 12 is 3. Both terms contain y, so the HCF is 3y.",
            "Divide each term by 3y: {{9y^2 ÷ 3y = 3y}} and {{12y ÷ 3y = 4}}.",
            "So {{9y^2 - 12y = 3y(3y - 4)}}.",
            "Check by expanding: {{3y * 3y - 3y * 4 = 9y^2 - 12y}}. ✓",
          ],
          commonError: "Stopping at {{3(3y^2 - 4y)}} or {{y(9y - 12)}}: the bracket still has a common factor, so it is not fully factorised.",
          difficulty: "core",
          guideRef: "factorising",
          hints: [
            "What is the HCF of 9 and 12?",
            "Is there a letter in both terms too?",
            "Take 3y outside the bracket and divide each term by 3y.",
          ],
          strategy: "Check by expanding",
        },
        {
          kind: "short",
          id: "expressions-p1-q11",
          question:
            "A ribbon is x cm long. Mei cuts 15 cm off it, then shares the rest equally between 4 friends. Write an expression for the length of ribbon, in cm, that each friend gets.",
          answer: { type: "expression", expr: "(x-15)/4", display: "{{(x - 15)/4}}" },
          traps: [
            { spec: { type: "expression", expr: "x-15/4" }, feedback: "Brackets needed: the *whole* of x − 15 is shared by 4, so write {{(x - 15)/4}}." },
            { spec: { type: "expression", expr: "x/4-15" }, feedback: "Order matters: Mei cuts the 15 cm off **first**, then shares. Your expression shares first, then cuts." },
          ],
          solution: [
            "After the cut, the ribbon is {{x - 15}} cm long.",
            "Sharing equally between 4 means dividing **all** of it by 4.",
            "Each friend gets {{(x - 15)/4}} cm. (You could also write {{1/4 (x - 15)}} or {{x/4 - 15/4}}.)",
          ],
          commonError: "Missing out the brackets, which divides only the 15 by 4.",
          difficulty: "core",
          guideRef: "writing-expressions",
          hints: [
            "Try it with x = 55 first: how long is each piece?",
            "Write down what is left after the cut, as an expression.",
            "Divide the whole of that by 4: you need a bracket or a fraction line.",
          ],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "expressions-p1-q12",
          question: "Fill in the bracket: {{10a^3 - 15a^2 + 5a = 5a(…)}}. What expression goes inside the bracket?",
          answer: { type: "expression", expr: "2a^2-3a+1" },
          traps: [
            { spec: { type: "expression", expr: "2a^2-3a" }, feedback: "{{5a ÷ 5a = 1}}, not 0. Expanding your bracket gives only two terms, but the original has three." },
            { spec: { type: "expression", expr: "2a^3-3a^2+a" }, feedback: "Divide each term by 5a, not just by 5: each power of a drops by one." },
          ],
          solution: [
            "Divide each term by 5a.",
            "{{10a^3 ÷ 5a = 2a^2}}, {{15a^2 ÷ 5a = 3a}} and {{5a ÷ 5a = 1}}.",
            "So the bracket is {{2a^2 - 3a + 1}}.",
            "Check: {{5a(2a^2 - 3a + 1) = 10a^3 - 15a^2 + 5a}}. ✓",
          ],
          commonError: "Leaving out the 1 when a whole term is taken out.",
          difficulty: "core",
          guideRef: "factorising",
          hints: [
            "Each term inside the bracket is an original term divided by 5a.",
            "Deal with the numbers, then the powers of a.",
            "What is {{5a ÷ 5a}}?",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "expressions-p1-q13",
          question: "Make x the subject of the formula {{y = (x + 3)/5}}.",
          answer: { type: "expression", expr: "5y-3", display: "{{x = 5y - 3}}" },
          traps: [
            { spec: { type: "expression", expr: "5(y-3)" }, feedback: "Undo the steps in reverse order. The last thing done to x was ÷ 5, so multiply by 5 **first**: {{5y = x + 3}}. Then subtract 3." },
            { spec: { type: "expression", expr: "5y+3" }, feedback: "Check the sign: to undo + 3, subtract 3." },
          ],
          solution: [
            "x has 3 added, then the result is divided by 5.",
            "Undo ÷ 5 first: multiply both sides by 5: {{5y = x + 3}}.",
            "Undo + 3: subtract 3 from both sides: {{x = 5y - 3}}.",
            "Check with x = 7: {{y = 10/5 = 2}}, and {{5 * 2 - 3 = 7}}. ✓",
          ],
          commonError: "Undoing the steps in the wrong order.",
          difficulty: "core",
          guideRef: "changing-the-subject",
          hints: [
            "Draw the function machine: x → + 3 → ÷ 5 → y.",
            "Run the machine backwards from y, undoing the last step first.",
            "Multiply both sides by 5, then subtract 3.",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "expressions-p1-q14",
          question:
            "Zara works out the value of {{-x^2 + 3x}} when x = −2. She writes:\n\n    {{-x^2 + 3x = 4 - 6 = -2}}\n\nExplain Zara's mistake and find the correct value.",
          marks: 3,
          modelAnswer:
            "{{-x^2}} means {{-(x^2)}}: square first, then make it negative (the index comes before the minus sign). {{x^2 = (-2)^2 = 4}}, so {{-x^2 = -4}}. Zara worked out {{(-x)^2}} instead, which is +4.\n\nHer 3x part is right: {{3 * (-2) = -6}}.\n\nCorrect value: {{-4 - 6 = -10}}.",
          markScheme: [
            { point: "Explains that {{-x^2}} means square x first, then make it negative (Zara found {{(-x)^2}})", keywords: ["square first", "then negative", "-(x^2)", "(-x)^2", "index", "order"] },
            { point: "Shows {{-x^2 = -4}} when x = −2", keywords: ["-4", "−4"] },
            { point: "Correct value −10", keywords: ["-10", "−10"] },
          ],
          commonError: "Saying the 3x part is wrong: it isn't, because {{3 * (-2) = -6}} is correct.",
          difficulty: "core",
          guideRef: "substitution",
          hints: [
            "In {{-x^2}}, which happens first: the squaring or the minus sign?",
            "Find {{x^2}} first, then put the minus sign in front.",
            "{{(-2)^2 = 4}}, so {{-x^2 = -4}}.",
          ],
          strategy: "Use the order of operations",
        },
        {
          kind: "written",
          id: "expressions-p1-q15",
          question:
            "Jun tries to 'solve' {{2(x + 4) = 2x + 8}}. He expands the bracket, subtracts 2x from both sides and ends up with 8 = 8. He thinks he has made a mistake.\n\nExplain what has happened. What type of statement is {{2(x + 4) = 2x + 8}}, and how could it be written?",
          marks: 3,
          modelAnswer:
            "Jun has not made a mistake. Expanding gives {{2x + 8 = 2x + 8}}: both sides are exactly the same, so the statement is true for **every** value of x (x = 1 gives 10 = 10; x = 5 gives 18 = 18). That is why the x's vanished and left 8 = 8, which is always true.\n\nIt is an **identity**, not an equation, so there is nothing to solve. It can be written with the identity sign: {{2(x + 4) ≡ 2x + 8}}.",
          markScheme: [
            { point: "Both sides are the same after expanding, so it is true for every value of x (8 = 8 is always true)", keywords: ["same", "every value", "any value", "all values", "always true", "8 = 8"] },
            { point: "Names it as an identity, not an equation", keywords: ["identity"] },
            { point: "Uses the ≡ sign", keywords: ["≡", "identically equal", "three lines"] },
          ],
          commonError: "Thinking every statement with an equals sign is an equation with one answer.",
          difficulty: "core",
          guideRef: "language-of-algebra",
          hints: [
            "Try a few values of x in both sides. What do you notice?",
            "An equation is true for particular values. What about this one?",
            "Which symbol means 'is identically equal to'?",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "written",
          id: "expressions-p1-q16",
          question: "Prove that the sum of any three consecutive whole numbers is a multiple of 3.",
          marks: 3,
          modelAnswer:
            "Let the smallest number be n. Then the three consecutive numbers are n, n + 1 and n + 2.\n\n    {{n + (n + 1) + (n + 2) = 3n + 3 = 3(n + 1)}}\n\n{{3(n + 1)}} is 3 × a whole number, so the sum is always a multiple of 3. (In fact it is 3 times the middle number.) Checking examples like 4 + 5 + 6 = 15 is a good start, but only the algebra covers every case.",
          markScheme: [
            { point: "Writes the three numbers using one letter, e.g. n, n + 1, n + 2", keywords: ["n + 1", "n + 2", "n+1", "n+2"] },
            { point: "Adds them to get 3n + 3", keywords: ["3n + 3", "3n+3"] },
            { point: "Factorises as 3(n + 1) and concludes it is a multiple of 3 for every n", keywords: ["3(n + 1)", "3(n+1)", "multiple of 3", "divisible by 3", "factor of 3"] },
          ],
          commonError: "Checking a few examples and calling it a proof.",
          difficulty: "core",
          guideRef: "factorising",
          hints: [
            "Call the smallest number n. What are the next two?",
            "Add your three expressions and simplify.",
            "Can you take a factor of 3 out of {{3n + 3}}?",
          ],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "expressions-p1-q17",
          question:
            "Siti says: 'Think of a number. Add 7. Multiply by 3. Subtract 6. Divide by 3. Now subtract the number you first thought of.'\n\nWhatever number you start with, you always end with the same answer. Use algebra to find it.",
          answer: { type: "number", value: 5 },
          traps: [
            { spec: { type: "number", value: 7 }, feedback: "Follow every step with algebra: the 'subtract 6' and 'divide by 3' change the 7. Start with n and write an expression after each step." },
          ],
          solution: [
            "Start with n.",
            "Add 7: {{n + 7}}.",
            "Multiply by 3: {{3(n + 7) = 3n + 21}}.",
            "Subtract 6: {{3n + 15}}.",
            "Divide by 3: {{(3n + 15)/3 = n + 5}}.",
            "Subtract n: {{n + 5 - n = 5}}. The answer is always 5.",
          ],
          solutions: [
            {
              label: "Try numbers, then trust the algebra",
              steps: [
                "Start with 10: 17, 51, 45, 15, then 15 − 10 = 5.",
                "Start with 1: 8, 24, 18, 6, then 6 − 1 = 5.",
                "Trying numbers is quicker for *finding* the answer, but only the algebra *proves* it works for every starting number.",
              ],
            },
          ],
          difficulty: "challenge",
          guideRef: "writing-expressions",
          hints: [
            "Call the starting number n and write an expression after each step.",
            "After 'multiply by 3' you have {{3(n + 7) = 3n + 21}}.",
            "Dividing {{3n + 15}} by 3 gives {{n + 5}}. What happens when you subtract n?",
          ],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "expressions-p1-q18",
          question: "Expand and simplify {{(2x + 3)(x - 4)}}.",
          answer: { type: "expression", expr: "2x^2-5x-12", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "2x^2-12" }, feedback: "You have only multiplied first × first and last × last. A grid gives four products, including {{2x * (-4) = -8x}} and {{3 * x = 3x}}." },
            { spec: { type: "expression", expr: "2x^2+5x-12" }, feedback: "Check the x-terms: {{-8x + 3x = -5x}}." },
          ],
          solution: [
            "Use a grid with 2x and 3 down the side and x and −4 along the top.",
            "The four products: {{2x * x = 2x^2}}, {{2x * (-4) = -8x}}, {{3 * x = 3x}}, {{3 * (-4) = -12}}.",
            "Add them: {{2x^2 - 8x + 3x - 12 = 2x^2 - 5x - 12}}.",
            "Check with x = 1: {{(5)(-3) = -15}} and {{2 - 5 - 12 = -15}}. ✓",
          ],
          commonError: "Missing out the two middle products.",
          difficulty: "challenge",
          guideRef: "double-brackets",
          hints: [
            "Every term in the first bracket multiplies every term in the second. How many products is that?",
            "Draw a 2 × 2 grid: 2x and 3 on one side, x and −4 on the other.",
            "Collect the two x-terms: {{-8x + 3x}}.",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "expressions-p1-q19",
          question: "Make x the subject of {{y = (3x - 2)/4 + 1}}.",
          answer: { type: "expression", expr: "(4y-2)/3", display: "{{x = (4y - 2)/3}}" },
          traps: [
            { spec: { type: "expression", expr: "(4y-1)/3" }, feedback: "The + 1 was the **last** thing done to x, so undo it **first**: {{y - 1 = (3x - 2)/4}}. Then multiply by 4." },
            { spec: { type: "expression", expr: "(4y-6)/3" }, feedback: "From {{4y - 4 = 3x - 2}} you need to **add** 2 to both sides, giving {{3x = 4y - 2}}." },
          ],
          solution: [
            "Follow x through: × 3, − 2, ÷ 4, + 1 gives y.",
            "Undo + 1: {{y - 1 = (3x - 2)/4}}.",
            "Undo ÷ 4: {{4(y - 1) = 3x - 2}}, so {{4y - 4 = 3x - 2}}.",
            "Undo − 2: {{4y - 2 = 3x}}.",
            "Undo × 3: {{x = (4y - 2)/3}}.",
            "Check with x = 2: {{y = 4/4 + 1 = 2}}, and {{(8 - 2)/3 = 2}}. ✓",
          ],
          commonError: "Undoing the + 1 last instead of first.",
          difficulty: "challenge",
          guideRef: "changing-the-subject",
          hints: [
            "List the operations done to x, in order.",
            "Undo them in reverse order: the + 1 comes off first.",
            "After undoing + 1 and ÷ 4 you should have {{4y - 4 = 3x - 2}}.",
          ],
          strategy: "Work backwards",
        },
        {
          kind: "written",
          id: "expressions-p1-q20",
          question: "Hana says: '{{(a + b)^2 = a^2 + b^2}}'. Is this always true, sometimes true or never true? Justify your answer.",
          marks: 3,
          modelAnswer:
            "**Sometimes true.**\n\nExpanding with a grid: {{(a + b)^2 = (a + b)(a + b) = a^2 + ab + ab + b^2 = a^2 + 2ab + b^2}}.\n\nSo Hana's statement is only true when the extra 2ab is zero, which happens when a = 0 or b = 0. For example, a = 0 and b = 5: {{(0 + 5)^2 = 25}} and {{0^2 + 5^2 = 25}}. ✓\n\nBut it is usually false: a = 1 and b = 2 give {{(1 + 2)^2 = 9}}, while {{1^2 + 2^2 = 5}}.",
          markScheme: [
            { point: "Correct expansion {{(a + b)^2 = a^2 + 2ab + b^2}}", keywords: ["2ab", "a^2 + 2ab + b^2", "a² + 2ab + b²"] },
            { point: "A counter-example showing it can be false, e.g. a = 1, b = 2 gives 9 and 5", keywords: ["9", "5", "counter", "not equal", "false"] },
            { point: "An example showing it can be true (a = 0 or b = 0), so the answer is 'sometimes'", keywords: ["sometimes", "a = 0", "b = 0", "zero"] },
          ],
          commonError: "'Squaring each term': the square of a sum is not the sum of the squares.",
          difficulty: "challenge",
          guideRef: "double-brackets",
          hints: [
            "Test a = 1, b = 2. Then test a = 0, b = 5.",
            "Write {{(a + b)^2}} as {{(a + b)(a + b)}} and expand with a grid.",
            "What extra term appears? When is it zero?",
          ],
          strategy: "Try small cases",
        },
      ],
    },
    {
      id: "expressions-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "expressions-p2-q01",
          question: "The area of a triangle is given by {{A = 1/2 b h}}. Is this an expression, an equation, a formula or an identity?",
          answer: { type: "text", accept: ["formula", "a formula", "it is a formula", "it's a formula"], display: "A formula" },
          traps: [
            { spec: { type: "text", accept: ["equation", "an equation", "it is an equation"] }, feedback: "It has an equals sign, but it isn't a puzzle with one answer to find. It is a rule linking different quantities (area, base and height): a **formula**." },
            { spec: { type: "text", accept: ["identity", "an identity", "it is an identity"] }, feedback: "An identity is the same expression written two ways, true for every value, like {{2(x + 1) ≡ 2x + 2}}. This is a rule linking three different quantities: a **formula**." },
          ],
          solution: [
            "It has an equals sign, so it is not just an expression.",
            "It links different quantities (area A, base b and height h) by a rule you substitute into.",
            "That makes it a **formula**.",
          ],
          difficulty: "warmup",
          guideRef: "language-of-algebra",
          hints: ["Does it link different real quantities by a rule?"],
        },
        {
          kind: "short",
          id: "expressions-p2-q02",
          question: "Simplify {{5xy + 3x - 2yx + x}}.",
          answer: { type: "expression", expr: "3xy+4x", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "7xy+4x" }, feedback: "The 2yx term has a minus sign in front of it: {{5xy - 2xy = 3xy}}." },
            { spec: { type: "expression", expr: "3xy+3x" }, feedback: "x on its own means 1x, so 3x + x = 4x." },
          ],
          solution: [
            "yx is the same as xy (you can multiply in any order), so 5xy and −2yx are like terms.",
            "{{5xy - 2xy = 3xy}}.",
            "{{3x + x = 4x}}.",
            "Answer: {{3xy + 4x}}.",
          ],
          commonError: "Not spotting that xy and yx are like terms.",
          difficulty: "warmup",
          guideRef: "simplifying",
          hints: ["Is yx the same as xy? Then collect the xy-terms and the x-terms separately."],
          strategy: "Group like terms",
        },
        {
          kind: "short",
          id: "expressions-p2-q03",
          question:
            "Hiring a kayak at Sentosa costs C dollars, where {{C = 15 + 8h}} and h is the number of hours. Find the cost, in dollars, of hiring a kayak for 3 hours.",
          answer: { type: "number", value: 39, display: "$39" },
          traps: [
            { spec: { type: "number", value: 69 }, feedback: "Multiply before adding: 8h means 8 × h, so {{C = 15 + 8 * 3 = 15 + 24}}." },
          ],
          solution: ["Substitute h = 3: {{C = 15 + 8 * 3}}.", "Multiply first: {{8 * 3 = 24}}.", "{{C = 15 + 24 = 39}}, so the cost is $39."],
          commonError: "Adding 15 + 8 before multiplying.",
          difficulty: "warmup",
          guideRef: "substitution",
          hints: ["Replace h with 3, then remember: multiply before you add."],
          strategy: "Use the order of operations",
        },
        {
          kind: "short",
          id: "expressions-p2-q04",
          question: "Expand {{x(x + 7)}}.",
          answer: { type: "expression", expr: "x^2+7x", form: "expanded" },
          traps: [
            { spec: { type: "expression", expr: "x^2+7" }, feedback: "The x outside multiplies **both** terms: {{x * 7 = 7x}}." },
            { spec: { type: "expression", expr: "2x+7x" }, feedback: "{{x * x = x^2}}, not 2x. (2x means x + x.)" },
          ],
          solution: ["Multiply x by each term inside: {{x * x = x^2}} and {{x * 7 = 7x}}.", "So {{x(x + 7) = x^2 + 7x}}."],
          commonError: "Writing x × x as 2x.",
          difficulty: "warmup",
          guideRef: "expanding",
          hints: ["Multiply the x outside by each term inside the bracket."],
          strategy: "Use the area model",
        },
        {
          kind: "short",
          id: "expressions-p2-q05",
          question: "Factorise {{5x + 20}}.",
          answer: { type: "expression", expr: "5(x+4)", form: "factorised" },
          traps: [
            { spec: { type: "expression", expr: "5(x+20)" }, feedback: "Divide **both** terms by 5: {{20 ÷ 5 = 4}}. Expand to check: {{5(x + 20) = 5x + 100}}." },
          ],
          solution: ["The HCF of 5 and 20 is 5.", "{{5x ÷ 5 = x}} and {{20 ÷ 5 = 4}}.", "So {{5x + 20 = 5(x + 4)}}. Check: {{5 * x + 5 * 4 = 5x + 20}}. ✓"],
          commonError: "Dividing only the first term by the common factor.",
          difficulty: "warmup",
          guideRef: "factorising",
          hints: ["What is the biggest number that divides both 5 and 20?"],
          strategy: "Check by expanding",
        },
        {
          kind: "short",
          id: "expressions-p2-q06",
          question: "Simplify {{(2x^3)^2 * 3x}}.",
          answer: { type: "expression", expr: "12x^7", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "6x^7" }, feedback: "Everything in the bracket is squared, including the 2: {{(2x^3)^2 = 4x^6}}." },
            { spec: { type: "expression", expr: "12x^6" }, feedback: "The 3x has an x in it too: {{x^6 * x = x^7}}." },
          ],
          solution: [
            "Square the bracket: {{(2x^3)^2 = 2x^3 * 2x^3 = 4x^6}}.",
            "Multiply by 3x: numbers {{4 * 3 = 12}}, letters {{x^6 * x^1 = x^7}}.",
            "Answer: {{12x^7}}.",
          ],
          commonError: "Squaring only the {{x^3}} and forgetting to square the 2.",
          difficulty: "core",
          guideRef: "simplifying",
          hints: [
            "Write the square out: {{(2x^3)^2 = 2x^3 * 2x^3}}.",
            "Multiply the numbers, then add the indices.",
            "x on its own is {{x^1}}.",
          ],
          strategy: "Write it out in full",
        },
        {
          kind: "short",
          id: "expressions-p2-q07",
          question: "Find the value of {{4x^2 + 6x}} when {{x = 1/2}}.",
          answer: { type: "number", value: 4 },
          traps: [
            { spec: { type: "number", value: 7 }, feedback: "Only x is squared: {{4x^2 = 4 * (1/2)^2 = 4 * 1/4 = 1}}. It looks as if you squared 4x." },
            { spec: { type: "number", value: 5 }, feedback: "{{(1/2)^2 = 1/2 * 1/2 = 1/4}}, not {{1/2}}." },
          ],
          solution: ["{{x^2 = (1/2)^2 = 1/4}}, so {{4x^2 = 4 * 1/4 = 1}}.", "{{6x = 6 * 1/2 = 3}}.", "{{1 + 3 = 4}}."],
          commonError: "Thinking that squaring always makes a number bigger: {{(1/2)^2}} is smaller than {{1/2}}.",
          difficulty: "core",
          guideRef: "substitution",
          hints: [
            "Work out {{x^2}} first. What is {{1/2 * 1/2}}?",
            "Then multiply by 4.",
            "{{6 * 1/2}} is half of 6.",
          ],
          strategy: "Use the order of operations",
        },
        {
          kind: "short",
          id: "expressions-p2-q08",
          question:
            "{{x^2 = 2x}} is an equation, not an identity: it is only true for some values of x. Find the **two** values of x that make it true.",
          answer: { type: "list", values: [0, 2], display: "x = 0 or x = 2" },
          solution: [
            "Try small values. x = 0: {{0^2 = 0}} and {{2 * 0 = 0}}. ✓",
            "x = 1: 1 and 2. ✗ x = 2: {{2^2 = 4}} and {{2 * 2 = 4}}. ✓",
            "x = 3: 9 and 6. ✗ For bigger x, {{x^2}} pulls further ahead. For negative x, {{x^2}} is positive but 2x is negative, so they never match.",
            "So x = 0 or x = 2.",
          ],
          commonError: "Missing x = 0 (for example by dividing both sides by x, which is not allowed when x could be 0).",
          difficulty: "core",
          guideRef: "language-of-algebra",
          hints: [
            "Try x = 0, 1, 2, 3, …",
            "Don't forget to test 0.",
            "Could a negative value work? Is {{x^2}} ever negative?",
          ],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "expressions-p2-q09",
          question: "Expand and simplify {{x(x + 4) - 3(x - 2)}}.",
          answer: { type: "expression", expr: "x^2+x+6", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "x^2+x-6" }, feedback: "{{-3 * (-2) = +6}}: negative × negative is positive." },
            { spec: { type: "expression", expr: "x^2+7x+6" }, feedback: "{{-3 * x = -3x}}, so the x-terms are {{4x - 3x = x}}." },
          ],
          solution: [
            "{{x(x + 4) = x^2 + 4x}}.",
            "{{-3(x - 2) = -3x + 6}}.",
            "Collect: {{x^2 + 4x - 3x + 6 = x^2 + x + 6}}.",
            "Check with x = 2: {{2(6) - 3(0) = 12}} and {{4 + 2 + 6 = 12}}. ✓",
          ],
          commonError: "Getting the sign of the 6 wrong after multiplying by −3.",
          difficulty: "core",
          guideRef: "expanding",
          hints: [
            "Expand each bracket separately. The −3 keeps its minus sign.",
            "{{-3 * (-2)}} is positive.",
            "Collect the x-terms: {{4x - 3x}}.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "expressions-p2-q10",
          question: "Factorise fully {{18p^2q + 12pq}}.",
          answer: { type: "expression", expr: "6pq(3p+2)", form: "factorised" },
          traps: [
            { spec: { type: "expression", expr: "6pq(3p+2q)" }, feedback: "{{12pq ÷ 6pq = 2}}: the q cancels completely. Expand to check: your answer gives {{12pq^2}}, not 12pq." },
            { spec: { type: "expression", expr: "6(3p+2)" }, feedback: "Expand to check: {{6(3p + 2) = 18p + 12}}. The HCF includes the letters p and q as well." },
          ],
          solution: [
            "HCF of 18 and 12 is 6.",
            "Both terms contain p (lowest power p) and q, so the HCF is 6pq.",
            "{{18p^2q ÷ 6pq = 3p}} and {{12pq ÷ 6pq = 2}}.",
            "So {{18p^2q + 12pq = 6pq(3p + 2)}}. Check by expanding. ✓",
          ],
          commonError: "Taking out only 6, or only 6p: the bracket then still has a common factor.",
          difficulty: "core",
          guideRef: "factorising",
          hints: [
            "Find the HCF of 18 and 12.",
            "Which letters appear in **both** terms? Use the lowest power of each.",
            "Divide each term by 6pq.",
          ],
          strategy: "Check by expanding",
        },
        {
          kind: "short",
          id: "expressions-p2-q11",
          question: "Arjun's scores in three quizzes were x, x + 6 and 2x − 3. Write a simplified expression for his **mean** score.",
          answer: { type: "expression", expr: "(4x+3)/3", display: "{{(4x + 3)/3}} (or {{4/3 x + 1}})" },
          traps: [
            { spec: { type: "expression", expr: "4x+3" }, feedback: "That's the total. The mean is the total divided by how many scores there are (3)." },
            { spec: { type: "expression", expr: "4x+3/3" }, feedback: "Brackets needed: the whole total is divided by 3, so write {{(4x + 3)/3}}." },
          ],
          solution: [
            "Total: {{x + (x + 6) + (2x - 3) = 4x + 3}}.",
            "Mean = total ÷ number of scores = {{(4x + 3)/3}}.",
            "This can also be written {{4/3 x + 1}}.",
          ],
          commonError: "Dividing only the last term by 3.",
          difficulty: "core",
          guideRef: "writing-expressions",
          hints: [
            "Mean = total ÷ how many.",
            "Add the three expressions and collect like terms first.",
            "Divide the **whole** total by 3.",
          ],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "expressions-p2-q12",
          question:
            "A mobile plan costs $20 a month, which includes 50 GB of data. Each extra GB costs $3. Write a formula for C, the monthly cost in dollars, when g GB of data are used (g is more than 50).",
          answer: { type: "expression", expr: "20+3(g-50)", display: "{{C = 20 + 3(g - 50)}} (or {{C = 3g - 130}})" },
          traps: [
            { spec: { type: "expression", expr: "20+3g" }, feedback: "The first 50 GB are included. Only the extra data, {{g - 50}} GB, costs $3 per GB." },
            { spec: { type: "expression", expr: "20+3g-50" }, feedback: "Brackets needed: the $3 is charged on each of the {{(g - 50)}} extra GB, so write {{3(g - 50)}}." },
          ],
          solution: [
            "Data beyond the 50 GB allowance: {{g - 50}} GB.",
            "Cost of the extra data: {{3(g - 50)}} dollars.",
            "So {{C = 20 + 3(g - 50)}}, which simplifies to {{C = 3g - 130}}.",
            "Check with g = 60: 10 extra GB cost $30, so C = $50, and {{3 * 60 - 130 = 50}}. ✓",
          ],
          commonError: "Charging for all g GB instead of only the extra ones.",
          difficulty: "core",
          guideRef: "writing-expressions",
          hints: [
            "Try it with numbers first: what would 60 GB cost?",
            "How many GB are *extra* if g GB are used?",
            "Monthly fee + $3 × (number of extra GB).",
          ],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "expressions-p2-q13",
          question: "Make b the subject of {{A = 1/2 b h}}.",
          answer: { type: "expression", expr: "2A/h", display: "{{b = (2A)/h}}" },
          traps: [
            { spec: { type: "expression", expr: "A/(2h)" }, feedback: "To undo × {{1/2}}, multiply by 2 (don't divide by 2): {{2A = b h}}." },
            { spec: { type: "expression", expr: "2A-h" }, feedback: "b is **multiplied** by h, so undo it by dividing by h, not subtracting." },
          ],
          solution: [
            "b is multiplied by {{1/2}} and by h.",
            "Multiply both sides by 2: {{2A = b h}}.",
            "Divide both sides by h: {{b = (2A)/h}}.",
            "Check: a triangle with b = 6 and h = 4 has A = 12, and {{(2 * 12)/4 = 6}}. ✓",
          ],
          commonError: "Dividing by 2 to 'undo' the half.",
          difficulty: "core",
          guideRef: "changing-the-subject",
          hints: [
            "What is being done to b?",
            "Get rid of the {{1/2}} first. What undoes halving?",
            "From {{2A = b h}}, divide both sides by h.",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "expressions-p2-q14",
          question:
            "The perimeter of a rectangle is {{P = 2(l + w)}}. Priya makes w the subject and gets {{w = P/2 - l}}. Jun makes w the subject and gets {{w = (P - 2l)/2}}.\n\nShow how each of them could have got their answer, and explain why both answers are correct.",
          marks: 3,
          modelAnswer:
            "**Priya (divide first):** {{P = 2(l + w)}}. Divide both sides by 2: {{P/2 = l + w}}. Subtract l: {{w = P/2 - l}}.\n\n**Jun (expand first):** {{P = 2l + 2w}}. Subtract 2l: {{P - 2l = 2w}}. Divide by 2: {{w = (P - 2l)/2}}.\n\n**Why both are right:** dividing the whole of {{P - 2l}} by 2 is the same as halving each part: {{(P - 2l)/2 = P/2 - (2l)/2 = P/2 - l}}. A numerical check agrees: with l = 3 and w = 5, P = 16. Priya: 8 − 3 = 5 ✓. Jun: {{(16 - 6)/2 = 5}} ✓.",
          markScheme: [
            { point: "Priya's method: divide both sides by 2, then subtract l", keywords: ["divide by 2", "p/2", "÷ 2", "subtract l", "l + w"] },
            { point: "Jun's method: expand to 2l + 2w, subtract 2l, then divide by 2", keywords: ["expand", "2l + 2w", "2l+2w", "subtract 2l", "p - 2l"] },
            { point: "Explains the answers are equivalent, e.g. {{(P - 2l)/2 = P/2 - l}}, or checks with numbers", keywords: ["same", "equivalent", "equal", "check", "both"] },
          ],
          commonError: "Thinking two different-looking answers can't both be right.",
          difficulty: "core",
          guideRef: "changing-the-subject",
          hints: [
            "Priya's answer starts with {{P/2}}. What did she do first?",
            "Jun's answer has 2l in it. What happens if you expand the bracket first?",
            "Can you split {{(P - 2l)/2}} into two fractions?",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "expressions-p2-q15",
          question:
            "Aisha and Ben both expand and simplify {{2(3x - 1) - (x - 5)}}.\n\nAisha gets {{5x + 3}}. Ben gets {{5x - 7}}.\n\nWho is correct? Explain the mistake the other person made.",
          marks: 3,
          modelAnswer:
            "**Aisha is correct.** {{2(3x - 1) = 6x - 2}}. The minus sign in front of the second bracket means multiply by −1: {{-(x - 5) = -x + 5}}. So {{6x - 2 - x + 5 = 5x + 3}}.\n\nBen wrote {{-(x - 5) = -x - 5}}: he only changed the sign of the first term inside the bracket, but {{-1 * (-5) = +5}}.\n\nCheck with x = 1: {{2(2) - (-4) = 4 + 4 = 8}}. Aisha's answer gives 5 + 3 = 8 ✓, while Ben's gives 5 − 7 = −2 ✗.",
          markScheme: [
            { point: "States Aisha is correct (5x + 3)", keywords: ["aisha", "5x + 3", "5x+3"] },
            { point: "Explains {{-(x - 5) = -x + 5}}: the minus multiplies both terms, so −1 × −5 = +5", keywords: ["-x + 5", "+5", "+ 5", "both terms", "-1", "negative times negative"] },
            { point: "Identifies Ben's error: he wrote −x − 5, changing only the first sign", keywords: ["ben", "-5", "- 5", "only", "first term", "sign"] },
          ],
          commonError: "Changing the sign of only the first term inside a bracket with a minus in front.",
          difficulty: "core",
          guideRef: "expanding",
          hints: [
            "What does the minus sign in front of {{(x - 5)}} multiply?",
            "{{-(x - 5)}} means {{-1 * (x - 5)}}.",
            "Test both answers with x = 1.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "written",
          id: "expressions-p2-q16",
          question:
            "Mei says that 'half of n, plus 3' and 'n plus 3, then halved' are the same thing. Write each phrase as an expression, test them with n = 10, and explain whether Mei is right.",
          marks: 3,
          modelAnswer:
            "'Half of n, plus 3' is {{n/2 + 3}}. 'n plus 3, then halved' is {{(n + 3)/2}}.\n\nWith n = 10: {{10/2 + 3 = 5 + 3 = 8}}, but {{(10 + 3)/2 = 13/2 = 6.5}}.\n\nThe results are different, so Mei is wrong. The order of the operations matters: in the second phrase the 3 is added *before* halving, so the 3 gets halved too. In fact {{(n + 3)/2 = n/2 + 3/2}}, which is always 1.5 less than {{n/2 + 3}}.",
          markScheme: [
            { point: "Correct expressions {{n/2 + 3}} and {{(n + 3)/2}}", keywords: ["n/2 + 3", "n/2+3", "(n + 3)/2", "(n+3)/2"] },
            { point: "Correct values with n = 10: 8 and 6.5", keywords: ["8", "6.5", "13/2"] },
            { point: "Concludes Mei is wrong because the order of operations differs (the 3 is halved too)", keywords: ["wrong", "not the same", "different", "order", "bracket", "halved"] },
          ],
          commonError: "Writing n + 3/2 for 'n plus 3, then halved': without a bracket only the 3 is halved.",
          difficulty: "core",
          guideRef: "writing-expressions",
          hints: [
            "Write the first phrase: halve n, then add 3.",
            "In the second phrase the whole of n + 3 is halved, so you need a bracket or a fraction line around n + 3.",
            "Substitute n = 10 into both.",
          ],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "expressions-p2-q17",
          question:
            "A cube has edges of length s cm and a total surface area of A cm². Write a formula for A in terms of s, then rearrange it to make s the subject. Type your formula for s.",
          answer: { type: "expression", expr: "sqrt(A/6)", display: "{{s = sqrt(A/6)}}" },
          traps: [
            { spec: { type: "expression", expr: "A/6" }, feedback: "{{A/6}} is {{s^2}}, the area of one face. Undo the square with a square root." },
            { spec: { type: "expression", expr: "sqrt(A)/6" }, feedback: "Undo in reverse order: × 6 was done last, so divide by 6 *before* taking the square root: {{s = sqrt(A/6)}}." },
          ],
          solution: [
            "A cube has 6 square faces, each of area {{s^2}}, so {{A = 6s^2}}.",
            "s is squared, then multiplied by 6. Undo × 6 first: {{A/6 = s^2}}.",
            "Undo the square with a square root (s is a length, so take the positive root): {{s = sqrt(A/6)}}.",
            "Check: a cube with 5 cm edges has {{A = 6 * 25 = 150}}, and {{sqrt(150/6) = sqrt(25) = 5}}. ✓",
          ],
          commonError: "Taking the square root before dividing by 6.",
          difficulty: "challenge",
          guideRef: "changing-the-subject",
          hints: [
            "How many faces does a cube have, and what is the area of each one?",
            "{{A = 6s^2}}. What is done to s, in order?",
            "Undo the × 6 first, then undo the square.",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "expressions-p2-q18",
          question: "Expand and simplify {{(x + 5)(x - 5) - (x - 5)^2}}.",
          answer: { type: "expression", expr: "10x-50", form: "simplified" },
          traps: [
            { spec: { type: "expression", expr: "0" }, feedback: "{{(x - 5)^2}} is not {{x^2 - 25}}. Write it as {{(x - 5)(x - 5)}}: it gives {{x^2 - 10x + 25}}." },
            { spec: { type: "expression", expr: "10x" }, feedback: "Subtract the **whole** of {{x^2 - 10x + 25}}: {{-(x^2 - 10x + 25) = -x^2 + 10x - 25}}. The last term becomes −25." },
          ],
          solution: [
            "{{(x + 5)(x - 5) = x^2 - 5x + 5x - 25 = x^2 - 25}}.",
            "{{(x - 5)^2 = (x - 5)(x - 5) = x^2 - 5x - 5x + 25 = x^2 - 10x + 25}}.",
            "Subtract: {{x^2 - 25 - (x^2 - 10x + 25) = x^2 - 25 - x^2 + 10x - 25 = 10x - 50}}.",
            "Check with x = 6: {{11 * 1 - 1^2 = 10}} and {{60 - 50 = 10}}. ✓",
          ],
          commonError: "Writing {{(x - 5)^2 = x^2 - 25}} or {{x^2 + 25}}.",
          difficulty: "challenge",
          guideRef: "double-brackets",
          hints: [
            "Expand each part separately with a grid.",
            "{{(x - 5)^2}} means {{(x - 5)(x - 5)}}: four products.",
            "Put the second expansion in a bracket before subtracting.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "expressions-p2-q19",
          question:
            "A rectangle has length {{3x + 2}} cm and width {{x - 1}} cm. A square has the same perimeter as the rectangle. Write a simplified expression for the side length of the square, in cm.",
          answer: { type: "expression", expr: "2x+1/2", display: "{{2x + 1/2}} (or {{(4x + 1)/2}})" },
          traps: [
            { spec: { type: "expression", expr: "8x+2" }, feedback: "That's the perimeter. A square has 4 equal sides, so divide by 4." },
            { spec: { type: "expression", expr: "x+1/4" }, feedback: "The perimeter goes all the way round: 2 lengths + 2 widths = 8x + 2, not 4x + 1." },
          ],
          solution: [
            "Perimeter of the rectangle: {{2(3x + 2) + 2(x - 1) = 6x + 4 + 2x - 2 = 8x + 2}}.",
            "A square has 4 equal sides, so each side is {{(8x + 2)/4}}.",
            "Simplify: {{(8x + 2)/4 = 2x + 1/2}} (or {{(4x + 1)/2}}).",
            "Check with x = 3: the rectangle is 11 by 2, perimeter 26. A square of side {{6 1/2}} has perimeter 26. ✓",
          ],
          commonError: "Adding one length and one width and calling it the perimeter.",
          difficulty: "challenge",
          guideRef: "writing-expressions",
          hints: [
            "Find the rectangle's perimeter first, as an expression.",
            "Perimeter = 2 × length + 2 × width. Collect like terms.",
            "Each side of the square is a quarter of the perimeter.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "written",
          id: "expressions-p2-q20",
          question: "Ethan claims: 'For every whole number n, {{n^2 + n}} is even.' Prove that Ethan is right.",
          marks: 3,
          modelAnswer:
            "Factorise: {{n^2 + n = n(n + 1)}}.\n\nn and n + 1 are **consecutive** whole numbers, so one of them must be even.\n\nAn even number multiplied by any whole number is even, so {{n(n + 1)}} is always even.\n\n(Checking examples such as n = 3, where 9 + 3 = 12, is a good start, but only an argument like this covers every n.)",
          markScheme: [
            { point: "Factorises {{n^2 + n = n(n + 1)}}", keywords: ["n(n + 1)", "n(n+1)", "factorise"] },
            { point: "Notes that n and n + 1 are consecutive, so one of them is even", keywords: ["consecutive", "one of them", "one is even", "next to each other"] },
            { point: "Concludes the product is even for every n (even × whole number = even)", keywords: ["even times", "even ×", "product", "always even", "multiple of 2"] },
          ],
          solutions: [
            {
              label: "Split into cases",
              steps: [
                "If n is even: {{n^2}} is even × even = even, and even + even = even.",
                "If n is odd: {{n^2}} is odd × odd = odd, and odd + odd = even.",
                "Every whole number is odd or even, so {{n^2 + n}} is always even. This works too, but factorising is slicker: one line covers both cases at once.",
              ],
            },
          ],
          commonError: "Testing a few values of n and calling it a proof.",
          difficulty: "challenge",
          guideRef: "factorising",
          hints: [
            "Try n = 1, 2, 3, 4. Is the answer always even?",
            "Can you factorise {{n^2 + n}}?",
            "{{n(n + 1)}} is the product of two consecutive numbers. What do you know about any two consecutive numbers?",
          ],
          strategy: "Split into cases",
        },
      ],
    },
  ],

  // ===========================================================================
  // CHALLENGE — AoPS / UKMT-Junior style: insight, not grind
  // ===========================================================================
  challenge: [
    {
      kind: "short",
      id: "expressions-ch-q01",
      question: "Find the numbers a and b for which {{a(x + 3) - b(x - 1) ≡ 5x + 3}}. Give a first, then b.",
      answer: { type: "list", values: [2, -3], ordered: true, display: "a = 2, b = −3" },
      traps: [
        { spec: { type: "list", values: [2, 3], ordered: true }, feedback: "Check the sign of b. With x = −3 the left side is {{-b(-4) = 4b}}, and the right side is −12." },
      ],
      solution: [
        "An identity is true for **every** x, so the x-terms on each side must match, and so must the constant terms.",
        "Expand: {{a(x + 3) - b(x - 1) = ax + 3a - bx + b = (a - b)x + (3a + b)}}.",
        "Match the x-terms: {{a - b = 5}}. Match the constants: {{3a + b = 3}}.",
        "Add the two: {{4a = 8}}, so a = 2. Then {{2 - b = 5}}, so b = −3.",
        "Check: {{2(x + 3) + 3(x - 1) = 2x + 6 + 3x - 3 = 5x + 3}}. ✓",
      ],
      solutions: [
        {
          label: "Choose clever values of x (slicker)",
          steps: [
            "Because the identity holds for **every** x, pick values of x that make a bracket vanish.",
            "x = 1 kills the b-bracket: {{a(4) - b(0) = 5 + 3}}, so 4a = 8 and a = 2.",
            "x = −3 kills the a-bracket: {{a(0) - b(-4) = -15 + 3}}, so 4b = −12 and b = −3.",
            "Slicker: each choice of x isolates one unknown, so there are no simultaneous equations to solve.",
          ],
        },
      ],
      commonError: "Treating ≡ like an ordinary equation and trying to 'solve for x'.",
      difficulty: "challenge",
      guideRef: "language-of-algebra",
      hints: [
        "An identity is true for **every** value of x. How could you use that?",
        "Put x = 1 into both sides. What happens to the b-bracket?",
        "Now choose a value of x that makes the a-bracket zero.",
        "x = 1 gives 4a = 8; x = −3 gives 4b = −12.",
      ],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "expressions-ch-q02",
      question: "Given that {{x - 2y = 3}}, find the value of {{5x - 10y + (2y - x)^2}}.",
      answer: { type: "number", value: 24 },
      traps: [
        { spec: { type: "number", value: 6 }, feedback: "{{(2y - x)^2 = (-3)^2 = +9}}, not −9: a square is never negative." },
      ],
      solution: [
        "You can't find x and y separately, so write everything in terms of {{x - 2y}}.",
        "{{5x - 10y = 5(x - 2y) = 5 * 3 = 15}}.",
        "{{2y - x = -(x - 2y) = -3}}, so {{(2y - x)^2 = (-3)^2 = 9}}.",
        "Total: {{15 + 9 = 24}}.",
      ],
      solutions: [
        {
          label: "Pick values that fit",
          steps: [
            "Choose any x and y with {{x - 2y = 3}}, for example x = 3 and y = 0.",
            "{{5 * 3 - 0 + (0 - 3)^2 = 15 + 9 = 24}}.",
            "Another pair to be safe: x = 5, y = 1 gives {{25 - 10 + (2 - 5)^2 = 15 + 9 = 24}}.",
            "Picking values is quicker, but factorising is slicker: it *proves* the answer is 24 for every pair, not just the ones you tried.",
          ],
        },
      ],
      commonError: "Thinking you need to know x and y separately.",
      difficulty: "challenge",
      guideRef: "substitution",
      hints: [
        "You can't find x and y individually, so look for {{x - 2y}} hiding inside the expression.",
        "Factorise {{5x - 10y}}.",
        "How is {{2y - x}} related to {{x - 2y}}?",
        "{{2y - x = -3}}, and squaring removes the minus sign.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "expressions-ch-q03",
      question:
        "A large rectangle is cut into four smaller rectangles by one straight cut across and one straight cut down, as shown. The perimeters of three of the small rectangles are 16 cm, 20 cm and 24 cm. Find the perimeter, in cm, of the shaded rectangle.",
      diagram: `<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A large rectangle cut by one vertical line and one horizontal line into four rectangles. The top-left rectangle has perimeter 16 cm, the top-right 20 cm, the bottom-left 24 cm, and the shaded bottom-right rectangle is marked with a question mark."><rect x="0" y="0" width="400" height="300" fill="#ffffff"/><rect x="182" y="114" width="90" height="162" fill="#fde68a"/><rect x="128" y="24" width="144" height="252" fill="none" stroke="#1f2937" stroke-width="2"/><line x1="182" y1="24" x2="182" y2="276" stroke="#1f2937" stroke-width="2"/><line x1="128" y1="114" x2="272" y2="114" stroke="#1f2937" stroke-width="2"/><g font-family="sans-serif" fill="#1f2937" text-anchor="middle"><text x="155" y="73" font-size="13">16 cm</text><text x="227" y="73" font-size="13">20 cm</text><text x="155" y="199" font-size="13">24 cm</text><text x="227" y="201" font-size="20" font-weight="bold">?</text></g></svg>`,
      answer: { type: "number", value: 28 },
      traps: [
        { spec: { type: "number", value: 12 }, feedback: "Check which pairs go together. The rectangles **diagonally opposite** each other have the same total perimeter: top-left + shaded = top-right + bottom-left." },
      ],
      solution: [
        "Introduce letters: let the two widths be a (left) and b (right), and the two heights c (top) and d (bottom).",
        "Then top-left: {{2(a + c) = 16}}; top-right: {{2(b + c) = 20}}; bottom-left: {{2(a + d) = 24}}; shaded: {{2(b + d)}}.",
        "Add top-right and bottom-left, then subtract top-left: {{2(b + c) + 2(a + d) - 2(a + c) = 2b + 2c + 2a + 2d - 2a - 2c = 2b + 2d}}.",
        "That is exactly the shaded perimeter, so it is {{20 + 24 - 16 = 28}} cm.",
        "In general, diagonally opposite rectangles have the same total perimeter: 16 + 28 = 20 + 24.",
      ],
      solutions: [
        {
          label: "Find some actual lengths",
          steps: [
            "From {{2(a + c) = 16}}, a + c = 8. Try a = 3 and c = 5.",
            "Then b + c = 10 gives b = 5, and a + d = 12 gives d = 9.",
            "Shaded perimeter: {{2(5 + 9) = 28}} cm.",
            "This works, but you would need to check that other choices give the same answer. The letters method is slicker: it shows the answer is 28 whatever the lengths are.",
          ],
        },
      ],
      commonError: "Assuming the rectangles are squares, or that the cuts are in the middle.",
      difficulty: "challenge",
      guideRef: "simplifying",
      hints: [
        "Label the two widths a and b, and the two heights c and d.",
        "Write each known perimeter as an expression, e.g. {{2(a + c) = 16}}.",
        "Which combination of the three known perimeters adds and cancels to leave {{2(b + d)}}?",
        "Try top-right + bottom-left − top-left.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "written",
      id: "expressions-ch-q04",
      question:
        "Choose a two-digit number whose digits are different, such as 72. Reverse its digits (27) and subtract the smaller number from the larger: 72 − 27 = 45.\n\nProve that the answer is **always** a multiple of 9.",
      marks: 3,
      modelAnswer:
        "Let the number have tens digit a and units digit b, with a bigger than b. Its value is {{10a + b}} (not ab, which would mean a × b). Reversed, it is {{10b + a}}.\n\n    {{(10a + b) - (10b + a) = 10a + b - 10b - a = 9a - 9b = 9(a - b)}}\n\nSince a − b is a whole number, {{9(a - b)}} is a multiple of 9. (If b is the bigger digit, swap the roles: the answer is {{9(b - a)}}.) Bonus: the answer is always 9 times the difference of the digits, e.g. 72 − 27 = 9 × 5 = 45.",
      markScheme: [
        { point: "Writes the number as 10a + b and its reverse as 10b + a", keywords: ["10a + b", "10a+b", "10b + a", "10b+a", "place value"] },
        { point: "Subtracts and simplifies to 9a − 9b", keywords: ["9a - 9b", "9a-9b", "9a − 9b"] },
        { point: "Factorises to 9(a − b) and concludes it is a multiple of 9 for every such number", keywords: ["9(a - b)", "9(a-b)", "9(a − b)", "multiple of 9", "divisible by 9"] },
      ],
      solutions: [
        {
          label: "Place-value view",
          steps: [
            "Swapping the digits moves a from the tens column to the units column: its value drops from 10a to a, a loss of 9a.",
            "Meanwhile b moves up from units to tens: a gain of 9b.",
            "So the number changes by {{9a - 9b = 9(a - b)}}, a multiple of 9. The algebra version is slicker to write down; this view explains *why* 9 appears (10 − 1 = 9).",
          ],
        },
      ],
      commonError: "Writing the two-digit number as ab, which means a × b, instead of 10a + b.",
      difficulty: "challenge",
      guideRef: "writing-expressions",
      hints: [
        "Testing examples won't prove it. Use letters for the digits: tens digit a, units digit b.",
        "The number 72 is 7 × 10 + 2. So what is the value of the number with digits a and b?",
        "Write the reversed number the same way, then subtract and simplify.",
        "Can you take a common factor out of {{9a - 9b}}?",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "expressions-ch-q05",
      question: "Without a calculator, work out {{2025 * 2027 - 2024 * 2028}}.",
      answer: { type: "number", value: 3 },
      traps: [
        { spec: { type: "number", value: -3 }, feedback: "Which product is bigger? With n = 2026: {{(n - 1)(n + 1) = n^2 - 1}} and {{(n - 2)(n + 2) = n^2 - 4}}, so the first product is the bigger one." },
      ],
      solution: [
        "Let n = 2026, the number in the middle of all four.",
        "Then {{2025 * 2027 = (n - 1)(n + 1) = n^2 + n - n - 1 = n^2 - 1}}.",
        "And {{2024 * 2028 = (n - 2)(n + 2) = n^2 - 4}}.",
        "So the difference is {{(n^2 - 1) - (n^2 - 4) = 3}}. The huge {{n^2}} cancels!",
      ],
      solutions: [
        {
          label: "Try small cases",
          steps: [
            "The same pattern with small numbers: {{5 * 7 - 4 * 8 = 35 - 32 = 3}}.",
            "And {{9 * 11 - 8 * 12 = 99 - 96 = 3}}.",
            "Always 3. Small cases are quicker for *spotting* the answer, but letting n = 2026 is slicker: it proves the answer in one line.",
          ],
        },
      ],
      commonError: "Trying to multiply out the four-digit numbers (slow and error-prone).",
      difficulty: "challenge",
      guideRef: "double-brackets",
      hints: [
        "All four numbers are close to one particular number. Which one?",
        "Let n = 2026. Write each of the four numbers in terms of n.",
        "Expand {{(n - 1)(n + 1)}} and {{(n - 2)(n + 2)}}. What happens to the n-terms?",
        "The {{n^2}} terms cancel when you subtract.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "written",
      id: "expressions-ch-q06",
      question:
        "Arjun substitutes n = 1, 2, 3, 4 and 5 into {{n^2 + n + 41}} and gets 43, 47, 53, 61 and 71, all prime numbers. He claims that {{n^2 + n + 41}} is **always** prime when n is a positive whole number.\n\nWithout working out any big numbers, find a value of n that proves Arjun wrong. Explain why it works.",
      marks: 3,
      modelAnswer:
        "Choose **n = 41**. Then every term contains a factor of 41:\n\n    {{41^2 + 41 + 41 = 41(41 + 1 + 1) = 41 * 43}}\n\nSo the value is 41 × 43, which has factors 41 and 43: it is not prime. One counter-example is enough to show that an 'always' claim is false, so Arjun is wrong.\n\n(n = 40 also works: {{40^2 + 40 + 41 = 40(40 + 1) + 41 = 40 * 41 + 41 = 41 * 41}}. Remarkably, the expression *is* prime for every n from 0 to 39, a famous discovery of Leonhard Euler, which is why testing a few cases can fool you.)",
      markScheme: [
        { point: "Chooses a suitable value, e.g. n = 41 (or n = 40)", keywords: ["41", "40", "n = 41", "n = 40"] },
        { point: "Shows the value has a factor of 41 by factorising, e.g. 41(41 + 1 + 1) = 41 × 43", keywords: ["41 × 43", "41 x 43", "41 × 41", "factor", "factorise", "41("] },
        { point: "States it is therefore not prime, and that one counter-example disproves 'always'", keywords: ["not prime", "counter", "one example", "disprove", "composite"] },
      ],
      solutions: [
        {
          label: "n = 40 instead",
          steps: [
            "{{40^2 + 40 = 40(40 + 1) = 40 * 41}}.",
            "Add 41: {{40 * 41 + 41 = 41(40 + 1) = 41 * 41}}.",
            "So n = 40 gives a perfect square, which is not prime. Both work, but n = 41 is slicker because the common factor is obvious at a glance.",
          ],
        },
      ],
      commonError: "Testing more and more small values, which all give primes up to n = 39.",
      difficulty: "challenge",
      guideRef: "factorising",
      hints: [
        "To break 'always prime', you need one value of n where the answer has a factor other than 1 and itself.",
        "Which value of n would make **every** term share a factor?",
        "What if n is 41?",
        "{{41^2 + 41 + 41}}: take out the common factor.",
      ],
      strategy: "Look for a counter-example",
    },
    {
      kind: "short",
      id: "expressions-ch-q07",
      question:
        "A number machine doubles its input and then subtracts 3. Ethan puts x into the machine, then feeds each output back in, until the machine has been used **10 times** altogether. Write the final output as a simplified expression in x.",
      answer: { type: "expression", expr: "1024x-3069", form: "simplified" },
      traps: [
        { spec: { type: "expression", expr: "1024x-30" }, feedback: "The 3s don't just add up: each one is doubled by every later pass. Work out 1, 2 and 3 passes and look for a pattern in the constant term." },
        { spec: { type: "expression", expr: "20x-30" }, feedback: "Each pass **doubles** everything, so after 10 passes x has been doubled 10 times: {{2^10 = 1024}}." },
      ],
      solution: [
        "Do a few passes and look for a pattern.",
        "1 pass: {{2x - 3}}.",
        "2 passes: {{2(2x - 3) - 3 = 4x - 9}}.",
        "3 passes: {{2(4x - 9) - 3 = 8x - 21}}.",
        "4 passes: {{2(8x - 21) - 3 = 16x - 45}}. The constants 3, 9, 21, 45 are 3 × 1, 3 × 3, 3 × 7, 3 × 15: always 3 × (a power of 2, minus 1).",
        "After 10 passes: {{2^10 x - 3(2^10 - 1) = 1024x - 3 * 1023 = 1024x - 3069}}.",
      ],
      solutions: [
        {
          label: "Find the number that doesn't move (slicker)",
          steps: [
            "Which input comes out unchanged? 2 × 3 − 3 = 3, so 3 is a 'fixed point'.",
            "Measure from 3: if the input is {{3 + d}}, the output is {{2(3 + d) - 3 = 3 + 2d}}. The distance from 3 doubles every pass.",
            "x starts {{x - 3}} away from 3. After 10 passes it is {{1024(x - 3)}} away.",
            "Output: {{3 + 1024(x - 3) = 1024x - 3069}}. Slicker: no pattern-spotting needed, and it works for any number of passes.",
          ],
        },
      ],
      commonError: "Assuming the constant just goes up by 3 each pass.",
      difficulty: "challenge",
      guideRef: "expanding",
      hints: [
        "Work out the output after 1, 2 and 3 passes.",
        "The coefficient of x doubles each time. What about the constants 3, 9, 21, …?",
        "Add 3 to each constant: 6, 12, 24, … Now can you see the pattern?",
        "Is there an input the machine leaves unchanged? Measure everything from that number.",
      ],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "expressions-ch-q08",
      question:
        "x and y are whole numbers from 1 to 10 inclusive (they may be equal). What is the **smallest** possible value of {{xy - 3x - 2y}}?",
      answer: { type: "number", value: -22 },
      traps: [
        { spec: { type: "number", value: -13 }, feedback: "That's x = 1, y = 10. Try making x as **big** as possible with y small instead: when y = 1 the expression is {{-2x - 2}}." },
      ],
      solution: [
        "Write the expression as {{x(y - 3) - 2y}} and split into cases by the value of y.",
        "y = 1: {{-2x - 2}}, smallest when x = 10, giving −22.",
        "y = 2: {{-x - 4}}, smallest when x = 10, giving −14.",
        "y = 3: the value is always −6.",
        "y ≥ 4: {{y - 3}} is positive, so take x = 1, giving {{(y - 3) - 2y = -y - 3}}, which is never below −13.",
        "So the smallest value is −22, when x = 10 and y = 1. Check: 10 − 30 − 2 = −22. ✓",
      ],
      solutions: [
        {
          label: "A factorising trick (slicker)",
          steps: [
            "Notice that {{(x - 2)(y - 3) = xy - 3x - 2y + 6}}.",
            "So {{xy - 3x - 2y = (x - 2)(y - 3) - 6}}.",
            "x − 2 runs from −1 to 8 and y − 3 runs from −2 to 7. The most negative product is {{8 * (-2) = -16}} (better than {{(-1) * 7 = -7}}).",
            "Smallest value: {{-16 - 6 = -22}}. Slicker: one product to make as negative as possible instead of ten cases.",
          ],
        },
      ],
      commonError: "Only trying x and y both equal to 1 or both equal to 10.",
      difficulty: "challenge",
      guideRef: "substitution",
      hints: [
        "Try some extreme values: x and y each equal to 1 or 10.",
        "Fix y = 1. What does the expression become? Which x makes it smallest?",
        "Write it as {{x(y - 3) - 2y}}. When is {{y - 3}} negative?",
        "Check the cases y = 1, 2, 3 separately from y ≥ 4.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "expressions-ch-q09",
      question: "Make x the subject of {{y = (x + 3)/(x - 2)}}.",
      answer: { type: "expression", expr: "(2y+3)/(y-1)", display: "{{x = (2y + 3)/(y - 1)}} (or {{x = 2 + 5/(y - 1)}})" },
      traps: [
        { spec: { type: "expression", expr: "(2y+3)/(1-y)" }, feedback: "Sign slip. Test it: x = 3 gives y = 6, and your formula should give back 3. Collect the x-terms as {{xy - x}} so the bracket is {{(y - 1)}}." },
        { spec: { type: "expression", expr: "(2y-3)/(y-1)" }, feedback: "Check the sign of the 3. From {{xy - 2y = x + 3}}, adding 2y and subtracting x gives {{xy - x = 2y + 3}}." },
      ],
      solution: [
        "x appears twice, so first clear the fraction: multiply both sides by {{(x - 2)}}: {{y(x - 2) = x + 3}}.",
        "Expand: {{xy - 2y = x + 3}}.",
        "Collect the x-terms on one side and everything else on the other: {{xy - x = 2y + 3}}.",
        "Factorise out x: {{x(y - 1) = 2y + 3}}.",
        "Divide by {{(y - 1)}}: {{x = (2y + 3)/(y - 1)}}.",
        "Check with x = 3: {{y = 6/1 = 6}}, and {{(12 + 3)/(6 - 1) = 3}}. ✓",
      ],
      solutions: [
        {
          label: "Make x appear only once (slicker)",
          steps: [
            "Rewrite the top as {{(x - 2) + 5}}: {{y = (x - 2 + 5)/(x - 2) = 1 + 5/(x - 2)}}.",
            "Now x appears only once. Subtract 1: {{y - 1 = 5/(x - 2)}}.",
            "Flip both sides: {{x - 2 = 5/(y - 1)}}.",
            "Add 2: {{x = 2 + 5/(y - 1)}}, which equals {{(2y + 3)/(y - 1)}}.",
            "Slicker: once x appears only once, you just undo the steps in reverse order.",
          ],
        },
      ],
      commonError: "Trying to 'undo' the fraction while x is still on both the top and the bottom.",
      difficulty: "challenge",
      guideRef: "changing-the-subject",
      hints: [
        "x appears twice, on the top and on the bottom. Clear the fraction first.",
        "Multiply both sides by {{(x - 2)}} and expand.",
        "Get every x-term on one side, then factorise x out.",
        "You should reach {{x(y - 1) = 2y + 3}}.",
      ],
      strategy: "Use the inverse",
    },
    {
      kind: "written",
      id: "expressions-ch-q10",
      question:
        "Spot the flaw. Here is a 'proof' that 2 = 1.\n\n1. Let a = b, where a and b are not zero.\n2. Multiply both sides by a: {{a^2 = ab}}.\n3. Subtract {{b^2}} from both sides: {{a^2 - b^2 = ab - b^2}}.\n4. Factorise both sides: {{(a + b)(a - b) = b(a - b)}}.\n5. Divide both sides by {{(a - b)}}: {{a + b = b}}.\n6. Since a = b, this says {{2b = b}}, so 2 = 1.\n\nWhich line is wrong, and why? Check line 4 carefully first.",
      marks: 3,
      modelAnswer:
        "Lines 1 to 4 are fine. Line 4 is correct factorising: expanding {{(a + b)(a - b)}} gives {{a^2 - ab + ab - b^2 = a^2 - b^2}}, and {{b(a - b) = ab - b^2}}.\n\n**Line 5 is the flaw.** Because a = b, the bracket {{a - b}} equals **0**, so line 5 divides both sides by zero, which is never allowed.\n\nLine 4 really says 0 = 0, which is true. But 0 = 0 can be written as {{2 * 0 = 1 * 0}} too, and you cannot 'cancel' the zeros to conclude 2 = 1.",
      markScheme: [
        { point: "Checks that line 4 is correct, e.g. by expanding both sides", keywords: ["line 4", "expand", "a^2 - b^2", "correct", "fine"] },
        { point: "Identifies line 5 as the error", keywords: ["line 5", "step 5", "divide"] },
        { point: "Explains that a − b = 0 because a = b, so line 5 divides by zero", keywords: ["zero", "0", "a - b = 0", "divide by zero", "dividing by 0"] },
      ],
      solutions: [
        {
          label: "Test with numbers",
          steps: [
            "Let a = b = 3. Line 2: 9 = 9 ✓. Line 3: 0 = 0 ✓. Line 4: {{6 * 0 = 3 * 0}}, i.e. 0 = 0 ✓.",
            "Line 5: 6 = 3 ✗. The first false statement appears here, so line 5 is the broken step.",
            "Testing numbers finds the faulty line fastest; the algebra (a − b = 0) explains *why* it is broken. Use both.",
          ],
        },
      ],
      commonError: "Blaming line 4: the factorising there is correct.",
      difficulty: "challenge",
      guideRef: "factorising",
      hints: [
        "Check each line by testing it with real numbers, say a = b = 3.",
        "Expand the brackets in line 4. Do both sides really match the line above?",
        "If a = b, what is the value of {{a - b}}?",
        "Which number are you never allowed to divide by?",
      ],
      strategy: "Check by substituting",
    },
  ],
};
