// ---------------------------------------------------------------------------
// Powers of 10 & Standard Form — MCQ papers (4 × 20).
// Each wrong option is a specific misconception; options are shuffled at
// display time, so explanations name distractors by value, never position.
// ---------------------------------------------------------------------------
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "standard-form-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "standard-form-m1-q01",
        question: "Work out 4.7 × 100.",
        options: [
          "4.700",
          "470",
          "47",
          "0.047",
        ],
        answerIndex: 1,
        explanation: "× 100 makes the number 100 times bigger, so every digit moves **two** places to the left: 4.7 → 47 → 470. The answer 4.700 comes from \"adding two zeros\" — but zeros on the end of a decimal change nothing, so 4.700 is still 4.7.",
        difficulty: "warmup",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Multiplying by 100 moves every digit two places. Which way — left or right?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q02",
        question: "Which of these is equal to {{10^4}}?",
        options: [
          "40",
          "1000",
          "100 000",
          "10 000",
        ],
        answerIndex: 3,
        explanation: "{{10^4}} means four 10s multiplied together: 10 × 10 × 10 × 10 = 10 000, a 1 followed by four zeros. The answer 40 comes from working out 10 × 4 instead. 1000 has four *digits*, but only three zeros, so it is {{10^3}}.",
        difficulty: "warmup",
        guideRef: "powers-of-ten",
        hints: [
          "{{10^4}} means four 10s multiplied together.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q03",
        question: "Which number is written correctly in standard form?",
        options: [
          "{{3.6 * 10^5}}",
          "{{36 * 10^4}}",
          "{{0.36 * 10^6}}",
          "{{3.6 + 10^5}}",
        ],
        answerIndex: 0,
        explanation: "Standard form is {{A * 10^n}} with {{1 <= A < 10}}. In {{3.6 * 10^5}} the front number 3.6 is between 1 and 10. {{36 * 10^4}} has the same value (360 000), but 36 is too big to be the front number; {{0.36 * 10^6}} fails because 0.36 is less than 1. {{3.6 + 10^5}} adds instead of multiplying.",
        difficulty: "warmup",
        guideRef: "large-numbers",
        hints: [
          "Check two things: is the front number at least 1 and less than 10, and is it *multiplied* by a power of 10?",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q04",
        question: "Write 0.004 in standard form.",
        options: [
          "{{4 * 10^(-2)}}",
          "{{4 * 10^3}}",
          "{{4 * 10^(-3)}}",
          "{{0.4 * 10^(-2)}}",
        ],
        answerIndex: 2,
        explanation: "To turn 0.004 into 4 the decimal point jumps **3** places, so 0.004 = {{4 * 10^(-3)}}. Check: {{10^(-3)}} = 0.001 and 4 × 0.001 = 0.004. {{4 * 10^(-2)}} comes from counting only the two zeros after the point — that equals 0.04. {{4 * 10^3}} = 4000, far too big.",
        difficulty: "warmup",
        guideRef: "small-numbers",
        hints: [
          "How many places must the decimal point jump to turn 0.004 into 4?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q05",
        question: "Which of these numbers is the largest?",
        options: [
          "{{9.9 * 10^2}}",
          "{{2.4 * 10^5}}",
          "{{8.7 * 10^4}}",
          "{{5.2 * 10^(-7)}}",
        ],
        answerIndex: 1,
        explanation: "Compare the powers of 10 first: {{10^5}} is the biggest power, so {{2.4 * 10^5}} = 240 000 wins. {{9.9 * 10^2}} is tempting because 9.9 is the biggest front number, but it is only 990. {{5.2 * 10^(-7)}} has a *negative* power, so it is less than 1.",
        difficulty: "warmup",
        guideRef: "comparing-standard-form",
        hints: [
          "Look at the powers of 10 before you look at the front numbers.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q06",
        question: "Work out 23 × 0.01.",
        options: [
          "0.23",
          "2300",
          "2.3",
          "0.023",
        ],
        answerIndex: 0,
        explanation: "0.01 is one hundredth, so × 0.01 is the same as ÷ 100: 23 → 2.3 → 0.23. The answer 2300 comes from multiplying by 100 — but multiplying by a number less than 1 must make 23 *smaller*. 2.3 treats 0.01 as a tenth.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Is 0.01 bigger or smaller than 1? So will the answer be bigger or smaller than 23?",
          "0.01 = {{1/100}}, so × 0.01 means ÷ 100.",
          "Move every digit of 23 two places to the right.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q07",
        question: "Ravi says: \"To multiply by 10 you just add a zero, so 2.5 × 10 = 2.50.\" What is his mistake?",
        options: [
          "There is no mistake — adding a zero always multiplies by 10.",
          "He should have moved the decimal point one place left to get 0.25.",
          "The answer should be 250, because 10 has two digits, so the digits move two places.",
          "Writing a 0 on the end of a decimal doesn't change its value; the digits should move one place left to give 25.",
        ],
        answerIndex: 3,
        explanation: "2.50 and 2.5 are the same number, so Ravi hasn't multiplied at all. × 10 moves every digit one place left: 2.5 × 10 = 25. Getting 0.25 is dividing by 10, and 250 is 2.5 × 100 — 10 has two digits but only one zero, so the digits move one place.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Is 2.50 bigger than 2.5?",
          "\"Add a zero\" works for whole numbers like 7 → 70. What does × 10 really do to each digit?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q08",
        question: "What is {{10^(-2)}} as a decimal?",
        options: [
          "−100",
          "−20",
          "0.01",
          "0.001",
        ],
        answerIndex: 2,
        explanation: "A negative power means *divide*: {{10^(-2) = 1/10^2 = 1/100}} = 0.01. The answer −100 comes from thinking the minus sign makes the number negative — but {{10^(-2)}} is a small positive number. −20 works out 10 × (−2). 0.001 has one zero too many: it is {{10^(-3)}}.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Continue the pattern: {{10^1}} = 10, {{10^0}} = 1, {{10^(-1)}} = ?",
          "Each step down the pattern divides by 10.",
          "{{10^(-2)}} = 1 ÷ 10 ÷ 10.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q09",
        question: "Mei asks why {{10^0}} is equal to 1. Which is the best explanation?",
        options: [
          "In the pattern 1000, 100, 10, … each power of 10 is the one before divided by 10, so {{10^0}} = 10 ÷ 10 = 1.",
          "It isn't 1: {{10^0}} = 0, because 10 × 0 = 0.",
          "It isn't 1: {{10^0}} = 10, because 10 hasn't been multiplied by anything.",
          "The 0 in the power cancels the 0 in 10, which leaves 1.",
        ],
        answerIndex: 0,
        explanation: "Going down from {{10^3}} = 1000 to {{10^2}} = 100 to {{10^1}} = 10, the power drops by 1 and the value is divided by 10 each time. One more step gives 10 ÷ 10 = 1. The answer 0 is the classic slip of reading {{10^0}} as 10 × 0. The 'cancelling zeros' idea gets 1 by luck: it would make {{20^0}} equal 2, but {{20^0}} is also 1.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Write {{10^3}}, {{10^2}} and {{10^1}} as ordinary numbers. What happens at each step?",
          "Each time the power goes down by 1, you divide by 10.",
          "So what is {{10^1}} ÷ 10?",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q10",
        question: "Earth is about 150 000 000 km from the Sun. Which is this distance in standard form?",
        options: [
          "{{1.5 * 10^7}} km",
          "{{1.5 * 10^8}} km",
          "{{1.5 * 10^9}} km",
          "{{15 * 10^7}} km",
        ],
        answerIndex: 1,
        explanation: "Put the point after the first digit to get 1.5. To get back to 150 000 000 the point moves **8** places, so the distance is {{1.5 * 10^8}} km. {{1.5 * 10^7}} comes from counting the seven zeros — but the 5 has to move too. {{1.5 * 10^9}} counts all nine digits. {{15 * 10^7}} is the right size, but 15 is not between 1 and 10.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "What is the front number? Put the decimal point after the first non-zero digit.",
          "Count how many places the point moves from 1.5 to 150 000 000.",
          "1.5 → 15 → 150 → … count each jump.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q11",
        question: "Write {{6.02 * 10^5}} as an ordinary number.",
        options: [
          "60 200 000",
          "60 200",
          "6.0200000",
          "602 000",
        ],
        answerIndex: 3,
        explanation: "× {{10^5}} moves every digit 5 places left: 6.02 → 60.2 → 602 → 6020 → 60 200 → 602 000. The answer 60 200 000 comes from sticking five zeros on the end of 602 — but two of the five moves were already used to turn 6.02 into 602. 6.0200000 adds zeros after the decimal point, which changes nothing.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Multiplying by {{10^5}} moves the digits how many places?",
          "The first two moves turn 6.02 into 602.",
          "You need three more moves after 602.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q12",
        question: "A red blood cell is about {{7.5 * 10^(-6)}} m across. Write this as an ordinary number.",
        options: [
          "0.00000075 m",
          "0.000075 m",
          "0.0000075 m",
          "7 500 000 m",
        ],
        answerIndex: 2,
        explanation: "× {{10^(-6)}} moves the digits 6 places right: 7.5 → 0.75 → 0.075 → 0.0075 → 0.00075 → 0.000075 → 0.0000075. The answer 0.00000075 comes from writing six zeros after the point — but the very first move already puts the 7 into the tenths column. 7 500 000 m is 7500 km, wider than Australia: a positive power would make it huge.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "Is the number bigger or smaller than 1?",
          "× {{10^(-6)}} means ÷ 1 000 000: move the digits 6 places to the right.",
          "Count one move at a time: 7.5 → 0.75 is the first move.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q13",
        question: "Jun writes 0.00056 = {{5.6 * 10^(-3)}}. What was his mistake?",
        options: [
          "He counted the 3 zeros after the point, but the point jumps 4 places to turn 0.00056 into 5.6, so it should be {{5.6 * 10^(-4)}}.",
          "He needed a positive power: 0.00056 = {{5.6 * 10^3}}.",
          "He should have written {{56 * 10^(-5)}}, because 56 is the number you can see.",
          "There is no mistake — three zeros after the point means a power of −3.",
        ],
        answerIndex: 0,
        explanation: "Check his answer: {{5.6 * 10^(-3)}} = 0.0056, which is ten times too big. From 0.00056 to 5.6 the point jumps 4 places (past 0, 0, 0 and 5), so the answer is {{5.6 * 10^(-4)}}. {{56 * 10^(-5)}} does equal 0.00056 but isn't standard form, because 56 is not between 1 and 10.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "Turn Jun's answer back into an ordinary number. Do you get 0.00056?",
          "Count how many places the point jumps to turn 0.00056 into 5.6.",
          "Every jump counts — including the jump past the 5.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q14",
        question: "Which list is in order from smallest to largest?",
        options: [
          "{{1.7 * 10^6}}, {{3.05 * 10^5}}, {{3.2 * 10^5}}, {{9.1 * 10^4}}",
          "{{9.1 * 10^4}}, {{3.05 * 10^5}}, {{3.2 * 10^5}}, {{1.7 * 10^6}}",
          "{{9.1 * 10^4}}, {{3.2 * 10^5}}, {{3.05 * 10^5}}, {{1.7 * 10^6}}",
          "{{1.7 * 10^6}}, {{3.2 * 10^5}}, {{3.05 * 10^5}}, {{9.1 * 10^4}}",
        ],
        answerIndex: 1,
        explanation: "Sort by power first: {{10^4}} < {{10^5}} < {{10^6}}. The two numbers with {{10^5}} are then compared by their front numbers: 3.05 < 3.2 (think 3.05 and 3.20). Sorting by the front numbers alone (1.7, 3.05, 3.2, 9.1) ignores the powers. Putting {{3.2 * 10^5}} before {{3.05 * 10^5}} comes from thinking 05 is bigger than 2. The list that starts with {{1.7 * 10^6}} and has {{3.2 * 10^5}} second is the right order backwards — largest first.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "Which number has the smallest power of 10?",
          "Two numbers share {{10^5}} — compare their front numbers.",
          "Is 3.05 bigger or smaller than 3.2? Write 3.2 as 3.20.",
        ],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q15",
        question: "Aisha works out 0.00094 ÷ 20 on her calculator. The screen is shown. What is the answer as an ordinary number?",
        diagram: `<svg viewBox="0 0 240 120" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Calculator screen. Top line: 0.00094 ÷ 20. Answer line: 4.7E-05"><rect x="0" y="0" width="240" height="120" fill="#ffffff"/><rect x="4" y="4" width="232" height="112" rx="12" fill="#334155"/><rect x="18" y="18" width="204" height="84" rx="6" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><text x="28" y="42" font-size="13" font-family="sans-serif" fill="#1f2937">0.00094÷20</text><text x="210" y="86" font-size="14" font-family="sans-serif" font-weight="bold" fill="#1f2937" text-anchor="end">4.7E-05</text></svg>`,
        options: [
          "0.0000047",
          "470 000",
          "−0.3",
          "0.000047",
        ],
        answerIndex: 3,
        explanation: "`4.7E-05` is the calculator's way of writing {{4.7 * 10^(-5)}}. Move the digits 5 places right: 0.000047. Estimate to check: 0.001 ÷ 20 = 0.00005, close to 0.000047. 470 000 ignores the minus sign — dividing a small number by 20 can't give something huge. −0.3 reads E−05 as \"subtract 5\", but E means \"× 10 to the power of\".",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "What does the E on a calculator screen stand for?",
          "`4.7E-05` means {{4.7 * 10^(-5)}}.",
          "Move the digits of 4.7 five places to the right.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q16",
        question: "Work out {{(3 * 10^4) * (2 * 10^5)}}. Give your answer in standard form.",
        options: [
          "{{6 * 10^20}}",
          "{{5 * 10^9}}",
          "{{6 * 10^9}}",
          "{{6 * 10^(-1)}}",
        ],
        answerIndex: 2,
        explanation: "Multiply the front numbers and the powers of 10 separately: 3 × 2 = 6 and {{10^4 * 10^5 = 10^(4+5) = 10^9}}. The answer {{6 * 10^20}} comes from multiplying 4 × 5 — but when you multiply powers of 10 you *add* the indices (four 10s times five 10s is nine 10s). {{5 * 10^9}} adds the front numbers instead of multiplying them.",
        difficulty: "core",
        guideRef: "calculating-standard-form",
        hints: [
          "Rearrange: (3 × 2) × ({{10^4 * 10^5}}).",
          "When you multiply powers of 10, what happens to the indices?",
          "{{10^4 * 10^5}} is four 10s times five 10s. How many 10s altogether?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q17",
        question: "Always, sometimes or never true? \"Multiplying a number by 0.1 makes it smaller.\"",
        options: [
          "Sometimes — it's true for positive numbers, but 0 stays the same and negative numbers get bigger.",
          "Always — 0.1 is less than 1, so the answer is always smaller.",
          "Never — multiplying always makes a number bigger.",
          "Sometimes — it's true for whole numbers but not for decimals.",
        ],
        answerIndex: 0,
        explanation: "For positive numbers, × 0.1 gives a tenth, which is smaller: 8 × 0.1 = 0.8. But 0 × 0.1 = 0 (no change), and −5 × 0.1 = −0.5, which is *bigger* than −5 because it is closer to zero. So the statement is only sometimes true. \"Always\" forgets zero and the negative numbers; \"not for decimals\" fails because 0.6 × 0.1 = 0.06 is smaller too.",
        difficulty: "challenge",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Test a positive number, zero and a negative number.",
          "Work out −5 × 0.1. Is −0.5 bigger or smaller than −5?",
          "Picture −5 and −0.5 on a number line.",
        ],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q18",
        question: "Wei Ling says: \"If you double a number written in standard form, the power of 10 never changes.\" Is she right?",
        options: [
          "Yes — doubling only changes the front number, never the power.",
          "No — doubling always adds 1 to the power.",
          "No — doubling doubles the power, so {{10^5}} becomes {{10^10}}.",
          "No — the power goes up by 1 when the front number is 5 or more, e.g. 2 × {{7 * 10^5}} = {{1.4 * 10^6}}.",
        ],
        answerIndex: 3,
        explanation: "Doubling {{3 * 10^5}} gives {{6 * 10^5}} — same power. But doubling {{7 * 10^5}} gives {{14 * 10^5}}, and 14 is too big to be the front number, so it becomes {{1.4 * 10^6}}. The power goes up exactly when double the front number reaches 10, which happens when it is 5 or more. \"Yes\" is only true for small front numbers. Doubling the power to {{10^10}} would multiply the number by 100 000, not by 2.",
        difficulty: "challenge",
        guideRef: "large-numbers",
        hints: [
          "Try doubling {{3 * 10^5}}. Then try doubling {{7 * 10^5}}.",
          "After doubling, is the front number still less than 10?",
          "For which front numbers does doubling reach 10 or more?",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q19",
        question: "A **positive** number is written in standard form as {{A * 10^n}}. Always, sometimes or never true? \"If n is negative, the number is between 0 and 1.\"",
        options: [
          "Sometimes — {{9.9 * 10^(-1)}} is bigger than 1.",
          "Always — even the biggest case is just under {{10 * 10^(-1)}}, which is 1.",
          "Never — a negative power makes the number negative.",
          "Sometimes — it's only true when n is −2 or lower.",
        ],
        answerIndex: 1,
        explanation: "A is less than 10, and when n is negative {{10^n}} is at most {{10^(-1)}} = 0.1. So {{A * 10^n}} is less than 10 × 0.1 = 1, and it is positive. That makes it always between 0 and 1. {{9.9 * 10^(-1)}} is tempting, but it equals 0.99, which is *less* than 1. A negative power makes a number small, not negative.",
        difficulty: "challenge",
        guideRef: "small-numbers",
        hints: [
          "What is the biggest A can be? And the biggest {{10^n}} can be when n is negative?",
          "Try the extreme case A = 9.99, n = −1.",
          "{{9.99 * 10^(-1)}} = 0.999. Can you ever reach 1?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "standard-form-m1-q20",
        question: "Let {{x = 3 * 10^(-5)}}. Which of these is the largest?",
        options: [
          "{{x^2}}",
          "{{10x}}",
          "{{1/x}}",
          "{{sqrt(x)}}",
        ],
        answerIndex: 2,
        explanation: "x is a small positive number (0.00003). Dividing 1 by a number less than 1 gives a number *bigger* than 1: {{1/x}} is about 33 000. The others all stay below 1: {{10x}} = 0.0003, {{sqrt(x)}} ≈ 0.0055 and {{x^2}} = {{9 * 10^(-10)}}. The tempting choice {{x^2}} is actually the smallest — squaring a number less than 1 makes it smaller.",
        difficulty: "challenge",
        guideRef: "comparing-standard-form",
        hints: [
          "Is x bigger or smaller than 1?",
          "Which of these operations can turn a number less than 1 into a number bigger than 1?",
          "Try the same four things with an easier small number, like x = 0.01.",
        ],
        strategy: "Try small cases",
      },
    ],
  },
  {
    id: "standard-form-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "standard-form-m2-q01",
        question: "Work out 3.8 ÷ 10.",
        options: [
          "3.08",
          "38",
          "0.38",
          "0.038",
        ],
        answerIndex: 2,
        explanation: "÷ 10 moves every digit one place to the right: 3.8 → 0.38. The answer 3.08 comes from \"putting in a zero\" — that only shrinks the 8, not the 3. 38 is 3.8 × 10, and 0.038 is 3.8 ÷ 100.",
        difficulty: "warmup",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Dividing by 10 moves every digit one place. Which way — left or right?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q02",
        question: "How many times bigger is {{10^5}} than {{10^4}}?",
        options: [
          "10 times",
          "1 time",
          "1.25 times",
          "90 000 times",
        ],
        answerIndex: 0,
        explanation: "{{10^5}} = {{10^4}} × 10: it has one more 10 multiplied in, so it is 10 times bigger (100 000 compared with 10 000). The powers differ by 1, but a difference of 1 in the power means one extra *factor* of 10, not 1. 90 000 is how much *more* {{10^5}} is — the difference, not how many times bigger. 1.25 divides the powers, 5 ÷ 4.",
        difficulty: "warmup",
        guideRef: "powers-of-ten",
        hints: [
          "Write both as ordinary numbers and compare them.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q03",
        question: "Write 90 000 in standard form.",
        options: [
          "{{9 * 10^5}}",
          "{{9 * 10^4}}",
          "{{90 * 10^3}}",
          "{{9 * 10^(-4)}}",
        ],
        answerIndex: 1,
        explanation: "90 000 = 9 × 10 000 = {{9 * 10^4}}. {{9 * 10^5}} counts the five digits instead of the four places the 9 has moved — it equals 900 000. {{90 * 10^3}} has the right value, but 90 is not between 1 and 10. A negative power would make the number less than 1.",
        difficulty: "warmup",
        guideRef: "large-numbers",
        hints: [
          "90 000 = 9 × ? Write the ? as a power of 10.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q04",
        question: "Write {{3 * 10^(-2)}} as an ordinary number.",
        options: [
          "0.003",
          "300",
          "−300",
          "0.03",
        ],
        answerIndex: 3,
        explanation: "{{10^(-2)}} = 0.01, so {{3 * 10^(-2)}} = 3 × 0.01 = 0.03. The answer 0.003 comes from writing two zeros after the point and then the 3 — but the 3 only moves two places, into the hundredths column. 300 and −300 both misread the negative power: it makes the number small, not big or negative.",
        difficulty: "warmup",
        guideRef: "small-numbers",
        hints: [
          "{{10^(-2)}} is one hundredth. What is 3 hundredths as a decimal?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q05",
        question: "Which statement is true?",
        options: [
          "{{6.5 * 10^(-3) < 6.5 * 10^(-4)}}",
          "{{6.5 * 10^(-3) = 6.5 * 10^(-4)}}",
          "{{6.5 * 10^(-3) > 6.5 * 10^(-4)}}",
          "You can't tell which is bigger without a calculator.",
        ],
        answerIndex: 2,
        explanation: "{{10^(-3)}} = 0.001 is bigger than {{10^(-4)}} = 0.0001, so 0.0065 > 0.00065. Choosing < comes from thinking −4 is \"bigger\" than −3 — but on a number line −4 is further left, so {{10^(-4)}} is the smaller power. Having the same front number doesn't make two numbers equal when the powers differ.",
        difficulty: "warmup",
        guideRef: "comparing-standard-form",
        hints: [
          "Which is bigger: {{10^(-3)}} or {{10^(-4)}}? Write them both as decimals.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q06",
        question: "A shelf is 2450 mm long. How long is it in metres? (1 m = 1000 mm)",
        options: [
          "24.5 m",
          "2.45 m",
          "245 m",
          "2 450 000 m",
        ],
        answerIndex: 1,
        explanation: "Metres are bigger units, so there will be fewer of them: 2450 ÷ 1000 = 2.45 m (every digit moves three places right). 24.5 m comes from dividing by 100, as if 1 m were 100 mm. 2 450 000 m multiplies instead of dividing — a shelf 2450 km long!",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Will the number of metres be bigger or smaller than the number of millimetres?",
          "1000 mm make 1 m, so divide by 1000.",
          "÷ 1000 moves every digit three places to the right.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q07",
        question: "Which power of 10 is equal to 0.0001?",
        options: [
          "{{10^(-4)}}",
          "{{10^(-3)}}",
          "{{10^4}}",
          "{{10^(-5)}}",
        ],
        answerIndex: 0,
        explanation: "0.0001 = {{1/10000}} = {{1/10^4}} = {{10^(-4)}}. Quick check: the 1 is in the **4th** decimal place, so the power is −4. {{10^(-3)}} comes from counting the three zeros after the point — but that is 0.001. {{10^(-5)}} counts all five digits, and {{10^4}} = 10 000.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Which decimal place is the 1 in?",
          "0.1 = {{10^(-1)}} and 0.01 = {{10^(-2)}}. Continue the pattern.",
          "The 1 is in the fourth decimal place.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q08",
        question: "The place-value chart shows a number before (top row) and after (bottom row) a calculation. Which calculation does it show?",
        diagram: `<svg viewBox="0 0 400 175" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Place-value chart with columns 10, 1, 0.1, 0.01, 0.001 and 0.0001. Top row shows 3.45 (3 in the ones column, 4 in tenths, 5 in hundredths). Bottom row shows 0.0345. Arrows show each digit moving two columns to the right."><rect x="0" y="0" width="400" height="175" fill="#ffffff"/><rect x="20" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="50" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">10</text><rect x="20" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="20" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="80" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="110" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">1</text><rect x="80" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="80" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="140" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="170" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.1</text><rect x="140" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="140" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="200" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="230" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.01</text><rect x="200" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="200" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="260" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="290" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.001</text><rect x="260" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="260" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="320" y="10" width="60" height="28" fill="#c7d2fe" stroke="#334155"/><text x="350" y="29" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.0001</text><rect x="320" y="38" width="60" height="40" fill="#ffffff" stroke="#334155"/><rect x="320" y="125" width="60" height="40" fill="#ffffff" stroke="#334155"/><text x="110" y="64" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="170" y="64" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="230" y="64" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="110" y="151" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0</text><text x="170" y="151" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0</text><text x="230" y="151" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="290" y="151" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="350" y="151" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><circle cx="140" cy="64" r="3" fill="#1f2937"/><circle cx="140" cy="151" r="3" fill="#1f2937"/><line x1="110" y1="72" x2="222" y2="129.9" stroke="#b45309" stroke-width="2"/><polygon points="230,134 220.2,133.4 223.8,126.3" fill="#b45309"/><line x1="170" y1="72" x2="282" y2="129.9" stroke="#b45309" stroke-width="2"/><polygon points="290,134 280.2,133.4 283.8,126.3" fill="#b45309"/><line x1="230" y1="72" x2="342" y2="129.9" stroke="#b45309" stroke-width="2"/><polygon points="350,134 340.2,133.4 343.8,126.3" fill="#b45309"/></svg>`,
        options: [
          "3.45 × 100",
          "3.45 ÷ 10",
          "3.45 ÷ 0.01",
          "3.45 ÷ 100",
        ],
        answerIndex: 3,
        explanation: "Each digit moves **two** columns to the right, so every digit is worth {{1/100}} of what it was: 3.45 ÷ 100 = 0.0345. Moving right means getting smaller, so 3.45 × 100 has the direction backwards (it gives 345). 3.45 ÷ 0.01 is the same as × 100, so it also gives 345. ÷ 10 would move the digits only one column.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Are the digits moving into bigger or smaller columns?",
          "How many columns does each digit move?",
          "One column to the right is ÷ 10. What about two columns?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q09",
        question: "Work out {{10^5 * 10^3}}.",
        options: [
          "{{10^15}}",
          "{{10^8}}",
          "{{100^8}}",
          "{{10^2}}",
        ],
        answerIndex: 1,
        explanation: "{{10^5}} is five 10s multiplied together and {{10^3}} is three more, making eight 10s: {{10^8}} = 100 000 000. The answer {{10^15}} comes from multiplying 5 × 3 — but you are counting factors of 10, so you add. {{100^8}} wrongly multiplies the 10s together as well, and {{10^2}} subtracts.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "How many 10s are multiplied together in {{10^5}}? In {{10^3}}?",
          "Write all the 10s as one long multiplication and count them.",
          "Multiplying powers of 10: add the indices.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q10",
        question: "Mount Everest is 8849 m tall. Which is its height in standard form?",
        options: [
          "{{8.849 * 10^4}} m",
          "{{8849 * 10^0}} m",
          "{{8.849 * 10^3}} m",
          "{{8.8 * 10^3}} m",
        ],
        answerIndex: 2,
        explanation: "Put the point after the first digit: 8.849. Getting back to 8849 takes 3 jumps of the point, so 8849 = {{8.849 * 10^3}}. {{8.849 * 10^4}} counts the four digits — that would be 88 490 m. {{8.8 * 10^3}} = 8800 m has lost digits; standard form keeps every digit unless you are asked to round. In {{8849 * 10^0}} the front number is far bigger than 10.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "What is the front number? Put the point after the first digit.",
          "How many places does the point jump from 8.849 to 8849?",
          "8.849 → 88.49 → 884.9 → 8849.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q11",
        question: "A human hair is about 0.00008 m wide. Which is this width in standard form?",
        options: [
          "{{8 * 10^(-5)}} m",
          "{{8 * 10^(-4)}} m",
          "{{8 * 10^5}} m",
          "{{0.8 * 10^(-4)}} m",
        ],
        answerIndex: 0,
        explanation: "Turning 0.00008 into 8 takes **5** jumps of the point, so the width is {{8 * 10^(-5)}} m. {{8 * 10^(-4)}} comes from counting the four zeros after the point — but the point also has to jump past the 8. {{0.8 * 10^(-4)}} has the right value, but 0.8 isn't between 1 and 10. {{8 * 10^5}} m would be 800 km wide!",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "Count the jumps the decimal point makes to turn 0.00008 into 8.",
          "The number is less than 1, so the power is negative.",
          "Check: {{10^(-5)}} = 0.00001, and 8 of those is …?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q12",
        question: "Hana writes 72 000 as {{72 * 10^3}} and says it is in standard form. What is wrong?",
        options: [
          "Nothing — {{72 * 10^3}} equals 72 000, so it is in standard form.",
          "The front number should be 7.2, so it should be {{7.2 * 10^3}}.",
          "The front number must be less than 1, so it should be {{0.72 * 10^5}}.",
          "72 is not between 1 and 10; in standard form 72 000 is {{7.2 * 10^4}}.",
        ],
        answerIndex: 3,
        explanation: "{{72 * 10^3}} does equal 72 000, but standard form needs the front number to be at least 1 and less than 10. Make the front number 10 times smaller (72 → 7.2) and the power one bigger to make up for it: {{7.2 * 10^4}}. {{7.2 * 10^3}} only fixes the front number, so it equals 7200 — ten times too small. {{0.72 * 10^5}} has the right value, but 0.72 is less than 1.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "What are the rules for {{A * 10^n}} to be in standard form?",
          "Is 72 between 1 and 10?",
          "If the front number gets 10 times smaller, what must the power do?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q13",
        question: "Siti works out 0.6 ÷ 0.01 and gets 0.006. Which statement is correct?",
        options: [
          "She is right: dividing always makes a number smaller.",
          "She is wrong: ÷ 0.01 is the same as × 100, so 0.6 ÷ 0.01 = 60.",
          "She is wrong: ÷ 0.01 is the same as ÷ 10, so the answer is 0.06.",
          "She is wrong: ÷ 0.01 is the same as × 10, so the answer is 6.",
        ],
        answerIndex: 1,
        explanation: "Ask how many hundredths fit into 0.6: 0.6 is 60 hundredths, so 0.6 ÷ 0.01 = 60. Dividing by a number less than 1 makes the answer *bigger*. Siti's 0.006 is 0.6 ÷ 100 — she divided by 100 instead of by one hundredth. The answer 6 would be right for ÷ 0.1, not ÷ 0.01.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "How many lots of 0.01 fit into 0.6?",
          "Dividing by a number less than 1 — does the answer get bigger or smaller?",
          "0.01 = {{1/100}}, and dividing by {{1/100}} is the same as multiplying by 100.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q14",
        question: "What number is the arrow pointing to? Give it in standard form.",
        diagram: `<svg viewBox="0 0 420 100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from 0 to 0.001 split into 10 equal steps, with an arrow pointing at the 7th mark."><rect x="0" y="0" width="420" height="100" fill="#ffffff"/><line x1="30" y1="60" x2="390" y2="60" stroke="#1f2937" stroke-width="2"/><line x1="30" y1="48" x2="30" y2="72" stroke="#1f2937" stroke-width="2"/><line x1="66" y1="53" x2="66" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="102" y1="53" x2="102" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="138" y1="53" x2="138" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="174" y1="53" x2="174" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="210" y1="53" x2="210" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="246" y1="53" x2="246" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="282" y1="53" x2="282" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="318" y1="53" x2="318" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="354" y1="53" x2="354" y2="67" stroke="#1f2937" stroke-width="1.5"/><line x1="390" y1="48" x2="390" y2="72" stroke="#1f2937" stroke-width="2"/><text x="30" y="90" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0</text><text x="390" y="90" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.001</text><line x1="282" y1="14" x2="282" y2="42" stroke="#b91c1c" stroke-width="2.5"/><polygon points="282,52 276,41 288,41" fill="#b91c1c"/></svg>`,
        options: [
          "{{7 * 10^(-3)}}",
          "{{7 * 10^(-5)}}",
          "{{7 * 10^(-4)}}",
          "{{7 * 10^4}}",
        ],
        answerIndex: 2,
        explanation: "The line from 0 to 0.001 is split into 10 equal steps, so each step is 0.001 ÷ 10 = 0.0001. The arrow is 7 steps along: 7 × 0.0001 = 0.0007 = {{7 * 10^(-4)}}. {{7 * 10^(-3)}} = 0.007 treats each small step as 0.001 — but 0.001 is the whole line. {{7 * 10^(-5)}} makes each step 0.00001, which is ten times too small.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "What is the value of one small step?",
          "Ten equal steps make 0.001.",
          "One step is 0.0001 = {{10^(-4)}}. How many steps to the arrow?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q15",
        question: "The table shows the average distance of some planets from the Sun.\n\n| Planet | Distance (km) |\n|---|---|\n| Mercury | {{5.8 * 10^7}} |\n| Earth | {{1.5 * 10^8}} |\n| Jupiter | {{7.8 * 10^8}} |\n| Saturn | {{1.4 * 10^9}} |\n\nWhich planet is roughly 10 times as far from the Sun as Earth?",
        options: [
          "Saturn",
          "Jupiter",
          "Mercury",
          "None of these planets",
        ],
        answerIndex: 0,
        explanation: "Ten times Earth's distance is {{1.5 * 10^9}} km, and Saturn's {{1.4 * 10^9}} km is very close — a little over 9 times as far. Jupiter is tempting because 7.8 is the biggest front number, but it has the same power as Earth, {{10^8}}, so it is only about 5 times as far. Mercury's power is one *lower* than Earth's, so it is closer to the Sun.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "Write 10 times Earth's distance in standard form.",
          "Multiplying by 10 adds 1 to the power.",
          "Look for a planet with power 9 and a front number close to 1.5.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q16",
        question: "Work out {{(8 * 10^6) / (2 * 10^2)}}. Give your answer in standard form.",
        options: [
          "{{4 * 10^3}}",
          "{{6 * 10^4}}",
          "{{4 * 10^8}}",
          "{{4 * 10^4}}",
        ],
        answerIndex: 3,
        explanation: "Divide the front numbers and the powers separately: 8 ÷ 2 = 4 and {{10^6 / 10^2 = 10^(6-2) = 10^4}}. The answer {{4 * 10^3}} comes from dividing 6 by 2 — dividing powers of 10 means *subtracting* the indices. {{4 * 10^8}} adds them. Check: 8 000 000 ÷ 200 = 40 000.",
        difficulty: "core",
        guideRef: "calculating-standard-form",
        hints: [
          "Split it into (8 ÷ 2) × ({{10^6 / 10^2}}).",
          "Six 10s on top, two 10s underneath — how many are left after cancelling?",
          "Dividing powers of 10: subtract the indices.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q17",
        question: "A number goes into this function machine and 47 comes out. What number went in?",
        diagram: `<svg viewBox="0 0 454 80" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Function machine: input, then multiply by 100, then divide by 0.1, then multiply by 0.01, giving output 47."><rect x="0" y="0" width="454" height="80" fill="#ffffff"/><rect x="10" y="20" width="46" height="40" rx="6" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><text x="33" y="45" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">?</text><line x1="56" y1="40" x2="75" y2="40" stroke="#1f2937" stroke-width="2"/><polygon points="82,40 74,35 74,45" fill="#1f2937"/><rect x="82" y="20" width="76" height="40" rx="6" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><text x="120" y="45" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">× 100</text><line x1="158" y1="40" x2="177" y2="40" stroke="#1f2937" stroke-width="2"/><polygon points="184,40 176,35 176,45" fill="#1f2937"/><rect x="184" y="20" width="76" height="40" rx="6" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><text x="222" y="45" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">÷ 0.1</text><line x1="260" y1="40" x2="279" y2="40" stroke="#1f2937" stroke-width="2"/><polygon points="286,40 278,35 278,45" fill="#1f2937"/><rect x="286" y="20" width="76" height="40" rx="6" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><text x="324" y="45" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">× 0.01</text><line x1="362" y1="40" x2="381" y2="40" stroke="#1f2937" stroke-width="2"/><polygon points="388,40 380,35 380,45" fill="#1f2937"/><rect x="388" y="20" width="56" height="40" rx="6" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><text x="416" y="45" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">47</text><text x="33" y="74" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">in</text><text x="416" y="74" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">out</text></svg>`,
        options: [
          "470",
          "4.7",
          "0.47",
          "47",
        ],
        answerIndex: 1,
        explanation: "Combine the steps: × 100, then ÷ 0.1 (which is × 10), then × 0.01 (which is ÷ 100). Overall that is × 10, so the input was 47 ÷ 10 = 4.7. Check: 4.7 → 470 → 4700 → 47. The answer 470 comes from treating ÷ 0.1 as ÷ 10 — but dividing by a tenth makes a number bigger. 0.47 treats × 0.01 as ÷ 10, and 47 assumes the steps cancel out.",
        difficulty: "challenge",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Work backwards from 47, undoing the last box first.",
          "The inverse of × 0.01 is ÷ 0.01, which is × 100.",
          "Or combine the boxes: ÷ 0.1 is × 10 and × 0.01 is ÷ 100. What is the overall effect?",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q18",
        question: "In computing, \"kilo\" sometimes means {{10^3}} and sometimes means {{2^10}}. Which statement is true?",
        options: [
          "{{2^10}} is bigger, by 24.",
          "{{10^3}} is bigger, by 980.",
          "{{10^3}} is bigger, by 900.",
          "They are exactly equal — both are one thousand.",
        ],
        answerIndex: 0,
        explanation: "Double 1 ten times: 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024. So {{2^10}} = 1024, which is 24 more than {{10^3}} = 1000. \"Bigger by 980\" comes from working out {{2^10}} as 2 × 10 = 20, and \"bigger by 900\" from swapping it to {{10^2}} = 100. The two are close — that's why computer scientists borrowed the word \"kilo\" — but not equal.",
        difficulty: "challenge",
        guideRef: "powers-of-ten",
        hints: [
          "{{2^10}} means ten 2s multiplied together, not 2 × 10.",
          "Keep doubling: 2, 4, 8, 16, …",
          "After ten doublings you reach a number just over 1000.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q19",
        question: "A bacterium is about {{10^(-6)}} m long. How many of them, laid end to end, would stretch 1 cm? (1 cm = {{10^(-2)}} m)",
        options: [
          "1 000 000",
          "100 000 000",
          "10 000",
          "4",
        ],
        answerIndex: 2,
        explanation: "Divide: {{10^(-2) / 10^(-6) = 10^(-2 - (-6)) = 10^4}} = 10 000. Sense check: 1 mm is {{10^(-3)}} m, which fits 1000 bacteria, and 1 cm is 10 mm, so 10 × 1000 = 10 000. The answer 1 000 000 is how many fit in a whole metre — it forgets that 1 cm is only {{1/100}} of a metre. 4 is the difference between the powers, but that difference *is* the power, so the answer is {{10^4}}. 100 000 000 adds 6 + 2 instead.",
        difficulty: "challenge",
        guideRef: "powers-of-ten",
        hints: [
          "How many times does {{10^(-6)}} fit into {{10^(-2)}}? That is a division.",
          "Dividing powers of 10: subtract the indices — careful with the negatives.",
          "−2 − (−6) = −2 + 6.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m2-q20",
        question: "Light travels about {{3 * 10^5}} km every second. There are about {{8.64 * 10^4}} seconds in a day. Roughly how far does light travel in one day?",
        options: [
          "{{2.6 * 10^9}} km",
          "{{2.6 * 10^20}} km",
          "3.5 km",
          "{{2.6 * 10^10}} km",
        ],
        answerIndex: 3,
        explanation: "Distance = speed × time. 3 × 8.64 = 25.92 and {{10^5 * 10^4 = 10^9}}, giving {{25.92 * 10^9}}. 25.92 is too big to be the front number, so divide it by 10 and add 1 to the power: {{2.592 * 10^10}} ≈ {{2.6 * 10^10}} km. {{2.6 * 10^9}} forgets that last adjustment, so it is 10 times too small. {{2.6 * 10^20}} multiplies the powers, and 3.5 km divides the speed by the time.",
        difficulty: "challenge",
        guideRef: "calculating-standard-form",
        hints: [
          "Distance = speed × time.",
          "Multiply the front numbers and add the powers.",
          "Is your front number between 1 and 10? If not, adjust it — and the power.",
        ],
        strategy: "Make it simpler",
      },
    ],
  },
  {
    id: "standard-form-m3",
    title: "MCQ Paper 3",
    questions: [
      {
        kind: "mcq",
        id: "standard-form-m3-q01",
        question: "Work out 0.07 × 1000.",
        options: [
          "7",
          "700",
          "0.07000",
          "70",
        ],
        answerIndex: 3,
        explanation: "× 1000 moves every digit three places to the left: 0.07 → 0.7 → 7 → 70. The answer 7 moves only two places, and 700 moves four. 0.07000 just adds zeros after the decimal digits, which doesn't change the value at all.",
        difficulty: "warmup",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "× 1000 moves every digit three places left. Do it one place at a time.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q02",
        question: "What does {{10^3}} mean?",
        options: [
          "10 × 3",
          "10 × 10 × 10",
          "10 + 10 + 10",
          "3 × 3 × 3 × 3 × 3 × 3 × 3 × 3 × 3 × 3",
        ],
        answerIndex: 1,
        explanation: "The index 3 tells you how many 10s to multiply together: {{10^3}} = 10 × 10 × 10 = 1000. 10 × 3 = 30 multiplies by the index instead — a very common slip. 10 + 10 + 10 adds the 10s, and ten 3s multiplied together is {{3^10}}, with the base and index swapped.",
        difficulty: "warmup",
        guideRef: "powers-of-ten",
        hints: [
          "The small raised number tells you how many 10s are multiplied together.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q03",
        question: "Write {{4 * 10^3}} as an ordinary number.",
        options: [
          "12",
          "64",
          "4000",
          "120",
        ],
        answerIndex: 2,
        explanation: "{{10^3}} = 1000, so {{4 * 10^3}} = 4 × 1000 = 4000. The answer 64 comes from working out {{4^3}} — but the power belongs to the 10, not the 4. 12 is 4 × 3, and 120 is 4 × 10 × 3.",
        difficulty: "warmup",
        guideRef: "large-numbers",
        hints: [
          "Work out {{10^3}} first, then multiply by 4.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q04",
        question: "Which of these is equal to 0.5?",
        options: [
          "{{5 * 10^(-1)}}",
          "{{5 * 10^1}}",
          "{{5 * 10^0}}",
          "{{5 * 10^(-2)}}",
        ],
        answerIndex: 0,
        explanation: "{{10^(-1)}} = 0.1, and 5 × 0.1 = 0.5. {{5 * 10^1}} = 50 — a positive power makes the number bigger. {{5 * 10^0}} = 5 × 1 = 5, and {{5 * 10^(-2)}} = 0.05, which is ten times too small.",
        difficulty: "warmup",
        guideRef: "small-numbers",
        hints: [
          "Work out each one: {{10^1}} = 10, {{10^0}} = 1, {{10^(-1)}} = 0.1, {{10^(-2)}} = 0.01.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q05",
        question: "Which of these numbers is greater than one million?",
        options: [
          "{{9.9 * 10^5}}",
          "{{99 * 10^4}}",
          "{{8 * 10^(-7)}}",
          "{{1.2 * 10^6}}",
        ],
        answerIndex: 3,
        explanation: "One million is {{10^6}}, so {{1.2 * 10^6}} = 1 200 000 is bigger. {{9.9 * 10^5}} = 990 000 is just short — 9.9 is a big front number, but the power is lower. {{99 * 10^4}} is also 990 000, and {{8 * 10^(-7)}} is a tiny number less than 1.",
        difficulty: "warmup",
        guideRef: "comparing-standard-form",
        hints: [
          "Write one million as a power of 10, then compare.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q06",
        question: "1000 identical paper clips have a total mass of 450 g. What is the mass of one paper clip?",
        options: [
          "4.5 g",
          "0.045 g",
          "0.45 g",
          "450 000 g",
        ],
        answerIndex: 2,
        explanation: "Share 450 g between 1000 clips: 450 ÷ 1000 = 0.45 g (every digit moves three places right). 4.5 g is 450 ÷ 100 — the mass each clip would have if there were only 100 of them. 450 000 g (450 kg!) multiplies instead of dividing.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Should one clip weigh more or less than 1 g? Estimate first.",
          "Divide the total mass by the number of clips.",
          "÷ 1000 moves every digit three places to the right.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q07",
        question: "In the number 4.536, which place-value column is the digit 3 in?",
        options: [
          "{{10^2}}",
          "{{10^(-2)}}",
          "{{10^(-3)}}",
          "{{10^3}}",
        ],
        answerIndex: 1,
        explanation: "4.536 is 4 ones, 5 tenths, 3 hundredths and 6 thousandths. One hundredth is {{1/100}} = {{10^(-2)}}. {{10^2}} = 100 is the hundreds column — the 'ths' in 'hundredths' makes it a fraction. {{10^(-3)}} comes from counting the 3 as the third digit of the number, but the first digit, 4, is in the ones column, not a decimal place.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Name each digit's column: 4 is ones, 5 is …",
          "The second place after the point is hundredths.",
          "One hundredth = {{1/100}}. Which power of 10 is that?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q08",
        question: "In 2023 the population of Singapore was about 5 920 000. Which is this in standard form?",
        options: [
          "{{5.92 * 10^6}}",
          "{{592 * 10^4}}",
          "{{5.92 * 10^4}}",
          "{{5.92 * 10^7}}",
        ],
        answerIndex: 0,
        explanation: "Put the point after the first digit: 5.92. From 5.92 to 5 920 000 the point jumps 6 places, so the population is {{5.92 * 10^6}}. {{5.92 * 10^4}} counts only the four zeros — the 9 and the 2 have to move too. {{5.92 * 10^7}} counts all seven digits. {{592 * 10^4}} has the right value, but 592 isn't between 1 and 10.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Start with the front number 5.92.",
          "Count how many places the point jumps from 5.92 to 5 920 000.",
          "A whole number with 7 digits has power 6.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q09",
        question: "Write {{2.04 * 10^(-3)}} as an ordinary number.",
        options: [
          "0.000204",
          "0.0204",
          "0.00204",
          "2040",
        ],
        answerIndex: 2,
        explanation: "× {{10^(-3)}} moves the digits 3 places right: 2.04 → 0.204 → 0.0204 → 0.00204. The answer 0.000204 comes from writing three zeros after the point and then the digits — but the first move already puts the 2 into the tenths column. 2040 uses a positive power.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "Will the answer be bigger or smaller than 1?",
          "Move the digits one place right at a time, three times.",
          "After one move you have 0.204.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q10",
        question: "Without a calculator, which of these gives the largest answer?",
        options: [
          "8 × 50",
          "8 ÷ 0.1",
          "8000 × 0.01",
          "8 ÷ 0.01",
        ],
        answerIndex: 3,
        explanation: "Dividing by 0.01 is the same as multiplying by 100, so 8 ÷ 0.01 = 800. 8 × 50 = 400 is tempting if you believe multiplying always gives the biggest answer. 8 ÷ 0.1 = 80: fewer tenths than hundredths fit into 8. 8000 × 0.01 = 8000 ÷ 100 = 80.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Rewrite each division by a decimal as a multiplication.",
          "÷ 0.1 is × 10, and ÷ 0.01 is × 100.",
          "Now compare 800, 400, 80 and 80.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q11",
        question: "Which of these is NOT equal to 0.001?",
        options: [
          "{{10^(-3)}}",
          "{{1/(10 * 3)}}",
          "{{1/10^3}}",
          "0.1 × 0.1 × 0.1",
        ],
        answerIndex: 1,
        explanation: "{{1/(10 * 3)}} = {{1/30}}, which is about 0.033 — it mixes up {{10^3}} with 10 × 3. The others are all one thousandth: {{10^(-3)}} = {{1/10^3}} = {{1/1000}}, and 0.1 × 0.1 × 0.1 = 0.001 (a tenth of a tenth of a tenth). That last one is tempting to reject if you think 0.1 × 0.1 × 0.1 = 0.3.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Work out each option as a decimal.",
          "{{10^3}} means 10 × 10 × 10, not 10 × 3.",
          "0.1 × 0.1 = 0.01. Now multiply by 0.1 again.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q12",
        question: "Ethan's answer to a calculation is {{0.6 * 10^5}}. Which is this number correctly written in standard form?",
        options: [
          "{{6 * 10^4}}",
          "{{6 * 10^6}}",
          "{{6 * 10^5}}",
          "It is already in standard form.",
        ],
        answerIndex: 0,
        explanation: "0.6 is less than 1, so this isn't standard form yet. {{0.6 * 10^5}} = 60 000. Making the front number 10 times bigger (0.6 → 6) means the power must go *down* by 1: {{6 * 10^4}}. {{6 * 10^6}} adjusts the power the wrong way — it equals 6 000 000, a hundred times too big. {{6 * 10^5}} changes only the front number.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Write {{0.6 * 10^5}} as an ordinary number first.",
          "If the front number gets 10 times bigger, the power of 10 must make up for it.",
          "60 000 = 6 × ?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q13",
        question: "Which of these numbers is the largest?",
        options: [
          "{{9.5 * 10^(-3)}}",
          "{{4.8 * 10^(-5)}}",
          "{{3.1 * 10^(-2)}}",
          "{{0.2 * 10^(-1)}}",
        ],
        answerIndex: 2,
        explanation: "As decimals: {{3.1 * 10^(-2)}} = 0.031, {{0.2 * 10^(-1)}} = 0.02, {{9.5 * 10^(-3)}} = 0.0095 and {{4.8 * 10^(-5)}} = 0.000048. {{0.2 * 10^(-1)}} has the highest power, but it isn't in standard form — rewritten it is {{2 * 10^(-2)}}, which loses to 3.1. {{9.5 * 10^(-3)}} has the biggest front number, but powers matter first. {{4.8 * 10^(-5)}} is the smallest, not the largest: −5 is the lowest power.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "Check all four are in standard form first.",
          "With negative powers, {{10^(-2)}} is bigger than {{10^(-3)}}.",
          "Rewrite {{0.2 * 10^(-1)}} in standard form, then compare.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q14",
        question: "Which number is 1000 times bigger than {{4.2 * 10^7}}?",
        options: [
          "{{4.2 * 10^21}}",
          "{{4.2 * 10^8}}",
          "{{4.2 * 10^4}}",
          "{{4.2 * 10^10}}",
        ],
        answerIndex: 3,
        explanation: "1000 = {{10^3}}, so multiplying by 1000 adds 3 to the power: {{4.2 * 10^(7+3) = 4.2 * 10^10}}. {{4.2 * 10^21}} multiplies 7 × 3 — but × {{10^3}} means three *more* factors of 10. {{4.2 * 10^8}} is only 10 times bigger, and {{4.2 * 10^4}} is 1000 times *smaller*.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Write 1000 as a power of 10.",
          "Each extra × 10 adds 1 to the power.",
          "How many × 10s make × 1000?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q15",
        question: "A flu virus is about 120 nanometres across. One nanometre is {{10^(-9)}} m. Which is the virus's width in metres, in standard form?",
        options: [
          "{{1.2 * 10^(-11)}} m",
          "{{1.2 * 10^(-7)}} m",
          "{{120 * 10^(-9)}} m",
          "{{1.2 * 10^(-9)}} m",
        ],
        answerIndex: 1,
        explanation: "120 nm = {{120 * 10^(-9)}} m, but 120 is too big to be the front number. 120 = {{1.2 * 10^2}}, so the width is {{1.2 * 10^2 * 10^(-9)}} = {{1.2 * 10^(-7)}} m. {{1.2 * 10^(-11)}} moves the power the wrong way: making the front number 100 times smaller (120 → 1.2) means the power must go *up* by 2, from −9 to −7. {{1.2 * 10^(-9)}} forgets to change the power at all.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "Start with {{120 * 10^(-9)}}. Is that in standard form?",
          "Write 120 as {{1.2 * 10^2}}.",
          "Combine the powers: 2 + (−9).",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q16",
        question: "Wei Ling works out 3 000 000 × 4 000 000 on her calculator. The screen is shown. What is the value of the answer?",
        diagram: `<svg viewBox="0 0 240 120" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Calculator screen. Top line: 3000000 × 4000000. Answer line: 1.2E13"><rect x="0" y="0" width="240" height="120" fill="#ffffff"/><rect x="4" y="4" width="232" height="112" rx="12" fill="#334155"/><rect x="18" y="18" width="204" height="84" rx="6" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><text x="28" y="42" font-size="13" font-family="sans-serif" fill="#1f2937">3000000×4000000</text><text x="210" y="86" font-size="14" font-family="sans-serif" font-weight="bold" fill="#1f2937" text-anchor="end">1.2E13</text></svg>`,
        options: [
          "{{1.2 * 10^13}}",
          "{{1.2^13}}",
          "15.6",
          "120 000 000 000 000",
        ],
        answerIndex: 0,
        explanation: "E13 means \"× {{10^13}}\", so the screen shows {{1.2 * 10^13}}. Check: 3 million × 4 million = 12 × {{10^6 * 10^6}} = {{12 * 10^12}} = {{1.2 * 10^13}}. 120 000 000 000 000 is 12 followed by 13 zeros, which makes it ten times too big ({{1.2 * 10^14}}). {{1.2^13}} and 15.6 = 1.2 × 13 both misread the E.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "What does the E on a calculator screen stand for?",
          "E13 means × {{10^13}}.",
          "Estimate: 3 million × 4 million = 12 million million.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q17",
        question: "Find n if {{0.001 * 10^n = 10}}.",
        options: [
          "3",
          "−2",
          "4",
          "10 000",
        ],
        answerIndex: 2,
        explanation: "0.001 = {{10^(-3)}} and 10 = {{10^1}}, so {{10^(-3) * 10^n = 10^1}}. Adding indices: −3 + n = 1, so n = 4. Check: 0.001 × 10 000 = 10. n = 3 only gets you to 0.001 × 1000 = 1. 10 000 is the number you multiply by, but n is its *power*. −2 comes from adding −3 and 1 instead of finding the gap between them.",
        difficulty: "challenge",
        guideRef: "powers-of-ten",
        hints: [
          "Write 0.001 and 10 as powers of 10.",
          "When you multiply powers of 10, add the indices: −3 + n = 1.",
          "Or work backwards: how many places must 0.001 move to become 10?",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q18",
        question: "A news report says a company is worth \"a hundred thousand million dollars\". Which is this amount, in dollars, in standard form?",
        options: [
          "{{1 * 10^30}}",
          "{{1 * 10^11}}",
          "{{1.1 * 10^6}}",
          "{{1 * 10^12}}",
        ],
        answerIndex: 1,
        explanation: "\"A hundred thousand million\" means 100 000 lots of a million: {{10^5 * 10^6 = 10^(5+6) = 10^11}}. {{1 * 10^30}} multiplies the indices 5 × 6 instead of adding them. {{1.1 * 10^6}} adds 100 000 and 1 000 000 — but \"thousand million\" means *times*, just as \"two hundred\" means 2 × 100. {{1 * 10^12}} treats a hundred thousand as {{10^6}}, counting its six digits instead of its five zeros.",
        difficulty: "challenge",
        guideRef: "large-numbers",
        hints: [
          "Write a hundred thousand and a million as powers of 10.",
          "\"A hundred thousand million\" = 100 000 × 1 000 000.",
          "Multiplying powers of 10: add the indices.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q19",
        question: "Mei's calculation gives {{0.03 * 10^(-2)}}. Which is this number in standard form?",
        options: [
          "{{3 * 10^0}}",
          "{{3 * 10^(-2)}}",
          "{{3 * 10^(-3)}}",
          "{{3 * 10^(-4)}}",
        ],
        answerIndex: 3,
        explanation: "0.03 = {{3 * 10^(-2)}}, so the number is {{3 * 10^(-2) * 10^(-2)}} = {{3 * 10^(-4)}} = 0.0003. Making the front number 100 times bigger (0.03 → 3) means the power must make it 100 times smaller, so it goes *down* by 2: from −2 to −4. {{3 * 10^0}} = 3 moves the power the wrong way, and {{3 * 10^(-2)}} = 0.03 forgets to change it at all. {{3 * 10^(-3)}} treats 0.03 → 3 as one jump instead of two.",
        difficulty: "challenge",
        guideRef: "small-numbers",
        hints: [
          "Write the number as an ordinary decimal first.",
          "0.03 = {{3 * 10^(-2)}}. Substitute that in.",
          "{{10^(-2) * 10^(-2)}} = ?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m3-q20",
        question: "Work out {{3 * 10^4 + 5 * 10^3}}. Give your answer in standard form.",
        options: [
          "{{3.5 * 10^4}}",
          "{{8 * 10^7}}",
          "{{8 * 10^4}}",
          "{{1.5 * 10^8}}",
        ],
        answerIndex: 0,
        explanation: "You can only add front numbers when the powers match. Write them out: 30 000 + 5000 = 35 000 = {{3.5 * 10^4}}. {{8 * 10^4}} adds 3 + 5 as if both were ten-thousands — but {{5 * 10^3}} is only 5 thousands. {{8 * 10^7}} adds the front numbers *and* the powers, and {{1.5 * 10^8}} multiplies the two numbers instead of adding them.",
        difficulty: "challenge",
        guideRef: "calculating-standard-form",
        hints: [
          "Write both numbers out in full.",
          "Can 3 ten-thousands and 5 thousands make 8 of anything?",
          "30 000 + 5000 = ?",
        ],
        strategy: "Make it simpler",
      },
    ],
  },
  {
    id: "standard-form-m4",
    title: "MCQ Paper 4",
    questions: [
      {
        kind: "mcq",
        id: "standard-form-m4-q01",
        question: "Which calculation gives the same answer as 45 × 0.1?",
        options: [
          "45 ÷ 10",
          "45 × 10",
          "45 ÷ 100",
          "45 ÷ 0.1",
        ],
        answerIndex: 0,
        explanation: "0.1 is one tenth, and finding a tenth of something means dividing by 10: 45 × 0.1 = 45 ÷ 10 = 4.5. 45 × 10 = 450 goes the wrong way — multiplying by a number less than 1 makes 45 smaller. 45 ÷ 0.1 is also 450, and 45 ÷ 100 treats 0.1 as a hundredth.",
        difficulty: "warmup",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "0.1 is one tenth. What is one tenth of 45?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q02",
        question: "Which of these is 1 000 000 written as a power of 10?",
        options: [
          "{{10^7}}",
          "{{6^10}}",
          "{{10^6}}",
          "{{10 * 6}}",
        ],
        answerIndex: 2,
        explanation: "1 000 000 is 1 followed by six zeros — six 10s multiplied together: {{10^6}}. {{10^7}} counts all seven digits, including the 1. {{6^10}} swaps the base and the index (it's over 60 million), and 10 × 6 is just 60.",
        difficulty: "warmup",
        guideRef: "powers-of-ten",
        hints: [
          "Count the zeros — each one is a factor of 10.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q03",
        question: "Write {{2.5 * 10^4}} as an ordinary number.",
        options: [
          "250 000",
          "2500",
          "100",
          "25 000",
        ],
        answerIndex: 3,
        explanation: "× {{10^4}} moves the digits 4 places left: 2.5 → 25 → 250 → 2500 → 25 000. The answer 250 000 comes from writing four zeros after 25 — but one of the four moves was used to turn 2.5 into 25. 2500 moves only three places, and 100 is 2.5 × 4 × 10.",
        difficulty: "warmup",
        guideRef: "large-numbers",
        hints: [
          "Move the digits of 2.5 four places to the left, one place at a time.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q04",
        question: "Which of these is written correctly in standard form?",
        options: [
          "{{0.41 * 10^(-2)}}",
          "{{4.1 * 10^(-3)}}",
          "{{41 * 10^(-4)}}",
          "{{4.1 / 10^3}}",
        ],
        answerIndex: 1,
        explanation: "All four equal 0.0041, but standard form must look like {{A * 10^n}} with {{1 <= A < 10}}. Only {{4.1 * 10^(-3)}} fits. In {{0.41 * 10^(-2)}} the front number is too small, and in {{41 * 10^(-4)}} it is too big. {{4.1 / 10^3}} divides instead of multiplying by a negative power of 10.",
        difficulty: "warmup",
        guideRef: "small-numbers",
        hints: [
          "Check: is the front number between 1 and 10, and is it multiplied by a power of 10?",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q05",
        question: "A ribbon is 3.5 m long. How long is it in centimetres? (1 m = 100 cm)",
        options: [
          "350 cm",
          "35 cm",
          "3.500 cm",
          "0.035 cm",
        ],
        answerIndex: 0,
        explanation: "Centimetres are smaller units, so there are more of them: 3.5 × 100 = 350 cm. 35 cm only multiplies by 10. 0.035 cm divides instead of multiplying, and 3.500 is just 3.5 with extra zeros — the same number.",
        difficulty: "warmup",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Will the number of centimetres be bigger or smaller than 3.5?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q06",
        question: "A sheet of paper is 0.1 mm thick. How thick is a pile of 500 sheets?",
        options: [
          "5000 mm",
          "5 mm",
          "0.0002 mm",
          "50 mm",
        ],
        answerIndex: 3,
        explanation: "500 × 0.1 = 500 ÷ 10 = 50 mm, or 5 cm — about the thickness of a ream of printer paper. 5000 mm is a 5-metre pile: that treats × 0.1 as × 10. 5 mm treats 0.1 as a hundredth. 0.0002 mm divides 0.1 by 500, which would make the pile thinner than one sheet.",
        difficulty: "core",
        guideRef: "multiplying-dividing-by-powers-of-ten",
        hints: [
          "Estimate: how thick would 10 sheets be?",
          "× 0.1 is the same as ÷ 10.",
          "500 ÷ 10 = ?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q07",
        question: "Work out {{10^2 / 10^5}}. Give your answer as a decimal.",
        options: [
          "−1000",
          "1000",
          "0.001",
          "0.0001",
        ],
        answerIndex: 2,
        explanation: "Subtract the indices: {{10^2 / 10^5 = 10^(2-5) = 10^(-3)}} = 0.001. Check: 100 ÷ 100 000 = {{1/1000}}. The answer 1000 comes from working out 5 − 2 instead of 2 − 5 — but 100 ÷ 100 000 must be less than 1. −1000 treats the negative power as a negative number. 0.0001 is {{10^(-4)}}: one zero too many.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Is 100 ÷ 100 000 bigger or smaller than 1?",
          "Dividing powers of 10: subtract the indices, top minus bottom.",
          "{{10^(-3)}} = {{1/1000}}.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q08",
        question: "Which of these is NOT equal to 3 200 000?",
        options: [
          "{{3.2 * 10^6}}",
          "{{3.2 * 10^5}}",
          "{{32 * 10^5}}",
          "{{0.32 * 10^7}}",
        ],
        answerIndex: 1,
        explanation: "{{3.2 * 10^5}} = 320 000, ten times too small: from 3.2 to 3 200 000 the point moves 6 places, not 5. The other three all equal 3 200 000. {{32 * 10^5}} and {{0.32 * 10^7}} are tempting to pick because they *look* wrong — they aren't in standard form — but their values are correct. Value and form are different questions.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Convert each option back to an ordinary number.",
          "A number can be written correctly in many ways; only one of them is standard form.",
          "{{3.2 * 10^5}}: move the digits 5 places. What do you get?",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q09",
        question: "Which of these is equal to {{6 * 10^(-4)}}?",
        options: [
          "{{6/1000}}",
          "−60 000",
          "{{6/40}}",
          "{{6/10000}}",
        ],
        answerIndex: 3,
        explanation: "{{10^(-4) = 1/10^4 = 1/10000}}, so {{6 * 10^(-4) = 6/10000}} = 0.0006. {{6/1000}} = 0.006 would be {{6 * 10^(-3)}}. −60 000 treats the negative power as a negative number, and {{6/40}} uses 10 × 4 instead of {{10^4}}.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "What does a negative power mean?",
          "{{10^(-4)}} = {{1/10^4}}.",
          "{{10^4}} = 10 000.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q10",
        question: "The place-value table shows the digits of a number.\n\n| {{10^2}} | {{10^1}} | {{10^0}} | {{10^(-1)}} | {{10^(-2)}} | {{10^(-3)}} |\n|---|---|---|---|---|---|\n| 3 | 0 | 6 | 0 | 0 | 2 |\n\nWhat is the number?",
        options: [
          "306.002",
          "306.2",
          "3060.02",
          "306 002",
        ],
        answerIndex: 0,
        explanation: "{{10^2}} = 100, {{10^1}} = 10 and {{10^0}} = 1 (the ones column), then tenths, hundredths and thousandths. So the number is 3 hundreds, 6 ones and 2 thousandths: 306.002. 306.2 drops the zero place-holders, which moves the 2 into the tenths column. 3060.02 treats {{10^0}} as the tens column — but {{10^0}} = 1. 306 002 ignores the negative powers and reads every column as a whole-number column.",
        difficulty: "core",
        guideRef: "powers-of-ten",
        hints: [
          "Write each heading as an ordinary number: {{10^2}} = 100, …",
          "{{10^0}} = 1, so that is the ones column. The decimal point goes after it.",
          "The zeros hold places — don't drop them.",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q11",
        question: "The Moon is about 384 400 km from Earth. Which is this distance in standard form, correct to 2 significant figures?",
        options: [
          "{{3.84 * 10^5}} km",
          "{{3.8 * 10^6}} km",
          "{{3.8 * 10^5}} km",
          "{{38 * 10^4}} km",
        ],
        answerIndex: 2,
        explanation: "Exactly, 384 400 = {{3.844 * 10^5}} (the point jumps 5 places). To 2 significant figures the front number 3.844 becomes 3.8, because the next digit, 4, rounds down. So the answer is {{3.8 * 10^5}} km. {{3.84 * 10^5}} is correct to 3 significant figures, not 2. {{3.8 * 10^6}} counts the six digits — that is 3 800 000 km. In {{38 * 10^4}} the front number is too big.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "First write 384 400 in standard form exactly.",
          "How many places does the point jump from 3.844 to 384 400?",
          "Now round the front number to 2 significant figures.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q12",
        question: "Write 0.0306 in standard form.",
        options: [
          "{{3.6 * 10^(-2)}}",
          "{{3.06 * 10^(-2)}}",
          "{{3.06 * 10^(-3)}}",
          "{{306 * 10^(-4)}}",
        ],
        answerIndex: 1,
        explanation: "The front number is 3.06 — keep the zero between the 3 and the 6, because it holds a place. From 0.0306 to 3.06 the point jumps 2 places, so 0.0306 = {{3.06 * 10^(-2)}}. {{3.06 * 10^(-3)}} counts every zero in 0.0306, including the one after the 3, but only the jumps of the point matter. {{3.6 * 10^(-2)}} = 0.036 drops the place-holding zero.",
        difficulty: "core",
        guideRef: "small-numbers",
        hints: [
          "What is the front number? Start at the first non-zero digit and keep all the digits after it.",
          "Count the jumps of the point from 0.0306 to 3.06.",
          "Check: {{3.06 * 10^(-2)}} = 3.06 ÷ 100.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q13",
        question: "A scientist writes a number as {{45.6 * 10^7}}. Which is this number in standard form?",
        options: [
          "{{4.56 * 10^6}}",
          "{{4.56 * 10^7}}",
          "{{456 * 10^6}}",
          "{{4.56 * 10^8}}",
        ],
        answerIndex: 3,
        explanation: "45.6 is too big to be the front number. 45.6 = 4.56 × 10, so {{45.6 * 10^7 = 4.56 * 10 * 10^7 = 4.56 * 10^8}}. Making the front number 10 times smaller means the power must go *up* by 1. {{4.56 * 10^6}} adjusts the power the wrong way, so it is 100 times too small. {{4.56 * 10^7}} forgets to change the power at all.",
        difficulty: "core",
        guideRef: "large-numbers",
        hints: [
          "Is 45.6 between 1 and 10?",
          "Write 45.6 as 4.56 × 10.",
          "Combine that × 10 with the {{10^7}}.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q14",
        question: "Which of these numbers lies between {{10^4}} and {{10^5}}?",
        options: [
          "{{6.3 * 10^4}}",
          "{{6.3 * 10^5}}",
          "{{63 * 10^4}}",
          "{{0.63 * 10^4}}",
        ],
        answerIndex: 0,
        explanation: "{{10^4}} = 10 000 and {{10^5}} = 100 000, and {{6.3 * 10^4}} = 63 000 is between them. {{6.3 * 10^5}} = 630 000 is tempting because its power is 5, but it is above 100 000. The other two have power 4 but are not in standard form: {{63 * 10^4}} = 630 000 and {{0.63 * 10^4}} = 6300.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "Write {{10^4}} and {{10^5}} as ordinary numbers.",
          "Convert each option to an ordinary number.",
          "In standard form, every number with power 4 lies between {{10^4}} and {{10^5}}.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q15",
        question: "A film file is {{4.5 * 10^9}} bytes and a game app is {{6 * 10^8}} bytes. Which statement is true?",
        options: [
          "The app is bigger, because 6 is bigger than 4.5.",
          "The film is exactly 10 times the size of the app, because its power is one more.",
          "The film is 7.5 times the size of the app.",
          "The film is 0.75 times the size of the app.",
        ],
        answerIndex: 2,
        explanation: "Write both with the same power: {{4.5 * 10^9}} = {{45 * 10^8}}. Then 45 ÷ 6 = 7.5, so the film is 7.5 times the size of the app. One more power means exactly 10 times as big only when the front numbers match; here 4.5 is smaller than 6, which pulls it down to 7.5. 0.75 comes from dividing 4.5 by 6 and ignoring the powers.",
        difficulty: "core",
        guideRef: "comparing-standard-form",
        hints: [
          "Which has the bigger power of 10?",
          "Rewrite {{4.5 * 10^9}} using {{10^8}}.",
          "Now divide: 45 ÷ 6.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q16",
        question: "Work out {{(4 * 10^3) * (5 * 10^6)}}. Give your answer in standard form.",
        options: [
          "{{2 * 10^9}}",
          "{{2 * 10^10}}",
          "{{2 * 10^18}}",
          "{{9 * 10^9}}",
        ],
        answerIndex: 1,
        explanation: "4 × 5 = 20 and {{10^3 * 10^6 = 10^9}}, so the product is {{20 * 10^9}}. That isn't standard form: 20 = 2 × 10, so it becomes {{2 * 10^10}}. {{2 * 10^9}} turns 20 into 2 but forgets to add 1 to the power, making it 10 times too small. {{2 * 10^18}} multiplies the indices, and {{9 * 10^9}} adds the front numbers.",
        difficulty: "core",
        guideRef: "calculating-standard-form",
        hints: [
          "Multiply the front numbers, then the powers of 10.",
          "4 × 5 = 20. Is 20 allowed as the front number?",
          "20 = 2 × 10, so the power goes up by 1.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q17",
        question: "A whole number N is written in standard form as {{A * 10^5}}. What are the smallest and largest values N could have?",
        options: [
          "10 000 and 99 999",
          "100 000 and 1 000 000",
          "100 000 and 900 000",
          "100 000 and 999 999",
        ],
        answerIndex: 3,
        explanation: "A must satisfy {{1 <= A < 10}}. The smallest case is A = 1, giving 100 000. A can't be 10, but it can be 9.99999, giving 999 999 — the largest whole number below 1 000 000. 1 000 000 would need A = 10, which isn't allowed (it is {{1 * 10^6}}). 10 000 and 99 999 come from thinking power 5 means 5 digits — but {{10^5}} itself has 6 digits. 900 000 assumes A has to be a whole number.",
        difficulty: "challenge",
        guideRef: "large-numbers",
        hints: [
          "What values can A take?",
          "Try the extremes: the smallest possible A and the largest possible A.",
          "Can A be 10? What is the largest whole number below 1 000 000?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q18",
        question: "How many times smaller is {{3 * 10^(-7)}} than {{3 * 10^(-4)}}?",
        options: [
          "3 times",
          "{{10^11}} times",
          "1000 times",
          "It isn't smaller — it is bigger.",
        ],
        answerIndex: 2,
        explanation: "The front numbers match, so compare the powers. Going from {{10^(-4)}} down to {{10^(-7)}} is 3 steps, each one ÷ 10, so {{3 * 10^(-7)}} is {{10^3}} = 1000 times smaller. Check: 0.0003 ÷ 0.0000003 = 1000. \"3 times\" uses the difference of the powers directly — but a difference of 3 in the power means a factor of {{10^3}}. {{10^11}} adds 7 and 4, and thinking it is bigger comes from treating −7 as larger than −4.",
        difficulty: "challenge",
        guideRef: "comparing-standard-form",
        hints: [
          "Which is smaller: {{10^(-7)}} or {{10^(-4)}}?",
          "How many times do you divide by 10 to get from {{10^(-4)}} to {{10^(-7)}}?",
          "Three divisions by 10 is one division by …?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q19",
        question: "Zara's calculator shows {{2^50}} as `1.125899907E15`. How many digits does {{2^50}} have when it is written out in full?",
        options: [
          "16",
          "15",
          "10",
          "50",
        ],
        answerIndex: 0,
        explanation: "`E15` means × {{10^15}}, so {{2^50}} ≈ {{1.13 * 10^15}}. Numbers from {{10^15}} up to (but not including) {{10^16}} have 16 digits, because {{10^15}} is a 1 followed by 15 zeros. So {{2^50}} has 16 digits (it is 1 125 899 906 842 624). 15 is tempting, but that is the number of places the point moves, not the number of digits — the leading 1 is a digit too. 10 is just the digits on the screen.",
        difficulty: "challenge",
        guideRef: "comparing-standard-form",
        hints: [
          "What does E15 mean?",
          "How many digits do {{10^1}} = 10, {{10^2}} = 100 and {{10^3}} = 1000 have?",
          "A number {{A * 10^n}} (with n ≥ 0) has n + 1 digits before the point.",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "standard-form-m4-q20",
        question: "A phone has 64 GB of storage, where 1 GB = {{10^9}} bytes. Each photo uses {{4 * 10^6}} bytes. How many photos can the phone hold?",
        options: [
          "{{1.6 * 10^3}}",
          "{{1.6 * 10^4}}",
          "{{2.56 * 10^17}}",
          "{{1.6 * 10^(-5)}}",
        ],
        answerIndex: 1,
        explanation: "The phone holds {{64 * 10^9}} bytes. Divide: 64 ÷ 4 = 16 and {{10^9 / 10^6 = 10^3}}, giving {{16 * 10^3}} = 16 000 = {{1.6 * 10^4}} photos. {{1.6 * 10^3}} turns 16 into 1.6 but forgets to add 1 to the power. {{2.56 * 10^17}} multiplies instead of dividing — more photos than there are bytes! {{1.6 * 10^(-5)}} forgets that 1 GB is {{10^9}} bytes.",
        difficulty: "challenge",
        guideRef: "calculating-standard-form",
        hints: [
          "How many bytes are there in 64 GB?",
          "Number of photos = total bytes ÷ bytes per photo.",
          "Divide the front numbers, subtract the powers, then check the front number is between 1 and 10.",
        ],
        strategy: "Make it simpler",
      },
    ],
  },
];
