import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  // ======================================================================
  // MCQ Paper 1
  // ======================================================================
  {
    id: "decimals-rounding-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q01",
        question: "Work out 0.4 × 0.3.",
        options: ["0.12", "1.2", "0.012", "0.7"],
        answerIndex: 0,
        explanation:
          "4 × 3 = 12, and the two numbers have 1 + 1 = 2 decimal places between them, so the answer is 0.12. Sense check: 0.4 × 0.3 must be less than 0.4, because you are taking only 0.3 of it. 1.2 comes from counting only one decimal place; 0.7 comes from adding instead of multiplying.",
        difficulty: "warmup",
        guideRef: "multiplying-decimals",
        hints: ["Work out 4 × 3 first. Then ask: how many decimal places do 0.4 and 0.3 have altogether?"],
        strategy: "Count decimal places",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q02",
        question: "Round 6.4382 to 2 decimal places.",
        options: ["6.43", "6.44", "6.4", "6.438"],
        answerIndex: 1,
        explanation:
          "The second decimal place holds a 3. The digit straight after it is 8, which is 5 or more, so the 3 rounds up: 6.44. 6.43 just chops the extra digits off (truncating) without looking at the 8; 6.4 is only 1 decimal place.",
        difficulty: "warmup",
        guideRef: "decimal-places",
        hints: ["Find the 2nd digit after the point, then look only at the digit just after it."],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q03",
        question: "Which of these numbers is the smallest?\n\n0.3, 0.29, 0.209, 0.31",
        options: ["0.3", "0.29", "0.209", "0.31"],
        answerIndex: 2,
        explanation:
          "Write them all with three decimal places: 0.300, 0.290, 0.209, 0.310. Now compare like whole numbers of thousandths: 209 is the smallest, so 0.209 is the smallest. 0.3 is the tempting pick because it has the fewest digits, but length does not decide size — 0.3 is the same as 0.300.",
        difficulty: "warmup",
        guideRef: "ordering-and-shortcuts",
        hints: ["Pad every number with zeros so they all have three decimal places, then compare."],
        strategy: "Compare place by place",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q04",
        question: "Round 4870 to 1 significant figure.",
        options: ["5", "4000", "4900", "5000"],
        answerIndex: 3,
        explanation:
          "The first significant figure is the 4 in the thousands place. The next digit is 8, so round up to 5 thousands: 5000. Writing just 5 loses the place value — 4870 is nowhere near 5. 4900 is 2 significant figures, and 4000 chops instead of rounding.",
        difficulty: "warmup",
        guideRef: "significant-figures",
        hints: ["Which place is the first significant figure in? Your answer must still be roughly the same size as 4870."],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q05",
        question: "Which decimal is equal to {{2/9}}?",
        options: ["0.222… = 0.2̇", "0.29", "4.5", "0.2"],
        answerIndex: 0,
        explanation:
          "{{2/9}} means 2 ÷ 9. 9 goes into 20 twice with remainder 2, and the same step repeats for ever, giving 0.222… = 0.2̇. 4.5 comes from dividing 9 ÷ 2 — the wrong way round. 0.29 just writes the two digits next to each other.",
        difficulty: "warmup",
        guideRef: "recurring-decimals",
        hints: ["A fraction is a division: top ÷ bottom. Start 2.000 ÷ 9."],
        strategy: "Divide and watch the remainders",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q06",
        question: "Given that 37 × 24 = 888, what is 3.7 × 0.24?",
        options: ["8.88", "0.888", "88.8", "0.0888"],
        answerIndex: 1,
        explanation:
          "3.7 has 1 decimal place and 0.24 has 2, so the product has 3: 0.888. Estimate to check: 4 × 0.2 = 0.8. 8.88 comes from counting only 2 decimal places, which makes the answer ten times too big.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "How many decimal places do 3.7 and 0.24 have altogether?",
          "3.7 = 37 ÷ 10 and 0.24 = 24 ÷ 100. So the product is 888 divided by what?",
          "888 ÷ 1000 — then check it against the estimate 4 × 0.2.",
        ],
        strategy: "Count decimal places",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q07",
        question: "Work out 4.56 ÷ 0.4.",
        options: ["1.14", "114", "11.4", "0.114"],
        answerIndex: 2,
        explanation:
          "Multiply both numbers by 10 so the divisor is whole: 4.56 ÷ 0.4 = 45.6 ÷ 4 = 11.4. Check with the inverse: 0.4 × 11.4 = 4.56. 1.14 comes from changing 0.4 into 4 but leaving 4.56 alone — that is 4.56 ÷ 4, a different calculation. 114 multiplies 4.56 by 100 but 0.4 only by 10.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "Make the divisor a whole number. What must you multiply 0.4 by?",
          "Multiply BOTH numbers by 10 so the answer doesn't change.",
          "Now do 45.6 ÷ 4 by short division.",
        ],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q08",
        question: "Round 2.996 to 2 decimal places.",
        options: ["2.99", "2.910", "3.0", "3.00"],
        answerIndex: 3,
        explanation:
          "The hundredths digit is 9 and the next digit is 6, so round up. 2.99 + 0.01 = 3.00, and you keep both zeros to show 2 decimal places. 2.910 comes from writing '10' in the hundredths column instead of carrying; 2.99 truncates; 3.0 has the right value but shows only 1 decimal place.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "Which digit decides — and does it make the hundredths go up or stay?",
          "Rounding up means adding one hundredth: what is 2.99 + 0.01?",
          "The 9s roll over like a car's odometer: 2.99 → 3.00. How many decimal places must you show?",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q09",
        question: "Round 0.00456 to 2 significant figures.",
        options: ["0.0046", "0.00", "0.0045", "0.005"],
        answerIndex: 0,
        explanation:
          "Leading zeros only hold place value, so the first significant figure is the 4. Keep 4 and 5, look at the next digit (6) and round up: 0.0046. 0.00 is what you get rounding to 2 decimal places, not 2 significant figures; 0.005 is only 1 significant figure; 0.0045 truncates.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Where does the first significant figure start?",
          "The zeros before the 4 are placeholders. Underline the 4 and the 5.",
          "The digit after the 5 is 6. Round up or keep?",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q10",
        question:
          "Durian costs $18.90 per kg. Wei Ling buys a durian with a mass of 2.85 kg. Round each number to 1 significant figure to estimate the cost.",
        options: ["$40", "$60", "$30", "$600"],
        answerIndex: 1,
        explanation:
          "$18.90 ≈ $20 and 2.85 kg ≈ 3 kg, so the cost is about 20 × 3 = $60 (the exact cost is $53.865, about $53.87). $40 comes from chopping 2.85 down to 2 instead of rounding it to 3; $30 comes from chopping 18.90 down to 10.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round each number to 1 significant figure — look at the second digit to decide up or down.",
          "18.90 → 20 and 2.85 → 3.",
          "Now multiply the rounded numbers.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q11",
        question: "Which of these fractions gives a terminating decimal?",
        options: ["{{7/12}}", "{{4/15}}", "{{9/40}}", "{{5/6}}"],
        answerIndex: 2,
        explanation:
          "A fraction in its simplest form terminates exactly when its denominator has no prime factors except 2 and 5. 40 = 2 × 2 × 2 × 5, so {{9/40}} = 0.225 terminates. {{4/15}} is tempting because 15 contains a 5, but it also contains a 3, so {{4/15}} = 0.2666… recurs. 12 and 6 both contain a 3 as well.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "Write each denominator as a product of prime factors.",
          "Which primes go into 10, 100, 1000, …?",
          "Only 2s and 5s are allowed — find the denominator with no 3 in it.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q12",
        question: "Which calculation gives exactly the same answer as 4.7 × 9.9?",
        options: ["4.7 × 10 − 0.1", "4.7 × 10 − 4.7", "4 × 9 + 0.7 × 0.9", "4.7 × 10 − 4.7 × 0.1"],
        answerIndex: 3,
        explanation:
          "9.9 = 10 − 0.1, so 4.7 × 9.9 = 4.7 × 10 − 4.7 × 0.1 = 47 − 0.47 = 46.53. '4.7 × 10 − 0.1' forgets that you must take away 0.1 lots of 4.7, not just 0.1 (it gives 46.9). '4 × 9 + 0.7 × 0.9' misses the cross terms 4 × 0.9 and 0.7 × 9.",
        difficulty: "core",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "9.9 is very close to a friendly number. Which one?",
          "9.9 = 10 − 0.1, and every part of 9.9 has to be multiplied by 4.7.",
          "4.7 × (10 − 0.1): multiply 4.7 by both parts.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q13",
        question: "A ribbon 2.4 m long is cut into pieces that are each 0.15 m long. How many pieces are there?",
        options: ["16", "1.6", "160", "0.36"],
        answerIndex: 0,
        explanation:
          "You need 2.4 ÷ 0.15. Multiply both by 100: 240 ÷ 15 = 16 pieces. Check: 16 × 0.15 = 2.4. 1.6 comes from scaling the two numbers by different amounts (24 ÷ 15); 0.36 multiplies instead of dividing — and you can't have 0.36 of a piece.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "Is this a multiply or a divide? 'How many 0.15s fit into 2.4?'",
          "Multiply both 2.4 and 0.15 by 100 to make the divisor whole.",
          "240 ÷ 15.",
        ],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q14",
        question: "A rectangular rug is 3.4 m long and 2.5 m wide. What is its area?",
        diagram: `<svg viewBox="0 0 300 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A rectangle 3.4 m long and 2.5 m wide representing a rug"><rect x="0" y="0" width="300" height="200" fill="#ffffff"/><rect x="40" y="20" width="204" height="150" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><text x="142" y="192" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">3.4 m</text><text x="252" y="100" font-size="14" font-family="sans-serif" fill="#1f2937">2.5 m</text><text x="142" y="100" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#334155">rug</text></svg>`,
        options: ["11.8 m²", "6.2 m²", "8.5 m²", "85 m²"],
        answerIndex: 2,
        explanation:
          "Area = 3.4 × 2.5. 34 × 25 = 850, and there are 2 decimal places in total, so 8.50 = 8.5 m². Estimate: 3 × 3 = 9, which is close. 6.2 m² comes from multiplying the whole parts (3 × 2) and the decimal parts (0.4 × 0.5) separately — that misses 3 × 0.5 and 0.4 × 2. 11.8 m is the perimeter, not the area.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "Area of a rectangle = length × width.",
          "Work out 34 × 25 first.",
          "Then place the point: how many decimal places do 3.4 and 2.5 have altogether?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q15",
        question: "Round 306,512 to 3 significant figures.",
        options: ["307", "306,500", "307,000", "306,000"],
        answerIndex: 2,
        explanation:
          "A zero between non-zero digits is significant, so the first three significant figures are 3, 0 and 6. The next digit is 5, so round up to 307 thousand: 307,000. 306,500 comes from skipping the zero when counting figures; 307 loses the place value — the answer must still be about three hundred thousand.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Is the 0 in 306,512 significant?",
          "Zeros between non-zero digits always count. Underline 3, 0 and 6.",
          "The next digit is 5. Round, then fill the rest with zeros so the number keeps its size.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q16",
        question: "Priya uses a calculator to work out 31.2 × 0.48 and gets 149.76. Which statement is correct?",
        options: [
          "She is right: multiplying always makes a number bigger, and 149.76 is bigger than 31.2.",
          "She is wrong: 30 × 0.5 = 15, so the answer should be about 15.",
          "She is wrong: 0.48 is about a half, so the answer should be about 62.",
          "She is right: 31 × 5 = 155, which is close to 149.76.",
        ],
        answerIndex: 1,
        explanation:
          "Round to 1 significant figure: 30 × 0.5 = 15. The true answer is 14.976, so she probably slipped with the decimal point. 'About 62' doubles instead of halving — multiplying by about a half halves. '31 × 5 = 155' treats 0.48 as if it were 4.8. And multiplying a positive number by something less than 1 makes it smaller, not bigger.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round each number to 1 significant figure.",
          "What is 30 × 0.5? Is multiplying by 0.5 like doubling or like halving?",
          "Compare your estimate with 149.76.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q17",
        question:
          "Arjun rounds 3.45 to 1 decimal place and gets 3.5. Then he rounds 3.5 to the nearest whole number and gets 4. Which statement is correct?",
        options: [
          "3.45 to the nearest whole number is 3: rounding in two stages pushed it over halfway, so always round the original number.",
          "3.45 to the nearest whole number is 4, and his method is fine.",
          "3.45 to the nearest whole number is 3, because he should have rounded 3.45 to 3.4 first.",
          "3.45 to the nearest whole number is 4, because 3.45 is closer to 4 than to 3.",
        ],
        answerIndex: 0,
        explanation:
          "3.45 is 0.45 above 3 but 0.55 below 4, so to the nearest whole number it is 3 — only the tenths digit (4) decides. Rounding to 3.5 first moved the number up to the halfway point, and then it was rounded up a second time. 'Round 3.45 to 3.4 first' gets 3 for the wrong reason: 3.45 to 1 d.p. really is 3.5. The cure is to round the original number once.",
        difficulty: "challenge",
        guideRef: "decimal-places",
        hints: [
          "To round to the nearest whole number, which single digit should you look at?",
          "How far is 3.45 from 3? How far is it from 4?",
          "Compare 0.45 with 0.55 — which whole number is nearer?",
        ],
        strategy: "Spot the error",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q18",
        question:
          "{{1/7}} = 0.142857142857… where the block 142857 repeats for ever. What is the 100th digit after the decimal point?",
        options: ["2", "5", "7", "8"],
        answerIndex: 3,
        explanation:
          "The repeating block has 6 digits. 100 = 6 × 16 + 4, so after 16 complete blocks (96 digits) you need the 4th digit of the block: 1, 4, 2, 8 — it is 8. 7 is tempting if you assume the 100th digit finishes a block; 2 and 5 come from being one place out when counting into the block.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: [
          "How long is the repeating block?",
          "How many complete blocks fit into 100 digits, and how many digits are left over?",
          "100 = 6 × 16 + 4. Count 4 digits into the block.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q19",
        question:
          "x is a number with one decimal place, such as 6.8 or 7.0. When x is rounded to the nearest whole number, the result is 7. How many possible values of x are there?",
        options: ["9", "10", "11", "5"],
        answerIndex: 1,
        explanation:
          "x can be 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3 or 7.4 — that is 10 values. The error interval is {{6.5 <= x < 7.5}}. 11 wrongly includes 7.5, which rounds up to 8. 9 leaves out 6.5, but a halfway value rounds up, so 6.5 does round to 7.",
        difficulty: "challenge",
        guideRef: "error-intervals",
        hints: [
          "What is the smallest one-decimal-place number that rounds to 7? The largest?",
          "Halfway values round up: 6.5 → 7, but 7.5 → 8.",
          "List them from 6.5 up to 7.4 and count carefully.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m1-q20",
        question: "Without a calculator, work out 19.9 × 0.6 + 0.1 × 0.6.",
        options: ["11.94", "1.2", "120", "12"],
        answerIndex: 3,
        explanation:
          "Both products share the factor 0.6, so take it out: (19.9 + 0.1) × 0.6 = 20 × 0.6 = 12. 11.94 is only 19.9 × 0.6 — the extra 0.1 × 0.6 = 0.06 was forgotten. 1.2 is a place-value slip: 20 × 0.6 = 12, whereas 20 × 0.06 = 1.2.",
        difficulty: "challenge",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "What do the two products have in common?",
          "Factorise: (19.9 + 0.1) × 0.6.",
          "19.9 + 0.1 is a very friendly number.",
        ],
        strategy: "Make it simpler",
      },
    ],
  },

  // ======================================================================
  // MCQ Paper 2
  // ======================================================================
  {
    id: "decimals-rounding-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q01",
        question: "Work out 6 ÷ 0.2.",
        options: ["3", "1.2", "30", "0.3"],
        answerIndex: 2,
        explanation:
          "How many 0.2s fit into 6? Five fit into every 1, so 5 × 6 = 30. Or scale both by 10: 60 ÷ 2 = 30. 3 comes from changing 0.2 into 2 without changing the 6; 1.2 multiplies instead of dividing.",
        difficulty: "warmup",
        guideRef: "dividing-decimals",
        hints: ["How many lots of 0.2 fit into 1? So how many fit into 6?"],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q02",
        question: "Which statement is true?",
        options: ["−0.7 < −0.65", "0.09 > 0.1", "−0.3 < −0.31", "0.5 < 0.45"],
        answerIndex: 0,
        explanation:
          "−0.7 = −0.70 is further below zero than −0.65, so it is smaller: −0.7 < −0.65 is true. '−0.3 < −0.31' is false, because −0.31 is further below zero, so −0.31 is the smaller one. '0.09 > 0.1' is the 'more digits means bigger' trap: 0.09 is 9 hundredths and 0.1 is 10 hundredths.",
        difficulty: "warmup",
        guideRef: "ordering-and-shortcuts",
        hints: ["Picture a number line. For negative numbers, further from zero means smaller."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q03",
        question: "How many significant figures does 0.0705 have?",
        options: ["4", "2", "3", "5"],
        answerIndex: 2,
        explanation:
          "Start counting at the first non-zero digit, the 7. Then 7, 0 and 5 are significant — the zero between 7 and 5 counts — so there are 3. 4 counts the zero just after the point, which is only a placeholder; 2 wrongly ignores the zero sandwiched between 7 and 5.",
        difficulty: "warmup",
        guideRef: "significant-figures",
        hints: ["Start counting at the first non-zero digit. Do zeros between non-zero digits count?"],
        strategy: "Count from the first non-zero digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q04",
        question: "Work out 0.04 × 300.",
        options: ["1.2", "120", "0.12", "12"],
        answerIndex: 3,
        explanation:
          "Split 300 into 100 × 3. 0.04 × 100 = 4, and 4 × 3 = 12. 1.2 and 120 have the decimal point in the wrong place — check: 4 hundredths taken 300 times is 1200 hundredths, which is 12.",
        difficulty: "warmup",
        guideRef: "multiplying-decimals",
        hints: ["What is 0.04 × 100? Then multiply by 3."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q05",
        question:
          "A meal at a hawker centre costs $4.85. Round each number to 1 significant figure to estimate the cost of 19 meals.",
        options: ["$100", "$80", "$95", "$1000"],
        answerIndex: 0,
        explanation:
          "$4.85 ≈ $5 and 19 ≈ 20, so the cost is about 5 × 20 = $100 (the exact cost is $92.15). $80 comes from chopping 4.85 down to 4 instead of rounding it; $95 only rounds one of the two numbers.",
        difficulty: "warmup",
        guideRef: "estimation",
        hints: ["Round $4.85 and 19 to 1 significant figure each, then multiply."],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q06",
        question: "Which is the correct dot notation for 0.181818…?",
        options: ["0.18̇", "0.1̇8̇", "0.1̇81̇", "0.1̇"],
        answerIndex: 1,
        explanation:
          "The repeating block is '18', so the dots go over the first and last digits of that block: 0.1̇8̇. 0.18̇ means 0.18888… (only the 8 repeats). 0.1̇81̇ would mean the block '181' repeats: 0.181181…. 0.1̇ is 0.111….",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "Which group of digits repeats?",
          "Dots go over the first and last digit of the repeating block.",
          "Read each choice back as a decimal: 0.18̇ means 0.1888….",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q07",
        question: "Which of these numbers rounds to 4.3 when rounded to 1 decimal place?",
        options: ["4.249", "4.35", "4.25", "4.2"],
        answerIndex: 2,
        explanation:
          "4.25 has 2 tenths and the next digit is 5, so it rounds up to 4.3. Numbers that round to 4.3 lie from 4.25 up to (but not including) 4.35. 4.35 is tempting because it contains '.3', but the 5 after the 3 pushes it up to 4.4. 4.249 is just below the halfway point 4.25, so it rounds down to 4.2.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "Numbers that round to 4.3 lie between two halfway points. What are they?",
          "The halfway points are 4.25 and 4.35. Which one rounds to 4.3?",
          "Round each choice, looking only at the hundredths digit.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q08",
        question: "Mangoes cost $4.20 per kg. Jun buys 1.5 kg of mangoes. How much does he pay?",
        options: ["$2.80", "$5.70", "$63.00", "$6.30"],
        answerIndex: 3,
        explanation:
          "Cost = price per kg × mass = 4.20 × 1.5. 1 kg costs $4.20 and half a kg costs $2.10, so 1.5 kg costs $6.30. $2.80 comes from dividing instead of multiplying; $5.70 adds the numbers; $63.00 has the decimal point in the wrong place.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "Multiply or divide? Think: 2 kg would cost 2 × $4.20.",
          "Split 1.5 kg into 1 kg + 0.5 kg.",
          "$4.20 plus half of $4.20.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q09",
        question: "Round 8.0516 to 3 significant figures.",
        options: ["8.05", "8.052", "8.1", "8.0"],
        answerIndex: 0,
        explanation:
          "The 0 between 8 and 5 is significant, so the first three significant figures are 8, 0 and 5. The next digit is 1, so keep the 5: 8.05. 8.052 is 3 decimal places (or comes from skipping the zero); 8.1 is 2 significant figures; 8.0 chops off a figure.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Is the 0 in 8.0516 significant?",
          "Zeros between non-zero digits count, so the first three are 8, 0 and 5.",
          "The next digit is 1 — round up or keep?",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q10",
        question: "Which calculation has the same answer as 3.6 ÷ 0.04?",
        options: ["360 ÷ 4", "36 ÷ 4", "3.6 ÷ 4", "3600 ÷ 4"],
        answerIndex: 0,
        explanation:
          "Multiply both numbers by 100 to make the divisor whole: 3.6 ÷ 0.04 = 360 ÷ 4 = 90. '3.6 ÷ 4' changes only the divisor, which changes the answer. '36 ÷ 4' multiplies 3.6 by 10 but 0.04 by 100 — both numbers must be scaled by the same amount.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "What must you multiply 0.04 by to get a whole number?",
          "Do exactly the same to 3.6.",
          "Both × 100.",
        ],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q11",
        question: "Round each number to 1 significant figure to estimate {{(21.3 + 38.9)/0.47}}.",
        options: ["30", "12", "120", "1200"],
        answerIndex: 2,
        explanation:
          "To 1 s.f.: (20 + 40) ÷ 0.5 = 60 ÷ 0.5 = 120 (the exact value is about 128). 30 comes from halving 60 — but dividing by 0.5 doubles, because there are two halves in every 1. 12 and 1200 have the decimal point in the wrong place.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round each of the three numbers to 1 significant figure.",
          "Work out the top first: 20 + 40.",
          "60 ÷ 0.5 means 'how many halves are there in 60?'",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q12",
        question: "Write 0.65 as a fraction in its simplest form.",
        options: ["{{65/10}}", "{{13/20}}", "{{6/5}}", "{{13/200}}"],
        answerIndex: 1,
        explanation:
          "0.65 is 65 hundredths, {{65/100}}. Divide top and bottom by 5 to get {{13/20}}. {{13/200}} comes from putting 65 over 1000, which is 0.065. {{65/10}} is 6.5, and {{6/5}} just uses the digits as top and bottom.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "The last digit, 5, is in which column: tenths, hundredths or thousandths?",
          "Write 0.65 over 100.",
          "Simplify {{65/100}}: what is the HCF of 65 and 100?",
        ],
        strategy: "Use place value",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q13",
        question: "Put these numbers in order from smallest to largest:\n\n−0.6, −0.06, −0.66, −0.606",
        options: [
          "−0.06, −0.6, −0.606, −0.66",
          "−0.606, −0.66, −0.6, −0.06",
          "−0.66, −0.6, −0.606, −0.06",
          "−0.66, −0.606, −0.6, −0.06",
        ],
        answerIndex: 3,
        explanation:
          "Compare distances from zero first: 0.660 > 0.606 > 0.600 > 0.060. For negative numbers the one furthest from zero is the smallest, so the order is −0.66, −0.606, −0.6, −0.06. '−0.06, −0.6, −0.606, −0.66' is the order of the positive numbers — the minus signs reverse it. Putting −0.6 before −0.606 forgets that 0.606 is bigger than 0.600.",
        difficulty: "core",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "Ignore the signs for a moment. Write each with 3 decimal places and order the sizes.",
          "Now put the minus signs back. Which number is furthest below zero?",
          "The furthest from zero is the smallest negative number.",
        ],
        strategy: "Compare place by place",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q14",
        question: "A website had 6,036,860 visits last year. Round this to 2 significant figures.",
        options: ["6,040,000", "6.0", "6,036,900", "6,000,000"],
        answerIndex: 3,
        explanation:
          "The first two significant figures are 6 and 0 (millions and hundred-thousands). The next digit is 3, so round down: 6,000,000. It looks like a 1 s.f. answer, but here the second significant figure just happens to be 0. 6,040,000 is 3 significant figures; 6.0 loses the place value — the answer must still be about six million.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Name the first two significant figures and their place values.",
          "The second significant figure is the 0 in the hundred-thousands place. What is the next digit?",
          "Round, then fill with zeros so the number keeps its size.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q15",
        question: "Without working it out exactly, which statement about 0.7 × 0.8 is true?",
        options: ["It is greater than 0.8", "It is between 0.7 and 0.8", "It is less than 0.7", "It equals 1.5"],
        answerIndex: 2,
        explanation:
          "0.7 × 0.8 means 'eight tenths of 0.7', which is less than all of 0.7. In fact 0.7 × 0.8 = 0.56. 'Greater than 0.8' comes from believing that multiplying always makes things bigger — that only happens when you multiply by a number greater than 1. 'Between 0.7 and 0.8' treats multiplying like averaging; 1.5 is the sum, not the product.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "0.7 × 0.8 is the same as 0.8 of 0.7. Is that more or less than all of 0.7?",
          "What happens when you multiply a positive number by something less than 1?",
          "Check: 7 × 8 = 56, then place the point.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q16",
        question:
          "Hana estimates 6.8 × 3.7 by rounding both numbers up: 7 × 4 = 28. Without working out 6.8 × 3.7, which statement is true?",
        options: [
          "28 is an underestimate",
          "28 is an overestimate, because both numbers were rounded up",
          "28 is exactly right",
          "You cannot tell without working out 6.8 × 3.7",
        ],
        answerIndex: 1,
        explanation:
          "7 is bigger than 6.8 and 4 is bigger than 3.7. Making both factors of a product bigger makes the product bigger, so 28 is an overestimate (the exact answer is 25.16). 'You cannot tell' would be right if one number went up and the other went down — here both went up, so you can tell.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "When each number was rounded, did it go up or down?",
          "If both factors get bigger, what happens to the product?",
          "Both up → product up.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q17",
        question:
          "Always, sometimes or never true? 'A fraction with denominator 12 gives a recurring decimal.'",
        options: [
          "Always true, because 12 has a factor of 3",
          "Never true, because 12 is even",
          "Sometimes true: it recurs exactly when the numerator is odd",
          "Sometimes true: it terminates when the numerator is a multiple of 3",
        ],
        answerIndex: 3,
        explanation:
          "{{1/12}} = 0.08333… recurs, but {{3/12}} = {{1/4}} = 0.25 terminates. Since 12 = 2 × 2 × 3, the fraction terminates only if the 3 cancels, which happens when the numerator is a multiple of 3. 'Recurs exactly when the numerator is odd' fails twice: {{3/12}} has an odd numerator but terminates, and {{2/12}} = {{1/6}} has an even numerator but recurs.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: [
          "Try {{1/12}}, {{2/12}}, {{3/12}} and {{6/12}}.",
          "Simplify each fraction first, then look at the new denominator.",
          "12 = 2 × 2 × 3. When does the 3 cancel?",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q18",
        question:
          "In a 100 m race, Aisha's time is 12.347 s and Siti's time is 12.351 s. The scoreboard can show times rounded to 1 decimal place or to 2 decimal places. Which statement is true?",
        options: [
          "To 1 d.p. the times look different, but to 2 d.p. they look equal",
          "To 1 d.p. the times look equal, but to 2 d.p. they look different",
          "The times look equal both to 1 d.p. and to 2 d.p.",
          "The times look different both to 1 d.p. and to 2 d.p.",
        ],
        answerIndex: 0,
        explanation:
          "To 1 d.p.: 12.347 → 12.3 (next digit 4) but 12.351 → 12.4 (next digit 5), so they look different. To 2 d.p.: 12.347 → 12.35 (the 7 rounds the 4 up) and 12.351 → 12.35, so they look equal. The two times sit either side of 12.35, the halfway point between 12.3 and 12.4. 'Equal to 1 d.p. but different to 2 d.p.' is what most people expect, because more decimal places usually separates numbers — but not always.",
        difficulty: "challenge",
        guideRef: "decimal-places",
        hints: [
          "Round both times to 1 d.p. Then round both to 2 d.p.",
          "For 12.347 to 2 d.p., the digit after the hundredths is 7.",
          "Compare each pair of rounded times.",
        ],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q19",
        question: "Given that 391 ÷ 17 = 23, what is 3.91 ÷ 0.017?",
        options: ["2.3", "230", "23", "0.23"],
        answerIndex: 1,
        explanation:
          "Multiply both numbers by 1000 so the divisor becomes 17: 3.91 ÷ 0.017 = 3910 ÷ 17. 3910 is 10 times 391, so the answer is 10 × 23 = 230. Check: 0.017 × 230 = 3.91. 0.23 only allows for 3.91 being 391 ÷ 100 and forgets that dividing by the small number 0.017 makes the answer much bigger.",
        difficulty: "challenge",
        guideRef: "dividing-decimals",
        hints: [
          "Make the divisor 17 by multiplying both numbers by the same power of 10.",
          "0.017 × 1000 = 17. What is 3.91 × 1000?",
          "3910 ÷ 17 is how many times 391 ÷ 17?",
        ],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m2-q20",
        question:
          "A length L is recorded as 8 cm after being truncated to a whole number of centimetres (everything after the decimal point is chopped off). Which is the error interval for L?",
        options: ["{{7.5 <= L < 8.5}}", "{{8 <= L < 9}}", "{{8 <= L <= 9}}", "{{7.5 < L <= 8.5}}"],
        answerIndex: 1,
        explanation:
          "Truncating chops off the decimal part, so every length from 8 cm up to (but not including) 9 cm is recorded as 8: {{8 <= L < 9}}. {{7.5 <= L < 8.5}} is the interval for rounding to the nearest cm — truncation never turns 7.6 into 8. 9 itself is excluded, because 9 truncates to 9.",
        difficulty: "challenge",
        guideRef: "error-intervals",
        hints: [
          "Try some values: what do 7.9, 8.0, 8.7 and 8.99 truncate to?",
          "Truncation only ever chops — nothing rounds up.",
          "The smallest value is exactly 8; the largest gets as close to 9 as you like.",
        ],
        strategy: "Try small cases",
      },
    ],
  },

  // ======================================================================
  // MCQ Paper 3
  // ======================================================================
  {
    id: "decimals-rounding-m3",
    title: "MCQ Paper 3",
    questions: [
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q01",
        question: "Use an estimate to decide which calculator display shows the answer to 0.82 × 59.6.",
        options: ["4.8872", "48.872", "488.72", "0.48872"],
        answerIndex: 1,
        explanation:
          "0.82 ≈ 0.8 and 59.6 ≈ 60, so the answer is about 0.8 × 60 = 48. Only 48.872 is close. The other displays have the right digits but the decimal point in the wrong place, for example 488.72 is ten times too big.",
        difficulty: "warmup",
        guideRef: "estimation",
        hints: ["Round both numbers to 1 significant figure and multiply."],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q02",
        question: "Work out {{0.3^2}}.",
        options: ["0.9", "0.6", "0.09", "0.009"],
        answerIndex: 2,
        explanation:
          "{{0.3^2}} = 0.3 × 0.3. 3 × 3 = 9 and there are 2 decimal places in total, so 0.09. 0.9 forgets to count both decimal places; 0.6 doubles instead of squaring.",
        difficulty: "warmup",
        guideRef: "multiplying-decimals",
        hints: ["Squaring means multiplying the number by itself. Count the decimal places."],
        strategy: "Count decimal places",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q03",
        question: "Dividing a number by 0.25 always gives the same answer as …",
        options: ["multiplying by 4", "dividing by 4", "multiplying by 0.25", "multiplying by 25"],
        answerIndex: 0,
        explanation:
          "0.25 is a quarter, and there are 4 quarters in every 1, so dividing by 0.25 is the same as multiplying by 4. For example 3 ÷ 0.25 = 12 = 3 × 4. 'Dividing by 4' does the opposite — it makes the number smaller, but dividing by a number less than 1 makes it bigger.",
        difficulty: "warmup",
        guideRef: "dividing-decimals",
        hints: ["How many 0.25s fit into 1?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q04",
        question: "The speed of light is about 299,792 km per second. Round this to 1 significant figure.",
        options: ["200,000 km per second", "3 km per second", "290,000 km per second", "300,000 km per second"],
        answerIndex: 3,
        explanation:
          "The first significant figure is the 2 in the hundred-thousands place. The next digit is 9, so round up to 3 hundred thousand: 300,000 km per second. 200,000 chops instead of rounding; 3 loses the place value — the answer must still be about the same size as 299,792.",
        difficulty: "warmup",
        guideRef: "significant-figures",
        hints: ["Your answer must still be roughly the same size as 299,792. Which digit decides?"],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q05",
        question: "The number line shows the section between −0.4 and −0.3 shaded. Which number lies between −0.4 and −0.3?",
        diagram: `<svg viewBox="0 0 400 90" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from minus 0.5 to 0 with ticks every 0.1; the section from minus 0.4 to minus 0.3 is shaded"><rect x="0" y="0" width="400" height="90" fill="#ffffff"/><rect x="98" y="30" width="68" height="20" fill="#fde68a"/><line x1="30" y1="40" x2="370" y2="40" stroke="#1f2937" stroke-width="2"/><line x1="30" y1="32" x2="30" y2="48" stroke="#1f2937" stroke-width="2"/><line x1="98" y1="32" x2="98" y2="48" stroke="#1f2937" stroke-width="2"/><line x1="166" y1="32" x2="166" y2="48" stroke="#1f2937" stroke-width="2"/><line x1="234" y1="32" x2="234" y2="48" stroke="#1f2937" stroke-width="2"/><line x1="302" y1="32" x2="302" y2="48" stroke="#1f2937" stroke-width="2"/><line x1="370" y1="32" x2="370" y2="48" stroke="#1f2937" stroke-width="2"/><text x="30" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−0.5</text><text x="98" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−0.4</text><text x="166" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−0.3</text><text x="234" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−0.2</text><text x="302" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−0.1</text><text x="370" y="70" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">0</text></svg>`,
        options: ["−0.45", "−0.035", "−0.35", "−0.25"],
        answerIndex: 2,
        explanation:
          "−0.35 is exactly halfway between −0.4 and −0.3, in the shaded section. −0.035 is tempting because it contains a 3 and a 5, but it is only 35 thousandths below zero — much closer to zero than −0.3. −0.45 is below −0.4 and −0.25 is above −0.3.",
        difficulty: "warmup",
        guideRef: "ordering-and-shortcuts",
        hints: ["Write −0.4 and −0.3 as −0.40 and −0.30. Which choice fits between them?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q06",
        question:
          "GST of 9% on a $45.95 bag is 45.95 × 0.09 = $4.1355. What is the GST to the nearest cent?",
        options: ["$4.14", "$4.13", "$4.10", "$4.136"],
        answerIndex: 0,
        explanation:
          "A cent is $0.01, so 'nearest cent' means 2 decimal places. In 4.1355 the hundredths digit is 3 and the next digit is 5, so round up: $4.14. $4.13 chops instead of rounding; $4.136 is 3 decimal places — there is no such thing as a tenth of a cent.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "A cent is $0.01. How many decimal places is that?",
          "Find the hundredths digit of 4.1355 and the digit just after it.",
          "4.13|55 — the next digit is 5.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q07",
        question:
          "Aisha says: 'A fraction gives a terminating decimal whenever its denominator is even.' Which fraction shows that she is wrong?",
        options: ["{{1/5}}", "{{1/8}}", "{{1/3}}", "{{1/6}}"],
        answerIndex: 3,
        explanation:
          "To disprove her claim you need an even denominator whose decimal does NOT terminate. 6 is even and {{1/6}} = 0.1666… recurs, so she is wrong. {{1/5}} = 0.2 terminates with an odd denominator, but that does not contradict her — she never said odd denominators recur. {{1/8}} = 0.125 agrees with her claim, and {{1/3}} has an odd denominator so it says nothing about it.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "A counterexample must fit the 'if' part of her claim but not the 'then' part.",
          "So you need an even denominator…",
          "…whose decimal goes on for ever. Divide to check.",
        ],
        strategy: "Find a counterexample",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q08",
        question: "Given that 2.4 × 3.5 = 8.4, what is 0.24 × 350?",
        options: ["8.4", "84", "840", "0.84"],
        answerIndex: 1,
        explanation:
          "0.24 is 2.4 ÷ 10 and 350 is 3.5 × 100. Dividing one factor by 10 and multiplying the other by 100 makes the product 10 times bigger: 8.4 × 10 = 84. 8.4 comes from thinking the two changes cancel out — they don't, because 10 and 100 are different.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "How has 2.4 changed to become 0.24? How has 3.5 changed to become 350?",
          "÷ 10 and × 100. What is the overall effect on the product?",
          "Overall the product is multiplied by 10.",
        ],
        strategy: "Look for an invariant",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q09",
        question: "A calculator shows the area of a circular pond as 153.93804 m². Round this to 3 significant figures.",
        options: ["153.938 m²", "153 m²", "154 m²", "150 m²"],
        answerIndex: 2,
        explanation:
          "The first three significant figures are 1, 5 and 3; the next digit is 9, so round up: 154 m². 153.938 is 3 decimal places, not 3 significant figures. 153 chops instead of rounding, and 150 is only 2 significant figures.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Count significant figures from the first non-zero digit. Which are the first three?",
          "1, 5, 3 — and what is the next digit?",
          "A 9 rounds the 3 up.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q10",
        question: "Which of these calculations has the largest answer?",
        options: ["8 × 5", "8 ÷ 0.5", "8 × 0.5", "8 ÷ 0.05"],
        answerIndex: 3,
        explanation:
          "There are 20 lots of 0.05 in every 1, so 8 ÷ 0.05 = 8 × 20 = 160. 8 × 5 = 40 is the tempting choice if you think multiplying always beats dividing. 8 ÷ 0.5 = 16 and 8 × 0.5 = 4. Dividing by a small positive number gives a big answer.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "How many 0.05s fit into 1?",
          "So 8 ÷ 0.05 is the same as 8 × what?",
          "Work out all four — 40, 16, 4 and … — and compare.",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q11",
        question: "Round each number to 1 significant figure to estimate 412 ÷ 0.79.",
        options: ["320", "500", "50", "5000"],
        answerIndex: 1,
        explanation:
          "To 1 s.f. the calculation is 400 ÷ 0.8. Multiply both by 10: 4000 ÷ 8 = 500 (the exact answer is about 521.5). 320 comes from multiplying 400 by 0.8 instead of dividing — dividing by a number less than 1 must give MORE than 400.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round 412 and 0.79 to 1 significant figure.",
          "400 ÷ 0.8 — make the divisor a whole number.",
          "4000 ÷ 8.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q12",
        question: "Work out 6.3 × 101 without a calculator.",
        options: ["636.3", "631", "69.3", "6363"],
        answerIndex: 0,
        explanation:
          "101 = 100 + 1, so 6.3 × 101 = 6.3 × 100 + 6.3 × 1 = 630 + 6.3 = 636.3. 631 adds 1 instead of one lot of 6.3. 69.3 uses 10 + 1 instead of 100 + 1. 6363 copies the pattern 63 × 101 = 6363 but forgets that 6.3 has a decimal point.",
        difficulty: "core",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "Split 101 into two friendly numbers.",
          "101 = 100 + 1. Multiply 6.3 by each part.",
          "630 + 6.3.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q13",
        question: "Write {{5/11}} as a decimal.",
        options: ["0.45", "2.2", "0.4̇5̇", "0.45̇"],
        answerIndex: 2,
        explanation:
          "5 ÷ 11 = 0.454545…, with the block 45 repeating, so it is written 0.4̇5̇. 0.45̇ would mean 0.4555…, where only the 5 repeats. 0.45 stops after two digits, but 11 has no factors of 2 or 5, so {{5/11}} cannot terminate. 2.2 divides 11 by 5, the wrong way round.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "Divide 5 by 11: 50 ÷ 11 = 4 remainder 6. Keep going.",
          "60 ÷ 11 = 5 remainder 5 — you are back where you started.",
          "Which block repeats, and where do the dots go?",
        ],
        strategy: "Divide and watch the remainders",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q14",
        question: "Mei works out 0.84 ÷ 0.4 and gets 0.21. What was her mistake?",
        options: [
          "Nothing — her answer is correct",
          "She changed 0.4 into 4 but did not change 0.84 into 8.4",
          "She should have multiplied: the answer is 0.336",
          "She divided 0.4 by 0.84 instead",
        ],
        answerIndex: 1,
        explanation:
          "0.84 ÷ 4 = 0.21, so she turned 0.4 into 4 without doing the same to 0.84. Scaling both by 10 gives 8.4 ÷ 4 = 2.1. Check with the inverse: 0.4 × 2.1 = 0.84, but 0.4 × 0.21 = 0.084 — so 'her answer is correct' fails the check. 0.336 is 0.84 × 0.4, a different calculation.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "Check her answer with the inverse: what is 0.4 × 0.21?",
          "What would 0.84 ÷ 4 be?",
          "To keep the answer the same, both numbers must be multiplied by 10.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q15",
        question: "A door is 2.0372 m tall. What is its height to the nearest centimetre?",
        options: ["2.04 m", "2.03 m", "2.037 m", "2.0 m"],
        answerIndex: 0,
        explanation:
          "1 cm = 0.01 m, so 'nearest centimetre' means 2 decimal places of a metre. In 2.0372 the hundredths digit is 3 and the next digit is 7, so round up: 2.04 m. 2.037 m is to the nearest millimetre (3 d.p.); 2.03 m chops instead of rounding; 2.0 m is to the nearest 10 cm.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "What is 1 cm as a decimal of a metre?",
          "So 'nearest cm' means how many decimal places in metres?",
          "Look at the digit after the hundredths.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q16",
        question:
          "The table shows prices at a stationery shop.\n\n| Item | Price |\n|---|---|\n| Notebook | $2.95 |\n| Pen | $1.15 |\n| Calculator | $18.90 |\n\nPriya buys 4 notebooks, 6 pens and 1 calculator. Round each price to 1 significant figure to estimate the total cost.",
        options: ["$28", "$38", "$44", "$24"],
        answerIndex: 1,
        explanation:
          "To 1 s.f.: $2.95 ≈ $3, $1.15 ≈ $1 and $18.90 ≈ $20. So 4 × 3 + 6 × 1 + 20 = 12 + 6 + 20 = $38 (the exact total is $37.60). $24 comes from chopping every price down ($2, $1, $10); $28 chops only the calculator to $10; $44 rounds $1.15 up to $2, but its second digit is 1, so it rounds down.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round each price to 1 significant figure. What is $2.95 to 1 s.f.?",
          "Multiply each rounded price by how many she buys.",
          "Add 12 + 6 + 20.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q17",
        question:
          "Zara estimates 63.8 ÷ 7.2 as 60 ÷ 8 = 7.5. Without a calculator, decide which statement is true.",
        options: [
          "7.5 is an overestimate, because 8 is bigger than 7.2",
          "7.5 is exactly right, because the two changes cancel out",
          "You cannot tell, because one number went down and the other went up",
          "7.5 is an underestimate, because the top went down and the bottom went up",
        ],
        answerIndex: 3,
        explanation:
          "63.8 was rounded DOWN to 60 (less to share out) and 7.2 was rounded UP to 8 (sharing between more). Both changes make the answer smaller, so 7.5 is an underestimate — the true answer is about 8.86. 'You cannot tell' would be right for a product, but in a division, rounding the top down and the bottom up both push the answer the same way.",
        difficulty: "challenge",
        guideRef: "estimation",
        hints: [
          "What happens to a division if you make the top number smaller?",
          "What happens to a division if you make the bottom number bigger?",
          "Do both changes push the answer the same way?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q18",
        question: "How many of the fractions {{1/2}}, {{1/3}}, {{1/4}}, …, {{1/20}} are terminating decimals?",
        options: ["7", "10", "12", "6"],
        answerIndex: 0,
        explanation:
          "{{1/n}} terminates only when n has no prime factors other than 2 and 5. From 2 to 20 those are 2, 4, 5, 8, 10, 16 and 20 — 7 fractions. 10 comes from thinking every even denominator works, but {{1/6}} = 0.1666… does not. 12 counts every denominator with a factor 2 or 5, such as 6 and 15, but their factor 3 makes them recur.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: [
          "Which primes are allowed in the denominator of a terminating decimal?",
          "List the numbers from 2 to 20 built only from 2s and 5s.",
          "Don't forget 16 = 2 × 2 × 2 × 2 and 20 = 2 × 2 × 5.",
        ],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q19",
        question: "Without a calculator, work out 0.99 × 1.01.",
        options: ["1", "1.0001", "0.9999", "0.999"],
        answerIndex: 2,
        explanation:
          "Split 1.01 into 1 + 0.01: 0.99 × 1.01 = 0.99 + 0.99 × 0.01 = 0.99 + 0.0099 = 0.9999. The extra 0.0099 is a little less than the 0.01 that was lost, so the answer is just under 1. '1' assumes the −0.01 and +0.01 cancel out. 0.999 misplaces the point: 99 × 101 = 9999 and there are 4 decimal places.",
        difficulty: "challenge",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "Split 1.01 into 1 + 0.01.",
          "0.99 × 1 = 0.99. What is 0.99 × 0.01?",
          "Add 0.99 + 0.0099 carefully, lining up the points.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m3-q20",
        question: "Hana's height is 1.62 m, correct to the nearest centimetre. Which of these could NOT be her actual height?",
        options: ["1.615 m", "1.6249 m", "1.618 m", "1.625 m"],
        answerIndex: 3,
        explanation:
          "To the nearest cm the error interval is {{1.615 <= h < 1.625}}. 1.625 m would round UP to 1.63 m, so it is impossible. 1.615 m is tempting, but it is the lower bound and rounds up to 1.62 m, so it is allowed. 1.6249 m is just below the upper bound and rounds down to 1.62 m.",
        difficulty: "challenge",
        guideRef: "error-intervals",
        hints: [
          "Half a centimetre is 0.005 m. What are the lower and upper bounds?",
          "The bounds are 1.615 and 1.625. Which one is included?",
          "Test 1.625: what does it round to?",
        ],
        strategy: "Consider extremes",
      },
    ],
  },

  // ======================================================================
  // MCQ Paper 4
  // ======================================================================
  {
    id: "decimals-rounding-m4",
    title: "MCQ Paper 4",
    questions: [
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q01",
        question: "Each bag holds 0.75 kg of rice. What is the total mass of 12 bags?",
        options: ["0.9 kg", "9 kg", "90 kg", "12.75 kg"],
        answerIndex: 1,
        explanation:
          "0.75 × 12: 75 × 12 = 900, and there are 2 decimal places, so 9.00 = 9 kg. Or: 4 bags make 3 kg, so 12 bags make 9 kg. 12.75 kg adds instead of multiplying; 0.9 kg and 90 kg have the point in the wrong place.",
        difficulty: "warmup",
        guideRef: "multiplying-decimals",
        hints: ["0.75 kg is three quarters of a kilogram. How many kilograms do 4 bags make?"],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q02",
        question: "Round 15.508 to the nearest whole number.",
        options: ["15", "15.5", "16", "20"],
        answerIndex: 2,
        explanation:
          "For the nearest whole number, look at the tenths digit. It is 5, so round up: 16. 15 chops the decimals off instead of rounding; 15.5 is 1 decimal place; 20 is to the nearest 10.",
        difficulty: "warmup",
        guideRef: "decimal-places",
        hints: ["Which single digit decides when you round to a whole number?"],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q03",
        question: "Write {{3/8}} as a decimal.",
        options: ["0.38", "0.375", "2.6̇", "0.0375"],
        answerIndex: 1,
        explanation:
          "{{3/8}} = 3 ÷ 8 = 0.375 (or: {{1/8}} = 0.125, and 3 × 0.125 = 0.375). 0.38 just writes the digits 3 and 8 after a point; 2.6̇ = 2.666… divides 8 by 3, the wrong way round.",
        difficulty: "warmup",
        guideRef: "recurring-decimals",
        hints: ["{{3/8}} means 3 ÷ 8. Or start from {{1/8}} = 0.125."],
        strategy: "Use a known fact",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q04",
        question: "Which of these numbers is the largest?\n\n−2.5, −2.05, −2.55, −2.505",
        options: ["−2.05", "−2.5", "−2.55", "−2.505"],
        answerIndex: 0,
        explanation:
          "For negative numbers, the one closest to zero is the largest. With three decimal places they are −2.500, −2.050, −2.550 and −2.505, so −2.05 is closest to zero. −2.55 is the pick if you ignore the minus signs — but it is actually the smallest.",
        difficulty: "warmup",
        guideRef: "ordering-and-shortcuts",
        hints: ["Which of these numbers is closest to zero?"],
        strategy: "Compare place by place",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q05",
        question: "Which of these numbers is written to exactly 3 significant figures?",
        options: ["0.045", "0.0450", "0.00045", "4.050"],
        answerIndex: 1,
        explanation:
          "Start counting at the first non-zero digit. 0.0450 has 4, 5 and the final 0 — a zero at the end after the decimal point is significant, because it was written on purpose to show the accuracy. 0.045 and 0.00045 have only 2 (the zeros in front are placeholders). 4.050 has 4.",
        difficulty: "warmup",
        guideRef: "significant-figures",
        hints: ["Start at the first non-zero digit. Leading zeros never count; zeros after it do."],
        strategy: "Count from the first non-zero digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q06",
        question: "Given that 23 × 47 = 1081, which of these is equal to 1.081?",
        options: ["2.3 × 4.7", "0.23 × 0.47", "0.023 × 47", "0.0023 × 4.7"],
        answerIndex: 2,
        explanation:
          "1.081 has 3 decimal places, so the two numbers must have 3 decimal places between them: 0.023 has 3 and 47 has none, so 0.023 × 47 = 1.081. 2.3 × 4.7 has only 2 decimal places in total, giving 10.81; 0.23 × 0.47 has 4, giving 0.1081.",
        difficulty: "core",
        guideRef: "multiplying-decimals",
        hints: [
          "How many decimal places does 1.081 have?",
          "Count the decimal places in each pair of numbers.",
          "You need a total of exactly 3.",
        ],
        strategy: "Count decimal places",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q07",
        question: "Ravi walks 3.6 km in 0.75 hours. What is his average speed in km per hour?",
        options: ["2.7 km per hour", "48 km per hour", "about 0.21 km per hour", "4.8 km per hour"],
        answerIndex: 3,
        explanation:
          "Speed = distance ÷ time = 3.6 ÷ 0.75. Multiply both by 100: 360 ÷ 75 = 4.8 km per hour. Sense check: in three quarters of an hour he walks 3.6 km, so in a full hour he walks a bit more. 2.7 multiplies instead of dividing; about 0.21 divides the wrong way round (0.75 ÷ 3.6).",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "Speed = distance ÷ time.",
          "3.6 ÷ 0.75 — scale both numbers so the divisor is whole.",
          "360 ÷ 75. Try 75 × 4 = 300 first.",
        ],
        strategy: "Make the divisor whole",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q08",
        question: "Round each number to 1 significant figure to estimate {{(4.92 * 0.0398)/0.0195}}.",
        options: ["1", "10", "100", "0.1"],
        answerIndex: 1,
        explanation:
          "To 1 s.f.: (5 × 0.04) ÷ 0.02 = 0.2 ÷ 0.02. Multiply both by 100: 20 ÷ 2 = 10 (the exact value is about 10.04). 1 and 100 come from miscounting decimal places when dividing 0.2 by 0.02.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round each of the three numbers to 1 significant figure.",
          "Work out the top first: 5 × 0.04.",
          "0.2 ÷ 0.02 — make the divisor a whole number.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q09",
        question: "Work out 7.3 × 8.6 and give your answer to 2 significant figures.",
        options: ["63", "62", "62.8", "60"],
        answerIndex: 0,
        explanation:
          "73 × 86 = 6278 and there are 2 decimal places, so 7.3 × 8.6 = 62.78. To 2 s.f. keep the 6 and the 2; the next digit is 7, so round up: 63. 62.8 is 3 significant figures; 62 chops instead of rounding; 60 is only 1 significant figure.",
        difficulty: "core",
        guideRef: "significant-figures",
        hints: [
          "Work out 73 × 86 first, then place the point.",
          "62.78 — which are the first two significant figures?",
          "The next digit is 7.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q10",
        question: "Which fraction is equal to the recurring decimal 0.1̇ = 0.111…?",
        options: ["{{1/10}}", "{{1/11}}", "{{1/9}}", "{{11/100}}"],
        answerIndex: 2,
        explanation:
          "1 ÷ 9 = 0.111… because 9 goes into 10 once with remainder 1, again and again. {{1/10}} = 0.1 stops after one digit, {{11/100}} = 0.11 stops after two, and {{1/11}} = 0.0909… repeats the block 09, not 1.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: [
          "Which division keeps leaving a remainder of 1?",
          "10 ÷ 9 = 1 remainder 1. What happens next?",
          "Check each choice by dividing top by bottom.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q11",
        question: "The number line goes from −2 to −1, with a small tick every 0.1. Which point is at −1.35?",
        diagram: `<svg viewBox="0 0 460 110" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from minus 2 to minus 1 with ticks every 0.1 and four labelled points P, Q, R and S"><rect x="0" y="0" width="460" height="110" fill="#ffffff"/><line x1="30" y1="60" x2="430" y2="60" stroke="#1f2937" stroke-width="2"/><line x1="30" y1="50" x2="30" y2="70" stroke="#1f2937" stroke-width="2"/><line x1="70" y1="54" x2="70" y2="66" stroke="#334155"/><line x1="110" y1="54" x2="110" y2="66" stroke="#334155"/><line x1="150" y1="54" x2="150" y2="66" stroke="#334155"/><line x1="190" y1="54" x2="190" y2="66" stroke="#334155"/><line x1="230" y1="50" x2="230" y2="70" stroke="#1f2937" stroke-width="2"/><line x1="270" y1="54" x2="270" y2="66" stroke="#334155"/><line x1="310" y1="54" x2="310" y2="66" stroke="#334155"/><line x1="350" y1="54" x2="350" y2="66" stroke="#334155"/><line x1="390" y1="54" x2="390" y2="66" stroke="#334155"/><line x1="430" y1="50" x2="430" y2="70" stroke="#1f2937" stroke-width="2"/><text x="30" y="90" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−2</text><text x="230" y="90" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−1.5</text><text x="430" y="90" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−1</text><circle cx="150" cy="60" r="5" fill="#c7d2fe" stroke="#1f2937"/><circle cx="170" cy="60" r="5" fill="#c7d2fe" stroke="#1f2937"/><circle cx="290" cy="60" r="5" fill="#c7d2fe" stroke="#1f2937"/><circle cx="310" cy="60" r="5" fill="#c7d2fe" stroke="#1f2937"/><text x="150" y="40" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">P</text><text x="170" y="40" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">Q</text><text x="290" y="40" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">R</text><text x="310" y="40" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">S</text></svg>`,
        options: ["P", "Q", "R", "S"],
        answerIndex: 2,
        explanation:
          "−1.35 lies between −1.4 and −1.3: start at −1 and move 0.35 to the LEFT — three small gaps and a half — to reach R. Q is at −1.65, which is 0.35 to the right of −2: measuring from the wrong end. S is at −1.3, half a gap short. P is at −1.7, which comes from treating each small gap as 0.05.",
        difficulty: "core",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "Each small gap is 0.1. Is −1.35 nearer to −1 or to −2?",
          "−1.35 is between −1.3 and −1.4.",
          "Start at −1 and move 0.35 to the left.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q12",
        question: "Round {{2/3}} to 3 decimal places.",
        options: ["0.666", "0.67", "0.6667", "0.667"],
        answerIndex: 3,
        explanation:
          "{{2/3}} = 0.6666…. To 3 d.p. the fourth 6 rounds the third 6 up, giving 0.667. 0.666 chops the decimal off instead of rounding — the digits after it are 6s, which round up. 0.67 is 2 decimal places and 0.6667 is 4.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "Write {{2/3}} as a decimal to at least 4 places.",
          "0.666|6… — what is the digit after the third decimal place?",
          "A 6 rounds up.",
        ],
        strategy: "Look at the next digit",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q13",
        question:
          "Always, sometimes or never true? 'When you divide a positive number by a number between 0 and 1, the answer is bigger than the number you started with.'",
        options: [
          "Always true",
          "Sometimes true: only when the divisor is less than 0.5",
          "Never true",
          "Sometimes true: only when the starting number is bigger than 1",
        ],
        answerIndex: 0,
        explanation:
          "Always. Dividing by a number between 0 and 1 asks how many of these small pieces fit in, and more than one piece fits into every 1. For example 3 ÷ 0.5 = 6 and 0.2 ÷ 0.8 = 0.25, which is bigger than 0.2. 'Only when the divisor is less than 0.5' is wrong: 4 ÷ 0.8 = 5 is still bigger than 4.",
        difficulty: "core",
        guideRef: "dividing-decimals",
        hints: [
          "Try a few: 6 ÷ 0.5, 6 ÷ 0.8, 0.3 ÷ 0.6.",
          "How many 0.8s fit into 1 — more or fewer than one?",
          "Dividing by d (between 0 and 1) is the same as multiplying by {{1/d}}, which is bigger than 1.",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q14",
        question:
          "A car uses 6.8 litres of petrol for every 100 km. Use rounding to 1 significant figure to estimate how much petrol it uses on a 512 km journey.",
        options: ["3.5 litres", "35 litres", "350 litres", "3500 litres"],
        answerIndex: 1,
        explanation:
          "512 km ≈ 500 km, which is 5 lots of 100 km, and 6.8 ≈ 7 litres per 100 km. So about 7 × 5 = 35 litres (the exact amount is 34.816 litres). 350 litres comes from multiplying 7 by 50 — but 500 km is 5 hundreds, not 50. 3.5 litres would only take the car about 50 km.",
        difficulty: "core",
        guideRef: "estimation",
        hints: [
          "Round 512 and 6.8 to 1 significant figure.",
          "How many lots of 100 km are in 500 km?",
          "7 litres for each of those lots.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q15",
        question: "Work out 2.5 × 3.7 × 4 without a calculator.",
        options: ["37", "370", "24.8", "3.7"],
        answerIndex: 0,
        explanation:
          "You can multiply in any order, so pair the friendly numbers: 2.5 × 4 = 10, then 10 × 3.7 = 37. 370 is a place-value slip (10 × 3.7 is 37, not 370). 24.8 adds 2.5 and 3.7 before multiplying by 4.",
        difficulty: "core",
        guideRef: "ordering-and-shortcuts",
        hints: [
          "Which two of the three numbers multiply to something friendly?",
          "What is 2.5 × 4?",
          "Now 10 × 3.7.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q16",
        question:
          "Aisha says: 'To round to 1 decimal place, just delete every digit after the first decimal place.' For which of these numbers does her method give the correct answer?",
        options: ["6.38", "6.45", "6.42", "6.97"],
        answerIndex: 2,
        explanation:
          "Her method is truncating, which only matches rounding when the next digit is 0 to 4. 6.42 → 6.4 either way. For 6.45 the 5 means round up to 6.5, but deleting gives 6.4. 6.38 should round to 6.4, not 6.3, and 6.97 should round to 7.0, not 6.9.",
        difficulty: "core",
        guideRef: "decimal-places",
        hints: [
          "Round each number properly to 1 d.p., then apply her method. Compare.",
          "When does rounding NOT change the tenths digit?",
          "Look for a hundredths digit of 4 or less.",
        ],
        strategy: "Spot the error",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q17",
        question:
          "A whole number rounds to 2600 when rounded to 2 significant figures, and to 3000 when rounded to 1 significant figure. What is the smallest it could be?",
        options: ["2500", "2551", "2600", "2550"],
        answerIndex: 3,
        explanation:
          "To round to 2600 (2 s.f.) a whole number must be from 2550 to 2649. All of those are at least 2500, so they also round to 3000 (1 s.f.). The smallest is 2550, because a halfway value rounds up. 2500 rounds to 2500 to 2 s.f., not 2600. 2551 forgets that 2550 itself rounds up to 2600.",
        difficulty: "challenge",
        guideRef: "significant-figures",
        hints: [
          "Which whole numbers round to 2600 to 2 s.f.? Find the halfway point just below 2600.",
          "Now check: do those numbers also round to 3000 to 1 s.f.?",
          "Does a number exactly halfway round up or down?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q18",
        question:
          "{{a}} and {{b}} are two different numbers, both between 0 and 1. Which statement must be true?",
        options: [
          "{{a * b}} is smaller than both {{a}} and {{b}}",
          "{{a * b}} lies between {{a}} and {{b}}",
          "{{a * b}} is bigger than both {{a}} and {{b}}",
          "It depends on which of {{a}} and {{b}} is bigger",
        ],
        answerIndex: 0,
        explanation:
          "{{a * b}} means '{{a}} lots of {{b}}'. Since {{a}} is less than 1, that is less than all of {{b}}; in the same way it is less than {{a}}, because {{b}} is less than 1. For example 0.5 × 0.4 = 0.2, smaller than both. 'Lies between them' feels right if you think of multiplying as a kind of averaging, but 0.9 × 0.8 = 0.72 is below both 0.8 and 0.9.",
        difficulty: "challenge",
        guideRef: "multiplying-decimals",
        hints: [
          "Try {{a}} = 0.5 and {{b}} = 0.4. Then try two other pairs.",
          "Multiplying {{b}} by a number less than 1 gives less than {{b}}.",
          "Use the same argument the other way round for {{a}}.",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q19",
        question:
          "Let x = 0.4̇5̇ = 0.454545…. Then 100x = 45.4545…. Use 100x − x to write x as a fraction in its simplest form.",
        options: ["{{9/20}}", "{{4/9}}", "{{1/2}}", "{{5/11}}"],
        answerIndex: 3,
        explanation:
          "Subtracting lines up the endless tails so they cancel: 100x − x = 45.4545… − 0.4545… = 45, so 99x = 45 and x = {{45/99}} = {{5/11}}. Check: 5 ÷ 11 = 0.4545…. {{9/20}} = 0.45 exactly — it stops, so it cannot equal a recurring decimal. {{4/9}} = 0.444…, where only the 4 repeats.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: [
          "Write 100x = 45.4545… above x = 0.4545…. What happens when you subtract?",
          "The digits after the point match, so they cancel: 99x = 45.",
          "Simplify {{45/99}} by dividing top and bottom by 9.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "decimals-rounding-m4-q20",
        question: "A number x is 4.7 when rounded to 1 decimal place. Which is the error interval for x?",
        options: ["{{4.6 <= x < 4.8}}", "{{4.65 <= x <= 4.75}}", "{{4.7 <= x < 4.8}}", "{{4.65 <= x < 4.75}}"],
        answerIndex: 3,
        explanation:
          "Numbers that round to 4.7 run from the halfway point below (4.65) to the halfway point above (4.75). 4.65 rounds up to 4.7, so it is included (≤); 4.75 rounds up to 4.8, so it is excluded (<). {{4.65 <= x <= 4.75}} wrongly includes 4.75; {{4.7 <= x < 4.8}} is the interval for truncating, not rounding.",
        difficulty: "challenge",
        guideRef: "error-intervals",
        hints: [
          "What is halfway between 4.6 and 4.7? Between 4.7 and 4.8?",
          "Which of those halfway values rounds to 4.7, and which rounds to 4.8?",
          "Lower bound included, upper bound excluded.",
        ],
        strategy: "Consider extremes",
      },
    ],
  },
];
