// Equations & Inequalities — four 20-question MCQ papers.
// Every distractor is a specific misconception; explanations name it by value.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  // ======================================================================
  // MCQ PAPER 1
  // ======================================================================
  {
    id: "equations-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "equations-m1-q01",
        question: "Solve {{x + 9 = 4}}.",
        options: ["{{x = -5}}", "{{x = 13}}", "{{x = 5}}", "{{x = -13}}"],
        answerIndex: 0,
        explanation:
          "Subtract 9 from both sides: x = 4 − 9 = −5. Check: −5 + 9 = 4 ✓. The answer 13 comes from adding 9 to both sides, which piles on another 9 instead of undoing it. The answer 5 loses the sign: 4 − 9 is below zero.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["What single step undoes '+ 9'? Do it to both sides."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m1-q02",
        question: "Which inequality means '*x* is at least 5'?",
        options: ["{{x > 5}}", "{{x < 5}}", "{{x >= 5}}", "{{x <= 5}}"],
        answerIndex: 2,
        explanation:
          "'At least 5' means 5 or more, so 5 itself is allowed: {{x >= 5}}. {{x > 5}} is tempting, but it leaves out 5 itself. {{x <= 5}} means 'at most 5', which is the opposite direction.",
        difficulty: "warmup",
        guideRef: "inequalities",
        hints: ["Is 5 itself allowed? Which symbol includes the boundary number?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m1-q03",
        question: "Solve {{3x - 7 = 11}}.",
        options: ["{{x = 4/3}}", "{{x = 6}}", "{{x = 18}}", "{{x = 54}}"],
        answerIndex: 1,
        explanation:
          "Undo the − 7 first by adding 7 to both sides: 3x = 18. Then divide by 3: x = 6. Check: 3 × 6 − 7 = 11 ✓. {{4/3}} comes from subtracting 7 instead of adding it. 18 stops one step early: that is 3x, not x. 54 multiplies by 3 instead of dividing.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["Undo the operations in reverse order: deal with the − 7 before the × 3."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "equations-m1-q04",
        question: "Solve {{4(x - 2) = 20}}.",
        options: ["{{x = 5.5}}", "{{x = 3}}", "{{x = 5}}", "{{x = 7}}"],
        answerIndex: 3,
        explanation:
          "Divide both sides by 4: x − 2 = 5, so x = 7. (Or expand: 4x − 8 = 20, 4x = 28, x = 7.) Check: 4 × (7 − 2) = 20 ✓. 5.5 comes from expanding as 4x − 2, where the 4 only multiplied the x. 5 stops at x − 2 = 5 without adding the 2 back.",
        difficulty: "warmup",
        guideRef: "equations-with-brackets",
        hints: ["Either divide both sides by 4 first, or multiply out the bracket. The 4 multiplies *both* terms inside."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m1-q05",
        question: "Solve {{x/3 = 8}}.",
        options: ["{{x = 8/3}}", "{{x = 24}}", "{{x = 5}}", "{{x = 11}}"],
        answerIndex: 1,
        explanation:
          "x has been divided by 3, so multiply both sides by 3: x = 24. Check: {{24/3 = 8}} ✓. {{8/3}} divides by 3 a second time instead of undoing the division. 5 and 11 treat '÷ 3' as if it were '+ 3' or '− 3'.",
        difficulty: "warmup",
        guideRef: "fractional-equations",
        hints: ["What is the opposite of dividing by 3?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m1-q06",
        question: "Solve {{7x - 3 = 4x + 12}}.",
        options: ["{{x = 5}}", "{{x = 3}}", "{{x = 15}}", "{{x = 15/11}}"],
        answerIndex: 0,
        explanation:
          "Subtract 4x from both sides: 3x − 3 = 12. Add 3: 3x = 15, so x = 5. Check: 7 × 5 − 3 = 32 and 4 × 5 + 12 = 32 ✓. x = 3 comes from subtracting 3 from 12 instead of adding it. {{15/11}} comes from moving 4x across without changing its sign, giving 11x = 15.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Get all the x-terms on one side first. Which x-term is smaller?",
          "Subtract 4x from both sides: {{3x - 3 = 12}}.",
          "Now it is a two-step equation: undo the − 3, then the × 3.",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m1-q07",
        question: "Which inequality is shown on the number line?",
        diagram: `<svg viewBox="0 0 360 70" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from −4 to 5 with an open circle at −2, a filled circle at 3 and the segment between them shaded"><rect width="360" height="70" fill="#ffffff"/><line x1="10" y1="35" x2="350" y2="35" stroke="#334155" stroke-width="1.5"/><g stroke="#334155" stroke-width="1.5"><line x1="25" y1="29" x2="25" y2="41"/><line x1="60" y1="29" x2="60" y2="41"/><line x1="95" y1="29" x2="95" y2="41"/><line x1="130" y1="29" x2="130" y2="41"/><line x1="165" y1="29" x2="165" y2="41"/><line x1="200" y1="29" x2="200" y2="41"/><line x1="235" y1="29" x2="235" y2="41"/><line x1="270" y1="29" x2="270" y2="41"/><line x1="305" y1="29" x2="305" y2="41"/><line x1="340" y1="29" x2="340" y2="41"/></g><g font-size="12" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="25" y="58">−4</text><text x="60" y="58">−3</text><text x="95" y="58">−2</text><text x="130" y="58">−1</text><text x="165" y="58">0</text><text x="200" y="58">1</text><text x="235" y="58">2</text><text x="270" y="58">3</text><text x="305" y="58">4</text><text x="340" y="58">5</text></g><line x1="95" y1="35" x2="270" y2="35" stroke="#4f46e5" stroke-width="5"/><circle cx="95" cy="35" r="6" fill="#ffffff" stroke="#1f2937" stroke-width="2"/><circle cx="270" cy="35" r="6" fill="#1f2937"/></svg>`,
        options: ["{{-2 <= x < 3}}", "{{-2 < x < 3}}", "{{-2 <= x <= 3}}", "{{-2 < x <= 3}}"],
        answerIndex: 3,
        explanation:
          "An open (empty) circle means the number is *not* included, so −2 < x. A filled circle means it *is* included, so x ≤ 3. Together: {{-2 < x <= 3}}. {{-2 <= x < 3}} has the meanings of the two circles the wrong way round.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Look at each end separately. Is the circle at −2 filled or empty?",
          "Empty circle → strict (< or >). Filled circle → the end is included (≤ or ≥).",
          "−2 is not included, but 3 is.",
        ],
        strategy: "Check each end separately",
      },
      {
        kind: "mcq",
        id: "equations-m1-q08",
        question:
          "Ravi solves {{5x + 8 = 3}} like this:\n\n    5x + 8 = 3\n    5x = 11\n    x = 2.2\n\nWhat was his mistake?",
        options: [
          "He should have divided by 5 before dealing with the 8",
          "He should have subtracted 5 instead of dividing by 5",
          "He added 8 instead of subtracting it; the solution is x = −1",
          "He made no mistake: x = 2.2 is correct",
        ],
        answerIndex: 2,
        explanation:
          "To undo + 8 you subtract 8 from both sides: 5x = 3 − 8 = −5, so x = −1. Check: 5 × (−1) + 8 = 3 ✓. Substituting Ravi's 2.2 gives 5 × 2.2 + 8 = 19, not 3, so 2.2 cannot be right. Dividing by 5 first is allowed (it just creates fractions), so that was not his error.",
        difficulty: "core",
        guideRef: "solving-equations",
        hints: [
          "Substitute x = 2.2 back into {{5x + 8}}. Do you get 3?",
          "Look at the step from line 1 to line 2. What happened to the 8?",
          "To remove + 8 you must subtract 8 from both sides: 3 − 8 = ?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m1-q09",
        question: "The rectangle has length {{(2x + 3)}} cm and width x cm. Its perimeter is 36 cm. What is the value of x?",
        diagram: `<svg viewBox="0 0 300 140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A rectangle with length (2x + 3) cm along the top and width x cm down the left side"><rect width="300" height="140" fill="#ffffff"/><rect x="60" y="35" width="180" height="70" fill="#c7d2fe" stroke="#1f2937" stroke-width="2"/><text x="150" y="25" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">(2x + 3) cm</text><text x="52" y="75" font-size="13" font-family="sans-serif" text-anchor="end" fill="#1f2937">x cm</text></svg>`,
        options: ["{{x = 11}}", "{{x = 5.5}}", "{{x = 5}}", "{{x = 6}}"],
        answerIndex: 2,
        explanation:
          "Perimeter = 2 lengths + 2 widths: 2(2x + 3) + 2x = 6x + 6. So 6x + 6 = 36, 6x = 30 and x = 5. Check: length 13 cm, width 5 cm, and 13 + 5 + 13 + 5 = 36 ✓. x = 11 comes from adding one length and one width, which is only half the perimeter. x = 5.5 comes from doubling the 2x but not the + 3.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "How many lengths and how many widths go all the way round a rectangle?",
          "Perimeter = {{2(2x + 3) + 2x}}. Simplify it.",
          "{{6x + 6 = 36}}.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m1-q10",
        question: "Solve {{3(2x - 5) = 21}}.",
        options: ["{{x = 13/3}}", "{{x = 6}}", "{{x = 1}}", "{{x = 12}}"],
        answerIndex: 1,
        explanation:
          "Divide both sides by 3: 2x − 5 = 7. Add 5: 2x = 12. Divide by 2: x = 6. Expanding first also works: 6x − 15 = 21, 6x = 36, x = 6. {{13/3}} comes from expanding as 6x − 5, but the 3 must multiply the 5 as well. x = 1 comes from subtracting 5 instead of adding it. 12 is 2x, not x.",
        difficulty: "core",
        guideRef: "equations-with-brackets",
        hints: [
          "Two routes: divide both sides by 3 first, or expand the bracket. Which gives smaller numbers?",
          "Dividing by 3 gives {{2x - 5 = 7}}.",
          "Now undo the − 5, then the × 2.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m1-q11",
        question: "Solve the inequality {{4x + 3 > 23}}.",
        options: ["{{x > 5}}", "{{x < 5}}", "{{x >= 5}}", "{{x > 6.5}}"],
        answerIndex: 0,
        explanation:
          "Treat it like an equation: subtract 3 (4x > 20), then divide by 4 (x > 5). Dividing by a *positive* number never flips the sign, so {{x < 5}} is wrong. {{x >= 5}} wrongly includes 5: 4 × 5 + 3 = 23, which is not *greater* than 23. 6.5 comes from adding 3 instead of subtracting it.",
        difficulty: "core",
        guideRef: "solving-inequalities",
        hints: [
          "Solve it exactly as you would {{4x + 3 = 23}}, keeping the > sign throughout.",
          "Subtract 3 from both sides, then divide by 4.",
          "Does dividing by a positive number change the direction of the sign?",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m1-q12",
        question: "Solve {{(2x - 1)/5 = 3}}.",
        options: ["{{x = 7}}", "{{x = 16}}", "{{x = 1.6}}", "{{x = 8}}"],
        answerIndex: 3,
        explanation:
          "All of 2x − 1 is divided by 5, so multiply both sides by 5 first: 2x − 1 = 15. Then 2x = 16 and x = 8. Check: (16 − 1) ÷ 5 = 3 ✓. x = 7 comes from subtracting 1 instead of adding it. 16 stops before dividing by 2. 1.6 treats the equation as {{2x - 1/5 = 3}}, as if only the 1 were divided by 5.",
        difficulty: "core",
        guideRef: "fractional-equations",
        hints: [
          "What was the last thing done to x? Undo that first.",
          "Multiply both sides by 5: {{2x - 1 = 15}}.",
          "Now add 1, then divide by 2.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "equations-m1-q13",
        question: "The diagram shows three angles on a straight line. Find x.",
        diagram: `<svg viewBox="0 0 360 150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Three angles on a straight line, marked 2x degrees, 45 degrees and (x + 30) degrees from right to left"><rect width="360" height="150" fill="#ffffff"/><line x1="20" y1="130" x2="340" y2="130" stroke="#1f2937" stroke-width="2"/><line x1="180" y1="130" x2="217.6" y2="26.6" stroke="#1f2937" stroke-width="2"/><line x1="180" y1="130" x2="133.5" y2="30.3" stroke="#1f2937" stroke-width="2"/><circle cx="180" cy="130" r="3" fill="#1f2937"/><g font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="228" y="104">2x°</text><text x="178" y="78">45°</text><text x="126" y="104">(x + 30)°</text></g></svg>`,
        options: ["{{x = 95}}", "{{x = 50}}", "{{x = 105}}", "{{x = 35}}"],
        answerIndex: 3,
        explanation:
          "Angles on a straight line add up to 180°: 2x + 45 + x + 30 = 180, so 3x + 75 = 180, 3x = 105 and x = 35. Check: 70° + 45° + 65° = 180° ✓. x = 95 uses 360°, which is for angles round a point. x = 50 forgets the 45° angle. 105 is 3x, not x.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "What do angles on a straight line add up to?",
          "Add the three angles: {{2x + 45 + x + 30}}.",
          "{{3x + 75 = 180}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m1-q14",
        question: "Solve {{3x + 14 = 7x - 2}}.",
        options: ["{{x = 4}}", "{{x = 3}}", "{{x = -4}}", "{{x = 16}}"],
        answerIndex: 0,
        explanation:
          "Collect x on the side with *more* x's (7x) so the x-term stays positive. Subtract 3x: 14 = 4x − 2. Add 2: 16 = 4x, so x = 4. Check: 3 × 4 + 14 = 26 and 7 × 4 − 2 = 26 ✓. x = 3 comes from 14 − 2 instead of 14 + 2. x = −4 is a sign slip: if you subtract 7x instead, you get −4x = −16, and a negative divided by a negative is positive. 16 is 4x, not x.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Which side has more x's? Gather the x-terms there.",
          "Subtract 3x from both sides: {{14 = 4x - 2}}.",
          "Undo the − 2, then divide by 4.",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m1-q15",
        question: "x is an integer and {{-3 <= x < 2}}. Which list shows every possible value of x?",
        options: ["−2, −1, 0, 1, 2", "−3, −2, −1, 0, 1", "−2, −1, 0, 1", "−3, −2, −1, 0, 1, 2"],
        answerIndex: 1,
        explanation:
          "The ≤ next to −3 means −3 *is* included; the < next to 2 means 2 is *not*. So the integers are −3, −2, −1, 0, 1. The list −2, −1, 0, 1, 2 has both ends the wrong way round, and the list from −3 to 2 includes both ends.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Check each end separately: is −3 allowed? Is 2?",
          "≤ includes the end number; < does not.",
          "Start at −3 and count up, stopping before 2.",
        ],
        strategy: "Check each end separately",
      },
      {
        kind: "mcq",
        id: "equations-m1-q16",
        question: "Two numbers x and y satisfy {{x + y = 10}} and {{x - y = 4}}. What are x and y?",
        options: ["x = 3 and y = 7", "x = 6 and y = 4", "x = 7 and y = 3", "x = 14 and y = −4"],
        answerIndex: 2,
        explanation:
          "Add the two equations: the y's cancel, giving 2x = 14, so x = 7. Then 7 + y = 10 gives y = 3. Check the *other* equation too: 7 − 3 = 4 ✓. x = 6 and y = 4 fits only the first equation (6 − 4 = 2, not 4). x = 3 and y = 7 swaps them: 3 − 7 = −4. x = 14 forgets to halve 2x = 14.",
        difficulty: "core",
        guideRef: "simultaneous-equations",
        hints: [
          "What happens to the y's if you add the two equations together?",
          "Adding gives {{2x = 14}}.",
          "Find x, put it into {{x + y = 10}}, then check in the other equation.",
        ],
        strategy: "Eliminate a variable",
      },
      {
        kind: "mcq",
        id: "equations-m1-q17",
        question: "The sum of three consecutive odd numbers is 147. What is the largest of the three numbers?",
        options: ["49", "47", "51", "50"],
        answerIndex: 2,
        explanation:
          "Consecutive odd numbers go up in 2s: n, n + 2, n + 4. So 3n + 6 = 147, 3n = 141, n = 47, and the numbers are 47, 49 and 51. Quicker: the middle number is the mean, 147 ÷ 3 = 49, so the largest is 51. 50 comes from using n, n + 1, n + 2, but 48, 49, 50 are not all odd. 49 is the middle number, not the largest.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "If the smallest odd number is n, what is the next odd number?",
          "Write the sum: {{n + (n + 2) + (n + 4) = 147}}.",
          "Or: the middle one of three equally spaced numbers is their mean.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m1-q18",
        question: "Is the inequality {{2x > x}} always true, sometimes true or never true?",
        options: [
          "Always true: doubling a number always makes it bigger",
          "Never true: 2x and x are the same letter",
          "Sometimes true: only when x is a whole number",
          "Sometimes true: exactly when {{x > 0}}",
        ],
        answerIndex: 3,
        explanation:
          "Subtract x from both sides: {{2x > x}} becomes {{x > 0}}. So it is true for every positive number and false otherwise: x = 3 gives 6 > 3 ✓, but x = −3 gives −6 > −3 ✗ and x = 0 gives 0 > 0 ✗. 'Doubling always makes it bigger' is the trap: it fails for zero and for negatives. 'Only whole numbers' fails too: x = 0.5 works and x = 0 does not.",
        difficulty: "challenge",
        guideRef: "solving-inequalities",
        hints: [
          "Try a positive number, zero and a negative number.",
          "Solve it like an equation: subtract x from both sides.",
          "What does {{x > 0}} tell you about which values work?",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "equations-m1-q19",
        question:
          "Mei is 4 times as old as her brother Jun. In 6 years' time she will be twice as old as him. How old is Mei now?",
        options: ["3", "12", "18", "24"],
        answerIndex: 1,
        explanation:
          "Let Jun be j, so Mei is 4j. In 6 years: 4j + 6 = 2(j + 6), so 4j + 6 = 2j + 12, 2j = 6 and j = 3. Mei is 12. Check: in 6 years they will be 18 and 9, and 18 = 2 × 9 ✓. 24 comes from adding 6 to Jun's age but not to Mei's. 3 is Jun's age and 18 is Mei's age in 6 years.",
        difficulty: "challenge",
        guideRef: "forming-equations",
        hints: [
          "Let Jun's age now be j. Write Mei's age now, then both ages in 6 years.",
          "In 6 years Mei is {{4j + 6}} and Jun is {{j + 6}}.",
          "Mei's future age = 2 × Jun's future age: {{4j + 6 = 2(j + 6)}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m1-q20",
        question: "Solve {{(x + 5)/3 = (x - 1)/2}}.",
        options: ["{{x = 13}}", "{{x = 6}}", "{{x = 7}}", "{{x = -17}}"],
        answerIndex: 0,
        explanation:
          "Multiply both sides by 6 (the LCM of 3 and 2): 2(x + 5) = 3(x − 1), so 2x + 10 = 3x − 3 and x = 13. Check: {{18/3 = 6}} and {{12/2 = 6}} ✓. x = 6 comes from writing 2x + 5 = 3x − 1: the multiplier must reach every term of each numerator. x = −17 comes from multiplying the wrong way across, 3(x + 5) = 2(x − 1). x = 7 is a sign slip when collecting 10 and −3.",
        difficulty: "challenge",
        guideRef: "fractional-equations",
        hints: [
          "Clear both fractions at once: which number do 3 and 2 both divide into?",
          "Multiply both sides by 6: {{2(x + 5) = 3(x - 1)}}.",
          "Expand both brackets, then collect x on the side with more x's.",
        ],
        strategy: "Clear the fractions",
      },
    ],
  },

  // ======================================================================
  // MCQ PAPER 2
  // ======================================================================
  {
    id: "equations-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "equations-m2-q01",
        question: "Solve {{x - 8 = -2}}.",
        options: ["{{x = -10}}", "{{x = 6}}", "{{x = -6}}", "{{x = 10}}"],
        answerIndex: 1,
        explanation:
          "Add 8 to both sides: x = −2 + 8 = 6. Check: 6 − 8 = −2 ✓. −10 comes from subtracting 8 again instead of undoing it. 10 ignores the minus sign on the 2.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["What undoes '− 8'? Do it to both sides."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m2-q02",
        question: "Which of these numbers is a solution of {{x <= -2}}?",
        options: ["0", "−1", "2", "−5"],
        answerIndex: 3,
        explanation:
          "{{x <= -2}} means −2 or anything further *left* on the number line. −5 is to the left of −2, so it works. −1 is tempting because 1 is less than 2, but −1 is to the *right* of −2, so it is bigger: −1 > −2.",
        difficulty: "warmup",
        guideRef: "inequalities",
        hints: ["Picture a number line. Which numbers are to the left of −2?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m2-q03",
        question: "Solve {{x/5 + 2 = 6}}.",
        options: ["{{x = 20}}", "{{x = 40}}", "{{x = 28}}", "{{x = 4/5}}"],
        answerIndex: 0,
        explanation:
          "Subtract 2 first: {{x/5 = 4}}. Then multiply by 5: x = 20. Check: {{20/5 + 2 = 6}} ✓. 28 comes from multiplying the 6 by 5 but not the 2 (x + 2 = 30). 40 comes from adding 2 instead of subtracting it. {{4/5}} divides by 5 instead of multiplying.",
        difficulty: "warmup",
        guideRef: "fractional-equations",
        hints: ["Undo the + 2 first, then undo the ÷ 5."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "equations-m2-q04",
        question: "Which value of x is the solution of {{6 - 2x = 14}}?",
        options: ["{{x = 4}}", "{{x = 10}}", "{{x = -4}}", "{{x = -10}}"],
        answerIndex: 2,
        explanation:
          "Subtract 6 from both sides: −2x = 8, so x = −4. Check: 6 − 2 × (−4) = 6 + 8 = 14 ✓. x = 4 ignores the minus in front of 2x: 6 − 8 = −2, not 14. x = −10 comes from adding 6 instead of subtracting it (−2x = 20).",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["Subtract 6 from both sides first, or test each value. Watch the minus sign in front of 2x."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m2-q05",
        question: "Aisha wants to solve {{5(x - 3) = 35}} by expanding the bracket. What should her first line be?",
        options: ["{{5x - 15 = 35}}", "{{5x - 3 = 35}}", "{{5x + 15 = 35}}", "{{x - 15 = 35}}"],
        answerIndex: 0,
        explanation:
          "The 5 multiplies *every* term inside the bracket: 5 × x = 5x and 5 × (−3) = −15. So 5x − 15 = 35, giving 5x = 50 and x = 10. 5x − 3 forgets to multiply the 3. 5x + 15 loses the sign: a positive times a negative is negative.",
        difficulty: "warmup",
        guideRef: "equations-with-brackets",
        hints: ["Multiply each term inside the bracket by 5, keeping its sign."],
        strategy: "Use the area model",
      },
      {
        kind: "mcq",
        id: "equations-m2-q06",
        question: "Solve {{9x - 4 = 5x + 10}}.",
        options: ["{{x = 1.5}}", "{{x = 1}}", "{{x = 3.5}}", "{{x = 14}}"],
        answerIndex: 2,
        explanation:
          "Subtract 5x: 4x − 4 = 10. Add 4: 4x = 14. Divide by 4: x = 3.5. Solutions do not have to be whole numbers! Check: 9 × 3.5 − 4 = 27.5 and 5 × 3.5 + 10 = 27.5 ✓. 1.5 comes from 10 − 4 instead of 10 + 4. x = 1 comes from adding the 5x to the left side (14x = 14) instead of subtracting it.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Gather the x-terms on the side with more x's.",
          "Subtract 5x from both sides: {{4x - 4 = 10}}.",
          "4x = 14. Don't worry if the answer is not a whole number.",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m2-q07",
        question: "Solve {{x/3 - 2 <= 1}}.",
        options: ["{{x <= 1}}", "{{x <= 9}}", "{{x >= 9}}", "{{x <= 3}}"],
        answerIndex: 1,
        explanation:
          "Add 2: {{x/3 <= 3}}. Multiply by 3: {{x <= 9}}. Check with x = 9: 3 − 2 = 1, and ≤ allows equality ✓. {{x <= 3}} stops before multiplying by 3. {{x >= 9}} flips the sign for no reason: multiplying by a positive number keeps the direction. {{x <= 1}} divides by 3 instead of multiplying.",
        difficulty: "core",
        guideRef: "solving-inequalities",
        hints: [
          "Solve it like an equation: undo the − 2 first.",
          "Now you have {{x/3 <= 3}}. What undoes ÷ 3?",
          "Multiplying by a positive number does not change the inequality sign.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m2-q08",
        question:
          "At a hawker centre, Arjun buys 3 bowls of vegetable laksa and one drink costing $1.80. He pays $15.30 in total. Which equation can he solve to find p, the price in dollars of one bowl?",
        options: ["{{3p = 15.30 + 1.80}}", "{{p + 3 + 1.80 = 15.30}}", "{{3(p + 1.80) = 15.30}}", "{{3p + 1.80 = 15.30}}"],
        answerIndex: 3,
        explanation:
          "Three bowls cost 3p and the drink adds $1.80, so 3p + 1.80 = 15.30. Solving: 3p = 13.50, p = 4.50, so a bowl costs $4.50. {{3(p + 1.80) = 15.30}} would mean he bought three drinks. {{3p = 15.30 + 1.80}} adds the drink's cost when it should be taken away.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "Total cost = (cost of the bowls) + (cost of the drink).",
          "Three bowls at $p each cost 3p dollars.",
          "Now add the one drink and set it equal to the total paid.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m2-q09",
        question: "The number line shows the solution of an inequality. Which of these values is NOT a solution?",
        diagram: `<svg viewBox="0 0 360 70" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from −4 to 5 with an open circle at −1 and an arrow shaded to the right"><rect width="360" height="70" fill="#ffffff"/><line x1="10" y1="35" x2="350" y2="35" stroke="#334155" stroke-width="1.5"/><g stroke="#334155" stroke-width="1.5"><line x1="25" y1="29" x2="25" y2="41"/><line x1="60" y1="29" x2="60" y2="41"/><line x1="95" y1="29" x2="95" y2="41"/><line x1="130" y1="29" x2="130" y2="41"/><line x1="165" y1="29" x2="165" y2="41"/><line x1="200" y1="29" x2="200" y2="41"/><line x1="235" y1="29" x2="235" y2="41"/><line x1="270" y1="29" x2="270" y2="41"/><line x1="305" y1="29" x2="305" y2="41"/><line x1="340" y1="29" x2="340" y2="41"/></g><g font-size="12" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="25" y="58">−4</text><text x="60" y="58">−3</text><text x="95" y="58">−2</text><text x="130" y="58">−1</text><text x="165" y="58">0</text><text x="200" y="58">1</text><text x="235" y="58">2</text><text x="270" y="58">3</text><text x="305" y="58">4</text><text x="340" y="58">5</text></g><line x1="130" y1="35" x2="340" y2="35" stroke="#4f46e5" stroke-width="5"/><polygon points="354,35 340,28 340,42" fill="#4f46e5"/><circle cx="130" cy="35" r="6" fill="#ffffff" stroke="#1f2937" stroke-width="2"/></svg>`,
        options: ["−1", "−0.5", "0", "4"],
        answerIndex: 0,
        explanation:
          "The circle at −1 is open, so −1 itself is not included: the line shows {{x > -1}}. −0.5 *is* a solution: it is negative, but it lies to the right of −1, so it is bigger than −1. 0 and 4 are also to the right of −1.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Is the circle at −1 filled or open? What does that say about −1 itself?",
          "The arrow points right: every number greater than −1 is shaded.",
          "Is −0.5 greater or less than −1?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m2-q10",
        question: "Solve {{4(x + 2) - 3(x - 1) = 15}}.",
        options: ["{{x = 10}}", "{{x = 26}}", "{{x = 14}}", "{{x = 4}}"],
        answerIndex: 3,
        explanation:
          "Expand each bracket: 4x + 8 − 3x + 3 = 15, because −3 × −1 = +3. Simplify: x + 11 = 15, so x = 4. Check: 4 × 6 − 3 × 3 = 24 − 9 = 15 ✓. x = 10 comes from writing −3(x − 1) as −3x − 3, the sign slip that catches most people. x = 14 comes from multiplying only the x in each bracket. 26 adds 11 instead of subtracting it.",
        difficulty: "core",
        guideRef: "equations-with-brackets",
        hints: [
          "Expand both brackets first. Be careful with −3 × −1.",
          "{{4x + 8 - 3x + 3 = 15}}.",
          "Collect like terms: {{x + 11 = 15}}.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m2-q11",
        question: "Solve {{8x + 13 = 7}}.",
        options: ["{{x = 5/2}}", "{{x = -3/4}}", "{{x = -4/3}}", "{{x = -6}}"],
        answerIndex: 1,
        explanation:
          "Subtract 13: 8x = −6. Divide by 8: {{x = -6/8 = -3/4}}. Check: 8 × (−0.75) + 13 = −6 + 13 = 7 ✓. {{-4/3}} is upside down: it divides 8 by −6 instead of −6 by 8. {{5/2}} comes from adding 13 instead of subtracting it (8x = 20). −6 is 8x, not x.",
        difficulty: "core",
        guideRef: "solving-equations",
        hints: [
          "Undo the + 13 first. Will the answer be positive or negative?",
          "8x = −6.",
          "x = −6 ÷ 8. Write it as a fraction and simplify.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m2-q12",
        question: "Solve {{3x/4 = 9}}.",
        options: ["{{x = 36}}", "{{x = 27/4}}", "{{x = 12}}", "{{x = 3/4}}"],
        answerIndex: 2,
        explanation:
          "Multiply both sides by 4: 3x = 36. Divide by 3: x = 12. Check: {{(3 * 12)/4 = 36/4 = 9}} ✓. 36 is 3x, not x: one step short. {{27/4}} multiplies 9 by {{3/4}} instead of dividing by it. {{3/4}} divides by 4 instead of multiplying.",
        difficulty: "core",
        guideRef: "fractional-equations",
        hints: [
          "Two things were done to x: × 3 and ÷ 4. Undo both.",
          "Multiply both sides by 4 first: {{3x = 36}}.",
          "Dividing by {{3/4}} is the same as multiplying by {{4/3}}.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "equations-m2-q13",
        question: "The angles of the triangle are x°, 2x° and {{(x + 20)}}°. What is the size of the largest angle?",
        diagram: `<svg viewBox="0 0 340 225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle with angle x degrees at the bottom left, 2x degrees at the top and (x + 20) degrees at the bottom right"><rect width="340" height="225" fill="#ffffff"/><polygon points="40,200 300,200 215.1,53.1" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><g font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="84" y="192">x°</text><text x="212" y="92">2x°</text><text x="252" y="192">(x + 20)°</text></g></svg>`,
        options: ["40°", "60°", "170°", "80°"],
        answerIndex: 3,
        explanation:
          "Angles in a triangle add up to 180°: x + 2x + x + 20 = 180, so 4x = 160 and x = 40. The angles are 40°, 80° and 60°, so the largest is 80°. 40° is x itself, so always reread what the question asks for. 170° comes from using 360° (the angle sum of a quadrilateral). 60° is the third angle, not the largest.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "What do the angles in a triangle add up to?",
          "{{x + 2x + x + 20 = 180}}.",
          "Find x, then work out all three angles.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m2-q14",
        question:
          "Wei Ling solves {{5x + 3 = 2x - 9}}:\n\n    3x + 3 = −9\n    3x = −6\n    x = −2\n\nWhere did she go wrong?",
        options: [
          "Line 1: she should have added 2x to both sides",
          "Line 2: −9 − 3 is −12, so 3x = −12 and x = −4",
          "Line 3: −6 ÷ 3 is 2, not −2",
          "Nowhere: x = −2 is correct",
        ],
        answerIndex: 1,
        explanation:
          "Line 1 is fine (she subtracted 2x from both sides). In line 2 she must subtract 3 from both sides: −9 − 3 = −12, so 3x = −12 and x = −4. Check: 5 × (−4) + 3 = −17 and 2 × (−4) − 9 = −17 ✓. Her x = −2 fails the check: 5 × (−2) + 3 = −7 but 2 × (−2) − 9 = −13.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Substitute x = −2 into both sides. Do they match?",
          "Check each line. In line 2, what must be done to both sides to remove the + 3?",
          "−9 − 3 = ?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m2-q15",
        question:
          "A water-park slide is for riders who are at least 120 cm tall and shorter than 190 cm. Which inequality describes the allowed heights, h cm?",
        options: ["{{120 <= h < 190}}", "{{120 < h <= 190}}", "{{120 <= h <= 190}}", "{{120 < h < 190}}"],
        answerIndex: 0,
        explanation:
          "'At least 120' includes 120 itself, so {{120 <= h}}. 'Shorter than 190' does not include 190, so {{h < 190}}. Together: {{120 <= h < 190}}. {{120 < h <= 190}} has the ends swapped: it would turn away a rider who is exactly 120 cm but let in one who is exactly 190 cm.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Deal with each end separately: is a rider of exactly 120 cm allowed? Exactly 190 cm?",
          "'At least' includes the number (≤ or ≥); 'shorter than' does not (< or >).",
          "Write the smaller number on the left, then h, then the larger number.",
        ],
        strategy: "Check each end separately",
      },
      {
        kind: "mcq",
        id: "equations-m2-q16",
        question: "Solve the simultaneous equations {{3x + y = 17}} and {{x + y = 9}}.",
        options: ["x = 5 and y = 4", "x = 8 and y = 1", "x = 4 and y = 5", "x = 13 and y = −4"],
        answerIndex: 2,
        explanation:
          "Both equations contain + y, so subtract the second from the first: 2x = 8, so x = 4. Then 4 + y = 9 gives y = 5. Check: 3 × 4 + 5 = 17 ✓. x = 8 and y = 1 forgets to halve 2x = 8. x = 5 and y = 4 swaps the values: 3 × 5 + 4 = 19, not 17. x = 13 comes from adding 17 and 9 instead of subtracting.",
        difficulty: "core",
        guideRef: "simultaneous-equations",
        hints: [
          "Both equations have exactly one y. What happens if you subtract one equation from the other?",
          "{{(3x + y) - (x + y) = 17 - 9}}, so {{2x = 8}}.",
          "Find x, then substitute into {{x + y = 9}}.",
        ],
        strategy: "Eliminate a variable",
      },
      {
        kind: "mcq",
        id: "equations-m2-q17",
        question:
          "Zara has $12 more than Siti. Zara then gives Siti $20. Now Siti has twice as much money as Zara. How much did Zara have at the start?",
        options: ["$36", "$56", "$28", "$48"],
        answerIndex: 3,
        explanation:
          "Let Siti start with $s, so Zara has s + 12. After the gift, Siti has s + 20 and Zara has s + 12 − 20 = s − 8. So s + 20 = 2(s − 8), which gives s + 20 = 2s − 16 and s = 36. Zara started with 36 + 12 = $48. Check: afterwards Siti has $56 and Zara $28, and 56 = 2 × 28 ✓. $36 is Siti's starting amount; $56 and $28 are the amounts *after* the gift.",
        difficulty: "challenge",
        guideRef: "forming-equations",
        hints: [
          "Let Siti's starting amount be s. Write Zara's starting amount.",
          "After the gift Siti has {{s + 20}} and Zara has {{s + 12 - 20}}.",
          "Siti's new amount = 2 × Zara's new amount. Then reread what the question asks for.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m2-q18",
        question: "Solve {{5 - 3x > 17}}.",
        options: ["{{x < -4}}", "{{x > -4}}", "{{x > 4}}", "{{x < -22/3}}"],
        answerIndex: 0,
        explanation:
          "Subtract 5: {{-3x > 12}}. Dividing by a *negative* number reverses the inequality: {{x < -4}}. Test x = −5: 5 + 15 = 20 > 17 ✓. {{x > -4}} forgets to flip, but then x = 0 would be a solution, and 5 − 0 = 5 is not more than 17. To avoid dividing by a negative, add 3x and subtract 17 instead: {{-12 > 3x}}, so x < −4. {{x > 4}} drops the minus sign on the 3x.",
        difficulty: "challenge",
        guideRef: "solving-inequalities",
        hints: [
          "Subtract 5 from both sides first.",
          "You now need to divide by −3. What happens to an inequality when you divide by a negative number?",
          "Test your answer with a number, e.g. x = −5 or x = 0.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m2-q19",
        question: "How many solutions does {{2(x + 3) = 2x + 5}} have?",
        options: [
          "Exactly one: {{x = 0}}",
          "Infinitely many: every x works",
          "None: it simplifies to 6 = 5",
          "Exactly one: {{x = -1/4}}",
        ],
        answerIndex: 2,
        explanation:
          "Expand: 2x + 6 = 2x + 5. Subtracting 2x leaves 6 = 5, which is false whatever x is, so there are no solutions. (2x + 6 is always exactly 1 more than 2x + 5.) The answer x = 0 is tempting because the x's vanish, but vanishing x's don't mean x = 0; they mean no value of x can fix the mismatch. {{x = -1/4}} comes from moving 2x across without changing its sign (4x + 6 = 5).",
        difficulty: "challenge",
        guideRef: "unknowns-both-sides",
        hints: [
          "Expand the bracket. What do you notice about the x-terms on each side?",
          "Subtract 2x from both sides. What is left?",
          "Is '6 = 5' ever true?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m2-q20",
        question: "Solve {{x/2 + x/3 = 10}}.",
        options: ["{{x = 50}}", "{{x = 12}}", "{{x = 25}}", "{{x = 2}}"],
        answerIndex: 1,
        explanation:
          "Multiply every term by 6: 3x + 2x = 60, so 5x = 60 and x = 12. Check: 6 + 4 = 10 ✓. x = 50 comes from adding the denominators ({{x/2 + x/3 = x/5}}): never add denominators! x = 25 comes from adding tops and bottoms ({{(2x)/5 = 10}}). x = 2 comes from multiplying the left side by 6 but forgetting the 10.",
        difficulty: "core",
        guideRef: "fractional-equations",
        hints: [
          "You can't add fractions with different denominators directly. What could you multiply every term by?",
          "6 is the LCM of 2 and 3. Multiply *every* term by 6, including the 10.",
          "{{3x + 2x = 60}}.",
        ],
        strategy: "Clear the fractions",
      },
    ],
  },

  // ======================================================================
  // MCQ PAPER 3
  // ======================================================================
  {
    id: "equations-m3",
    title: "MCQ Paper 3",
    questions: [
      {
        kind: "mcq",
        id: "equations-m3-q01",
        question: "The scales balance. Each box has the same mass, n kg. Find n.",
        diagram: `<svg viewBox="0 0 360 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Balanced scales: three boxes each of mass n kg and a 6 kg weight on the left balance a 30 kg weight on the right"><rect width="360" height="190" fill="#ffffff"/><rect x="140" y="170" width="80" height="8" fill="#334155"/><polygon points="180,122 160,170 200,170" fill="#e2e8f0" stroke="#334155" stroke-width="2"/><rect x="20" y="116" width="320" height="6" fill="#1f2937"/><g fill="#c7d2fe" stroke="#1f2937" stroke-width="1.5"><rect x="28" y="84" width="30" height="32"/><rect x="64" y="84" width="30" height="32"/><rect x="100" y="84" width="30" height="32"/></g><rect x="136" y="90" width="36" height="26" fill="#fde68a" stroke="#1f2937" stroke-width="1.5"/><rect x="236" y="78" width="72" height="38" fill="#fde68a" stroke="#1f2937" stroke-width="1.5"/><g font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="43" y="105">n</text><text x="79" y="105">n</text><text x="115" y="105">n</text><text x="154" y="107" font-size="11">6 kg</text><text x="272" y="102">30 kg</text></g></svg>`,
        options: ["{{n = 12}}", "{{n = 4}}", "{{n = 8}}", "{{n = 24}}"],
        answerIndex: 2,
        explanation:
          "The scales show 3n + 6 = 30. Take 6 kg off both pans: 3n = 24. Share both sides into 3 equal parts: n = 8. Check: 3 × 8 + 6 = 30 ✓. n = 4 comes from dividing 30 by 3 before removing the 6 kg. n = 12 adds the 6 kg instead of removing it. 24 stops at 3n.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["What could you take off *both* pans and keep them balanced?"],
        strategy: "Keep the balance",
      },
      {
        kind: "mcq",
        id: "equations-m3-q02",
        question: "Which of these is NOT a solution of {{x >= 2.5}}?",
        options: ["2", "2.5", "3", "100"],
        answerIndex: 0,
        explanation:
          "{{x >= 2.5}} means 2.5 or more. 2 is less than 2.5, so it is not a solution. 2.5 *is* a solution, because ≥ includes the boundary value itself.",
        difficulty: "warmup",
        guideRef: "inequalities",
        hints: ["Does '≥' include the number 2.5 itself? Which option is smaller than 2.5?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m3-q03",
        question: "Solve {{2(3x + 1) = 26}}.",
        options: ["{{x = 25/6}}", "{{x = 14/3}}", "{{x = 12}}", "{{x = 4}}"],
        answerIndex: 3,
        explanation:
          "Divide both sides by 2: 3x + 1 = 13. Then 3x = 12 and x = 4. Check: 2 × (12 + 1) = 26 ✓. {{25/6}} comes from expanding as 6x + 1, but the 2 must multiply the 1 too. {{14/3}} adds 1 instead of subtracting it. 12 is 3x, not x.",
        difficulty: "warmup",
        guideRef: "equations-with-brackets",
        hints: ["Dividing both sides by 2 first keeps the numbers small."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m3-q04",
        question: "Solve {{x/6 = -2}}.",
        options: ["{{x = -1/3}}", "{{x = -12}}", "{{x = 12}}", "{{x = -8}}"],
        answerIndex: 1,
        explanation:
          "Multiply both sides by 6: x = −12. Check: {{-12/6 = -2}} ✓. {{-1/3}} divides by 6 instead of multiplying. 12 drops the negative sign: a negative times a positive is negative. −8 treats '÷ 6' as '+ 6'.",
        difficulty: "warmup",
        guideRef: "fractional-equations",
        hints: ["What undoes 'divide by 6'?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m3-q05",
        question: "Solve {{20 = 4x + 8}}.",
        options: ["{{x = 7}}", "{{x = 12}}", "{{x = -3}}", "{{x = 3}}"],
        answerIndex: 3,
        explanation:
          "x can be on the right; the balance works both ways. Subtract 8 from both sides: 12 = 4x, so x = 3. Check: 4 × 3 + 8 = 20 ✓. x = 7 comes from adding 8 instead of subtracting it. −3 comes from thinking the sign changes when the equation is 'turned round', but 20 = 4x + 8 and 4x + 8 = 20 say exactly the same thing. 12 is 4x, not x.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["It doesn't matter which side x is on: undo the + 8 first."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m3-q06",
        question: "Solve {{12 - 2x = 3x + 2}}.",
        options: ["{{x = 10}}", "{{x = 2}}", "{{x = -2}}", "{{x = 14/5}}"],
        answerIndex: 1,
        explanation:
          "Add 2x to both sides so the x-term is positive: 12 = 5x + 2. Subtract 2: 10 = 5x, so x = 2. Check: 12 − 4 = 8 and 6 + 2 = 8 ✓. x = 10 comes from combining −2x and 3x into just x. {{14/5}} comes from adding 2 to 12 instead of subtracting it. −2 is a sign slip.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "There is −2x on the left. Adding 2x to both sides removes it.",
          "{{12 = 5x + 2}}.",
          "Subtract 2, then divide by 5.",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m3-q07",
        question: "x is an integer. Which inequality gives exactly the values 3, 4, 5 and 6?",
        options: ["{{2 < x <= 6}}", "{{3 < x <= 6}}", "{{3 <= x < 6}}", "{{2 <= x < 6}}"],
        answerIndex: 0,
        explanation:
          "In {{2 < x <= 6}}, 2 is excluded, so the first integer is 3, and 6 is included: 3, 4, 5, 6 ✓. {{3 < x <= 6}} misses 3, because < excludes its boundary. {{3 <= x < 6}} misses 6, and {{2 <= x < 6}} gives 2, 3, 4, 5.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Test each option: list the integers it allows.",
          "< or > excludes the end number; ≤ or ≥ includes it.",
          "Which option includes both 3 and 6, but nothing else?",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "equations-m3-q08",
        question:
          "This isosceles triangle has two sides of {{(3x - 1)}} cm and a base of {{(x + 4)}} cm. Its perimeter is 37 cm. How long is the base?",
        diagram: `<svg viewBox="0 0 320 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Isosceles triangle with two equal sloping sides of (3x − 1) cm and a base of (x + 4) cm"><rect width="320" height="200" fill="#ffffff"/><polygon points="115,170 205,170 160,37" fill="#bae6fd" stroke="#1f2937" stroke-width="2"/><g stroke="#1f2937" stroke-width="2"><line x1="131.8" y1="101.6" x2="143.2" y2="105.4"/><line x1="176.8" y1="105.4" x2="188.2" y2="101.6"/></g><g font-size="13" font-family="sans-serif" fill="#1f2937"><text x="128" y="96" text-anchor="end">(3x − 1) cm</text><text x="192" y="96" text-anchor="start">(3x − 1) cm</text><text x="160" y="190" text-anchor="middle">(x + 4) cm</text></g></svg>`,
        options: ["5 cm", "14 cm", "9 cm", "12.5 cm"],
        answerIndex: 2,
        explanation:
          "Perimeter: 2(3x − 1) + (x + 4) = 6x − 2 + x + 4 = 7x + 2. So 7x + 2 = 37, 7x = 35 and x = 5. The base is 5 + 4 = 9 cm. Check: 14 + 14 + 9 = 37 ✓. 5 cm is x, not the base. 14 cm is a sloping side. 12.5 cm comes from counting the sloping side only once (4x + 3 = 37).",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "An isosceles triangle has two equal sides. Include both in the perimeter.",
          "Perimeter = {{2(3x - 1) + (x + 4)}}.",
          "Solve {{7x + 2 = 37}}, then use x to find the base.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m3-q09",
        question: "Solve {{3(x - 2) < 12}}.",
        options: ["{{x < 14/3}}", "{{x < 6}}", "{{x > 6}}", "{{x < 2}}"],
        answerIndex: 1,
        explanation:
          "Divide both sides by 3: x − 2 < 4. Add 2: x < 6. Check x = 5: 3 × 3 = 9 < 12 ✓, while x = 6 gives exactly 12, which is not less than 12. {{x < 14/3}} comes from expanding as 3x − 2. {{x > 6}} flips the sign, but we only divided by a positive number. {{x < 2}} subtracts 2 instead of adding it.",
        difficulty: "core",
        guideRef: "solving-inequalities",
        hints: [
          "Treat it like an equation: divide by 3 first, or expand.",
          "{{x - 2 < 4}}.",
          "Undo the − 2. Did you multiply or divide by anything negative?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m3-q10",
        question: "Solve {{(x + 9)/4 = x - 3}}.",
        options: ["{{x = 7}}", "{{x = 4}}", "{{x = -1}}", "{{x = 21}}"],
        answerIndex: 0,
        explanation:
          "Multiply both sides by 4, and the *whole* right side gets multiplied: x + 9 = 4(x − 3) = 4x − 12. Subtract x and add 12: 21 = 3x, so x = 7. Check: {{16/4 = 4}} and 7 − 3 = 4 ✓. x = 4 comes from writing 4x − 3, multiplying only the x by 4. x = −1 is a sign slip with the 12. 21 stops at 3x.",
        difficulty: "core",
        guideRef: "fractional-equations",
        hints: [
          "Clear the fraction: multiply both sides by 4.",
          "The right side becomes {{4(x - 3)}}. Use a bracket!",
          "{{x + 9 = 4x - 12}}. Collect x on the right.",
        ],
        strategy: "Clear the fractions",
      },
      {
        kind: "mcq",
        id: "equations-m3-q11",
        question:
          "A taxi fare is a $3.90 flag-down charge plus $0.62 per km. Priya's fare is $22.50. Without a calculator, which is the best estimate of how far she travelled?",
        options: ["about 3 km", "about 12 km", "about 36 km", "about 30 km"],
        answerIndex: 3,
        explanation:
          "The equation is 3.90 + 0.62d = 22.50. Round: 4 + 0.6d ≈ 22.5, so 0.6d ≈ 18.5, which is roughly 18, and d ≈ 18 ÷ 0.6 = 30. (Exactly: 18.60 ÷ 0.62 = 30 km.) About 36 km comes from forgetting the flag-down charge (22.50 ÷ 0.62 ≈ 36). About 12 km comes from multiplying by 0.62 instead of dividing. About 3 km is a place-value slip.",
        difficulty: "core",
        guideRef: "solving-equations",
        hints: [
          "Write an equation for the fare, then round the numbers to make it easy.",
          "Take off the flag-down charge: about $18.50 pays for the distance.",
          "How many lots of about 60 cents make about $18?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "equations-m3-q12",
        question: "Hana solves {{5(x + 3) = 40}} by dividing both sides by 5 first. Which line should she write next?",
        options: ["{{x + 3 = 35}}", "{{x + 15 = 8}}", "{{x + 3 = 8}}", "{{5x + 3 = 8}}"],
        answerIndex: 2,
        explanation:
          "Dividing the whole left side by 5 just removes the 5 in front of the bracket: x + 3 = 8, so x = 5. Expanding gives the same answer (5x + 15 = 40, 5x = 25, x = 5), but dividing first is quicker here because 40 is a multiple of 5. {{x + 15 = 8}} mixes the two methods: it expands to 5x + 15 = 40, then divides the 5x and the 40 by 5 but not the 15. {{5x + 3 = 8}} divides the right side by 5 but not the left. {{x + 3 = 35}} subtracts 5 instead of dividing.",
        difficulty: "core",
        guideRef: "equations-with-brackets",
        hints: [
          "5(x + 3) means 5 lots of (x + 3). What is one lot?",
          "Divide *both* sides by 5.",
          "40 ÷ 5 = 8.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m3-q13",
        question: "The angles of a quadrilateral are x°, 2x°, 3x° and 90°. Find x.",
        options: ["{{x = 45}}", "{{x = 15}}", "{{x = 60}}", "{{x = 270}}"],
        answerIndex: 0,
        explanation:
          "Angles in a quadrilateral add up to 360°: x + 2x + 3x + 90 = 360, so 6x = 270 and x = 45. The angles are 45°, 90°, 135° and 90°, which total 360° ✓. x = 15 uses 180°, the angle sum of a triangle. x = 60 forgets the 90° angle. 270 is 6x, not x.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "What do the angles in a quadrilateral add up to?",
          "{{x + 2x + 3x + 90 = 360}}.",
          "Collect the x-terms: {{6x + 90 = 360}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m3-q14",
        question: "Marcus wants to solve {{4x + 7 = 9x - 8}} and keep the x-term positive. What is the best first step?",
        options: [
          "Subtract 9x from both sides",
          "Add 8 to the left side only",
          "Divide both sides by 4",
          "Subtract 4x from both sides",
        ],
        answerIndex: 3,
        explanation:
          "Subtract the *smaller* x-term, 4x, from both sides: 7 = 5x − 8. Then 15 = 5x and x = 3. Check: 4 × 3 + 7 = 19 and 9 × 3 − 8 = 19 ✓. Subtracting 9x also works, but it gives −5x = −15, so you must divide by a negative. 'Add 8 to the left side only' breaks the balance: whatever you do, do it to both sides.",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Which side has more x's?",
          "Taking away the smaller x-term leaves a positive number of x's.",
          "After subtracting 4x: {{7 = 5x - 8}}.",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m3-q15",
        question: "Which statement is always true?",
        options: [
          "If {{x > 3}}, then {{x > 5}}",
          "If {{x < 3}}, then {{x < -3}}",
          "If {{x > 5}}, then {{x > 3}}",
          "If {{x >= 3}}, then {{x > 3}}",
        ],
        answerIndex: 2,
        explanation:
          "Every number bigger than 5 is also bigger than 3, so 'if x > 5 then x > 3' is always true. 'If x > 3 then x > 5' is the tempting one, but x = 4 breaks it. 'If x < 3 then x < −3' fails for x = 0. 'If x ≥ 3 then x > 3' fails for x = 3 itself.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "For each statement, look for a counterexample: one number that breaks it.",
          "Picture a number line. If you are to the right of 5, where are you compared with 3?",
          "Try x = 4 in the first statement.",
        ],
        strategy: "Find a counterexample",
      },
      {
        kind: "mcq",
        id: "equations-m3-q16",
        question:
          "The table shows two orders at a school bookshop.\n\n| Order | Pens | Notebooks | Total cost |\n|---|---|---|---|\n| First | 2 | 1 | $7 |\n| Second | 2 | 3 | $13 |\n\nAll pens cost the same, and all notebooks cost the same. How much is one notebook?",
        options: ["$2", "$3", "$6", "$5"],
        answerIndex: 1,
        explanation:
          "The second order is the first order plus 2 more notebooks, and it costs $6 more. So 2 notebooks cost $6 and one notebook costs $3. (Then 2 pens + $3 = $7, so a pen costs $2.) $6 is the cost of *two* notebooks. $2 is the price of a pen. $5 is the cost of a pen and a notebook together.",
        difficulty: "core",
        guideRef: "simultaneous-equations",
        hints: [
          "Compare the two orders. What is different, and how much more does it cost?",
          "The extra 2 notebooks account for the extra $6.",
          "In symbols: {{(2p + 3n) - (2p + n) = 13 - 7}}.",
        ],
        strategy: "Eliminate a variable",
      },
      {
        kind: "mcq",
        id: "equations-m3-q17",
        question:
          "Mrs Tan shares a bag of sweets among her class. If every pupil gets 5 sweets, there are 12 left over. If every pupil gets 6 sweets, she is 15 sweets short. How many pupils are in the class?",
        options: ["27", "3", "147", "162"],
        answerIndex: 0,
        explanation:
          "Let there be p pupils. The number of sweets is the same both ways: 5p + 12 = 6p − 15. Subtract 5p and add 15: p = 27. Check: 5 × 27 + 12 = 147 and 6 × 27 − 15 = 147 ✓. The neat insight: giving everyone one more sweet uses up the 12 spare *and* 15 more, so there are 12 + 15 = 27 pupils. 3 comes from 15 − 12, treating 'short' as if it meant more sweets left over. 147 is the number of sweets, and 162 is the number needed for 6 each.",
        difficulty: "challenge",
        guideRef: "forming-equations",
        hints: [
          "Let p be the number of pupils. Write the number of sweets in two different ways.",
          "'15 short' means the bag has 15 fewer than 6p.",
          "{{5p + 12 = 6p - 15}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m3-q18",
        question: "x is an integer with {{3x + 2 > 11}} and {{2x - 1 <= 13}}. How many possible values of x are there?",
        options: ["5", "4", "3", "7"],
        answerIndex: 1,
        explanation:
          "Solve each one: 3x > 9 gives x > 3, and 2x ≤ 14 gives x ≤ 7. So {{3 < x <= 7}}, and the integers are 4, 5, 6, 7: four values. 5 wrongly includes 3, but x > 3 is strict. 3 leaves out 7, but x ≤ 7 includes it. 7 is just the upper limit, not a count.",
        difficulty: "challenge",
        guideRef: "solving-inequalities",
        hints: [
          "Solve each inequality separately.",
          "You should get x > 3 and x ≤ 7. Write these as one two-sided inequality.",
          "List the integers, checking each end carefully.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m3-q19",
        question:
          "Priya solves {{3(x - 4) - 2(x - 5) = 7}} like this:\n\n    3x − 12 − 2x − 10 = 7\n    x − 22 = 7\n    x = 29\n\nWhat is the correct solution?",
        options: ["{{x = 29}}", "{{x = 5}}", "{{x = 14}}", "{{x = 9}}"],
        answerIndex: 3,
        explanation:
          "Her first line has a sign error: −2 × −5 = +10, not −10. Correct: 3x − 12 − 2x + 10 = 7, so x − 2 = 7 and x = 9. Check: 3 × 5 − 2 × 4 = 15 − 8 = 7 ✓. 29 is Priya's answer, and it fails the check (75 − 48 = 27). x = 5 comes from subtracting the 2 instead of adding it. x = 14 comes from expanding −2(x − 5) as −2x + 5.",
        difficulty: "challenge",
        guideRef: "equations-with-brackets",
        hints: [
          "Substitute x = 29 into the left side. Does it give 7?",
          "Look closely at −2(x − 5). What is −2 × −5?",
          "Correct line 1: {{3x - 12 - 2x + 10 = 7}}.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m3-q20",
        question: "Solve {{(2x + 1)/3 - (x - 2)/4 = 5/2}}.",
        options: ["{{x = 6.4}}", "{{x = -1.5}}", "{{x = 4}}", "{{x = 8}}"],
        answerIndex: 2,
        explanation:
          "Multiply every term by 12 (the LCM of 3, 4 and 2): 4(2x + 1) − 3(x − 2) = 30. Expand carefully: 8x + 4 − 3x + 6 = 30, so 5x + 10 = 30, 5x = 20 and x = 4. Check: {{9/3 - 2/4 = 3 - 1/2 = 5/2}} ✓. x = 6.4 comes from −3 × −2 = −6, a sign slip. x = −1.5 comes from multiplying the left side by 12 but leaving the right side as {{5/2}}. x = 8 adds the 10 instead of subtracting it.",
        difficulty: "challenge",
        guideRef: "fractional-equations",
        hints: [
          "Find one number that clears all three denominators.",
          "Multiply every term by 12: {{4(2x + 1) - 3(x - 2) = 30}}.",
          "Careful: −3 × −2 = +6.",
        ],
        strategy: "Clear the fractions",
      },
    ],
  },

  // ======================================================================
  // MCQ PAPER 4
  // ======================================================================
  {
    id: "equations-m4",
    title: "MCQ Paper 4",
    questions: [
      {
        kind: "mcq",
        id: "equations-m4-q01",
        question: "Solve {{-3x = 21}}.",
        options: ["{{x = 7}}", "{{x = -1/7}}", "{{x = -63}}", "{{x = -7}}"],
        answerIndex: 3,
        explanation:
          "Divide both sides by −3: x = 21 ÷ (−3) = −7. Check: −3 × (−7) = 21 ✓. x = 7 forgets that a positive divided by a negative is negative. −63 multiplies by −3 instead of dividing. {{-1/7}} divides the wrong way round (−3 ÷ 21).",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["What is x being multiplied by? Undo it, sign included."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m4-q02",
        question: "How should {{x < 6}} be drawn on a number line?",
        options: [
          "Filled circle at 6, arrow pointing left",
          "Open circle at 6, arrow pointing left",
          "Open circle at 6, arrow pointing right",
          "Filled circle at 6, arrow pointing right",
        ],
        answerIndex: 1,
        explanation:
          "6 itself is not included (x is *less than* 6, not equal to it), so the circle is open. The solutions are all smaller than 6, so the arrow points left. A filled circle would mean {{x <= 6}}, and pointing right would mean x > 6.",
        difficulty: "warmup",
        guideRef: "inequalities",
        hints: ["Is 6 itself a solution? Are the solutions bigger or smaller than 6?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m4-q03",
        question: "Jun says {{x = 4}} is the solution of {{7x - 9 = 3x + 7}}. Is he right?",
        options: [
          "No: 7x − 9 is 74 − 9 = 65 when x = 4",
          "No: the right side is 3 + 4 + 7 = 14",
          "Yes: both sides equal 19",
          "Yes, because 7 − 3 = 4",
        ],
        answerIndex: 2,
        explanation:
          "Substitute x = 4: the left side is 7 × 4 − 9 = 19 and the right side is 3 × 4 + 7 = 19. Both sides match, so x = 4 is correct ✓. '74 − 9' treats 7x as the digits 7 and 4 side by side, but 7x means 7 × x. '3 + 4 + 7' reads 3x as 3 + x. '7 − 3 = 4' gives the right number by coincidence, not by a valid method.",
        difficulty: "warmup",
        guideRef: "solving-equations",
        hints: ["Replace x with 4 on *both* sides. Remember that 7x means 7 × x."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "equations-m4-q04",
        question: "Solve {{6(x - 1) = 30}}.",
        options: ["{{x = 6}}", "{{x = 4}}", "{{x = 31/6}}", "{{x = 5}}"],
        answerIndex: 0,
        explanation:
          "Divide both sides by 6: x − 1 = 5, so x = 6. Check: 6 × 5 = 30 ✓. {{31/6}} comes from expanding as 6x − 1 instead of 6x − 6. x = 4 subtracts 1 instead of adding it. x = 5 stops at x − 1 = 5.",
        difficulty: "warmup",
        guideRef: "equations-with-brackets",
        hints: ["Divide both sides by 6 first: 30 is a multiple of 6."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "equations-m4-q05",
        question: "Solve {{(x - 3)/4 = 2}}.",
        options: ["{{x = 5}}", "{{x = 20}}", "{{x = 11}}", "{{x = 3.5}}"],
        answerIndex: 2,
        explanation:
          "Multiply both sides by 4: x − 3 = 8. Add 3: x = 11. Check: (11 − 3) ÷ 4 = 2 ✓. 20 treats it as {{x/4 - 3 = 2}}, but the 3 is inside the fraction, so it was subtracted *before* dividing. x = 5 subtracts 3 instead of adding it. 3.5 divides 2 by 4 instead of multiplying.",
        difficulty: "warmup",
        guideRef: "fractional-equations",
        hints: ["The whole of x − 3 is divided by 4. What undoes that?"],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "equations-m4-q06",
        question: "Solve {{2x - 5 = 6x + 7}}.",
        options: ["{{x = 3}}", "{{x = 1/2}}", "{{x = 3/2}}", "{{x = -3}}"],
        answerIndex: 3,
        explanation:
          "Subtract 2x (the smaller x-term) from both sides: −5 = 4x + 7. Subtract 7: −12 = 4x, so x = −3. Check: 2 × (−3) − 5 = −11 and 6 × (−3) + 7 = −11 ✓. x = 3 drops the negative sign. {{1/2}} comes from 7 − 5 instead of −5 − 7. {{3/2}} comes from moving 6x across without changing its sign (8x = 12).",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Which side has more x's? Collect the x-terms there.",
          "Subtract 2x: {{-5 = 4x + 7}}.",
          "−5 − 7 = −12. Will the answer be positive or negative?",
        ],
        strategy: "Collect like terms",
      },
      {
        kind: "mcq",
        id: "equations-m4-q07",
        question:
          "A CCA trip costs $45 per student plus $120 to hire a coach. The budget is at most $800. What is the greatest number of students who can go?",
        options: ["15", "16", "17", "18"],
        answerIndex: 0,
        explanation:
          "Let n be the number of students: 45n + 120 ≤ 800, so 45n ≤ 680 and n ≤ 15.1… The number of students must be a whole number, so the greatest is 15. Check: 45 × 15 + 120 = $795 ✓, but 16 students would cost $840, which is over budget. 16 comes from rounding 15.1 up. 17 ignores the coach: 800 ÷ 45 ≈ 17.8, and 18 rounds that up.",
        difficulty: "core",
        guideRef: "solving-inequalities",
        hints: [
          "Write an inequality for the total cost of n students.",
          "{{45n + 120 <= 800}}.",
          "n must be a whole number. Should you round up or down?",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q08",
        question: "A rectangle's length is 4 cm more than its width, w cm. Its perimeter is 44 cm. Which equation is correct?",
        options: ["{{w + w + 4 = 44}}", "{{2w + 2(w + 4) = 44}}", "{{w(w + 4) = 44}}", "{{4w + 4 = 44}}"],
        answerIndex: 1,
        explanation:
          "The length is w + 4. Perimeter = 2 widths + 2 lengths = 2w + 2(w + 4). Solving: 4w + 8 = 44, so w = 9, giving a 9 cm by 13 cm rectangle (9 + 13 + 9 + 13 = 44 ✓). {{w(w + 4) = 44}} is the *area*, not the perimeter. {{4w + 4 = 44}} adds the extra 4 cm only once, but there are two lengths. {{w + w + 4 = 44}} is only half the perimeter.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "Sketch the rectangle and label all four sides.",
          "Each length is {{w + 4}}. How many lengths and widths are there?",
          "Perimeter means adding *all four* sides.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "equations-m4-q09",
        question: "What is the sum of all the integers x with {{-4 < x <= 3}}?",
        options: ["−4", "−3", "6", "0"],
        answerIndex: 3,
        explanation:
          "The integers are −3, −2, −1, 0, 1, 2, 3: −4 is excluded by <, and 3 is included by ≤. They pair off: −3 + 3 = 0, −2 + 2 = 0 and −1 + 1 = 0, so the sum is 0. −4 comes from wrongly including −4. −3 comes from leaving out 3. 6 adds only the positive integers.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "List the integers first, checking each end.",
          "−4 is not included; 3 is.",
          "Look for pairs that add to zero.",
        ],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "equations-m4-q10",
        question:
          "Wei Ling buys 4 packets of durian puffs in a sale. Each packet is $1.50 off its usual price, p dollars. She pays $18 altogether. What is the usual price of one packet?",
        options: ["$3.00", "$4.50", "$6.00", "$4.88"],
        answerIndex: 2,
        explanation:
          "Each packet costs p − 1.50 in the sale, so 4(p − 1.50) = 18. Divide by 4: p − 1.50 = 4.50, so p = 6.00. Check: 4 × $4.50 = $18 ✓. $4.50 is the *sale* price, one step short. $3.00 subtracts the discount again instead of adding it back. $4.88 comes from 4p − 1.50 = 18, taking the $1.50 off only once instead of off each packet.",
        difficulty: "core",
        guideRef: "equations-with-brackets",
        hints: [
          "Write the sale price of one packet in terms of p.",
          "Four packets: {{4(p - 1.50) = 18}}.",
          "Divide both sides by 4 first.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q11",
        question: "Solve {{0.5x + 3 = 1}}.",
        options: ["{{x = -1}}", "{{x = -4}}", "{{x = 8}}", "{{x = 4}}"],
        answerIndex: 1,
        explanation:
          "Subtract 3: 0.5x = −2. Dividing by 0.5 is the same as doubling, so x = −4. Check: 0.5 × (−4) + 3 = −2 + 3 = 1 ✓. −1 multiplies by 0.5 instead of dividing. 8 comes from adding 3 instead of subtracting it (0.5x = 4). 4 loses the negative sign.",
        difficulty: "core",
        guideRef: "solving-equations",
        hints: [
          "Undo the + 3 first.",
          "0.5x means half of x. If half of x is −2, what is x?",
          "Dividing by 0.5 doubles a number.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m4-q12",
        question: "Solve {{5 - x/3 = 1}}.",
        options: ["{{x = 12}}", "{{x = -12}}", "{{x = 18}}", "{{x = 4/3}}"],
        answerIndex: 0,
        explanation:
          "Add {{x/3}} to both sides and subtract 1: {{4 = x/3}}, so x = 12. Check: 5 − 4 = 1 ✓. −12 comes from losing track of the minus sign in front of {{x/3}}. 18 comes from adding 1 to 5 instead of subtracting ({{x/3 = 6}}). {{4/3}} divides by 3 instead of multiplying.",
        difficulty: "core",
        guideRef: "fractional-equations",
        hints: [
          "The {{x/3}} is being *subtracted*. Try adding {{x/3}} to both sides.",
          "{{5 = 1 + x/3}}, so {{x/3 = 4}}.",
          "Now multiply both sides by 3.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "equations-m4-q13",
        question: "In an isosceles triangle, each base angle is 15° more than twice the top angle, t°. What size is each base angle?",
        options: ["30°", "75°", "125°", "81°"],
        answerIndex: 1,
        explanation:
          "Each base angle is (2t + 15)°, and there are two of them: t + 2(2t + 15) = 180, so 5t + 30 = 180, t = 30 and each base angle is 2 × 30 + 15 = 75°. Check: 30 + 75 + 75 = 180 ✓. 125° comes from counting only one base angle (t + 2t + 15 = 180). 81° comes from doubling the 2t but not the 15. 30° is t, the top angle.",
        difficulty: "core",
        guideRef: "forming-equations",
        hints: [
          "How many base angles does an isosceles triangle have?",
          "Angle sum: {{t + 2(2t + 15) = 180}}.",
          "Find t, then work out {{2t + 15}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q14",
        question:
          "Two bike-hire shops at East Coast Park charge:\n\n| Shop | Fixed charge | Per hour |\n|---|---|---|\n| Pedal Pals | $10 | $6 |\n| Easy Rider | $4 | $8 |\n\nAfter how many hours do the two shops cost the same?",
        options: ["7", "{{3/7}}", "3", "28"],
        answerIndex: 2,
        explanation:
          "Pedal Pals costs 10 + 6h and Easy Rider costs 4 + 8h. Set them equal: 10 + 6h = 4 + 8h. Subtract 6h and 4: 6 = 2h, so h = 3. Check: 10 + 18 = $28 and 4 + 24 = $28 ✓. 28 is the *cost* at that point, not the number of hours. 7 comes from adding the fixed charges (14 ÷ 2). {{3/7}} comes from adding the hourly rates (6 = 14h).",
        difficulty: "core",
        guideRef: "unknowns-both-sides",
        hints: [
          "Write an expression for each shop's cost after h hours.",
          "Set them equal: {{10 + 6h = 4 + 8h}}.",
          "Collect the h-terms on the side with more h's.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q15",
        question: "Zara draws {{x > -2}} like this. What is wrong with her diagram?",
        diagram: `<svg viewBox="0 0 360 70" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Number line from −4 to 5 with a filled circle at −2 and an arrow shaded to the right"><rect width="360" height="70" fill="#ffffff"/><line x1="10" y1="35" x2="350" y2="35" stroke="#334155" stroke-width="1.5"/><g stroke="#334155" stroke-width="1.5"><line x1="25" y1="29" x2="25" y2="41"/><line x1="60" y1="29" x2="60" y2="41"/><line x1="95" y1="29" x2="95" y2="41"/><line x1="130" y1="29" x2="130" y2="41"/><line x1="165" y1="29" x2="165" y2="41"/><line x1="200" y1="29" x2="200" y2="41"/><line x1="235" y1="29" x2="235" y2="41"/><line x1="270" y1="29" x2="270" y2="41"/><line x1="305" y1="29" x2="305" y2="41"/><line x1="340" y1="29" x2="340" y2="41"/></g><g font-size="12" font-family="sans-serif" text-anchor="middle" fill="#1f2937"><text x="25" y="58">−4</text><text x="60" y="58">−3</text><text x="95" y="58">−2</text><text x="130" y="58">−1</text><text x="165" y="58">0</text><text x="200" y="58">1</text><text x="235" y="58">2</text><text x="270" y="58">3</text><text x="305" y="58">4</text><text x="340" y="58">5</text></g><line x1="95" y1="35" x2="340" y2="35" stroke="#4f46e5" stroke-width="5"/><polygon points="354,35 340,28 340,42" fill="#4f46e5"/><circle cx="95" cy="35" r="6" fill="#1f2937"/></svg>`,
        options: [
          "The arrow should point left",
          "The circle should be at 2, not −2",
          "Nothing: it is correct",
          "The circle should be open, because −2 is not included",
        ],
        answerIndex: 3,
        explanation:
          "x > −2 means *greater than* −2, so −2 itself is not a solution and the circle must be open. Her filled circle shows x ≥ −2. The arrow is fine: numbers greater than −2 lie to its right. 'Nothing is wrong' misses that a filled circle includes the end number.",
        difficulty: "core",
        guideRef: "inequalities",
        hints: [
          "Is −2 itself a solution of {{x > -2}}?",
          "What does a filled circle mean? What does an open one mean?",
        ],
        strategy: "Check each end separately",
      },
      {
        kind: "mcq",
        id: "equations-m4-q16",
        question: "{{2x + 3y = 13}} and {{2x + y = 7}}. What is the value of y?",
        options: ["{{y = 3}}", "{{y = 6}}", "{{y = 5}}", "{{y = 2}}"],
        answerIndex: 0,
        explanation:
          "Both equations contain 2x, so subtract: (2x + 3y) − (2x + y) = 13 − 7 gives 2y = 6, so y = 3. Then 2x + 3 = 7 gives x = 2. Check: 2 × 2 + 3 × 3 = 13 ✓. y = 6 forgets to halve 2y. y = 2 is the value of x, not y. 5 is x + y, which comes from adding the equations (4x + 4y = 20).",
        difficulty: "core",
        guideRef: "simultaneous-equations",
        hints: [
          "Which letter has the same coefficient in both equations?",
          "Subtract the second equation from the first to eliminate x.",
          "{{2y = 6}}.",
        ],
        strategy: "Eliminate a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q17",
        question:
          "A bag has 3 times as many red counters as blue counters. Ten red counters are taken out and 10 blue counters are put in. Now there are equal numbers of red and blue. How many counters are in the bag now?",
        options: ["10", "30", "40", "20"],
        answerIndex: 2,
        explanation:
          "Let there be b blue counters at the start, so 3b red. After the swap: red 3b − 10, blue b + 10. These are equal, so 3b − 10 = b + 10, 2b = 20 and b = 10. At the start there were 30 red and 10 blue; now there are 20 red and 20 blue, which is 40 counters. (The total never changed: 10 went out and 10 came in.) 20 is the number of each colour now, not the total. 10 and 30 are the starting numbers of blue and red.",
        difficulty: "challenge",
        guideRef: "forming-equations",
        hints: [
          "Let b be the starting number of blue counters. How many red are there?",
          "After the change: red {{3b - 10}}, blue {{b + 10}}.",
          "Set them equal and solve. Then reread what the question asks for.",
        ],
        strategy: "Look for an invariant",
      },
      {
        kind: "mcq",
        id: "equations-m4-q18",
        question:
          "Mei has $35 and saves $14 a week. Arjun has $5 and saves $17 a week. After how many whole weeks will Arjun first have *more* money than Mei?",
        options: ["10", "30", "14", "11"],
        answerIndex: 3,
        explanation:
          "After w weeks Mei has 35 + 14w and Arjun has 5 + 17w. We need 5 + 17w > 35 + 14w, so 3w > 30 and w > 10. After exactly 10 weeks they both have $175, which is equal, not more, so the first whole week is 11 (Arjun $192, Mei $189 ✓). 10 is when they are level. 30 forgets to divide 3w > 30 by 3. 14 comes from adding the starting amounts instead of finding the gap between them.",
        difficulty: "challenge",
        guideRef: "solving-inequalities",
        hints: [
          "Write expressions for each person's money after w weeks.",
          "{{5 + 17w > 35 + 14w}}.",
          "Solving gives w > 10. Is w = 10 itself enough?",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "equations-m4-q19",
        question:
          "Ethan looks at {{5x - 3 = 2x - 3}} and says: 'Both sides have − 3, so 5x = 2x. That's impossible, so there is no solution.' Which is correct?",
        options: [
          "He is wrong: {{x = 0}} is a solution",
          "He is right: there is no solution",
          "He is wrong: every value of x works",
          "He is wrong: {{x = 1}}, because 5 − 3 = 2",
        ],
        answerIndex: 0,
        explanation:
          "5x = 2x is not impossible: subtract 2x to get 3x = 0, so x = 0. Check: 5 × 0 − 3 = −3 and 2 × 0 − 3 = −3 ✓. 'No solution' is the trap: 5 lots of a number can equal 2 lots of it when the number is 0. 'Every value works' fails for x = 1, which gives 2 on the left but −1 on the right.",
        difficulty: "challenge",
        guideRef: "unknowns-both-sides",
        hints: [
          "Is there any number for which 5 times it equals 2 times it?",
          "Subtract 2x from both sides of 5x = 2x.",
          "3x = 0. What must x be?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "equations-m4-q20",
        question: "Siti spends {{1/3}} of her money on books and {{1/4}} of it on lunch. She has $25 left. How much did she start with?",
        options: ["$35", "$60", "$42.86", "$100"],
        answerIndex: 1,
        explanation:
          "Let her money be $m: {{m - m/3 - m/4 = 25}}. Multiply every term by 12: 12m − 4m − 3m = 300, so 5m = 300 and m = 60. Check: $20 on books and $15 on lunch leaves $25 ✓. $35 comes from adding {{1/3 + 1/4}} as {{2/7}} (adding tops and bottoms). $42.86 treats the $25 as the part she *spent* ({{7/12}}) instead of the part left ({{5/12}}). $100 treats $25 as a quarter of her money.",
        difficulty: "challenge",
        guideRef: "fractional-equations",
        hints: [
          "Let m be her starting money. Write what is left as an expression.",
          "{{m - m/3 - m/4 = 25}}. Clear the fractions by multiplying every term by 12.",
          "Or think of a bar: she spent {{1/3 + 1/4 = 7/12}}, so {{5/12}} of her money is $25.",
        ],
        strategy: "Use a bar model",
      },
    ],
  },
];
