// Percentages — Practice Papers 3 and 4.
// Paper 3: problem solving in context and multi-step questions.
// Paper 4: exam style — linked parts, tables/diagrams and reasoning.
import type { Paper } from "../../types.ts";

export const morePapers: Paper[] = [
  // =========================================================================
  // PRACTICE PAPER 3 — problem solving in context
  // =========================================================================
  {
    id: "percentages-p3",
    title: "Practice Paper 3",
    questions: [
      {
        kind: "short",
        id: "percentages-p3-q01",
        question:
          "Four friends check how full their phone storage is.\n\n| Friend | Storage used |\n|---|---|\n| Mei | {{3/5}} |\n| Jun | 0.65 |\n| Zara | 62% |\n| Ravi | {{5/8}} |\n\nHow full is the fullest phone? Give your answer as a percentage.",
        answer: { type: "number", value: 65, display: "65% (Jun's phone)" },
        traps: [
          { spec: { type: "number", value: 62.5 }, feedback: "{{5/8}} = 62.5% — but check Jun: 0.65 = 65%, which is bigger." },
          { spec: { type: "number", value: 0.65 }, feedback: "That's Jun's amount as a decimal. Multiply by 100 to write it as a percentage." },
        ],
        solution: [
          "Put everything into percentages so the amounts can be compared.",
          "Mei: {{3/5 = 60/100}} = 60%.",
          "Jun: 0.65 = 65%.",
          "Zara: 62%.",
          "Ravi: {{5/8}} = 5 ÷ 8 = 0.625 = 62.5%.",
          "The largest is 65%, so Jun's phone is the fullest.",
        ],
        commonError: "Thinking 0.65 must be small because it is a decimal — every amount in the table is less than one whole.",
        difficulty: "warmup",
        guideRef: "fdp-conversions",
        hints: ["Put all four amounts into the same form — percentages are easiest to compare.", "{{3/5 = 60/100}}. For {{5/8}}, work out 5 ÷ 8."],
        strategy: "Convert to the same form",
      },
      {
        kind: "short",
        id: "percentages-p3-q02",
        question:
          "A CCA trip to Sentosa costs $36 per student. The school pays 25% of the cost and each family pays the rest. How much does each family pay? Give your answer in dollars.",
        answer: { type: "number", value: 27, display: "$27" },
        traps: [{ spec: { type: "number", value: 9 }, feedback: "$9 is the school's 25% share. The family pays the other 75%." }],
        solution: [
          "The family pays 100% − 25% = 75% of the cost.",
          "25% is a quarter: 36 ÷ 4 = $9.",
          "75% = 3 × $9 = $27 (or $36 − $9 = $27).",
        ],
        difficulty: "warmup",
        guideRef: "percentage-of-amount",
        hints: ["What percentage is left for the family to pay?", "25% is one quarter. Find a quarter of $36 first."],
        strategy: "Find the remaining percentage",
      },
      {
        kind: "short",
        id: "percentages-p3-q03",
        question:
          "Siti gets $80 pocket money a month. She spends $12 of it on MRT fares. What percentage of her pocket money goes on MRT fares?",
        answer: { type: "number", value: 15, display: "15%" },
        traps: [
          { spec: { type: "number", value: 6.67, tolerance: 0.05 }, feedback: "You worked out 80 ÷ 12. The part ($12) goes on top: {{12/80}}." },
          { spec: { type: "number", value: 0.15 }, feedback: "0.15 is the decimal — multiply by 100 to get the percentage." },
        ],
        solution: ["Write the part over the whole: {{12/80}}.", "{{12/80 = 3/20 = 15/100}}.", "So 15% of her pocket money goes on MRT fares."],
        difficulty: "warmup",
        guideRef: "one-as-percentage-of-another",
        hints: ["Write the part over the whole as a fraction.", "Make the denominator 100: {{12/80 = 3/20}} = {{?/100}}."],
        strategy: "Part over whole",
      },
      {
        kind: "short",
        id: "percentages-p3-q04",
        question:
          "A durian stall raises all its prices by 12%. A box of durians used to cost $25. Use a single multiplier to find the new price, in dollars.",
        answer: { type: "number", value: 28, display: "$28" },
        traps: [
          { spec: { type: "number", value: 3 }, feedback: "$3 is the increase. Add it on — or use the multiplier 1.12 to get the new price in one step." },
          { spec: { type: "number", value: 30 }, feedback: "× 1.2 is a 20% increase. 12% as a decimal is 0.12, so the multiplier is 1.12." },
        ],
        solution: ["After a 12% rise, the new price is 100% + 12% = 112% of the old price.", "Multiplier = 1.12.", "25 × 1.12 = $28."],
        difficulty: "warmup",
        guideRef: "multipliers",
        hints: ["The new price is what percentage of the old price?", "112% written as a decimal is the multiplier."],
        strategy: "Use a multiplier",
      },
      {
        kind: "short",
        id: "percentages-p3-q05",
        question: "A bicycle is priced at $340 before GST. GST of 9% is added. How much GST is added? Give your answer in dollars.",
        answer: { type: "number", value: 30.6, display: "$30.60" },
        traps: [{ spec: { type: "number", value: 370.6 }, feedback: "That's the full price including GST. The question asks only for the GST that is added." }],
        solution: ["9% = 0.09.", "0.09 × 340 = 30.6.", "GST added = $30.60."],
        solutions: [{ label: "Mental: 10% − 1%", steps: ["10% of $340 = $34.", "1% of $340 = $3.40.", "9% = $34 − $3.40 = $30.60."] }],
        difficulty: "warmup",
        guideRef: "money-percentages",
        hints: ["You need 9% of $340.", "9% = 10% − 1%."],
        strategy: "Build up from 10%",
      },
      {
        kind: "short",
        id: "percentages-p3-q06",
        question:
          "In November, 260 mm of rain fell at Changi. In December, at the height of the monsoon, 338 mm fell. Find the percentage increase in rainfall from November to December.",
        answer: { type: "number", value: 30, display: "30%" },
        traps: [
          { spec: { type: "number", value: 23.08, tolerance: 0.05 }, feedback: "You divided by December's 338 mm. Percentage change always compares with the *original* amount — November's." },
          { spec: { type: "number", value: 78 }, feedback: "78 mm is the actual increase. Now write it as a percentage of the November amount." },
        ],
        solution: ["Increase = 338 − 260 = 78 mm.", "Percentage increase = {{78/260}} × 100.", "{{78/260}} = 0.3, so the increase is 30%."],
        commonError: "Dividing the change by the new value instead of the original value.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["What is the actual increase in millimetres?", "Which month is the 'original'? Put the increase over that amount.", "Work out {{78/260}} × 100."],
        strategy: "Change ÷ original",
      },
      {
        kind: "short",
        id: "percentages-p3-q07",
        question: "In a sale, a rice cooker has 15% off. Hana pays $85 for it. What was the price before the sale, in dollars?",
        answer: { type: "number", value: 100, display: "$100" },
        traps: [
          { spec: { type: "number", value: 97.75 }, feedback: "You added 15% of $85. But the 15% was taken off the *original* price, not the sale price — divide by 0.85 instead." },
        ],
        solution: ["After 15% off, Hana pays 85% of the original price.", "So 0.85 × original = 85.", "Original = 85 ÷ 0.85 = $100.", "Check: 15% of $100 is $15, and $100 − $15 = $85 ✓"],
        solutions: [{ label: "Find 1% first", steps: ["85% of the original price is $85.", "So 1% is 85 ÷ 85 = $1.", "100% is $100."] }],
        commonError: "Adding 15% of the sale price back on — that 15% is of the wrong amount.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["$85 is what percentage of the original price?", "85% of the original is $85. What is 1%?", "Divide $85 by 0.85."],
        strategy: "Work backwards",
      },
      {
        kind: "short",
        id: "percentages-p3-q08",
        question:
          "A bottle holds 1.5 litres of soya bean milk. Priya pours herself a 330 ml glass from it. What percentage of the bottle has she poured?",
        answer: { type: "number", value: 22, display: "22%" },
        traps: [{ spec: { type: "number", value: 220 }, feedback: "You divided 330 by 1.5 — the units don't match. Change 1.5 litres to 1500 ml first." }],
        solution: ["Use the same units: 1.5 litres = 1500 ml.", "{{330/1500}} × 100 = 22%."],
        commonError: "Mixing millilitres and litres in the same fraction.",
        difficulty: "core",
        guideRef: "one-as-percentage-of-another",
        hints: ["Are both amounts in the same unit?", "1 litre = 1000 ml.", "Work out {{330/1500}} × 100."],
        strategy: "Same units first",
      },
      {
        kind: "written",
        id: "percentages-p3-q09",
        question:
          "Two hawker stalls raise their prices.\n\n| Stall | Dish | Old price | New price |\n|---|---|---|---|\n| A | Chee cheong fun | $2.50 | $3.00 |\n| B | Vegetarian bee hoon set | $6.00 | $6.80 |\n\nWei Ling says, \"Stall B put its price up by more.\" Explain one way in which she is right and one way in which she is wrong. Show your working.",
        marks: 3,
        modelAnswer:
          "**In dollars she is right.** Stall A's price went up by $3.00 − $2.50 = $0.50. Stall B's went up by $6.80 − $6.00 = $0.80, which is more.\n\n**As a percentage she is wrong.** Stall A's increase is {{0.50/2.50}} × 100 = 20%. Stall B's is {{0.80/6.00}} × 100 ≈ 13.3%. Stall A's price rose by the bigger *percentage*, because its starting price was much smaller.",
        markScheme: [
          { point: "Finds the actual increases, $0.50 and $0.80, so B's rise is bigger in dollars", keywords: ["0.50", "0.5", "0.80", "0.8", "50 cents", "80 cents"] },
          { point: "Finds the percentage increases: A is 20%, B is about 13.3%", keywords: ["20%", "13.3", "13%"] },
          { point: "Concludes she is right about the dollar (absolute) increase but wrong about the percentage increase", keywords: ["absolute", "percentage", "dollars", "relative", "bigger percentage"] },
        ],
        commonError: "Only comparing the dollar increases and forgetting that the starting prices are different.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["There are two ways to measure 'more': in dollars, or as a percentage.", "Work out each increase, then divide it by that stall's old price.", "Compare {{0.50/2.50}} with {{0.80/6.00}}."],
        strategy: "Compare absolute and relative change",
      },
      {
        kind: "short",
        id: "percentages-p3-q10",
        question:
          "Arjun's grandmother puts $1500 into a savings account that pays 4% **simple** interest per year. She takes no money out. How much is in the account after 5 years? Give your answer in dollars.",
        answer: { type: "number", value: 1800, display: "$1800" },
        traps: [
          { spec: { type: "number", value: 300 }, feedback: "$300 is the interest. The question asks how much is in the account, so add the $1500 back." },
          { spec: { type: "number", value: 1824.98, tolerance: 0.01 }, feedback: "That's compound interest — interest on the interest. Simple interest is the same $60 every year." },
        ],
        solution: ["Interest each year = 4% of $1500 = $60.", "Interest for 5 years = 5 × $60 = $300.", "Total = $1500 + $300 = $1800."],
        solutions: [{ label: "Use the formula", steps: ["{{I = (PRT)/100 = (1500 * 4 * 5)/100}} = 300.", "Total = 1500 + 300 = $1800."] }],
        commonError: "Giving only the interest, or adding interest on the interest (that is compound interest).",
        difficulty: "core",
        guideRef: "money-percentages",
        hints: ["How much interest is earned in one year?", "Simple interest is the same amount every year.", "Add 5 years of interest to the $1500."],
        strategy: "Find one year, then scale",
      },
      {
        kind: "short",
        id: "percentages-p3-q11",
        question:
          "In Term 1, a school's recycling drive collected 640 kg of paper. In Term 2 it collected 35% less. Use a single multiplier to find how many kilograms it collected in Term 2.",
        answer: { type: "number", value: 416, display: "416 kg" },
        traps: [
          { spec: { type: "number", value: 224 }, feedback: "224 kg is the *decrease* (35% of 640). Term 2's amount is the 65% that's left." },
          { spec: { type: "number", value: 864 }, feedback: "That's a 35% *increase*. 'Less' means the multiplier is below 1: 0.65." },
        ],
        solution: ["35% less means 100% − 35% = 65% is left.", "Multiplier = 0.65.", "640 × 0.65 = 416 kg."],
        difficulty: "core",
        guideRef: "multipliers",
        hints: ["What percentage of the Term 1 amount is collected in Term 2?", "Write that percentage as a decimal multiplier.", "Work out 640 × 0.65."],
        strategy: "Use a multiplier",
      },
      {
        kind: "written",
        id: "percentages-p3-q12",
        question:
          "An MRT train has 1240 passengers on board. At Dhoby Ghaut, 17.5% of them get off and nobody gets on. **Without a calculator**, work out how many passengers are still on the train. Show how you build up 17.5%.",
        marks: 3,
        modelAnswer:
          "Build 17.5% from easy pieces:\n\n    10% of 1240 = 124\n    5% of 1240 = 62   (half of 10%)\n    2.5% of 1240 = 31   (half of 5%)\n    17.5% = 124 + 62 + 31 = 217\n\nSo 217 passengers get off, and 1240 − 217 = **1023** passengers are still on the train.",
        markScheme: [
          { point: "Finds 10% = 124 and halves it to get 5% = 62 (or other correct building blocks)", keywords: ["124", "62", "10%", "5%"] },
          { point: "Finds 2.5% = 31 and adds to get 17.5% = 217", keywords: ["31", "2.5%", "217"] },
          { point: "Subtracts to get 1023 passengers still on the train", keywords: ["1023"] },
        ],
        solutions: [
          { label: "Work with what's left", steps: ["82.5% of the passengers stay on.", "82.5% = 50% + 25% + 5% + 2.5% = 620 + 310 + 62 + 31 = 1023."] },
        ],
        commonError: "Stopping at 217 — that's the number who got off, not the number still on the train.",
        difficulty: "core",
        guideRef: "percentage-of-amount",
        hints: ["17.5 = 10 + 5 + 2.5. Can you find each of those percentages?", "5% is half of 10%, and 2.5% is half of 5%.", "Once you know how many get off, how many are left?"],
        strategy: "Build up from 10%",
      },
      {
        kind: "short",
        id: "percentages-p3-q13",
        question:
          "A florist buys 120 roses at $1.50 each. She sells 100 of them at $2.40 each; the other 20 wilt and are thrown away. Find her percentage profit. Give your answer to 1 decimal place.",
        answer: { type: "number", value: 33.3, display: "33.3%" },
        traps: [
          { spec: { type: "number", value: 25 }, feedback: "You divided the profit by the takings ($240). Percentage profit is measured against the cost price ($180)." },
          {
            spec: { type: "number", value: 60 },
            feedback: "Check two things: she only sold 100 roses (but paid for all 120), and her $60 profit must be written as a percentage of the cost.",
          },
        ],
        solution: [
          "Cost price = 120 × $1.50 = $180.",
          "Takings = 100 × $2.40 = $240.",
          "Profit = $240 − $180 = $60.",
          "Percentage profit = {{60/180}} × 100 = 33.33…% ≈ 33.3%.",
        ],
        commonError: "Dividing the profit by the selling price instead of the cost price.",
        difficulty: "core",
        guideRef: "money-percentages",
        hints: ["Find her total cost and her total takings first.", "She only sells 100 roses, but she paid for all 120.", "Percentage profit = profit ÷ cost price × 100."],
        strategy: "Organise the information",
      },
      {
        kind: "short",
        id: "percentages-p3-q14",
        question:
          "A maths test has two sections. Aisha gets 60% of the 40 questions in Section A right, and 85% of the 20 questions in Section B right. What percentage of all the questions did she get right? Give your answer to 1 decimal place.",
        answer: { type: "number", value: 68.3, display: "68.3%" },
        traps: [
          {
            spec: { type: "number", value: 72.5 },
            feedback: "72.5% is the average of 60% and 85%. But Section A has twice as many questions, so it counts for more — find how many questions she actually got right.",
          },
        ],
        solution: [
          "Section A: 60% of 40 = 24 right.",
          "Section B: 85% of 20 = 17 right.",
          "Total: 24 + 17 = 41 right out of 60.",
          "{{41/60}} × 100 = 68.33…% ≈ 68.3%.",
        ],
        commonError: "Averaging the two percentages when the sections are different sizes.",
        difficulty: "core",
        guideRef: "one-as-percentage-of-another",
        hints: ["Can you just average 60% and 85%? Which section has more questions?", "Find how many questions she got right in each section.", "Write her total correct out of 60 as a percentage."],
        strategy: "Go back to the actual numbers",
      },
      {
        kind: "written",
        id: "percentages-p3-q15",
        question:
          "Two shops sell the same air fryer.\n\n- **Shop A:** $129, now 25% off\n- **Shop B:** $110, now 15% off\n\nMei says, \"Shop A is the better deal because 25% is a bigger discount.\" Is Mei right? Show working to support your answer.",
        marks: 3,
        modelAnswer:
          "Shop A: 129 × 0.75 = **$96.75**.\n\nShop B: 110 × 0.85 = **$93.50**.\n\nShop B is cheaper by $96.75 − $93.50 = $3.25, so Mei is **wrong**. A bigger percentage discount doesn't guarantee a lower price, because the percentages are taken off different starting prices.",
        markScheme: [
          { point: "Shop A sale price $96.75", keywords: ["96.75"] },
          { point: "Shop B sale price $93.50", keywords: ["93.50", "93.5"] },
          { point: "Concludes Mei is wrong — Shop B is cheaper — because the discounts are taken off different prices", keywords: ["wrong", "shop b", "cheaper", "3.25", "different"] },
        ],
        commonError: "Comparing the percentages instead of the final prices.",
        difficulty: "core",
        guideRef: "money-percentages",
        hints: ["A percentage on its own doesn't tell you a price — what is each discount a percentage *of*?", "Work out each sale price.", "Shop A: multiply by 0.75. Shop B: multiply by 0.85."],
        strategy: "Compare final amounts",
      },
      {
        kind: "short",
        id: "percentages-p3-q16",
        question: "A new mobile game has 500 players. The number of players grows by 20% each month. How many players does it have after 2 months?",
        answer: { type: "number", value: 720 },
        traps: [{ spec: { type: "number", value: 700 }, feedback: "That adds 20% of 500 twice. In the second month the 20% is of the *new* total, 600." }],
        solution: ["The multiplier for a 20% increase is 1.2.", "After 1 month: 500 × 1.2 = 600.", "After 2 months: 600 × 1.2 = 720.", "In one step: 500 × {{1.2^2}} = 500 × 1.44 = 720."],
        commonError: "Adding 40% in one go instead of applying 20% twice.",
        difficulty: "core",
        guideRef: "repeated-change",
        hints: ["What is the multiplier for a 20% increase?", "Apply it once for each month.", "The second increase is 20% of 600, not 20% of 500."],
        strategy: "Repeated multiplier",
      },
      {
        kind: "short",
        id: "percentages-p3-q17",
        question:
          "Marcus's HDB flat has a floor area 25% bigger than Siti's. By what percentage is Siti's flat **smaller** than Marcus's?",
        answer: { type: "number", value: 20, display: "20%" },
        traps: [
          {
            spec: { type: "number", value: 25 },
            feedback: "25% compares with *Siti's* area. 'Smaller than Marcus's' compares with Marcus's area, which is bigger — so the percentage is smaller.",
          },
        ],
        solution: [
          "No areas are given, so pick an easy one: say Siti's flat is 80 m².",
          "Then Marcus's flat is 80 × 1.25 = 100 m².",
          "Siti's flat is 20 m² smaller than Marcus's.",
          "As a percentage of Marcus's area: {{20/100}} × 100 = 20%.",
        ],
        solutions: [
          {
            label: "With multipliers",
            steps: ["Marcus = Siti × 1.25, so Siti = Marcus ÷ 1.25 = Marcus × 0.8.", "Multiplying by 0.8 is a 20% decrease, so Siti's flat is 20% smaller."],
          },
        ],
        commonError: "Assuming the answer is also 25% — but the two percentages are measured from different starting amounts.",
        difficulty: "challenge",
        guideRef: "percentage-change",
        hints: ["No areas are given — so choose one yourself. What would make the numbers easy?", "If Siti's flat is 80 m², how big is Marcus's?", "Now compare the difference with *Marcus's* area."],
        strategy: "Try a specific value",
      },
      {
        kind: "short",
        id: "percentages-p3-q18",
        question:
          "A shop increases the price of a pair of headphones by 25%. A month later, in a sale, it reduces the new price by 20%. The sale price is $60.\n\nArjun says, \"+25% then −20% is a 5% increase overall, so the original price was 60 ÷ 1.05.\"\n\nFind the original price, in dollars.",
        answer: { type: "number", value: 60, display: "$60" },
        traps: [
          { spec: { type: "number", value: 57.14, tolerance: 0.05 }, feedback: "That's Arjun's method — but percentage changes don't add like that. Combine the multipliers instead: 1.25 × 0.8 = ?" },
          { spec: { type: "number", value: 75 }, feedback: "60 ÷ 0.8 undoes the sale, but you still need to undo the 25% increase." },
        ],
        solution: [
          "Turn each change into a multiplier: +25% → × 1.25 and −20% → × 0.8.",
          "Overall multiplier = 1.25 × 0.8 = 1.",
          "So the sale price equals the original price: original × 1 = $60.",
          "The original price was $60. Arjun is wrong: percentage changes multiply, they don't add.",
        ],
        solutions: [{ label: "Undo each step", steps: ["Undo the sale: 60 ÷ 0.8 = $75.", "Undo the increase: 75 ÷ 1.25 = $60."] }],
        commonError: "Adding the percentage changes (+25 − 20 = +5) instead of multiplying the multipliers.",
        difficulty: "challenge",
        guideRef: "reverse-percentages",
        hints: ["Write each change as a multiplier.", "What single multiplier does the same job as both changes together?", "Work out 1.25 × 0.8. What does the answer tell you?"],
        strategy: "Work backwards",
      },
      {
        kind: "written",
        id: "percentages-p3-q19",
        question:
          "**Always, sometimes or never true?**\n\n\"If you increase an amount by a percentage and then decrease the result by the *same* percentage, you get back to where you started.\"\n\nDecide, and explain your reasoning. (Assume the amount and the percentage are both positive.)",
        marks: 3,
        modelAnswer:
          "**Never true.**\n\nExample: $100 increased by 10% is $110. Decreasing $110 by 10% takes off $11, giving $99 — less than $100.\n\nThis always happens: the decrease is a percentage of a **bigger** amount than the increase was, so more is taken off than was added on. With multipliers, a change of p% up then p% down gives {{(1 + p/100)(1 - p/100) = 1 - (p/100)^2}}, which is always less than 1. So you always end up **below** where you started.",
        markScheme: [
          { point: "Gives a correct numerical example showing you end lower (e.g. 100 → 110 → 99)", keywords: ["99", "110", "example", "lower", "less"] },
          { point: "Explains the decrease is taken from a bigger amount, so more is removed than was added (or the multipliers multiply to less than 1)", keywords: ["bigger", "larger", "more", "multiplier", "less than 1"] },
          { point: "Concludes 'never true' — you always finish below the start", keywords: ["never", "always lower", "always less", "below"] },
        ],
        commonError: "Thinking the two changes cancel because the percentages are the same.",
        difficulty: "challenge",
        guideRef: "repeated-change",
        hints: ["Try it with $100 and 10%.", "Try a bigger percentage, like 50%. Do you ever get back exactly?", "The 10% decrease is 10% of which amount — the original, or the bigger one?"],
        strategy: "Try small cases",
      },
      {
        kind: "short",
        id: "percentages-p3-q20",
        question:
          "Fresh mushrooms are 90% water by mass. Wei Ling dries 1 kg of fresh mushrooms in the sun until they are only 60% water. What is the mass of the dried mushrooms, in grams?",
        answer: { type: "number", value: 250, display: "250 g" },
        traps: [
          { spec: { type: "number", value: 700 }, feedback: "Taking 30% off the mass treats the two percentages as if they were of the same total. Focus on the part that *doesn't* change — the solid part." },
          { spec: { type: "number", value: 640 }, feedback: "60% of the *dried mushrooms* is water — not 60% of the original water. Use the solid part, which stays the same." },
        ],
        solution: [
          "The non-water part (the 'solid') doesn't change when the mushrooms dry.",
          "Fresh: solid = 10% of 1000 g = 100 g.",
          "Dried: water is 60%, so the solid is 40% of the dried mass.",
          "40% of the dried mass = 100 g, so the dried mass = 100 ÷ 0.4 = 250 g.",
          "Check: 250 g with 100 g solid leaves 150 g water, and {{150/250}} = 60% ✓",
        ],
        commonError: "Subtracting 90% − 60% = 30% of the mass — the two percentages are of different totals.",
        difficulty: "challenge",
        guideRef: "one-as-percentage-of-another",
        hints: ["When the mushrooms dry, which part of them stays exactly the same?", "Find the mass of the non-water part of the fresh mushrooms.", "After drying, that same mass is 40% of the total. Work backwards."],
        strategy: "Look for an invariant",
      },
    ],
  },

  // =========================================================================
  // PRACTICE PAPER 4 — exam style
  // =========================================================================
  {
    id: "percentages-p4",
    title: "Practice Paper 4 — Exam style",
    questions: [
      {
        kind: "short",
        id: "percentages-p4-q01",
        question:
          "Complete the table.\n\n| Fraction | Decimal | Percentage |\n|---|---|---|\n| {{1/8}} | 0.125 | **(a)** |\n| {{12/5}} | **(b)** | 240% |\n| {{7/25}} | **(c)** | **(d)** |\n\nType the four missing values in order (a), (b), (c), (d), separated by commas. For percentages, type just the number.",
        answer: { type: "list", values: [12.5, 2.4, 0.28, 28], ordered: true, display: "(a) 12.5%, (b) 2.4, (c) 0.28, (d) 28%" },
        traps: [
          {
            spec: { type: "list", values: [12.5, 0.24, 0.28, 28], ordered: true },
            feedback: "Check (b): 240% means 240 hundredths, which is 2.4 — more than one whole.",
          },
        ],
        solution: [
          "(a) Decimal → percentage: 0.125 × 100 = 12.5%.",
          "(b) Percentage → decimal: 240 ÷ 100 = 2.4. Check: 12 ÷ 5 = 2.4 ✓",
          "(c) {{7/25 = 28/100}} = 0.28.",
          "(d) 0.28 = 28%.",
        ],
        commonError: "Writing 240% as 0.24 — percentages over 100% are bigger than 1.",
        difficulty: "warmup",
        guideRef: "fdp-conversions",
        hints: ["Decimal → percentage: × 100. Percentage → decimal: ÷ 100.", "For {{7/25}}, make the denominator 100."],
        strategy: "Use a denominator of 100",
      },
      {
        kind: "short",
        id: "percentages-p4-q02",
        question: "10% of 480 is 48. Use this fact to find:\n\n(a) 15% of 480\n(b) 95% of 480\n\nGive both answers, (a) first.",
        answer: { type: "list", values: [72, 456], ordered: true, display: "(a) 72, (b) 456" },
        traps: [{ spec: { type: "list", values: [72, 432], ordered: true }, feedback: "432 is 90% of 480. For 95%, take away only 5% (24) from 480." }],
        solution: ["5% is half of 10%, so 5% of 480 = 24.", "(a) 15% = 10% + 5% = 48 + 24 = 72.", "(b) 95% = 100% − 5% = 480 − 24 = 456."],
        difficulty: "warmup",
        guideRef: "percentage-of-amount",
        hints: ["How can you get 5% from 10%?", "95% is 5% less than the whole amount."],
        strategy: "Build up from 10%",
      },
      {
        kind: "short",
        id: "percentages-p4-q03",
        question: "The bar chart shows how the 40 students in Class 8C travel to school. What percentage of the class travel by MRT?",
        diagram: `<svg viewBox="0 0 360 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Bar chart of how 40 students travel to school. The vertical axis shows number of students from 0 to 16 in steps of 2. Walk 6, Bus 14, MRT 12, Car 8."><rect x="0" y="0" width="360" height="250" fill="#ffffff"/><line x1="50" y1="180" x2="340" y2="180" stroke="#e5e7eb"/><line x1="50" y1="160" x2="340" y2="160" stroke="#e5e7eb"/><line x1="50" y1="140" x2="340" y2="140" stroke="#e5e7eb"/><line x1="50" y1="120" x2="340" y2="120" stroke="#e5e7eb"/><line x1="50" y1="100" x2="340" y2="100" stroke="#e5e7eb"/><line x1="50" y1="80" x2="340" y2="80" stroke="#e5e7eb"/><line x1="50" y1="60" x2="340" y2="60" stroke="#e5e7eb"/><line x1="50" y1="40" x2="340" y2="40" stroke="#e5e7eb"/><rect x="70" y="140" width="46" height="60" fill="#bae6fd" stroke="#334155"/><rect x="140" y="60" width="46" height="140" fill="#bae6fd" stroke="#334155"/><rect x="210" y="80" width="46" height="120" fill="#bae6fd" stroke="#334155"/><rect x="280" y="120" width="46" height="80" fill="#bae6fd" stroke="#334155"/><line x1="50" y1="200" x2="340" y2="200" stroke="#1f2937" stroke-width="1.5"/><line x1="50" y1="200" x2="50" y2="34" stroke="#1f2937" stroke-width="1.5"/><g font-size="11" font-family="sans-serif" fill="#1f2937" text-anchor="end"><text x="45" y="204">0</text><text x="45" y="184">2</text><text x="45" y="164">4</text><text x="45" y="144">6</text><text x="45" y="124">8</text><text x="45" y="104">10</text><text x="45" y="84">12</text><text x="45" y="64">14</text><text x="45" y="44">16</text></g><g font-size="12" font-family="sans-serif" fill="#1f2937" text-anchor="middle"><text x="93" y="216">Walk</text><text x="163" y="216">Bus</text><text x="233" y="216">MRT</text><text x="303" y="216">Car</text><text x="195" y="238">How students travel</text><text x="16" y="118" transform="rotate(-90 16 118)">Number of students</text></g></svg>`,
        answer: { type: "number", value: 30, display: "30%" },
        traps: [{ spec: { type: "number", value: 12 }, feedback: "12 is the number of students who use the MRT. Write it as a percentage of the whole class of 40." }],
        solution: ["The MRT bar reaches 12, so 12 students travel by MRT.", "{{12/40}} × 100 = 30%."],
        difficulty: "warmup",
        guideRef: "one-as-percentage-of-another",
        hints: ["Read the height of the MRT bar against the scale.", "Write it as a fraction of 40, then convert to a percentage."],
        strategy: "Part over whole",
      },
      {
        kind: "short",
        id: "percentages-p4-q04",
        question:
          "Write down the single multiplier that:\n\n(a) increases an amount by 7%\n(b) decreases an amount by 7%\n(c) increases an amount by 150%\n\nGive your three answers in order, separated by commas.",
        answer: { type: "list", values: [1.07, 0.93, 2.5], ordered: true, display: "(a) 1.07, (b) 0.93, (c) 2.5" },
        traps: [
          { spec: { type: "list", values: [1.07, 0.93, 1.5], ordered: true }, feedback: "Check (c): increasing by 150% gives 100% + 150% = 250% of the amount, so the multiplier is 2.5." },
          { spec: { type: "list", values: [1.7, 0.3, 2.5], ordered: true }, feedback: "7% is 0.07, not 0.7. So +7% is × 1.07 and −7% is × 0.93." },
        ],
        solution: ["(a) 100% + 7% = 107% → × 1.07.", "(b) 100% − 7% = 93% → × 0.93.", "(c) 100% + 150% = 250% → × 2.5."],
        difficulty: "warmup",
        guideRef: "multipliers",
        hints: ["Start from 100% — the amount you already have.", "Add or subtract the change, then divide by 100."],
        strategy: "Start from 100%",
      },
      {
        kind: "short",
        id: "percentages-p4-q05",
        question:
          "Part of Zara's receipt from a bookshop is shown.\n\n| Item | Price |\n|---|---|\n| Atlas | $24.00 |\n| Scientific calculator | $36.00 |\n| Subtotal | $60.00 |\n| GST at 9% | **(a)** |\n| Total | **(b)** |\n\nFind the missing amounts (a) and (b), in dollars, in that order.",
        answer: { type: "list", values: [5.4, 65.4], ordered: true, display: "(a) $5.40, (b) $65.40" },
        traps: [{ spec: { type: "list", values: [5.4, 54.6], ordered: true }, feedback: "GST is *added* to the subtotal, not taken off." }],
        solution: ["(a) 9% of $60 = 0.09 × 60 = $5.40.", "(b) Total = $60 + $5.40 = $65.40 (or 60 × 1.09 = 65.40)."],
        difficulty: "warmup",
        guideRef: "money-percentages",
        hints: ["10% of $60 is $6. What is 1%?", "9% = 10% − 1%. Then add the GST to the subtotal."],
        strategy: "Build up from 10%",
      },
      {
        kind: "short",
        id: "percentages-p4-q06",
        question:
          "Over one year, the drama club grew from 24 to 30 members and the badminton CCA grew from 40 to 48 members. Which group grew by the greater **percentage**? Give that percentage increase.",
        answer: { type: "number", value: 25, display: "25% (the drama club)" },
        traps: [
          { spec: { type: "number", value: 20 }, feedback: "20% is the badminton CCA's increase. Badminton gained more members (8), but drama grew by a bigger *percentage* because it started smaller." },
          { spec: { type: "number", value: 8 }, feedback: "8 is badminton's increase in members — the question asks for a percentage." },
        ],
        solution: ["Drama: increase = 30 − 24 = 6. {{6/24}} × 100 = 25%.", "Badminton: increase = 48 − 40 = 8. {{8/40}} × 100 = 20%.", "The drama club grew by the greater percentage: 25%."],
        commonError: "Choosing badminton because it gained more members.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["Find each actual increase first.", "Divide each increase by that group's *original* size.", "Compare {{6/24}} with {{8/40}}."],
        strategy: "Change ÷ original",
      },
      {
        kind: "short",
        id: "percentages-p4-q07",
        question: "A school's enrolment fell by 12% this year. There are now 1056 students. How many students were there last year?",
        answer: { type: "number", value: 1200 },
        traps: [
          {
            spec: { type: "number", value: 1182.72, tolerance: 0.5 },
            feedback: "You increased 1056 by 12%. But the 12% was of *last year's* number, not this year's — divide by 0.88 instead.",
          },
        ],
        solution: [
          "A 12% fall leaves 100% − 12% = 88% of last year's number.",
          "0.88 × last year = 1056.",
          "Last year = 1056 ÷ 0.88 = 1200 students.",
          "Check: 12% of 1200 = 144, and 1200 − 144 = 1056 ✓",
        ],
        commonError: "Adding 12% of 1056 back on — the 12% was of the original number.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["1056 is what percentage of last year's number?", "Write it as an equation: 0.88 × ? = 1056.", "Undo × 0.88 by dividing by 0.88."],
        strategy: "Use the inverse",
      },
      {
        kind: "short",
        id: "percentages-p4-q08",
        question: "A film lasts 2 hours 30 minutes. Mei has watched 1 hour 12 minutes of it. What percentage of the film has she watched?",
        answer: { type: "number", value: 48, display: "48%" },
        traps: [
          {
            spec: { type: "number", value: 48.7, tolerance: 0.05 },
            feedback: "Careful: 2 hours 30 minutes is not 2.3 hours, and 1 hour 12 minutes is not 1.12 hours. Change both times to minutes first.",
          },
        ],
        solution: ["Change both times to minutes.", "2 h 30 min = 150 minutes; 1 h 12 min = 72 minutes.", "{{72/150}} × 100 = 48%."],
        commonError: "Treating 2 h 30 min as 2.3 hours — there are 60 minutes in an hour, not 100.",
        difficulty: "core",
        guideRef: "one-as-percentage-of-another",
        hints: ["Hours and minutes don't work in tens. Pick one unit for both times.", "How many minutes are in 2 hours 30 minutes?", "Work out {{72/150}} × 100."],
        strategy: "Same units first",
      },
      {
        kind: "written",
        id: "percentages-p4-q09",
        question:
          "Ravi wants to decrease $80 by 15%. He says, \"To decrease by 15%, I just multiply by 0.15.\"\n\n(a) Explain what Ravi's calculation actually finds.\n(b) Write down the correct multiplier and use it to decrease $80 by 15%.",
        marks: 3,
        modelAnswer:
          "(a) 80 × 0.15 = $12. That is 15% **of** $80 — the size of the decrease, not the new amount.\n\n(b) After a 15% decrease, 100% − 15% = 85% is left, so the multiplier is **0.85**. 80 × 0.85 = **$68**.",
        markScheme: [
          { point: "Explains that × 0.15 finds 15% of the amount (the decrease, $12), not the new value", keywords: ["15% of", "12", "the decrease", "taken off", "not the new"] },
          { point: "Correct multiplier 0.85, because 100% − 15% = 85%", keywords: ["0.85", "85%"] },
          { point: "Correct answer $68", keywords: ["68"] },
        ],
        commonError: "Using 0.15 (the decrease) or 1.15 (an increase) instead of 0.85.",
        difficulty: "core",
        guideRef: "multipliers",
        hints: ["Work out 80 × 0.15. What does that number represent?", "After taking off 15%, what percentage of the $80 is left?"],
        strategy: "Spot the error",
      },
      {
        kind: "short",
        id: "percentages-p4-q10",
        question:
          "In 2025, 40% of Year 8 students chose Mandarin as their language option. In 2026 the figure was 50%.\n\n(a) By how many **percentage points** did the figure rise?\n(b) What was the **percentage increase** in the figure?\n\nGive both answers, (a) first.",
        answer: { type: "list", values: [10, 25], ordered: true, display: "(a) 10 percentage points, (b) 25%" },
        traps: [
          {
            spec: { type: "list", values: [10, 10], ordered: true },
            feedback: "Percentage points and percent are different. The rise of 10 points is {{10/40}} of the original 40%, which is a 25% increase.",
          },
        ],
        solution: ["(a) 50 − 40 = 10 percentage points.", "(b) Percentage increase = {{10/40}} × 100 = 25%."],
        commonError: "Saying the figure rose by 10% when it rose by 10 percentage points.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["Percentage points: just subtract the two percentages.", "A percentage increase compares the change with the original value, 40."],
        strategy: "Change ÷ original",
      },
      {
        kind: "short",
        id: "percentages-p4-q11",
        question:
          "A laptop has a marked price of $1200 before GST. The shop takes 15% off the marked price, and then GST of 9% is added to the discounted price. How much does Wei Ling pay? Give your answer in dollars.",
        answer: { type: "number", value: 1111.8, display: "$1111.80" },
        traps: [
          { spec: { type: "number", value: 1128 }, feedback: "You combined −15% and +9% into −6%. The 9% is added to the *discounted* price, so multiply: 1200 × 0.85 × 1.09." },
          { spec: { type: "number", value: 1020 }, feedback: "$1020 is the discounted price before GST. Now add the 9% GST." },
        ],
        solution: ["Discount: 1200 × 0.85 = $1020.", "Add GST: 1020 × 1.09 = $1111.80.", "In one line: 1200 × 0.85 × 1.09 = $1111.80."],
        commonError: "Adding and subtracting the percentages (−15 + 9 = −6) instead of chaining the multipliers.",
        difficulty: "core",
        guideRef: "money-percentages",
        hints: ["Do one change at a time. Which comes first?", "Which multiplier takes 15% off? Which multiplier adds 9%?", "Multiply 1200 by both multipliers."],
        strategy: "Chain the multipliers",
      },
      {
        kind: "short",
        id: "percentages-p4-q12",
        question: "The pie chart shows how a school splits its $24 000 CCA budget. How much is spent on Arts? Give your answer in dollars.",
        diagram: `<svg viewBox="0 0 300 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pie chart of a CCA budget: Sports 45 percent, Music 25 percent, Clubs 12 percent, and Arts with no percentage shown."><rect x="0" y="0" width="300" height="240" fill="#ffffff"/><path d="M150,120 L150,25 A95,95 0 0,1 179.36,210.35 Z" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><path d="M150,120 L179.36,210.35 A95,95 0 0,1 59.65,149.36 Z" fill="#fde68a" stroke="#334155" stroke-width="1.5"/><path d="M150,120 L59.65,149.36 A95,95 0 0,1 84.97,50.75 Z" fill="#bbf7d0" stroke="#334155" stroke-width="1.5"/><path d="M150,120 L84.97,50.75 A95,95 0 0,1 150,25 Z" fill="#fecaca" stroke="#334155" stroke-width="1.5"/><g font-size="12" font-family="sans-serif" fill="#1f2937" text-anchor="middle"><text x="200" y="112">Sports</text><text x="200" y="127">45%</text><text x="124" y="168">Music</text><text x="124" y="183">25%</text><text x="92" y="104">Arts</text><text x="92" y="119">?</text><text x="128" y="64">Clubs</text><text x="128" y="78">12%</text></g></svg>`,
        answer: { type: "number", value: 4320, display: "$4320" },
        traps: [{ spec: { type: "number", value: 18 }, feedback: "18% is the Arts percentage. The question asks for the amount in dollars." }],
        solution: ["The percentages in a pie chart add up to 100%.", "Arts = 100% − 45% − 25% − 12% = 18%.", "18% of $24 000 = 0.18 × 24 000 = $4320."],
        solutions: [{ label: "Build from 1%", steps: ["1% of $24 000 = $240.", "18% = 18 × $240 = $4320."] }],
        commonError: "Stopping at 18% — the question wants dollars.",
        difficulty: "core",
        guideRef: "percentage-of-amount",
        hints: ["What must all the percentages in a pie chart add up to?", "Find the Arts percentage first.", "1% of $24 000 is $240."],
        strategy: "Use the whole",
      },
      {
        kind: "written",
        id: "percentages-p4-q13",
        question:
          "Ethan's water bill this month is $46. This is 15% more than last month's bill. Ethan works out last month's bill like this:\n\n    15% of $46 = $6.90\n    $46 − $6.90 = $39.10\n\n(a) Explain what Ethan has done wrong.\n(b) Work out last month's bill correctly.",
        marks: 3,
        modelAnswer:
          "(a) The 15% increase was 15% of **last month's** bill, not 15% of $46. Ethan has taken 15% of the new, bigger amount, so he has taken off too much.\n\n(b) This month's bill is 115% of last month's, so last month's bill × 1.15 = 46. Last month's bill = 46 ÷ 1.15 = **$40**.\n\nCheck: 15% of $40 is $6, and $40 + $6 = $46 ✓",
        markScheme: [
          { point: "Explains the 15% is of last month's (original) bill, not of $46", keywords: ["original", "last month", "not of 46", "new amount", "bigger amount"] },
          { point: "Uses 115% — divides $46 by 1.15", keywords: ["115%", "1.15", "divide"] },
          { point: "Correct answer $40", keywords: ["40"] },
        ],
        commonError: "Taking 15% of the new amount off, instead of dividing by 1.15.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["The 15% was added on to which bill?", "$46 is what percentage of last month's bill?", "Divide $46 by 1.15."],
        strategy: "Spot the error",
      },
      {
        kind: "short",
        id: "percentages-p4-q14",
        question:
          "The table shows the results of a science test for two classes.\n\n| | Class 8A | Class 8B |\n|---|---|---|\n| Passed | 27 | 26 |\n| Did not pass | 3 | 6 |\n\nClass 8A had the higher pass rate. By how many **percentage points** was it higher? Give just the number.",
        answer: { type: "number", value: 8.75, display: "8.75 percentage points" },
        traps: [
          { spec: { type: "number", value: 1 }, feedback: "27 − 26 = 1 compares numbers of students. The classes are different sizes, so compare pass rates as percentages." },
          { spec: { type: "number", value: 0.0875, tolerance: 0.0005 }, feedback: "That's the difference between the decimals. Multiply by 100 to get percentage points." },
        ],
        solution: [
          "Class sizes: 8A has 27 + 3 = 30 students; 8B has 26 + 6 = 32 students.",
          "8A pass rate: {{27/30}} × 100 = 90%.",
          "8B pass rate: {{26/32}} × 100 = 81.25%.",
          "Difference: 90 − 81.25 = 8.75 percentage points.",
        ],
        commonError: "Dividing by the number who did not pass instead of by the class total.",
        difficulty: "core",
        guideRef: "one-as-percentage-of-another",
        hints: ["How many students are in each class altogether?", "Find each class's pass rate as a percentage.", "Subtract the two percentages."],
        strategy: "Compare percentages, not counts",
      },
      {
        kind: "short",
        id: "percentages-p4-q15",
        question:
          "A new e-scooter costs $1250. Its value falls by 20% every year.\n\n| End of year | Value |\n|---|---|\n| 0 | $1250 |\n| 1 | $1000 |\n| 2 | ? |\n| 3 | ? |\n\nWhat is the e-scooter worth at the end of year 3? Give your answer in dollars.",
        answer: { type: "number", value: 640, display: "$640" },
        traps: [
          {
            spec: { type: "number", value: 500 },
            feedback: "That takes 20% of $1250 off every year. Each year the 20% is of the value at the *start of that year*, which keeps getting smaller.",
          },
          { spec: { type: "number", value: 512 }, feedback: "You multiplied $1000 by 0.8 three times — that's the end of year 4. Start from $1250, or multiply $1000 by 0.8 only twice." },
        ],
        solution: ["The multiplier for a 20% fall is 0.8.", "Year 2: 1000 × 0.8 = $800.", "Year 3: 800 × 0.8 = $640.", "In one step: 1250 × {{0.8^3}} = 1250 × 0.512 = $640."],
        commonError: "Taking 20% of the original price off every year.",
        difficulty: "core",
        guideRef: "repeated-change",
        hints: ["What multiplier gives a 20% decrease?", "Use it on $1000 to get the year 2 value.", "Keep multiplying by 0.8 — once per year."],
        strategy: "Repeated multiplier",
      },
      {
        kind: "written",
        id: "percentages-p4-q16",
        question:
          "Marcus buys 40 second-hand books for $2.50 each. He sells 30 of them for $4 each and the other 10 for $1 each.\n\nMarcus says, \"I made a 23% profit.\" Ravi says, \"No — you made a 30% profit.\"\n\nWho is right? Show your working and explain the mistake the other person made.",
        marks: 4,
        modelAnswer:
          "Cost price = 40 × $2.50 = $100.\n\nTakings = 30 × $4 + 10 × $1 = $120 + $10 = $130.\n\nProfit = $130 − $100 = $30.\n\nPercentage profit = {{30/100}} × 100 = **30%**, so **Ravi is right**.\n\nMarcus divided the profit by his takings: {{30/130}} × 100 ≈ 23%. Percentage profit must be worked out as a percentage of the **cost price**, not the selling price.",
        markScheme: [
          { point: "Cost $100 and takings $130", keywords: ["100", "130"] },
          { point: "Profit $30, which is 30% of the cost price", keywords: ["30", "30%"] },
          { point: "States that Ravi is right", keywords: ["ravi"] },
          { point: "Explains Marcus divided by the takings ($130) instead of the cost price", keywords: ["takings", "selling price", "cost price", "divided by 130", "130"] },
        ],
        commonError: "Working out the profit as a percentage of the selling price.",
        difficulty: "core",
        guideRef: "money-percentages",
        hints: ["Work out how much Marcus spent and how much he took in.", "What is his profit in dollars?", "Percentage profit compares the profit with which amount?"],
        strategy: "Identify the original",
      },
      {
        kind: "short",
        id: "percentages-p4-q17",
        question:
          "A department store has **30% off everything**. Members get an **extra 20% off** the reduced price at the till.\n\nZara says, \"That's 50% off altogether!\"\n\nWhat is the actual overall percentage discount for a member?",
        answer: { type: "number", value: 44, display: "44%" },
        traps: [
          { spec: { type: "number", value: 50 }, feedback: "That's Zara's mistake. The extra 20% is taken off the *already reduced* price, so it's worth less than 20% of the original." },
          { spec: { type: "number", value: 56 }, feedback: "56% is the percentage of the original price a member *pays*. The discount is 100% − 56%." },
        ],
        solution: [
          "30% off → × 0.7. Extra 20% off → × 0.8.",
          "Overall multiplier = 0.7 × 0.8 = 0.56.",
          "A member pays 56% of the original price.",
          "Overall discount = 100% − 56% = 44%.",
        ],
        solutions: [{ label: "Try a $100 item", steps: ["$100 with 30% off = $70.", "20% off $70 is $14 off, so the member pays $56.", "Saving = $44 out of $100 = 44%."] }],
        commonError: "Adding the two discounts together.",
        difficulty: "challenge",
        guideRef: "money-percentages",
        hints: ["Try it on a $100 item.", "After 30% off, what's the price? Now take 20% off *that* price.", "Or multiply the two multipliers: 0.7 × 0.8."],
        strategy: "Try a specific value",
      },
      {
        kind: "short",
        id: "percentages-p4-q18",
        question:
          "A rectangular garden bed is 10 m long and 6 m wide. Its length is increased by 20% and its width is decreased by 20%, as shown. By what percentage does the **area** of the bed decrease?",
        diagram: `<svg viewBox="0 0 480 160" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two rectangles. Before: 10 m long and 6 m wide. After: the length is increased by 20 percent and the width is decreased by 20 percent, so the rectangle is longer and thinner."><rect x="0" y="0" width="480" height="160" fill="#ffffff"/><rect x="40" y="40" width="140" height="84" fill="#c7d2fe" stroke="#1f2937" stroke-width="1.5"/><rect x="226" y="56.8" width="168" height="67.2" fill="#bbf7d0" stroke="#1f2937" stroke-width="1.5"/><line x1="188" y1="90" x2="206" y2="90" stroke="#334155" stroke-width="1.5"/><path d="M206,85 L214,90 L206,95 Z" fill="#334155"/><g font-size="12" font-family="sans-serif" fill="#1f2937"><text x="110" y="32" text-anchor="middle">10 m</text><text x="34" y="86" text-anchor="end">6 m</text><text x="310" y="49" text-anchor="middle">length +20%</text><text x="400" y="94" text-anchor="start">width −20%</text><text x="110" y="146" text-anchor="middle">Before</text><text x="310" y="146" text-anchor="middle">After</text></g></svg>`,
        answer: { type: "number", value: 4, display: "4%" },
        traps: [
          { spec: { type: "number", value: 0 }, feedback: "The +20% and −20% don't cancel out. Work out the new length and width, then the new area." },
          { spec: { type: "number", value: 2.4 }, feedback: "2.4 m² is the decrease in area. Write it as a percentage of the original 60 m²." },
        ],
        solution: [
          "Original area = 10 × 6 = 60 m².",
          "New length = 10 × 1.2 = 12 m; new width = 6 × 0.8 = 4.8 m.",
          "New area = 12 × 4.8 = 57.6 m².",
          "Decrease = 60 − 57.6 = 2.4 m², and {{2.4/60}} × 100 = 4%.",
        ],
        solutions: [
          {
            label: "Multipliers only",
            steps: ["Area = length × width, so the area is multiplied by 1.2 × 0.8 = 0.96.", "0.96 means 96% of the original area: a 4% decrease — whatever size the bed started at."],
          },
        ],
        commonError: "Assuming +20% and −20% cancel, so the area stays the same.",
        difficulty: "challenge",
        guideRef: "multipliers",
        hints: ["Does +20% on one side and −20% on the other really cancel? Test it.", "Find the new length and width, then the new area.", "Or multiply the two multipliers together: 1.2 × 0.8."],
        strategy: "Multiply the multipliers",
      },
      {
        kind: "written",
        id: "percentages-p4-q19",
        question:
          "Priya has $1000 to save for 3 years. She can choose:\n\n- **Option A:** 5% **simple** interest per year\n- **Option B:** 4.8% **compound** interest per year\n\nRavi says, \"Option A is obviously better, because 5% is more than 4.8%.\" Is Ravi right? Show working to support your answer.",
        marks: 4,
        modelAnswer:
          "**Option A:** interest = 5% of $1000 = $50 each year, so 3 × $50 = $150. Total = **$1150**.\n\n**Option B:** 1000 × {{1.048^3}} = 1000 × 1.151022… = **$1151.02** (to the nearest cent). Year by year: $1048 → $1098.30 → $1151.02.\n\nOption B gives $1.02 more, so **Ravi is wrong**. With compound interest, each year's interest is also earned on the interest from earlier years, so the total grows faster than with simple interest — here, fast enough to beat the higher simple rate.",
        markScheme: [
          { point: "Option A total $1150 (interest $150)", keywords: ["1150", "150"] },
          { point: "Option B total $1151.02, using 1000 × 1.048 three times", keywords: ["1151.02", "1151", "1.048"] },
          { point: "States Ravi is wrong — Option B gives more", keywords: ["wrong", "option b", "more", "1.02"] },
          { point: "Reason: compound interest earns interest on the interest", keywords: ["interest on interest", "interest on the interest", "compound", "earlier", "grows"] },
        ],
        commonError: "Comparing the interest rates instead of the final amounts.",
        difficulty: "challenge",
        guideRef: "repeated-change",
        hints: ["Work out the final amount for each option — don't just compare the rates.", "Simple interest: the same $50 every year.", "Compound interest: multiply by 1.048 three times."],
        strategy: "Compare final amounts",
      },
      {
        kind: "short",
        id: "percentages-p4-q20",
        question: "When a number is increased by 40%, the answer is 36 more than when the same number is decreased by 20%. What is the number?",
        answer: { type: "number", value: 60 },
        traps: [
          { spec: { type: "number", value: 180 }, feedback: "The gap is not 40% − 20% = 20% of the number. From 80% of the number up to 140% of it is a gap of 60%." },
        ],
        solution: [
          "Increasing by 40% gives 140% of the number; decreasing by 20% gives 80% of it.",
          "The difference is 140% − 80% = 60% of the number.",
          "60% of the number = 36, so 1% = 0.6 and the number is 60.",
          "Check: 60 × 1.4 = 84 and 60 × 0.8 = 48; 84 − 48 = 36 ✓",
        ],
        solutions: [{ label: "Algebra", steps: ["Let the number be n.", "1.4n − 0.8n = 36.", "0.6n = 36, so n = 36 ÷ 0.6 = 60."] }],
        commonError: "Thinking the gap is 40% − 20% = 20% of the number.",
        difficulty: "challenge",
        guideRef: "multipliers",
        hints: ["Write each result as a percentage of the number.", "How far apart are 140% and 80%?", "60% of the number is 36. What is the whole number?"],
        strategy: "Introduce a variable",
      },
    ],
  },
];
